### ISSUE TITLE
it is not giving location on any website.

### ISSUE THREAD

**Issue by raj123** [minbrowser/min#1004]
how will it give location. I tried various websites to return location.

**Comment by PalmerAL** [comment]
The geolocation service built into Chromium requires paying Google per-request (and it's fairly expensive), so it's disabled in Min. The only alternative I know of is [Mozilla location service](https://location.services.mozilla.com/), but I'm not sure how feasible that is, and implementing it isn't a priority.

**Comment by raj123** [comment]
for this I have to get GOOGLE_API_KEY. right?

**Comment by PalmerAL** [comment]
Yes.

What are you working on? Are you planning to integrate Min into another project?

**Comment by ursulogalvan** [comment]
Hello, just a cuestion about this. How could I add, If I try, the Mozilla location services to mi Min installation? 

I'm starting to learn at least de basic of writing software and doing by trying to solve my personal needs In what refers to software seems very helpful for my learning process. 

(Also, please excuse for my terrible english since is not my native language.

**Comment by PalmerAL** [comment]
I haven't tried it, so I'm not exactly sure what would work, but I think the options would be:

1. Directly modify the Chromium codebase to use a different API - this is likely going to be tricky, and require you to build Chromium yourself, and stop working after upgrading to a new Chromium version, so I wouldn't recommend it.
2. Re-implement the geolocation API in JS. To do that, you would add something to the preload script that re-implements `navigator.geolocation`. Then, your implementation would make an API request to the mozilla API and return the result.

You'd also need to get a key from mozilla to use the API.

How much previous experience do you have? I think this is doable if you already have a pretty good understanding of JS and how Electron works, but if you don't it might be easier to start with something else first and then come back to this.

> please excuse for my terrible english since is not my native language

It's fine! And it actually is a reasonably complicated question.

**Comment by PalmerAL** [comment]
One other thing I forgot is that you'd need to get a list of wifi networks to submit to the API (as described [here](https://ichnaea.readthedocs.io/en/latest/api/geolocate.html)). There's an NPM module that claims to do that: https://www.npmjs.com/package/wireless-tools#iwlist
