### ISSUE TITLE
How to disable Cmd+D keyboard shortcut?

### ISSUE THREAD

**Issue by dancojocaru2000** [minbrowser/min#1007]
There are some websites that use Cmd+D as a keyboard shortcut, notably Google Meet, which uses it to toggle microphone. How to disable this keyboard shortcut from Min so that it can be used on websites?

**Comment by PalmerAL** [comment]
Go to Min > preferences, scroll down to keyboard shortcuts > add to favorites, and delete the shortcut in the text box.

**Comment by dancojocaru2000** [comment]
Thanks!
