### ISSUE TITLE
chat-syle slash commands for browser actions

### ISSUE THREAD

**Issue by cryptobird** [minbrowser/min#101]
One way to go about having a super minimal browser, and yet have the convenience of a larger browser, would be to have a slash commands in the URL bar. For example, typing '/back', '/forward', '/history', '/settings', '/adblock on',  etc. would do those things. As somebody who is usually on the keyboard rather than the mouse, this would be excellent. A great place to see this done excellently is slack, though they use it much more broadly. 

Icing on the cake would be to allow users to build plugins into that system. great way to keep it minimal _and_ extensible.

**Comment by PalmerAL** [comment]
I like this idea!

What other commands do you think would be useful?

Also, what's better about typing /back, for example, rather than using a keyboard shortcut like mod+left-arrow?

**Comment by idle-zealot** [comment]
Can I piggyback off of this idea? Perhaps we could create these commands, and have them executed when either entered into the url bar or when passed as arguments to the Min executable. That would mean that the browser could be automated, and users could set up their own keybindings using an external program if they so desired.

**Comment by cryptobird** [comment]
@PalmerAL A great example of some of this functionality can be seen in the Vivaldi browser's command palette. You can alias different search engines with a nickname; for example if I type "y cat videos" into the command palette, it will search for cat videos on youtube. This could be implimented so that if you type /y for youtube, or /w for wikipedia. 

To what @idle-zealot mentioned, that could be useful for command line arguments. You could pass your search engine alias and the search phrase as arguments.

/back and /forward were just examples, but other functionalities could be reordering, stacking or tiling tabs. like /tile 1 2 would tile the first and second tabs, or /tabmove 3 1 or /tabm 3 1 would move the 3rd tab to the first position. 

The best part, I think, would be that however minimal the built-in commands, if you made a robust enough API it would be really easy for other developers to make awesome additions.

**Comment by idle-zealot** [comment]
@cryptobird Your /y cat videos example is already sort of implemented. The search provider used is DuckDuckGo, which supports "bangs," meaning entering "!yt cat videos" into the search bar will search for "cat videos" on YouTube. A full list of bangs can be found at https://duckduckgo.com/bang

**Comment by cryptobird** [comment]
@idle-zealot man I had no idea! thanks for the tip :)

**Comment by wb9688** [comment]
A command for creating fullpage screenshots would also be handy...

**Comment by PalmerAL** [comment]
I think this might be better as custom !bang commands, rather than a separate / character.

**Comment by PalmerAL** [comment]
I've started working on this in the <a href="https://github.com/minbrowser/min/tree/custom-bangs">custom-bangs</a> branch.

**Comment by PalmerAL** [comment]
PR is #202.

**Comment by PalmerAL** [comment]
#202 has been merged. Commands can be used just like a !bang - by typing them in the searchbar. Current commands are:

* View settings
* Go back/forward
* Take a screenshot
* Clear history

Are there any other commands that should be added?

When Min gets support for extensions, they will be able to add additional commands as well.

**Comment by wb9688** [comment]
Does that screenshot command make a fullpage screenshot or a screenshot of
the current viewport?

**Comment by PalmerAL** [comment]
It's the current viewport. Full-page screenshots would be nice, but ```browserWindow.capturePage``` doesn't work if the screenshot size is larger than the size of the window. There's no way to resize the window to be larger than the size of the computer's screen unless the ```enableLargerThanScreen``` option is enabled, but that would also mean the user could resize the window to be larger than the screen, which wouldn't match every other native app.

**Comment by cryptobird** [comment]
adding the current tab to a new task would be cool. like, if I'm on amazon and i do !task shopping it'll create a new task called shopping with my amazon tab. maybe !fs or !full to make it fullscreen. potentially navigating tasks could be rad, like if I'm on my general browsing task i could type !shopping to go there. Though then there could be conflict with regular !commands if you happened to name a task 'yt' or something.

**Comment by PalmerAL** [comment]
OK, I've added some commands for tasks in 2be3f14c93fd4c923a8a965771c4dcf0ff0a8a14:

* ```!task <name>``` switches to a task. It will also work with numbers, so "!task 1" will switch to the first task.
* ```!newtask <name>``` will create a new task.
* ```!movetotask <name>``` will move the current tab to a task, or create a new task if there isn't a task with that name. Like the "!task" command, it will also work with a number instead of a task name.

**Comment by PalmerAL** [comment]
Actually, there should probably be some documentation somewhere about what the commands do. Filed an issue about that: #203.

**Comment by cryptobird** [comment]
this is seriously awesome. Min is quickly becoming my favorite and most-used browser.

**Comment by PalmerAL** [comment]
Thank you!

**Comment by PalmerAL** [comment]
This will be included in 1.4.0.

**Comment by PalmerAL** [comment]
1.4.0 has been released; you can download it from here: https://github.com/minbrowser/min/releases/tag/v1.4.0.
