### ISSUE TITLE
CTRL + T Not Working.

### ISSUE THREAD

**Issue by wildLori** [minbrowser/min#1012]
Hi, 
i really appreciate your work! 
It may sound really vague, but i can't explain myself why all the shortcut keys work, except CTRL+T for opening a new tab.
Shell i send you some kind of log / setting / other stuff?

**Comment by PalmerAL** [comment]
What OS and keyboard layout are you using? Have you customized any of the shortcuts in the preferences? Does it work if you press the shortcut with the searchbar open, instead of being focused on a webpage?

**Comment by wildLori** [comment]
Solved,
just re-installed.
Thanks anyway Palmer :)
