### ISSUE TITLE
Custom Search Cannot be Searche Within the Address Bar

### ISSUE THREAD

**Issue by jkwieder** [minbrowser/min#1015]
I'm not really sure if this counts as a bug or not, but it's definitely becoming a pet peeve of mine with this browser. 

I use a custom search engine (Ecosia), and everytime I try to search something in the address bar, I am redirected to Ecosia's main webpage. This redirection results in me having to re-enter my search into the Ecosia website instead of simply being redirected to the search I had just made.

If there's any way to fix this, please let me know. It would be greatly appreciated. :)

**Comment by jkwieder** [comment]
**Update!** I figured out how to fix this issue!
Once the custom search engine is entered into Preferences, it will make that search engine an option to search from instead of it simply being labeled as "custom." 

To access this search engine within the address bar, toggle the name of the search engine you put in instead of having it set to custom. 

In my case, this option shows up as "Ecosia," so I toggled the "Ecosia" option as my preferred search option instead of the "custom" option. 

Hope this makes sense to anyone else who may be struggling to fix this issue! :)

**Comment by PalmerAL** [comment]
The "custom" option works the way you thought originally; Ecosia only appears in the list because it's a built-in search engine already (that doesn't require any customization).

I can get Ecosia to work with the "custom" option by using this search string:
```
https://www.ecosia.org/search?q=%s
```
is that what you were doing?
