### ISSUE TITLE
Translation of the reading mode screen

### ISSUE THREAD

**Issue by idAlencar** [minbrowser/min#1018]
hi @PalmerAL , I want to translate the reading mode screen. I'm having trouble getting it to work,

/reader/index.html
I put the (data string) and <script src = "../../ dist / localization.build.js"> </script>

I informed the strings in localization / languages ​​/ en-US.json

What else can be done?

**Comment by PalmerAL** [comment]
Could you put your code in a branch somewhere to look at?

A couple things I can think of:

* The script needs to go at the end of the file (after the HTML with the strings).
* You need to run `npm run build` again after updating the translation files.

**Comment by idAlencar** [comment]
Branch reading-list  

> https://github.com/idAlencar/min-dev-test/tree/reading-list

changes in:
1 - /reader/index.html
2 - localization/languages/en-US.json

**Comment by PalmerAL** [comment]
I think there should only be one ../ in the file path, so it should be this:
```
  	<script src="../dist/localization.build.js"></script>
```

If you go to developer > inspect page > network and reload, you can see whether the script is being loaded correctly or not.

**Comment by idAlencar** [comment]
hi @PalmerAL , I just finished the general, I just need to add in some languages, you can take a look, I also worked on the sepia theme and made some adjustments in the sizes

**Comment by PalmerAL** [comment]
Can you open a PR?

I think the translation changes look good, but I'm not sure about the sepia theme changes. This seems really hard to read:

<img width="1241" src="https://user-images.githubusercontent.com/10314059/82591546-2603b200-9b65-11ea-9440-57cd1f894293.png">

The sepia theme is supposed to be almost like a light theme, but not quite as harsh to look at (to make it better for reading in the evening), so I think I'd prefer to keep the color scheme close to the original.

**Comment by idAlencar** [comment]
understand, I'll make it clearer, confess that I think the original theme is very close to white, I use reading mode a lot and after a while the sepia bothers me

**Comment by PalmerAL** [comment]
Yeah, that's probably fine.

**Comment by idAlencar** [comment]
Great, I will do PR

**Comment by PalmerAL** [comment]
This has been fixed.
