### ISSUE TITLE
How get and set settings in main.js?

### ISSUE THREAD

**Issue by IProudNoob** [minbrowser/min#1023]
Hi!
I try get settings in main.js.
But in console I see  

> App threw an error during load
> TypeError: Cannot read property 'get' of undefined

How get and set settings in main.js?

THX!!!

**Comment by PalmerAL** [comment]
That should work - see the example here: https://github.com/minbrowser/min/blob/master/main/main.js#L171

Can you post your code?

**Comment by IProudNoob** [comment]
> That should work - see the example here: https://github.com/minbrowser/min/blob/master/main/main.js#L171
> 
> Can you post your code?

Thanks for your fast answer 👍 )
It's work but only in createWindowWithBounds function.
Other places not working.

**Comment by PalmerAL** [comment]
Sorry, I forgot you have to wait for the app `ready` event (which createWindowWithBounds runs after). This should work:
```
app.on('ready', function () {
    settings.get(...
})
```

**Comment by IProudNoob** [comment]
THX!!! )))))
