### ISSUE TITLE
better collapsed tasks

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1039]
another feature request from me...

when i collapse tasks, first t abs title stays below the task. What if instead of showing title we took all open tab's favicons and put them next to each other?

**Comment by PalmerAL** [comment]
I think it could work. I made a prototype here: https://github.com/minbrowser/min/tree/task-favicons ; I'll try it out for a bit and see.

**Comment by shalva97** [comment]
woooow, thats amazing, it was unxepected to see your first comment with a prototype. Just checked out that branch and i am happy my idea got into Min, haha... me is happy...

but why did you made favicons pale? or is it something wrong on my machine...

**Comment by PalmerAL** [comment]
I made the icons partially-transparent so that they wouldn't stand out too much from the text around them; they could probably be a bit less transparent though.

**Comment by PalmerAL** [comment]
I increased the opacity from 0.6 to 0.8.

**Comment by PalmerAL** [comment]
I've merged the PR for this.
