### ISSUE TITLE
Add smooth scroll

### ISSUE THREAD

**Issue by towerofnix** [minbrowser/min#104]
One of my favourite features of Firefox is the smooth scrolling feedback I get. On every other browser I've used – Chrome, Safari, Min, etc. – scrolling is kind of jumpy. When I'm scrolling, I'd like to be able to see the content scroll.

With a magic mouse, this isn't noticable, because the smooth scroll is built-in to the mouse (I think) but unfortunately it isn't built-in to my generic scroll wheel mouse.

So.. just a small, minor feature request.

**Comment by TheInitializer** [comment]
Hey it's you!

I second this. My website is inexperiencable without it :P

**Comment by PalmerAL** [comment]
I think this is an Electron issue - can you please report it there?

**Comment by dbfreem** [comment]
Since this hasn't been reported anymore and it may be an electron issue, closing.
