### ISSUE TITLE
1Password CLI installation process not working (MacOS)

### ISSUE THREAD

**Issue by readtedium** [minbrowser/min#1048]
Hi there, the CLI installer for 1Password installs correctly, but Min doesn’t seem to recognize it for some reason, and it hangs without ever recognizing the installation.

<img width="515" alt="Screenshot 2020-06-04 11 43 36" src="https://user-images.githubusercontent.com/470216/83778544-d9d26a80-a658-11ea-896a-95bd226b018b.png">

Using MacOS Mojave 10.14.3.

**Comment by PalmerAL** [comment]
Can you also try doing `rm /usr/local/bin/op`, and then installing with the build from https://github.com/minbrowser/min/issues/1028#issuecomment-637832093 ?

**Comment by readtedium** [comment]
I did that and it got past that point, and I logged into the service successfully. Despite that, I am unable to actually use it to pull any passwords.
