### ISSUE TITLE
Focused input loses focus when the window receives focus

### ISSUE THREAD

**Issue by teunissenstefan** [minbrowser/min#1055]
Let's imagine the following scenario: I'm typing into a text input on a page, alt-tab to a different application, then alt-tab back into min, the text input that I was typing into is no longer focused. I then have to manually focus the text input again to start typing.

I would like to be able to start typing into the input right away after I switch back to min. So is this a bug or a feature? Because this is preventing me from using min more.

Edit: not sure why but for some reason I thought that it was a good idea to not add some system information. I'm on Manjaro, I'm using i3wm and Min 1.14.1.

**Comment by teunissenstefan** [comment]
Okay for some reason, now it is working as I would expect it, the focus does return to the text input. I have **not** restarted Min, I have **not** rebooted. I basically haven't changed anything, so maybe it was something that randomly happened? I'll post here if it happens again.

**Comment by PalmerAL** [comment]
I've seen this before occasionally as well; I think there's some kind of race condition that prevents it from working correctly. The view is supposed to be focused again [here](https://github.com/minbrowser/min/blob/master/js/webviews.js#L544-L548), but it's possible that something else is focusing the main window after that (or alternatively, `document.activeElement === document.body` could be false, but I'm not sure how that could happen).

**Comment by teunissenstefan** [comment]
Okay so I think I found out something, this seems to happen after I click the "Open menu" button (3 vertical dots). This behavior does not occur when I click other Min buttons like the "View Tasks" button. The the "Open menu" button remains focused even if I focus an input on a page. The behavior only returns to normal after I clicked another Min button like the "View Tasks" button, or even the address bar.

**Comment by PalmerAL** [comment]
OK, I can reproduce that as well, and that would make sense because `document.activeElement === document.body` will be false, so the view won't be re-focused. (I actually see this happening on all of the buttons; I'm not sure why the menu button would behave any differently from the other ones).

So I guess the right thing to do here is check whether there's a text input focused (like the searchbar), and return focus to the page as long as there isn't.

**Comment by PalmerAL** [comment]
Should be fixed in 38c9ff4ac4adf3db18b213b30a4ad8f3fdf502b5.

**Comment by teunissenstefan** [comment]
This does indeed fix the issue, thanks.
