### ISSUE TITLE
Close tabs by middle click in taks

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1056]
i think this will be good addition, sometimes i am lazy to aim mouse at X button...

**Comment by Gangsta0607** [comment]
It already works

**Comment by shalva97** [comment]
nope, i cant get it to work...

**Comment by PalmerAL** [comment]
This is already implemented here: https://github.com/minbrowser/min/blob/master/js/navbar/tabBar.js#L152-L156, so it should work; I don't have any hardware to test this with unfortunately.

**Comment by shalva97** [comment]
no, that works fine. i meant the tasks list,  in the window that appears with CTRL + E

**Comment by PalmerAL** [comment]
Oh, yeah, that is a good idea.

**Comment by PalmerAL** [comment]
If you could test this (either now or when it's released) to make sure it works, that would be great, since I have no way of actually testing this.

**Comment by shalva97** [comment]
hehe, just pulled it and it works flawlessly. thanks

**Comment by PalmerAL** [comment]
Great!
