### ISSUE TITLE
Way to syncronize with firefox or chrome bookmarks

### ISSUE THREAD

**Issue by Marco-Israel** [minbrowser/min#1058]
Hello,

I realy like your browser. Others takes so much overhead of system sorceress in this days only for reading web pages ...

But because I have to work at different places and computers I use the firefox bookmark synchronisation feature to hold bookmarks on different computers in line. I know this has nothing to do with information security. :( But I hope not loosing to much information here for getting such easy to use benefit...

Is there or could there be a similar feature in min or is/will it be possible to connect to bookmark stores other bowers? Or does someone know a way to hold bookmarks in such a way syncrone ?

My best to you and all readers  ! :)

**Comment by PalmerAL** [comment]
I agree this would be nice; unfortunately, a built-in sync system would require enough effort and expense to operate that it probably won't happen in the immediate future (maybe someday though).

There's also a proposal to add pocket integration: #1031, which might happen at some point.

...And if you did want to use a third-party service like Pocket, you could create a bookmarklet or userscript in Min to save pages to it, which you could then access on your other devices.

**Comment by Marco-Israel** [comment]
Thanks for replay :)

**Comment by Marco-Israel** [comment]
Thx for replay :)

**Comment by FcoMarcosMAbreu** [comment]
@PalmerAL, have you thinked about use Firebase to bring this feature. I believe there is also others alternatives.

**Comment by PalmerAL** [comment]
@FcoMarcosMAbreu That's a good point; it would reduce some of the complexity of running this (and it looks like they have some kind of syncing built-in). The downside to something like this is that it's not very efficient from a cost perspective.

I started writing out a really long cost comparison, but then Min crashed and lost my comment (sigh), so going off of database write pricing alone: I visit an average of 87 pages a day, so assuming my usage is representative, and assuming we had 50,000 users (probably a very high estimate, but it's good to plan), database writes alone would be $234 a month (assuming each page is a new document to sync), and there are more charges for database reads, transfer, storage, ... which added up to around $350/month.

In comparison, with something like DigitalOcean (which is basically DIY), you could get a server large enough to run everything for like $10-15, and then pay like $10 a month for a separate storage volume that's large enough to store everything.

So for a write-heavy workload (if I'm calculating this correctly), Firebase would be around 14x more expensive than running it myself, which would be fairly substantial given enough users. There's also the risk of Google eventually deciding to shut it down, which isn't an issue with a DIY service.

Either way, paying for this wouldn't be sustainable for me, so it would either need to be some kind of paid service, or I would need to find another source of funding. Doing this also introduces a lot of issues around privacy/reliability/etc, so it would take a fairly substantial amount of work and testing even with someone else's syncing platform.

**Comment by sjehuda** [comment]
This comment was posted at #1031 

> A solution to privately synchronize bookmarks using an XMPP account and standard formats has been made available https://github.com/minbrowser/min/discussions/2537 (Blasta)
