### ISSUE TITLE
My installed min browser is consuming so much internet data

### ISSUE THREAD

**Issue by coder963** [minbrowser/min#1059]
I am checking this in data usage overview report and min browser is taking 5 to 6 times more data than chrome.

**Comment by PalmerAL** [comment]
Are you loading the same set of pages in each? Do you have autoplaying videos disabled in Chrome?

**Comment by raj123** [comment]
no I am doing normal daily surfing. and videos are not running in neither chrome nor min.

**Comment by PalmerAL** [comment]
Is the video format the same (right-click on the video > "stats for nerds" > codecs)? Is the resolution the same?

I really can't think of anything else that would be causing a difference; Min is going to be downloading basically the same video that other browser are.

Although if it's a video you've played before, it might already be cached in the other browser, but not in Min? You could try clearing the cache in the other browser and checking the data usage them.

**Comment by coder963** [comment]
Closing this also as need to analyze this again. Not priority for now.
