### ISSUE TITLE
min not detected as browser

### ISSUE THREAD

**Issue by CodeIter** [minbrowser/min#1063]
min not detected as browser in **windows 10 setting app**
 and in **browser-select** chocolatey package

**Comment by CodeIter** [comment]
@ckolumbus has a [comment ](https://github.com/zumoshi/BrowserSelect/issues/57#issuecomment-533246678) on zumoshi/BrowserSelect#57 :     
> As a workaround you can add browsers via registry. I've created a template that shows how it works for FirefoxPortable
> 
> [gist : BrowserSelect_Example.reg](https://gist.github.com/ckolumbus/225170d8af9eb10cc558ac061bdab799) 

a gist for Min :    [BrowserSelect_MinBrowserChoco.reg](https://gist.github.com/CodeIter/c9cdde934ecc3b933fbc90ffcd677535#file-browserselect_minbrowserchoco-reg)

**Comment by PalmerAL** [comment]
This was fixed a while ago, at least for the installer version, by adding these registry keys: https://github.com/minbrowser/min/blob/master/main/registryConfig.js

If it's just the chocolatey package that's having issues, I'm guessing there's something about how it's packaged there that's making this not work.
