### ISSUE TITLE
min save raw gist *.reg file as html

### ISSUE THREAD

**Issue by CodeIter** [minbrowser/min#1064]
tested with [BrowserSelect_MinBrowserChoco.reg](https://gist.githubusercontent.com/CodeIter/c9cdde934ecc3b933fbc90ffcd677535/raw/9c893441e77fded1d62b1f8a4dbe127ce2e7172c/BrowserSelect_MinBrowserChoco.reg)

**Comment by BenStigsen** [comment]
_Response to #1063_

**Comment by PalmerAL** [comment]
Closing since #1063 is already open.
