### ISSUE TITLE
x86 linux version

### ISSUE THREAD

**Issue by Gangsta0607** [minbrowser/min#1066]
Hello. There is x86 version for windows, and x64 for linux, there is even arm version, but there's no x86 version for linux. Can you please make x86 linux binary or give advice about how to do it?
I have an old notebook and I'd like to escape from win7 to debian or arch, but there's no browser that works normal

**Comment by PalmerAL** [comment]
The amd64.deb download is x86, it's just named differently.

**Comment by Gangsta0607** [comment]
Oh, well, thanks

понедельник, 15 июня 2020 г. пользователь PalmerAL <notifications@github.com>
написал:

**Comment by Gangsta0607** [comment]
I tried amd64 deb package on lubuntu i386, but it says 'wrong architecture'

вт, 16 июн. 2020 г. в 06:04, PalmerAL <notifications@github.com>:

**Comment by PalmerAL** [comment]
Chromium dropped support for 32-bit linux a while ago, so the last version of Min that would work is 1.9.2 (and it's not possible to build later versions, unfortunately). If you want an up-to-date browser, I think the best option would be Firefox, since I believe the latest version is still supported.

**Comment by Gangsta0607** [comment]
The problem is that my notebook doesn't handle new browsers

вт, 16 июн. 2020 г. в 23:19, PalmerAL <notifications@github.com>:

**Comment by PalmerAL** [comment]
Sorry, I know it's unfortunate, but there's nothing I can do about it.

Firefox still supports 32-bit in the latest version, and I'd imagine that Firefox + content blocker would run at least reasonably fast.

**Comment by Gangsta0607** [comment]
I'd rather use windows with min, cause it works faster than others
Suddenly understood I don't actually need linux😅

сб, 20 июн. 2020 г. в 06:40, PalmerAL <notifications@github.com>:
