### ISSUE TITLE
Is Min a "minimal" browser ?

### ISSUE THREAD

**Issue by BillDietrich** [minbrowser/min#1070]
I thought Min was supposed to be minimal; it says so in the site home page title.  Yet it has bookmarks, reading list, password manager, search engines.  IMO, all of those should be removed.  Users can use an external bookmark manager, password manager, and do searching from a search engine's web page instead of the address/URL bar.  I want a minimal GUI browser that has as little code as possible but still usable.  Things such as tabs, ad-blocking, history are essential, they can't be done outside the browser.

So, a feature request: please remove all support of bookmarks, reading list, password manager, search engines.  Thanks.

I'm using Min 1.14.1 on Ubuntu 20.04 GNOME.

**Comment by BenStigsen** [comment]
Minimal does not have to mean "few items". For me minimal means "efficient access to the essentials." and what you consider to not be essential might be essential for other people, for me that includes all of the stuff you mentioned as non-essential.
> bookmarks, reading list, password manager, search engines

**Comment by PalmerAL** [comment]
I don't think "minimal" has to mean "not many features" - actually, one of my goals for a while now has been to figure out how to keep the UI minimal, but add enough functionality that Min is usable as a replacement for other browsers. All of those things (bookmarks, reading list, passwords, search engine) are designed in such a way that they don't add much to the UI if you don't use them, and they don't really have any effect on the overall performance of the browser. So I don't think removing them would have that much of a benefit.

**Comment by yw662** [comment]
Min is never a "minimal" browser given the fact that it is built on electron. It is much more reasonable to ask for removal of electron than these features.

Anyway, why don't you just use electron if you don't need these features right.

**Comment by PalmerAL** [comment]
Electron really doesn't add that much overhead compared to using the Chromium engine directly, and there aren't really any alternatives that would allow you to make a cross-platform browser based on Chromium with a custom UI. It would be an interesting project to see if you could create a new browser engine that uses fewer resources, but that's not anywhere close to being feasible to do.

Beyond that, I think it's definitely possible to build a JS-based UI that's as fast or faster than other browsers (and Firefox is JS-based as well). Also, we have ad-blocking enabled by default, which provides a pretty large increase in performance/decrease in memory usage compared to other browsers, at least in their default configurations.

**Comment by yw662** [comment]
I know it is not bad, especially when you are also using sth else with electron, like vscode.
I just mean, it make no sense to request removal of those features well still using electron.
