### ISSUE TITLE
Please add a preference to switch to new tab immediately

### ISSUE THREAD

**Issue by BillDietrich** [minbrowser/min#1072]
When I control-click on a link to open it in a new tab, the tab is created but focus remains on the original tab.  Please add a preference to switch focus to the new tab immediately.  Thanks.

I'm using Min 1.14.1 on Ubuntu 20.04 GNOME.

**Comment by BenStigsen** [comment]
I agree with this.

**Comment by BenStigsen** [comment]
This option has now been merged into the master branch. PR https://github.com/minbrowser/min/pull/1075
