### ISSUE TITLE
Preferences don't save/work

### ISSUE THREAD

**Issue by jerme42** [minbrowser/min#1082]
Hi,

I am not very adept at these things, but I want to change the preferences so the tabs don't recolor on each site. I assume this is the enable site theme check box? If I click or un-click with this or any of the radio buttons, those changes aren't reflected in browsing or upon restart, nor are they saved if I reopen the preferences page. Help?

**Comment by Sestowner** [comment]
I can't confirm this.
**OS**: Linux Mint 19.3
**Min**: 1.15.0


Which version of Min do you use?

**Comment by PalmerAL** [comment]
I can't reproduce this either; here's a couple other things you could try:

* If you click on the preferences tab title so the URL bar opens, do you see "min://settings", or something else?
* If you go to developer > inspect page > console, are there any errors listed?

It's possible this could be caused by c2ea7ee5123b06cc86914ea6e6ebceceebe04fa7 (which is new in 1.15); I don't immediately see how it could be though.

**Comment by jerme42** [comment]
OS: Windows 10
Min: 1.15.0

> If you click on the preferences tab title so the URL bar opens, do you see "min://settings", or something else?

It is a file path ending in /app/pages/settings/index.html

>If you go to developer > inspect page > console, are there any errors listed?

Yes:
DevTools failed to parse SourceMap: file:///.../AppData/Local/min/app-1.15.0/resources/app/ext/Dexie.min.js.map

**Comment by PalmerAL** [comment]
Do you have multiple instances of Min installed? My guess is that you have the 1st instance open, but the tab is the preferences page from the 2nd instance. If you close the tab and reopen the preferences from the menu, you should get the right one.

**Comment by jerme42** [comment]
Just the one. I'll try uninstalling and reinstalling in the morning (overseas atm).

**Comment by jerme42** [comment]
Nope. Same issue on reinstall.

**Comment by PalmerAL** [comment]
Can you try this?

1. Click on the settings tab, and post the full URL that appears here (you may need to redact your username).
2. Open the menu and go to developer > inspect browser > console tab. Type "__dirname" (two underscore characters) in the console, and post the output that appears here.

**Comment by jerme42** [comment]
>Click on the settings tab, and post the full URL that appears here (you may need to redact your username).
file:///C:/Users/.../AppData/Local/min/app-1.15.0/resources/app/pages/settings/index.html

I am not sure if it is related but the start page I get when I open min is a search for the executable [...AppData\Local\min\app-1.15.0\min.exe]

>Open the menu and go to developer > inspect browser > console tab. Type "__dirname" (two underscore characters) in the console, and post the output that appears here.

When I open the  console I get more errors than last time:

>bundle.js:8332 Error: ENOENT: no such file or directory, open 'C:\Users\...\AppData\Roaming\Min\settings.json'
    at Object.openSync (fs.js:440)
    at Object.func [as openSync] (electron/js2c/asar.js:140)
    at Object.readFileSync (fs.js:342)
    at Object.fs.readFileSync (electron/js2c/asar.js:542)
    at Object.initialize (bundle.js:8330)
    at Object.58 (bundle.js:8345)
    at o (bundle.js:1)
    at bundle.js:1
    at Object.57.util/settings/settings.js (bundle.js:8158)
    at o (bundle.js:1)
bundle.js:1711 Error: ENOENT: no such file or directory, open 'C:\Users\...\AppData\Roaming\Min\database-migration'
bundle.js:7845 database opened  453.37500001187436
placesWorker.js:3 worker started  34.28999999596272
database.js:27 database opened  143.26499999151565
bundle.js:9460 Uncaught Error
    at Object.fn (bundle.js:9460)
    at bundle.js:9507
    at Array.forEach (<anonymous>)
    at EventEmitter.<anonymous> (bundle.js:9505)
    at EventEmitter.emit (events.js:210)
    at Object.onMessage (init.ts:51)
bundle.js:6861 checking for updates
bundle.js:6867 got response from update check 
Object
bundle.js:6874 update is not available
DevTools failed to parse SourceMap: file:///C:/Users/.../AppData/Local/min/app-1.15.0/resources/app/node_modules/dexie/dist/dexie.min.js.map

When I run the command:

>C:\Users\...\AppData\Local\min\app-1.15.0\resources\app

**Comment by jerme42** [comment]
Yup. If I change it that will fix it?

**Comment by PalmerAL** [comment]
I think it will, or if that's too much of a hassle I should be able to fix it soon.

**Comment by jerme42** [comment]
That did the trick. Nice work!

**Comment by PalmerAL** [comment]
I'm going to leave this open until I fix the issue.
