### ISSUE TITLE
error when installing n ubuntu

### ISSUE THREAD

**Issue by coder963** [minbrowser/min#1087]
in windows and mac it is working perfectly.

But on ubuntu, i tried with following comand to make setup.
npm run build && node ./scripts/buildDebian.js

and it is giving something like postinst had bad permissions error-

![image](https://user-images.githubusercontent.com/310979/85364508-e56ece00-b540-11ea-871c-ae92b3d4bbae.png)

**Comment by Sestowner** [comment]
Try to run this command before you making setup:
```
$ chmod 775 resources/postinst_script
```

**Comment by coder963** [comment]
yes this command changed permission but after that. i found this error.

dpkg (subprocess): unable to execute new Min package pre-removal script (/var/lib/dpkg/tmp.ci/prerm) : No such file or directory
dpkg (subprocess): unable to execute installed Min package post-installation script (/var/lib/dpkg/info/min.postinst) : No such file or directory

**Comment by coder963** [comment]
This issue is corrected. I installed it from the very beginning and it started working. May be I did something wrong in first attempt. But am not able to execute it on root login as it was giving no sandbox error.

Closing this for now. Thanks.
