### ISSUE TITLE
appraisal

### ISSUE THREAD

**Issue by genseric** [minbrowser/min#1090]
hey again, 

i ve tried all of the browsers available to mac(edge,vivaldi,opera,sleipnir,maxthon,brave and maybe more). the outdated/non-maintained maxton and **min** are the only alternatives those kept the ram usage always the same. days pass and i always see the same ram usage. if i close a tab then unbelievably ram consumed by that tab is freed. i am bound to use chrome just for its cross-platform sync ability. i am a daily mac user, please keep going.

technically this is not an issue. just a thank you.

**Comment by PalmerAL** [comment]
Thank you, I'm glad it's working well!

I apologize for there being so many issues with the 1password integration; let me know if the latest build works for you when you get a chance.
