### ISSUE TITLE
Create a new app icon

### ISSUE THREAD

**Issue by PalmerAL** [minbrowser/min#1091]
In upcoming versions of macOS, all app icons are changing to rounded rectangles ([examples](https://developer.apple.com/design/human-interface-guidelines/macos/overview/whats-new-in-macos/#app-icons)). The Min icon needs to be updated to match.

For iOS, Chrome and Firefox both place their logo on top of a colored background:
https://apps.apple.com/us/app/firefox-private-safe-browser/id989804926
https://apps.apple.com/us/app/google-chrome/id535886823

I don't think it's possible to have different icons for different versions of macOS, so the new icon would need to fit in with the icons from current versions as well.

**Comment by PalmerAL** [comment]
I've been working with [@Hi_IamBen](https://twitter.com/Hi_IamBen) on a new design for the logo, and he came up with a design that I think would work pretty well:
<img width="360" src="https://user-images.githubusercontent.com/10314059/87110038-b5574880-c22b-11ea-847e-05eb78fb872f.png">

I think it looks better than the current logo, and it would be easier to adapt to the new macOS style than the existing one (the circle would be placed inside a white rounded rectangle).

Some other variations that we considered:
<img width="360" alt="Min-logo-fancy-circle-render" src="https://user-images.githubusercontent.com/10314059/87110182-05360f80-c22c-11ea-8735-1c348b608784.png">
<img width="360" src="https://user-images.githubusercontent.com/10314059/87110186-07986980-c22c-11ea-8ab7-70107578c774.png">
<img width="360" src="https://user-images.githubusercontent.com/10314059/87110190-09622d00-c22c-11ea-9c55-13c748ef1c4b.png">

@labtorie Any thoughts on this, since you worked on the last revision of the icon?

**Comment by antfu** [comment]
Vote for the first one! Looks very neat!

**Comment by idAlencar** [comment]
I like the idea of ​​first, but I think the color combination can follow the monochromatic circuit a little more, it can be a variety of colors from blue to yellow, causing a degradation in shades equal to the current blue. What do you think about this? 
Google translator
![Combinação monocromática](https://user-images.githubusercontent.com/58848807/87933285-5c758480-ca63-11ea-9840-541fec7d9aae.png)

**Comment by Syndamia** [comment]
I also vote for the first one. 

@idAlencar's idea is also nice, but I feel like it's a bit too 'blocky' and I'm not sure how well the line will look on the small scale of an app icon.

**Comment by PalmerAL** [comment]
I've made a PR for the first icon: https://github.com/minbrowser/min/pull/1195

@idAlencar I wanted to keep the color scheme similar to the current logo so that it's still recognizable to people after updating.

**Comment by gprst** [comment]
Out of curiosity, would there then be a way, even hacky (like replacing the local files or something), to still use the current icon for Min ?

**Comment by PalmerAL** [comment]
That should be possible if you copy over the old icons/ directory. The new icon isn't set in stone yet though - if you prefer the old one, do you have any feedback on what you like about it, or what you would change about the new one?

**Comment by gprst** [comment]
I guess it's only personal taste, but I really like its clean gradients and material look. I think I woulnd't have minded the new logo if it had a transparent backgroud, but imho the white backgroud ruins it. I understand the rounded square is to satisfy the future MacOS icon style, but it doesn't look sexy on Windows and Linux in my opinion, even worse next to cool logos like those of Firefox and Chrome. Furthermore, the screenshots of your PR make the new logo look tiny and like a smartphone app lost on a PC desktop.

I am really not here to criticize your initiative ; it is your app, your work, and I am truly respectful for that. I just personally really prefer the current logo.

**Comment by BlueManCZ** [comment]
The new logo looks overall good. But doesn't it contain too many fine-grained details, when you compare it to the Firefox or Chrome? I don't say it's bad. I can imagine this design on the website banner or GitHub readme. But when you scale it to the icon size, like 45x45px, it becomes a little vague.

![A](https://user-images.githubusercontent.com/17854950/91583371-6d15f600-e951-11ea-8928-a7c94d34d7e4.png)

**Comment by PalmerAL** [comment]
Thanks for the feedback. I do see how it can feel a little bit more generic than the old one, and I agree the lack of detail is an issue.

Ben and I have come up with another version of this that I think might work better:

<img width="593" alt="Screen Shot 2020-08-29 at 9 57 37 PM" src="https://user-images.githubusercontent.com/10314059/91664465-14f80480-eab5-11ea-9310-84e7d92784cc.png">

What do you think?

**Comment by Syndamia** [comment]
If we are going with this one, I think the background should have a bit more color, maybe something similar to this variant: 

<img src=https://user-images.githubusercontent.com/10314059/87110190-09622d00-c22c-11ea-9c55-13c748ef1c4b.png width=100>

**Comment by idAlencar** [comment]
An idea!
![20200831_140803_0000](https://user-images.githubusercontent.com/58848807/91746970-dc7b2800-eb93-11ea-9053-bea71d701123.png)

**Comment by PalmerAL** [comment]
How about this?

<img width="600" src="https://user-images.githubusercontent.com/10314059/91909079-318d6b80-ec72-11ea-8050-9375ffeaabdb.png">

**Comment by BlueManCZ** [comment]
Maybe I'm not objective, but this looks like it is already stylised in some icon theme. Especially the border feels this way. And I can agree with what @gprst already said.
> like a smartphone app lost on a PC desktop.

But it's just my personal opinion. Otherwise it looks good.

**Comment by Syndamia** [comment]
> Isn't there a way how to put this rounded baseplate only to Mac packages and less stylised icon into others?

That is an option, but then again, it shouldn't be *too* different. 

For example, Discord has a pretty different icon between Windows and Linux:

![discord-win](https://user-images.githubusercontent.com/46843671/91942017-e53e3c00-ed02-11ea-84e9-eeb251cc25ff.png)
*Right-most icon is the Discord icon on Windows*

![discord-mint](https://user-images.githubusercontent.com/46843671/91942075-f9823900-ed02-11ea-8981-433b74628afd.png)
*Right-most icon is the Discord icon on Linux (Linux Mint Cinnamon)*

They are pretty different, but the overall shapes and colors are pretty close. Even if we go with one icon for Mac and another for Windows and Linux, they should all have the same structure and (at least similar) colors. 

***

On a side note, I feel like @PalmerAL is going for something more smooth/simplistic while @gprst and @BlueManCZ prefer a more rough/geometric shape (please correct me if I'm wrong). @idAlencar's latest idea is probably the closes (for now) to a compromise between the two.

As for my two cents, I'm fine with anything, as long as it isn't too hard to see on a bright or dark background (although I do prefer lighter colors, I can live with anything).

**Comment by BlueManCZ** [comment]
Just to clarify @Syndamia, icon you see on Linux is from Linux Mint default icon theme [mint-y-icons](https://github.com/linuxmint/mint-y-icons).

![](https://raw.githubusercontent.com/linuxmint/mint-y-icons/4a958a678b0e3298b3190c3a46881c5cc73c12a8/src/apps/discord.svg)

It has nothing to do with default application icon.

Default Discord icon on linux is this: `/usr/share/pixmaps/discord.png`
![discord](https://user-images.githubusercontent.com/17854950/91958261-6697cd80-ed07-11ea-8414-7ba710066358.png)

**Comment by Syndamia** [comment]
@BlueManCZ oh, thank you, I kind of forgot about that. I updated my comment to be accurate.

**Comment by BlueManCZ** [comment]
My point was there is no reason to show Discord icon from the Linux icon theme. There are plenty of those online.
| [Numix-Circle](https://github.com/numixproject/numix-icon-theme-circle) | [Numix-Square](https://github.com/numixproject/numix-icon-theme-square) | [Suru++](https://github.com/gusbemacbe/suru-plus) | [Papirus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) | 
| --- | --- | --- | --- |
| <img src="https://raw.githubusercontent.com/numixproject/numix-core/master/icons/circle/48/discord.svg" width="64px"> | <img src="https://raw.githubusercontent.com/numixproject/numix-core/master/icons/square/48/discord.svg" width="64px"> | <img src="https://raw.githubusercontent.com/gusbemacbe/suru-plus/master/Suru%2B%2B/apps/scalable/discord.svg" width="64px"> | <img src="https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-icon-theme/master/Papirus/48x48/apps/discord.svg" width="64px"> |
| <img src="https://raw.githubusercontent.com/numixproject/numix-core/master/icons/circle/48/min.svg" width="64px"> | <img src="https://raw.githubusercontent.com/numixproject/numix-core/master/icons/square/48/min.svg" width="64px"> | <img src="https://raw.githubusercontent.com/gusbemacbe/suru-plus/master/Suru%2B%2B/apps/scalable/min.svg" width="64px"> | <img src="https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-icon-theme/master/Papirus/48x48/apps/min.svg" width="64px"> |

**Comment by gprst** [comment]
I do like the icon from @idAlencar : it reminds of the current icon, is simplistic, has basic colors. Even though I am personnaly not a fan of the gradient (I prefer flat colors), the icon's gorgeous, and I guess that without the squared lightblue background on Windows and Linux, it would still be recognizable and consistent.

**Comment by MarkWahlsten** [comment]
**I like the zen idea behind this concept, though I'm worried 90% of the time a lot of the detail will be lost at small sizes:**

<img width="77" alt="Screen Shot 2020-10-06 at 3 27 50 pm" src="https://user-images.githubusercontent.com/20477121/95171514-8def2800-07e8-11eb-90ef-1b780646ccb8.png">

At a small size, the details will kind of 'soften' the shape, and it'd lose its crispness.*

Also this might be a non-issue (also feel free to throw tomatoes)... but when I saw the zen circle, my immediate association was "health and wellness" / "meditation" – and not "a lightweight web browser, with minimalism as its core philosophy."

- I'm all for abstract/conceptual/non-literal icons, but I'd double-check what you go with isn't already being used in a different context. 
- Circle logos in general tend to be used fairly heavily in apps I've found (although that may just be iphone apps... so maybe it's a non-issue)

Something I do to check is I snap a screengrab of a logo concept, and do a reverse image search on google.


_* I understand there'd a trade-off though – a version with simplified brush stroke details possibly won't look great zoomed in... I guess it depends on your design brief?_

**Comment by Milo123459** [comment]
I agree with @MarkWahlsten . I like that design.

**Comment by PalmerAL** [comment]
Latest revision:

<img width="600"  src="https://user-images.githubusercontent.com/10314059/97259249-5cb2b800-17e8-11eb-9f4a-eb918171d36e.png">

I removed the border to hopefully make it seem less like an icon theme, and Ben revised the circle shape a bit.

To address some of the concerns mentioned here:

* The detail on the circle won't be visible at small icon sizes, but I'm hoping the basic circle shape should still work.
* The concept by @idAlencar is interesting, although I think it works better to have the area inside the circle and outside of it be one color; otherwise, it looks like a logo stacked on top of a square background, which I'm trying to avoid.
* It's possible to have a separate icon for non-Mac, although it would be better to keep them fairly similar at least. If this one works well enough, I'm hoping to be able to use an identical icon across platforms.

@MarkWahlsten That's a very good point regarding existing usage. I haven't been able to find anything that uses this circle + color combination already, but if anyone sees anything, please let me know.

**Comment by MarkWahlsten** [comment]
@PalmerAL — Nice! I really like Ben's revisions on the shape.

Looks good at small size, only feedback I can think of there is mostly just nitpicking. The gap between the start/end of the stroke starts to visually bleed together a bit when it's viewed at icon size. Anything too subtle could potentially be misinterpreted as a mistake. 

If it's possible to widen that gap without losing the nice circle shape, go for it, but it's not really a huge deal.   

Also I really like it without the border, and the more vibrant gradient colour.

**Comment by melgu** [comment]
The new app icon is too big compared to all other macOS Big Sur Icons.

<img width="538" alt="Bildschirmfoto 2020-11-18 um 12 44 23" src="https://user-images.githubusercontent.com/9601403/99526638-cfecbb80-299b-11eb-95fe-9a061d1ea42d.png">

**Comment by labtorie** [comment]
> @labtorie Any thoughts on this, since you worked on the last revision of the icon?
Sorry for being  that long.
