### ISSUE TITLE
PDF Zoom highly sensitive

### ISSUE THREAD

**Issue by oscarmorrison** [minbrowser/min#11]
The PDF zoom (using pinch or scroll) is highly sensitive, and needs to be dampened.

Min: 1.1.1
OS X: 10.11.4
Machine: Macbook Pro 15" Retina (Mid 2015)

**Comment by PalmerAL** [comment]
This is a bug in <a href="https://github.com/mozilla/pdf.js">pdf.js</a>. You should probably file an issue in that repository.

**Comment by PalmerAL** [comment]
The PDF viewer has been redesigned, and in combination with fb51b9706e988bf49aba7c636a5ff0a2ceaf64d8 this should be fixed.
