### ISSUE TITLE
Can't download pdfs

### ISSUE THREAD

**Issue by darrSonik** [minbrowser/min#1105]
I'm trying this browser for couple of days and I have to admit that I really like this browser. I had one problem, "logging into Gmail", and that's solved by changing the user agent before logging in.
Now, I'm facing another issue that I can't download pdf files from Gmail inbox. I also couldn't download pdf from [Overleaf](https://overleaf.com). I'm having this following error:
![Screenshot](https://user-images.githubusercontent.com/34137568/86362432-15337980-bc97-11ea-84fd-ce42ff994ffc.png)

I really do like this browser! Kudos to you devs.

**Comment by PalmerAL** [comment]
Are you using the Arch package? The latest release of Min is supposed to run with Electron 8, and Electron 9 isn't supported yet, but it looks like the Arch package is built using 9. Until the next release comes out, I think you can just install Electron 8 manually.

**Comment by darrSonik** [comment]
Thanks!
and yes, I'm using Arch package.

**Comment by PalmerAL** [comment]
BTW, there's a new version of the arch package available (1.15.0-2) that solves some more compatibility issues with Electron 9, although I think PDFs still aren't working.
