### ISSUE TITLE
Would a forward button be possible?

### ISSUE THREAD

**Issue by ep1955** [minbrowser/min#1113]
I've just discovered Min browser, thanks to Derek at DistroTube (which I also just discovered).  I really like Min but there is just one issue that keeps Min from being my go to, the lack of a forward button.  It would be a huge step forward (pun intended) for Min.  I realize that you can right click and go forward/backward but...

I'm keeping Min on my machine and hoping for this update.  Thanks for such a great browser!

Earl Parker II

**Comment by Sestowner** [comment]
Forward button is #744.
