### ISSUE TITLE
Touchscreen drag does not work in Leaflet.js maps

### ISSUE THREAD

**Issue by ebrensi** [minbrowser/min#1117]
Touchscreen pan and pinch-zoom works fine for Google maps, but doesn't do anything in [Leaflet.js](https://leafletjs.com) maps.  Leaflet is an open-source map API that a lot of people use.   I'm willing to try and fix it but I don't know where to start.

**Comment by PalmerAL** [comment]
I don't have a touchscreen device to test this with, but I think the first steps would be:

* Try it in Chrome; if it doesn't work there, file an issue in their bug tracker.
* Try it in an empty Electron app, and file an issue there if it doesn't work.

If it works in Electron but not in Min it may be trickier to figure out; I can't immediately think of anything specific to Min that would cause this.

**Comment by djtech-dev** [comment]
I tried it on my laptop on Linux and it works just fine.
If possible, could you retry it using the latest version of Min?

Thanks.

**Comment by ebrensi** [comment]
@djtech-dev this an old issue that appears to be resolved. I will close it.  Thanks for pointing this out.
