### ISSUE TITLE
Youtube ads

### ISSUE THREAD

**Issue by mtgperales** [minbrowser/min#1121]
Ads in Youtube suddenly starts popping while the the option "Block all ads and trackers" is enabled. Already checked other websites and the adblocker works on them.

![image](https://user-images.githubusercontent.com/65724818/87148237-a2eb1680-c2e0-11ea-9dbb-7447890a3ea1.png)

![image](https://user-images.githubusercontent.com/65724818/87148280-b6967d00-c2e0-11ea-9384-ee005f1c3b3b.png)

Using Min v1.15.0

**Comment by Casul51** [comment]
HI! I'm using userscript for this. Here it goes:
```
// ==UserScript==
// @name               No more youtube ads! - UPDATED
// @name:zh-CN         隐藏youtube google广告
// @namespace          FaZe BeeF
// @version            1.0.3
// @description        Automaticly Skips all youtube ads! with no waiting time.
// @description:zh-CN  BF5 : This skips all adds instantly. Youtube.com
// @author             FaZe BeeF
// @match              *://www.youtube.com/*
// ==/UserScript==

(function() {
    'use strict';
    var closeAd=function (){
        var css = '.video-ads .ad-container .adDisplay,#player-ads,.ytp-ad-module,.ytp-ad-image-overlay{ display: none!important; }',
            head = document.head || document.getElementsByTagName('head')[0],
            style = document.createElement('style');

        style.type = 'text/css';
        if (style.styleSheet){
            style.styleSheet.cssText = css;
        } else {
            style.appendChild(document.createTextNode(css));
        }

        head.appendChild(style);
    };
    var skipInt;
    var log=function(msg){
       // unsafeWindow.console.log (msg);
    };
    var skipAd=function(){
        //ytp-ad-preview-text
        //ytp-ad-skip-button
        var skipbtn=document.querySelector(".ytp-ad-skip-button.ytp-button")||document.querySelector(".videoAdUiSkipButton ");
        //var skipbtn=document.querySelector(".ytp-ad-skip-button ")||document.querySelector(".videoAdUiSkipButton ");
        if(skipbtn){
           skipbtn=document.querySelector(".ytp-ad-skip-button.ytp-button")||document.querySelector(".videoAdUiSkipButton ");
           log("skip");
           skipbtn.click();
           if(skipInt) {clearTimeout(skipInt);}
           skipInt=setTimeout(skipAd,500);
         }else{
              log("checking...");
              if(skipInt) {clearTimeout(skipInt);}
              skipInt=setTimeout(skipAd,500);
         }
    };

    closeAd();
    skipAd();

})();
```

**Comment by Syndamia** [comment]
@Casul51's solution worked for me, did it work for you @mtgperales?

**Comment by mtgperales** [comment]
Sorry for the late response i was out of town for like a week.

I've installed a new Arch distro on my laptop and immediately installed min from the official repositories. So far i haven't yet encountered the issue again but will try to use @Casul51 script if the problems comes back.

**Comment by PalmerAL** [comment]
Adding a link to the userscript: https://greasyfork.org/en/scripts/407477-no-more-youtube-ads-updated/code

**Comment by shubhamdmshah** [comment]
> Does the user script still valid? Since last two days i see that youtube ads show on playing.

Hey! I tried it today and it is working. :)

**Comment by shalva97** [comment]
I have been having problems on this, I mean adds ;D

there is one add from my country that often shows up and is not blocked at all, but others like Gramarly and weird mobile games are skipped in about 1 seccond, which is fine...

![image](https://user-images.githubusercontent.com/22417494/119261162-353d9580-bbe7-11eb-962e-c7556e2bc471.png)

**Comment by iambudi** [comment]
Hi, any workaround about this? Thank you.

**Comment by Ftwrr** [comment]
> HI! I'm using userscript for this. Here it goes:
> 
> ```
> // ==UserScript==
> // @name               No more youtube ads! - UPDATED
> // @name:zh-CN         隐藏youtube google广告
> // @namespace          FaZe BeeF
> // @version            1.0.3
> // @description        Automaticly Skips all youtube ads! with no waiting time.
> // @description:zh-CN  BF5 : This skips all adds instantly. Youtube.com
> // @author             FaZe BeeF
> // @match              *://www.youtube.com/*
> // ==/UserScript==
> 
> (function() {
>     'use strict';
>     var closeAd=function (){
>         var css = '.video-ads .ad-container .adDisplay,#player-ads,.ytp-ad-module,.ytp-ad-image-overlay{ display: none!important; }',
>             head = document.head || document.getElementsByTagName('head')[0],
>             style = document.createElement('style');
> 
>         style.type = 'text/css';
>         if (style.styleSheet){
>             style.styleSheet.cssText = css;
>         } else {
>             style.appendChild(document.createTextNode(css));
>         }
> 
>         head.appendChild(style);
>     };
>     var skipInt;
>     var log=function(msg){
>        // unsafeWindow.console.log (msg);
>     };
>     var skipAd=function(){
>         //ytp-ad-preview-text
>         //ytp-ad-skip-button
>         var skipbtn=document.querySelector(".ytp-ad-skip-button.ytp-button")||document.querySelector(".videoAdUiSkipButton ");
>         //var skipbtn=document.querySelector(".ytp-ad-skip-button ")||document.querySelector(".videoAdUiSkipButton ");
>         if(skipbtn){
>            skipbtn=document.querySelector(".ytp-ad-skip-button.ytp-button")||document.querySelector(".videoAdUiSkipButton ");
>            log("skip");
>            skipbtn.click();
>            if(skipInt) {clearTimeout(skipInt);}
>            skipInt=setTimeout(skipAd,500);
>          }else{
>               log("checking...");
>               if(skipInt) {clearTimeout(skipInt);}
>               skipInt=setTimeout(skipAd,500);
>          }
>     };
> 
>     closeAd();
>     skipAd();
> 
> })();
> ```

how to use?

**Comment by eltoncezar** [comment]
@Ftwrr https://github.com/minbrowser/min/wiki/userscripts

**Comment by Syndamia** [comment]
Yeah, YouTube has changed some things which make the script not work sometimes. And I couldn't find any other userscript that fixes that issue.

A somewhat viable alternative is using an [invidious](https://github.com/iv-org/invidious) instance, like [yewtu.be](http://yewtu.be) or [inv.riverside.rocks](https://inv.riverside.rocks). Those come with the added bonus that you can also watch age restricted videos, but have some feature drawbacks (feed isn't infinite, livestreams don't really work, ..). More complete list of trusted public instances [here](https://docs.invidious.io/Invidious-Instances.md).

**Comment by unrealbanter** [comment]
Did something change that's not allowing this to work properly?
I did what they said for scripts and went to application support/Min and created a folder named userscripts and put the script above in a .js file... am i missing anything?

**Comment by chloecdn** [comment]
I'm going to ressurect this thing of an issue, and share a new script i found on the web, that works ootb without any issues for me on all videos currently.

```js
// ==UserScript==
// @name         YouTube - Ad Skip
// @version      1.0
// @description  Skips and removes ads on YouTube automatically
// @author       Bobocato
// @match        https://www.youtube.com/*
// @grant        none
// @namespace https://greasyfork.org/users/167089
// ==/UserScript==

const equalText1 = "Skip Ads";
const equalText2 = "Skip Ad";

function addNewStyle(newStyle) {
    var styleElement = document.getElementById('styles_js');
    if (!styleElement) {
        styleElement = document.createElement('style');
        styleElement.type = 'text/css';
        styleElement.id = 'styles_js';
        document.getElementsByTagName('head')[0].appendChild(styleElement);
    }
    styleElement.appendChild(document.createTextNode(newStyle));
}

function skipAd(){
    console.log("Tried to skip a ad");
    if(document.getElementsByClassName("ytp-ad-skip-button").length > 0){
        if(document.getElementsByClassName("ytp-ad-skip-button")[0].childNodes[0].textContent === equalText1 || document.getElementsByClassName("ytp-ad-skip-button")[0].childNodes[0].textContent === equalText2){
            document.getElementsByClassName("ytp-ad-skip-button")[0].click();
        } else {
            setTimeout(skipAd(), 1000);
        }
    }
}

(function() {
    'use strict';
    addNewStyle('.ytp-ad-overlay-slot {display:none !important;}');
    setInterval(function (){
        if(window.location.href.substring(0,30) == "https://www.youtube.com/watch?"){
            skipAd();
        }
    }, 500);
})();
```

I modified a single value, which is the 500 at the bottom. It's the time in which period it constantly tries to skip ads as long as videos are playing. in my case, it searches every half a second for an ad, and skips it if it appears, no matter if the button says "skip in x seconds" or "skip now".

Now, 500 may seem a bit overkill. The default was at 1500, which i myself found a little too annoying. So yea, if you can spare the pc-performance like me, you can go lower than 1500, if you can't, you can always change it and restart your browser afterwards to update it.

**Comment by M-Arnone** [comment]
this one doesn't work for me but this one from Ftwrr works very well : https://github.com/minbrowser/min/issues/1121#issuecomment-909736307.

**Comment by javisgn** [comment]
Both the scrips don't work anymore, does someone have a solution?

**Comment by Kepler-69c** [comment]
@javisgn [This userscript](https://github.com/iamfugui/YouTubeADB) works for me. Alternatively, [GreasyFork](https://greasyfork.org/en/scripts/by-site/youtube.com) is a good source of user scripts.

**Comment by alexventuraio** [comment]
> @javisgn [This userscript](https://github.com/iamfugui/YouTubeADB) works for me. Alternatively, [GreasyFork](https://greasyfork.org/en/scripts/by-site/youtube.com) is a good source of user scripts.

I can confirm that it worked for me `Min Version 1.31.1 (1.31.1)` in `MacOS Sonoma 14.2.1 (23C71)`.

**Comment by BatchDebug** [comment]
Made an Advanced version that works faster
`// ==UserScript==
// @name         YouTube - Ad Skip+
// @version      1.0
// @description  Efficiently skips and removes ads on YouTube for a faster experience in minbrowser
// @author       Bobocato, CraftingManager
// @match        https://www.youtube.com/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    const adSelectors = [
        '.ytp-ad-skip-button',
        '.ytp-ad-overlay-close-button',
        '.ad-showing',
        '.video-ads'
    ];

    function removeAds() {
        adSelectors.forEach(selector => {
            document.querySelectorAll(selector).forEach(el => el.click());
        });
    }

    function hideAdElements() {
        const style = document.createElement('style');
        style.innerHTML = `
            .ytp-ad-overlay-slot,
            .video-ads,
            .ytp-ad-module {
                display: none !important;
            }
        `;
        document.head.appendChild(style);
    }

    function observeDOMChanges() {
        const observer = new MutationObserver(removeAds);
        observer.observe(document.body, { childList: true, subtree: true });
    }

    hideAdElements();
    observeDOMChanges();
})();
`

**Comment by ioc2e3** [comment]
> 啟用「封鎖所有廣告和追蹤器」選項後，YouTube 上的廣告突然開始彈出。 ...

Until now ...

Ads still pop up from time to time ...

.

**Comment by ioc2e3** [comment]
Not just youtube ...

Until now ...

Ads still pop up from time to time ...

.
