### ISSUE TITLE
Min Helper OSX

### ISSUE THREAD

**Issue by momosby** [minbrowser/min#113]
Min Helper OS X requires Radeon (read discrete) Graphics Card.

**Comment by PalmerAL** [comment]
Do you get a message that says you need a discrete graphics card, or does Min not work correctly without it?

I don't have a discrete graphics card, and I've never had any problems with the Min Helper process, so I don't think a discrete card is a requirement.

**Comment by momosby** [comment]
It uses the automatic Graphics Switcher from OS X. It just does this, if something like a special webplugin loads. I use Min primarily because it doesn't strain the battery like other browsers. Normal users wouldn't notice, as OS X does handle the graphics switching from integrated to discrete in the background. But I use gfxCardStatus, which tells me whenever a switch occurs. It is not min.app itself, but rather a helper process.

But iIthink there is a way to disable this in the info tab of an application. This usually disables an app from using the discrete graphics. But not Helper Processes...

**Comment by dbfreem** [comment]
Is this still an issue? Can it be closed?
