### ISSUE TITLE
sometimes search field closes  when searching on android documentation

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1137]
for example on this [page](https://developer.android.com/reference/packages) if i search animation i get 7 results, but cycling through them to about 4th or 6th result closes the search field.

**Comment by antfu** [comment]
Confirmed. Happened to me as well.

**Comment by PalmerAL** [comment]
It looks like the page has some JS that updates the URL as the page is scrolled, which causes [this code](https://github.com/minbrowser/min/blob/master/js/findinpage.js#L101-L105) to run when it shouldn't.
