### ISSUE TITLE
Sandboxing Issue.

### ISSUE THREAD

**Issue by Yusef-Aslam** [minbrowser/min#1139]
**Sandboxing issue:**
`The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /usr/lib/min/chrome-sandbox is owned by root and has mode 4755.
`

> _Reference: @Yusef-Aslam in https://github.com/minbrowser/min/issues/778#issuecomment-660332308_

**Comment by Syndamia** [comment]
Is there some other problem with sandboxing or are you just repeating issue #778?

**Comment by Syndamia** [comment]
Closed, because it looks like a duplicate of a comment in issue #778.
