### ISSUE TITLE
Support opening external links in apps

### ISSUE THREAD

**Issue by coder963** [minbrowser/min#1143]
when i am opening dialer url like following, it is going to search engine. It should open the dialer app. It works in chrome.
tel://987654210

**Comment by PalmerAL** [comment]
What do you mean by "dialer app"?

The general issue here is that we don't support opening links in external apps (except for mailto:, which is hard-coded). I think there may already be an issue for this, but I can't find it.

**Comment by coder963** [comment]
here dialer app means any app which is used for calling like skype/zoom. 

can this issue fix?

**Comment by coder963** [comment]
This issue is resolved.
