### ISSUE TITLE
when selecting text and copying, it also copies &nbsp;

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1149]
for example, if you copy [this](https://developers.google.com/maps/documentation/android-sdk/marker#java) code snippet and paste it inside any text editor it looks like this:

![image](https://user-images.githubusercontent.com/22417494/87951058-2a8f0d00-cab9-11ea-8a32-8f5b61fa866c.png)

**Comment by KagamineP** [comment]
Sorry, but I can't reproduce this on Windows. Can you explain, how you get that? Also, have you tried other text editor? (Sorry, sometimes my english bad because it's not my primary language). I've copied the code from the link, and there's no &nbsp
![Screenshot](https://user-images.githubusercontent.com/31146629/87979032-dbfa6680-caea-11ea-94bf-88dee10ca661.png)
;

**Comment by shalva97** [comment]
vscode shows it differently but it is same, for example:
![image](https://user-images.githubusercontent.com/22417494/88036268-5dd2aa00-cb54-11ea-83b4-b083dd277398.png)

normal spaces have more gray dots when you highlight it, the top function has twice as much dots.

try copying it from Chromium it will replace them with proper whitespace characters...

**Comment by Syndamia** [comment]
Hmm, this is wierd. For me it's fine. I pasted it in **Vim**, **xed** and **Atom** and it was fine, no wierd characters. Saving the text as files also didn't produce anything bizzare.

I did a hexdump and the result didn't show anything out of the ordinary:
 
![](https://i.imgur.com/vDgGecy.png)
*This is from the file saved in **Vim**, but **xed** and **Atom** had the same hexdump. I also tried saving it as a `.txt` file and got the same result. Files are saved with `UTF-8` encoding, so if it was there it should've shown up*

`7b` is the bracket, `0a` is the line feed (i.e. new line) and after that you only got `20` which are the whitespace characters.

@shalva97 Have you tried different clipboard managers? It seems that you are using **KDE**, so maybe try something other than the built-in on (**Klipper** if i'm not mistaken). 
I am using [**Parcellite**](http://parcellite.sourceforge.net/) so maybe try using that (*I don't know if it will work on **KDE** but give it a try, maybe even try out some others*).

Also, it could very well be me, **Parcellite** might be doing something and replacing the `&nbsp;`, more testing needs to be done. I might set up a **KDE** virtual machine later and test it even more.

**Comment by shalva97** [comment]
okay, i just noticed you have to copy it by Right click -> Copy. Maybe you used CRTL + C? because keyboard shortcut works fine

Disabling/enabling Klipper has no effect...

and here is my hexdump:
![image](https://user-images.githubusercontent.com/22417494/88476636-f731ff80-cf4a-11ea-8b53-263db0360d57.png)

**Comment by PalmerAL** [comment]
I can reproduce on macOS if I copy from the context menu. The original HTML is something like:

```
&nbsp; &nbsp; &nbsp;
```

And when it's copied, it gets copied as an alternating sequence of regular spaces (The `20` bytes), and [non-breaking spaces](https://en.wikipedia.org/wiki/Non-breaking_space), which are `c2 a0`.

I don't really understand Unicode all that well, and I'm not sure where these are supposed to be converted to normal spaces, but if I make this change, it seems to work correctly:

```diff
--- a/js/webviewMenu.js
+++ b/js/webviewMenu.js
@@ -186,7 +186,8 @@ const webviewMenu = {
       clipboardActions.push({
         label: l('copy'),
         click: function () {
-          clipboard.writeText(selection)
+          // clipboard.writeText(selection)
+          webviews.callAsync(tabs.getSelected(), 'copy')
         }
       })
     }
```

**Comment by shalva97** [comment]
iam happy you where able to reproduce it. just found out it also happens on NPM website...

Did you pushed that changes? i cannot find it

**Comment by PalmerAL** [comment]
I've pushed that change, if you could test whether it works that would be great.

**Comment by Sestowner** [comment]
> I've pushed that change...

It works for me.

**Comment by shalva97** [comment]
it also works for me. nice nice

**Comment by KagamineP** [comment]
It also works for me.

**Comment by PalmerAL** [comment]
Great!
