### ISSUE TITLE
A Java Script error occured in the main process

### ISSUE THREAD

**Issue by marklin0913** [minbrowser/min#1150]
Hi.I recently saw this popped up when using the MIn browser. And I think this may be helpful for the development.
![Screenshot_20200721_183440](https://user-images.githubusercontent.com/60455393/88046668-fa13a580-cb82-11ea-8498-7ffd73a3a08c.png)

**Comment by PalmerAL** [comment]
I think this was probably fixed in b99a3e28e41e58220e12c5a1b23a44272aadf9d7; can you test this again in the next release (which will come out in a couple weeks), and let me know if it's still happening then?
