### ISSUE TITLE
Video content changing in "picture in picture" crashes if the video is playing in a tab that doesn't have focus.

### ISSUE THREAD

**Issue by clayton-grey** [minbrowser/min#1154]
Like the title suggests, if I am playing a video using the picture in picture feature, the browser crashes if the video changes. 

Specifically, the "src" property of a video element is being changed, and play is being called there after. The crash doesn't happen if the tab playing the video has focus. 

Tested in 1.15.

**Comment by Sestowner** [comment]
I can't reproduce this.
**OS**: Linux Mint 20
**Min**: 1.15.0

**Comment by clayton-grey** [comment]
Seems reasonable that it could be OSX specific. I can confirm the crash also happens if you resize the PiP window while the tab doesn't have focus.

**Comment by Sestowner** [comment]
I can't reproduce this on Windows 7 either.

**Comment by PalmerAL** [comment]
I can reproduce as well on macOS 10.15. Best thing to do is probably to write a testcase and report it to Electron at some point.

**Comment by flightmansam** [comment]
@PalmerAL This is no longer a problem in electron 19.0.1. However there is a problem with drawing the PIP controls overlay (just shows red), https://github.com/electron/electron/issues/34406
