### ISSUE TITLE
Hotkeys for jumping to the top and bottom of a page

### ISSUE THREAD

**Issue by nedart** [minbrowser/min#1162]
There are a number of extensions for Chrome and Firefox that do this. Myself I just use a javascript bookmark in my bookmarks bar to quickly snap to the top or bottom of a page. Min has no such functionality and I would love to have these hotkeys.

**Comment by PalmerAL** [comment]
This is part of the vim-mode userscript: https://github.com/palmeral/min-vim-mode.
