### ISSUE TITLE
Userscripts/styles

### ISSUE THREAD

**Issue by bmollot** [minbrowser/min#117]
I understand not wanting to implement extensions, as that sounds very difficult. As an alternative, I suggest having some way to load custom scripts on domains matching a regex of the user's choosing.

**Comment by ThemeDork** [comment]
I would like to second the motion for supporting userscripts, or something similar. Of course, a night mode would also be sufficient for myself, similar to what you see in some of the mobile browsers, adding a dark theme to most websites.

**Comment by PalmerAL** [comment]
I've created a PR for this: #525. You can place javascript files in the ```userscripts``` directory of your profile folder ( ```~/library/application support/min/userscripts``` on mac, ```\users\username\appdata\roaming\min\userscripts``` on windows, and ```/home/username/.config/min/userscripts``` on linux), where the filename is the domain name + .js (such as "github.com.js"). Once this has been released, I'll add documentation to the wiki about it.

**Comment by PalmerAL** [comment]
This has been implemented in #525; it will be included in the 1.8.0 release. I've opened a new issue to add documentation for this: #548.
