### ISSUE TITLE
raw github content is with too big font

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1177]
* **Min Version:** 1.15.0
* **Operating system:**  Arch linux KDE

## Expected Behavior
for example if i go to this [text file](https://raw.githubusercontent.com/shalva97/dotFiles/master/packageListServer.fish), font should be just like any other website

## Actual Behavior
font is too big
![image](https://user-images.githubusercontent.com/22417494/88914030-0a0e4200-d273-11ea-8123-c80bc0913881.png)

## To Reproduce
go to this [file](https://raw.githubusercontent.com/shalva97/dotFiles/master/packageListServer.fish)

**Comment by idAlencar** [comment]
- Min Version: 1.15.0
- Operating system: Manjaro


I see normal
![Captura de tela de 2020-07-30 07 48 26](https://user-images.githubusercontent.com/58848807/88914720-694f6080-d239-11ea-9dfb-dda657c2c8a2.png)

**Comment by Sestowner** [comment]
I can't reproduce this either.
**OS**: Linux Mint 20
**Min**: 1.15.0

@shalva97 Try to press <kbd>Ctrl+0</kbd>.

**Comment by shalva97** [comment]
@Sestowner ctrl+0 worked :D 

not sure why it was zoomed

**Comment by shalva97** [comment]
ohhh i figured it out

zoom is shared between this [image](https://raw.githubusercontent.com/mobile-roadmap/android-developer-roadmap/master/images/android_roadmap.png) and [this text file](https://raw.githubusercontent.com/shalva97/dotFiles/master/packageListServer.fish). Zooming in one of them also zooms in another.

This feels wrong, why would it work like this?

**Comment by shalva97** [comment]
wait i think i got it. it is from same domain so it should save zoom. sorry guys i forgot about that...
