### ISSUE TITLE
setup not working for win 32 bit system

### ISSUE THREAD

**Issue by coder963** [minbrowser/min#1179]
it is not working for 32 bit windows system.

**Comment by PalmerAL** [comment]
I think the installer is 64-bit only, but the ZIP file download should work - can you try running this: https://github.com/minbrowser/min/releases/download/v1.15.0/Min-v1.15.0-win32-ia32.zip, and see if that works?

**Comment by coder963** [comment]
but the zip file has all the source code and it is much larger than installer file. is this ok?

**Comment by PalmerAL** [comment]
The zip file has the app resources separate from the main executable, but it should still work as long as you copy the entire folder.

The zip file is the same download size (71mb) as the installer (72mb); are you sure you're using the right one? (You want the "-ia32" zip, not the "source code" one).

**Comment by Syndamia** [comment]
Quoting from the Discord server:

> Quick update on the 1.17 release: this release includes a native module that needs to be compiled for the first time, and I can't get cross compilation (building for a different architecture than the build machine) to work: https://github.com/electron/electron-rebuild/issues/494
As a result, the Windows build for this release is going to be 64-bit only.
After this, I'm hoping to move the build process to github actions, which would allow us to add back 32 but windows builds and support ARM.

So this issue is outdated.
