### ISSUE TITLE
Not able to login to Google

### ISSUE THREAD

**Issue by mhamzas** [minbrowser/min#1183]
This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

![image](https://user-images.githubusercontent.com/4003164/89546039-8a0d4c80-d81d-11ea-801f-d1802b9784e6.png)

**Comment by Syndamia** [comment]
Hello @mhamzas, this is a known issue (it's practically the same as [not being able to sign into gmail](https://github.com/minbrowser/min/issues/868)). Refer to [this comment](https://github.com/minbrowser/min/issues/1123#issuecomment-657094959) for a fix.
