### ISSUE TITLE
change name for custom search engines in right click menu

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1186]
**Can you describe the problem you're facing?**
i have switched to my own Searx instance and added it to Min. There is "search with custom"  in the right click menu and it just doesnot look right....

**What solution would you like?**
It would be better if there was a way to name what search engine i have added and it would show up like this: "search with Searx"

**Are there any alternatives you've considered?**
domain from custom search engine url

**Comment by PalmerAL** [comment]
The domain approach would likely be simpler to implement; I'd be fine with doing that if that works for you?

**Comment by shalva97** [comment]
umm, maybe choseing a name will be better but... idk... okay let it be just a domain from the url

**Comment by shalva97** [comment]
nice <3
