### ISSUE TITLE
Text selection rendering issue in PDF

### ISSUE THREAD

**Issue by ajinkya-k** [minbrowser/min#1187]
When selecting text in a PDF, the selected text is occluded by a black shadow of the selected text with a white overlay. This hazing is more pronounced on a 4K display. See picture below: 

1080p  screen: 
![Screenshot (4)](https://user-images.githubusercontent.com/5984449/89666322-c6818c80-d89f-11ea-9143-288743dfffb5.png)

4K screen: 
![Screenshot (39)](https://user-images.githubusercontent.com/5984449/89666334-cbded700-d89f-11ea-9776-3bbe8d757e34.png)

**Comment by PalmerAL** [comment]
Thanks for reporting, fixed in cb46308e472b3ca509bcbd2ad8e794ade644ee91.

Is this a copy of Min you built yourself, or the released version? I thought this was only an issue in Chromium 83/Electron 9, but that hasn't been released yet, so now I'm wondering if this is an issue in the released version as well.

**Comment by ajinkya-k** [comment]
> Thanks for reporting, fixed in [cb46308](https://github.com/minbrowser/min/commit/cb46308e472b3ca509bcbd2ad8e794ade644ee91).
> 
> Is this a copy of Min you built yourself, or the released version? I thought this was only an issue in Chromium 83/Electron 9, but that hasn't been released yet, so now I'm wondering if this is an issue in the released version as well.

This is in the release version on the min website. How do I fix this in my own installation? I am using windows 10 and I cant seem to find the directory where it is installed. If you can point me to where the css file is I can replace on my machine.

**Comment by PalmerAL** [comment]
Interesting, thanks. The CSS file is here: `C:\Users\username\AppData\Local\min\app-1.15.0\resources\app\pages\pdfViewer\viewer.css`.
