### ISSUE TITLE
Preference: Don't jump to new tab

### ISSUE THREAD

**Issue by surajsharma** [minbrowser/min#119]
in 1.1.2, the viewport is hostage to every new tab opened. this shouldn't be the case or ideally, there should be a toggle somewhere that allows opening tabs in the background.

**Comment by burnoutberni** [comment]
You can click on links with your middle mouse button and it will open the link in a background tab.

**Comment by surajsharma** [comment]
no middle mouse button the trackpad (macbook)

**Comment by n3storm** [comment]
https://discussions.apple.com/thread/4026598?tstart=0
Two suggestions: two fingers tap or cmd+right click button

I cannot check this as I am a Linux users and we had middle clicking and emulating middle clicking through cliking two buttons simultaneously since ages.

**Comment by PalmerAL** [comment]
Would it be better to just make opening in background the default? Chrome, safari, and firefox all do this, so it might be better to just copy their behavior.

**Comment by surajsharma** [comment]
that is precisely the behaviour i would like to see, jumping to new tab is obnoxious and "open in new tab" also jumps to the new tab so the only option i have for now is cmd+click which is counterintuitive

**Comment by cryptobird** [comment]
I like the jumping to a new tab when you right click and open a link. Plus, when you ⌘-click a link it opens in the background.

**Comment by semtize** [comment]
Any updates as to whether this will be included or not? Would love to have it as a toggable option.
