### ISSUE TITLE
Support for Dashlane

### ISSUE THREAD

**Issue by chansantheman** [minbrowser/min#1191]
**Can you describe the problem you're facing?**
By far my favorite browser and cannot stop using it, but I found myself using it less and less these past few weeks due to having to log into dashlane on the web browser to just sign in to a webpage. Major hassle every time.

**What solution would you like?**
Support for Dashlane. Win 10

**Are there any alternatives you've considered?**
None that I know of.

**Comment by Milad-Laly** [comment]
I believe that dashlane makes their own extensions so this might not be possible. They have a standalone extension that works for chromium based browsers. However, min isn't chromium.
I can't find API keys or anything to connect to their servers using any programming language on their website.

I'll try and contact their support to see if they have a solution. However, I highly believe they won't be helpful. I'll be closing this issue and reopen it there is a solution.
