### ISSUE TITLE
Secure Playback (Spotify Web)

### ISSUE THREAD

**Issue by Noobie99** [minbrowser/min#1192]
**Can you describe the problem you're facing?**
Spotify Web ([https://open.spotify.com/](url)) requires secure playback to run.

I could not find a way to enable secure playback. Is there any way to do it?

**Comment by PalmerAL** [comment]
This is the same issue as #161; unfortunately, it isn't possible to fix this, because Google won't provide a license for the required component: https://blog.samuelmaddock.com/posts/the-end-of-indie-web-browsers/
