### ISSUE TITLE
Productivity/Usability Addons

### ISSUE THREAD

**Issue by ndrogers** [minbrowser/min#1198]
Chrome and Firefox have addons that make me bound to them. One such addon is "vimium" which allows me to navigate the web using only my keyboard. 

It would be nice to have the capability to add chrome addons, not only to have a simple browser, but to have a simple browser that I can build out with addons to suit my needs.

**Comment by PalmerAL** [comment]
Compatibility with existing WebExtensions is fairly difficult and requires a large amount of work, so it's unlikely to happen soon. However, Min does have [userscripts](https://github.com/minbrowser/min/wiki/userscripts) that can do many of the things that addons can. In particular, there's a userscript for Min that implements many of the features of Vimium: https://github.com/palmeral/min-vim-mode.
