### ISSUE TITLE
Option to stop autoplaying media

### ISSUE THREAD

**Issue by Nesaijn** [minbrowser/min#1199]
**Can you describe the problem you're facing?**
When opening, for example YouTube videos in another tab, min automatically starts playing the video.

**What solution would you like?**
An option to disable autoplay of media when no focus is given to the tab.

That is something I would like to see since I often open several videos back to back in a new tab.

**Comment by PalmerAL** [comment]
Autoplay will be disabled by default starting in the next release: 83357fdfe93cb25aa50c458179ba8a185fb1e962

**Comment by shalva97** [comment]
Autoplay is still disabled in 1.21.0, right? Im getting reddit adds getting autoplayed.

**Comment by PalmerAL** [comment]
It should be (and I'm seeing autoplay disabled on Youtube, so it's at least partially working). Chromium has some exceptions where autoplay is still allowed - if there's no sound I think, or if there's high "media engagement" on that site. There might be a flag to turn that off, but I don't recall seeing one.
