### ISSUE TITLE
Include more filtering lists

### ISSUE THREAD

**Issue by Nesaijn** [minbrowser/min#1200]
**Can you describe the problem you're facing?**
There are still some pop ups and ads I am facing. I have seen that min uses two lists, 
easylist.to/easylist/easylist.txt
and
easylist.to/easylist/easyprivacy.txt
I have also seen that EasyList for example has one more list which includes more entries.
https://easylist.to/easylist/fanboy-annoyance.txt
I tried adding it manually to the easylist+easyprivacy-noelementhiding.txt list but it did not help.
But I do know that UBlock Origin handles it well.

**What solution would you like?**
I saw on UBlock Origins site that there are the methods and lists used to filter requests. Maybe include them too?
https://ublockorigin.com/, at the bottom on the right inside the footer.

**Are there any alternatives you've considered?**
Or is this something I should report to the EasyList guys?

**Comment by PalmerAL** [comment]
Editing the txt file should work, what's the exact path of the file you modified?

I think I'm going to add an option to save a custom filter list in the user data directory to make this easier.

**Comment by Nesaijn** [comment]
Since I am on Linux it was this one:
`/usr/lib/min/ext/filterLists/easylist+easyprivacy-noelementhiding.txt`

It was probably just that the list did not include the entries that would have helped with the ads and pop ups I was facing. Maybe I have to include more lists.
But I wasn't sure if just adding them to the list would be a good solution, since it is getting updated by min and would override the changes I make. Also I didn't understand the "no element hiding" changes that are being made before creating the .txt file.

**Comment by PalmerAL** [comment]
That's definitely the right file. You'll need to restart Min after modifying it; that could potentially be the issue as well.

[Element hiding](https://adblockplus.org/filter-cheatsheet#elementhiding) rules aren't supported by Min, so they're removed from the default list. You can still include them in your own list though, they just won't do anything.

**Comment by Nesaijn** [comment]
I will experiment a bit with the list and see where it takes me. Maybe I will find a configuration that makes me satisfied.

**Comment by PalmerAL** [comment]
One other thing I realized while working on this: if you have the default setting of "block third-party ads and trackers" enabled, then custom filters you add won't apply to 1st-party resources; you need to enable the "block all" option for that.

**Comment by Nesaijn** [comment]
Oh, that is good to know.
