### ISSUE TITLE
1Password integration fails to load some passwords

### ISSUE THREAD

**Issue by CLBarajas** [minbrowser/min#1201]
* **Min Version:** 1.15.0
* **Operating system:** macOS 10.15.6
* `op` version: 1.4.0

```
barajas@MacBook-mini ~ % op update
1Password command-line tool 1.4.0.

You're using the latest version.
```

## Expected Behavior
Using the keyboard shortcut to load a password will successfully do so, or provide a drop-down menu for different options if they exist.

## Actual Behavior
No password entered, and key icon turns red.

## To Reproduce
1. Load a web page.
2. Use keyboard shortcut to enter password.
3. Enter master password as prompted.
4. Password does not fill, key icon turns red.

When inspecting the browser and reloading the page, there was an error reported in the Console:

```
bundle.js:4138 loadSuggestions
bundle.js:4141 got data of length  0
bundle.js:4178 Error accessing 1Password CLI. STDOUT: undefined. STDERR: undefined SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at OnePassword.loadSuggestions (bundle.js:4143)

loadSuggestions @ bundle.js:4178
async function (async)
loadSuggestions @ bundle.js:4140
getSuggestions @ bundle.js:4125
(anonymous) @ bundle.js:4330
Promise.then (async)
(anonymous) @ bundle.js:4315
(anonymous) @ bundle.js:9507
(anonymous) @ bundle.js:9505
emit @ events.js:210
onMessage @ init.ts:51
```

**Comment by PalmerAL** [comment]
How many passwords do you have saved? This looks like it might be the same as https://github.com/minbrowser/min/issues/1028#issuecomment-647235653

**Comment by CLBarajas** [comment]
My vault has 551 items, so I'm not sure that's it. If you know a way I can check that against your size limitations I could get a better sense of what's going on there.

**Comment by PalmerAL** [comment]
The original limit was 1MB, so that may not be it. Can you try it with the latest version from the repository?

```
git clone https://github.com/minbrowser/min.git
cd min
npm install
npm run start
```

**Comment by CLBarajas** [comment]
I tried both the `run start`, and the `run buildMac` option. Both apps result in the same "silent" (red key) failure, with limited console info:

```
bundle.js:4279 loadSuggestions
bundle.js:4282 got data of length  278569
bundle.js:4285 got matches of length 553
```

The public release at least failed with some more obvious information:

```

bundle.js:4138 loadSuggestions
bundle.js:4141 got data of length  278569
bundle.js:4144 got matches of length 553
bundle.js:4161 looking up credential, index  0
bundle.js:4165 got credential output of length  838
bundle.js:4178 Error accessing 1Password CLI. STDOUT: undefined. STDERR: undefined TypeError: Cannot read property 'value' of undefined
    at OnePassword.loadSuggestions (bundle.js:4167)
```

**Comment by PalmerAL** [comment]
Can you try adding these lines to `js/passwordManager/onePassword.js`, and posting the output?

```diff
diff --git a/js/passwordManager/onePassword.js b/js/passwordManager/onePassword.js
index 4b71afd7..0ce546f3 100644
--- a/js/passwordManager/onePassword.js
+++ b/js/passwordManager/onePassword.js
@@ -100,7 +100,7 @@ class OnePassword {
   // Loads credential suggestions for given domain name.
   async loadSuggestions(command, domain) {
     try {
-      console.log("loadSuggestions")
+      console.log("loadSuggestions", domain)
       let process = new ProcessSpawner(command, ['list', 'items', '--session=' + this.sessionKey])
       let data = await process.executeSyncInAsyncContext();
       console.log("got data of length ", data.length);
@@ -119,6 +119,7 @@ class OnePassword {
           return false;
         }
       });
+      console.log("got credentials for domain", credentials.length)
 
       var expandedCredentials = [];
 
@@ -131,6 +132,9 @@ class OnePassword {
         var usernameFields = credential.details.fields.filter(f => f.name == "username")
         var passwordFields = credential.details.fields.filter(f => f.name == "password")
 
+        console.log('got credential, ', (usernameFields.length > 0 ? usernameFields[0].value : 'no username'))
+        console.log("has password?", passwordFields.length > 0)
+
         if (usernameFields.length > 0 && passwordFields.length > 0) {
           expandedCredentials.push({
             username: usernameFields[0].value,
```

Also:
* What's the URL of the page you're trying to sign in to?
* If you open 1password and find the credentials for that site, what's in the "website" field?
* Does it work if you try a different site?

**Comment by CLBarajas** [comment]
Some sites work and others don't - for example, I successfully got credentials for Fastmail, but not GitHub.

On re-checking the entry in the main 1Password app, I discovered the user name is listed under different fields between the main login area and the "Saved Form" / "Web Form Details" area: the `username` at top is listed as a `login` lower down.

**Comment by CLBarajas** [comment]
Manually changing the `login` item in the Web Form Details area to be `username` got GitHub working properly, but I'd prefer a solution that doesn't involve auditing my entire vault.

**Comment by PalmerAL** [comment]
Can you try this and see if it works?

```diff
diff --git a/js/passwordManager/onePassword.js b/js/passwordManager/onePassword.js
index 4b71afd7..5a5539bf 100644
--- a/js/passwordManager/onePassword.js
+++ b/js/passwordManager/onePassword.js
@@ -100,7 +100,6 @@ class OnePassword {
   // Loads credential suggestions for given domain name.
   async loadSuggestions(command, domain) {
     try {
       console.log("loadSuggestions")
       let process = new ProcessSpawner(command, ['list', 'items', '--session=' + this.sessionKey])
       let data = await process.executeSyncInAsyncContext();
       console.log("got data of length ", data.length);
@@ -131,6 +130,10 @@ class OnePassword {
         var usernameFields = credential.details.fields.filter(f => f.name == "username")
         var passwordFields = credential.details.fields.filter(f => f.name == "password")
 
+        if (usernameFields.length === 0) {
+          usernameFields = credential.details.fields.filter(f => f.name == "login")
+        }
+
         if (usernameFields.length > 0 && passwordFields.length > 0) {
           expandedCredentials.push({
             username: usernameFields[0].value,
```

It's strange that there's too different names; I've only seen the `username` version when testing this before.

**Comment by CLBarajas** [comment]
OK, going over this a couple times, I don't think we necessarily want the `name` field - we want the `username` `designation`? Exporting an entry from `op` into JSON, I can see that out of the `fields` the username can be listed with an `email` or `login` `name` (along with a lot of other junk), but the right username should always have that `designation`.

That's all to say the recommended diff does not help in all situations.

**Comment by CLBarajas** [comment]
Also, related to this, is there any sort of timeout that can cause a silent failure? After a period of time I seem to lose the ability to fill in any passwords.

**Comment by PalmerAL** [comment]
Thanks for figuring that out; I didn't realize you could rename fields like that. Could you try the designation version and confirm that it works?
```diff
diff --git a/js/passwordManager/onePassword.js b/js/passwordManager/onePassword.js
index 4b71afd7..fbf9af6f 100644
--- a/js/passwordManager/onePassword.js
+++ b/js/passwordManager/onePassword.js
@@ -128,8 +128,8 @@ class OnePassword {
         let output = await process.executeSyncInAsyncContext()
         let credential = JSON.parse(output)
 
-        var usernameFields = credential.details.fields.filter(f => f.name == "username")
-        var passwordFields = credential.details.fields.filter(f => f.name == "password")
+        var usernameFields = credential.details.fields.filter(f => f.designation === "username")
+        var passwordFields = credential.details.fields.filter(f => f.designation === "password")
 
         if (usernameFields.length > 0 && passwordFields.length > 0) {
           expandedCredentials.push({
```

> Also, related to this, is there any sort of timeout that can cause a silent failure? After a period of time I seem to lose the ability to fill in any passwords.

The 1password CLI gets run synchronously (on a separate thread), so I guess if one of the calls to it hung, it could cause that. Do you see any errors in the console when that happens? If you don't, and you can reproduce it, I can make a patch with some more logging to hopefully show the issue.

**Comment by CLBarajas** [comment]
It looks like the `designation` is working more reliably, thanks.

If I can better reproduce the other error after being logged in, I can check for any errors and run through repro steps and file a new issue there.

**Comment by PalmerAL** [comment]
Thanks for testing that!

If you run into the other issue again, please do make another issue and let me know.
