### ISSUE TITLE
Min cannot minimize

### ISSUE THREAD

**Issue by flber** [minbrowser/min#1212]
Min version: 1.15.0
OS: Bunsenlabs Lithium

## Expected Behavior
Pressing the minimize button in the upper right hand corner of the window should minimze the window.

## Actual Behavior
It does not minimze

## To Reproduce
Run min on lithium?

**Comment by Sestowner** [comment]
This should be fixed in the next release by 99d94d06874253da1ff66bfe79f00ad2727b103d.

**Comment by flber** [comment]
Okay, great
