### ISSUE TITLE
Google login services Unavailable

### ISSUE THREAD

**Issue by Pinhotx** [minbrowser/min#1218]
When I try to sign in on google services, I am blocked by google saying this browser its not secure.

**Comment by Sestowner** [comment]
Which version of Min do you use? If you are still using 1.15 or below, upgrading to the [latest version](https://github.com/minbrowser/min/releases/latest) should solve the problem.

**Comment by Pinhotx** [comment]
Thank you. You right I was really using the old version. I didn't see that lol.

**Comment by PalmerAL** [comment]
@Pinhotx Did it work in the updated version?

**Comment by Pinhotx** [comment]
Yes. Thank you.

Em dom., 30 de ago. de 2020 às 00:04, PalmerAL <notifications@github.com>
escreveu:

**Comment by Pinhotx** [comment]
Yes. Thank you
