### ISSUE TITLE
Min fails to run on windows 10

### ISSUE THREAD

**Issue by flber** [minbrowser/min#1219]
Min version 1.16.0
Windows 10

## Expected Behavior
After the download and running of the installer, Min should be able to run

## Actual Behavior
On launch, Min fails with this error:
<img width="418" alt="min_error" src="https://user-images.githubusercontent.com/42008155/91603438-d847d400-e921-11ea-8d5f-8c236be9f6fa.png">

## To Reproduce
I'm not sure what specifically, other than downloading and running the installer

Additionally, building from the source also throws the same error

**Comment by PalmerAL** [comment]
It looks like your settings file is corrupted somehow, can you do this:

1. Post the contents of `\users\username\appdata\roaming\min\settings.json`.
2. Depending on the contents of the file, you might be able to edit it to fix it; otherwise, deleting it and restarting Min should work.

**Comment by flber** [comment]
Here are the contents of my settings.json file:
`{"darkMode":1,"searchEngine":{"name":"Google"},"passwordManager":{"name":"1Password"},"filtering":{"blockingLevel":2,"contentTypes":[],"exceptionDomains":[]},"keyMap":{"enterEditMode":"mod+l","fillPassword":"option"},"filteringBlockedCount":25786,"proxy":{"type":0},"openTabsInForeground":false,"customUserAgent":null}}l}`

**Comment by PalmerAL** [comment]
It looks like deleting the `l}` at the end should fix it in this case.

I'm not sure what a more general solution to this would be. I've seen this a few times before on Windows, so there's probably a bug somewhere in Electron or Node that's causing this, but without a consistent way to reproduce it I'm not sure there's much that can be done.

In Min, we could discard the settings file whenever it becomes corrupted, but I'm not sure unexpectedly losing settings would be any better.

**Comment by flber** [comment]
Hmm, it's throwing the same error after I removed the `1}`, rebuilt, and ran the installer.

**Comment by flber** [comment]
Oh well, I just deleted settings.json and it worked. Thanks for the help!

**Comment by flber** [comment]
Interesting, now settings.json is only storing `{"filteringBlockedCount":116}`

**Comment by PalmerAL** [comment]
I think I missed a character; you actually need to remove `}l}`. Sorry about that.

> Interesting, now settings.json is only storing {"filteringBlockedCount":116}

Settings only get saved once you change them from the default, so that's expected.

> when I change any of the settings it clears everything in the settings.json file, which seems undesirable

Are you editing the settings in an editor while Min is running? Min keeps an in-memory of the settings and saves the file based on that, so editing them externally while the browser is running won't work. Otherwise, I'm not sure what could cause that.

**Comment by flber** [comment]
Well anyway, after getting back to my windows machine I fixed the json, built from source, ran the installer, and now everything is working fine!
