### ISSUE TITLE
How do I run browser on OS X?

### ISSUE THREAD

**Issue by olgi3rd** [minbrowser/min#122]
I read README.md and I followed all instructions.

How do I run browser? What do I type in terminal?

**Comment by cryptobird** [comment]
@olgierd-on-fire you might try using the pre-built binary, I'm fairly certain it's up to date with the most recent changes! you can find it [here](https://palmeral.github.io/min)!

**Comment by PalmerAL** [comment]
@olgierd-on-fire If you just want to use Min, you can download a binary from the link @cryptobird mentioned above. If you want to develop it, you need to follow the instructions listed in the readme, and then launch it:

* Download a copy of electron from <a href="https://github.com/electron/electron/releases/tag/v0.37.1">here</a>.

* In the terminal, type the path to electron, followed by the path to min. Assuming min is in your documents folder, and electron is in your applications folder, it would look like this:

```
/Applications/Electron.app/Contents/MacOS/Electron /Users/username/Documents/Min
```

**Comment by glensimister** [comment]
Hi. I would like to know this too. I've already installed the binaries but i'd like to run Min from source. I've been working on a super-light-weight cryptocurrency which uses a browser extension along with GunDB. I'm exploring the possibility of building it into a browser. So how do i actually run Min from command line? I have followed the readme instructions but im not sure where to go from there. Thanks

**Comment by tjim** [comment]
Just tried this with node 6.2.0, electron 1.2.0 as well as 0.37.1. Something goes wrong on startup (window comes up blank), first error in console log is

    Uncaught TypeError: currentTask.tabs.add is not a function

Debugging shows that currentTask.tabs is an empty array.

**Comment by abrarShariar** [comment]
Is there any other instances of Min running at that moment? @tjim

**Comment by dbfreem** [comment]
This seems old and could probably be closed @PalmerAL

**Comment by PalmerAL** [comment]
Probably so, @olgi3rd please open another issue if you have any more problems.
