### ISSUE TITLE
Can't Mute Tab

### ISSUE THREAD

**Issue by iFarhaan** [minbrowser/min#1221]
While playing media in the website the tab can't be **muted**. Neither it shows any option in the **GUI** nor it supports **hotkeys**.

Almost Every Web Browser has this feature. We would like to have this in **Min** too. Such as speaker appearance in tab corner **while playing media** which can be toggled using **GUI** and hotkeys shortcut like **Ctrl+M**.

**Comment by BenStigsen** [comment]
The ability to mute tabs from the GUI is now available in [version 1.17.1](https://github.com/minbrowser/min/releases/tag/v1.17.1)
