### ISSUE TITLE
Question: Handling Zoom Meeting Url

### ISSUE THREAD

**Issue by iambudi** [minbrowser/min#1224]
Hi, 

Can min browser be configured to automatically open zoom meeting app when the url started with zoommtg:// ? Currently min pop up zoom pkg installer download instead.

Thanks.

**Comment by PalmerAL** [comment]
I don't think Electron has the API's to handle opening arbitrary external protocols, but Zoom is a common enough usecase that we could probably add a special handler for it (like what we do with [mailto](https://github.com/minbrowser/min/blob/master/main/main.js#L381-L383)).
