### ISSUE TITLE
Is there a way to customize the Menus' keybindings?

### ISSUE THREAD

**Issue by ashfinal** [minbrowser/min#1225]
For instance, I would like to change the default `Print(Ctrl+p)` to something else, what should I do? I found `menu.js` under `./resource/app/main/` folder, and changed the corresponding accelerator value, but that seemingly doesn't  work.

Thanks for your awesome work. :)

**Comment by PalmerAL** [comment]
You would need to edit `./resources/app/main.build.js`.

We could probably add that keybinding to the list of editable ones in the settings as well.

**Comment by ashfinal** [comment]
I modify the file as you said, and succeed(there is only one occurrence needed to do so). Cool!

As for adding the keybindings in settings, I think documenting this in wiki should suffice. Just my two cents. 😄
