### ISSUE TITLE
Nova versão do Min para Arch Linux?

### ISSUE THREAD

**Issue by ArthurSerp** [minbrowser/min#1228]
Quando sairá a versão 1.16 do Min para o Arch Linux?

**Comment by PalmerAL** [comment]
(Do Google Translate)

O pacote Arch é construído por um mantenedor separado, então não é algo sobre o qual tenhamos controle. Ele geralmente o atualiza rapidamente, mas se não estiver disponível em alguns dias, você pode tentar contatá-lo.
