### ISSUE TITLE
Preference/default change: ⌘1 goes left a tab, ⌘2 goes right. 

### ISSUE THREAD

**Issue by cryptobird** [minbrowser/min#123]
This is simply my personal preference for navigating tabs in a browser. I've tried to get used to this style of navigation, but because I jump tabs quite a bit it's just one too many keypresses. I 100% understand if you'd rather have the default as it is, but I would love to see a setting so that I can tabinate comfortably!

**Comment by cryptobird** [comment]
woops. should've dug through the issues, looks like similar issues abound. Perhaps a settings page is in order :/

**Comment by Zhomart** [comment]
Quick changing tabs using shortcuts ⌘1, ⌘2, ⌘3, ⌘4, ... would be awesome too.

**Comment by antfu** [comment]
Close in favor of #38

**Comment by antfu** [comment]
Close in favor of #38
