### ISSUE TITLE
1Password integration fails after a period of time

### ISSUE THREAD

**Issue by CLBarajas** [minbrowser/min#1235]
* **Min Version:** 1.16.0
* **Operating system:** macOS 10.15.6 

## Expected Behavior
After token expires, new password fill attempts prompt for another unlock.

## Actual Behavior
Silent password fill failure, on pages that have previously worked to unlock.

## To Reproduce
* Launch min
* Utilize 1Password fill successfully
* Use browser for an extended period of time without filling a password

## Workarounds
Quit and re-launch to restore session, and get prompted for a master password.

## Notes
This is a follow-up from the secondary issue reported in #1201, so I imagine I'll need some better logging to identify the source of the trouble.

**Comment by PalmerAL** [comment]
Argh, I missed this line in the 1password documentation when implementing this:

> Session tokens expire after 30 minutes of inactivity, after which you’ll need to sign in again.

So we'll need to add a method to sign in again and retry if retrieving the passwords fails.
