### ISSUE TITLE
Building Min on 32bit Ubuntu 16.04

### ISSUE THREAD

**Issue by 097115** [minbrowser/min#1240]
While building Min on this old 32bit Ubuntu (node 12.9.1, npm 6.10.2) with `npm run build && node ./scripts/buildDebian.js --platform=x86`, I encounter the following error (full log [here](http://ix.io/2xmO)):

    Packaging app for platform linux arm64 using electron v9.2.1
    Creating package (this may take a while)
    Error: could not find the Electron app binary at "dist/app/Min-linux-ia32/min". You may need to re-bundle the app using Electron Packager's "executableName" option.
        at /home/me/test/min/node_modules/electron-installer-common/src/installer.js:154:15
        at async Promise.all (index 3)
        at async module.exports (/home/me/test/min/node_modules/electron-installer-debian/src/installer.js:245:3) Error: could not find the Electron app binary at "dist/app/Min-linux-
    ia32/min". You may need to re-bundle the app using Electron Packager's "executableName" option.
        at /home/me/test/min/node_modules/electron-installer-common/src/installer.js:154:15
        at async Promise.all (index 3)
        at async module.exports (/home/me/test/min/node_modules/electron-installer-debian/src/installer.js:245:3)

Is it because of [this](https://www.electronjs.org/blog/linux-32bit-support), or is it possible to work around this error somehow?

The browser itself, though, is compiled correctly, can be launched via `./dist/app/Min-linux-ia32/Min`, and works just fine (and is really a godsend on this old machine ;)

So, is it just packaging that fails?

Building for 64bit OS, with `npm run build && node ./scripts/buildDebian.js --platform=amd64` works just fine, and `./dist/app/min_1.16.0_amd64.deb` is produced.

Thanks :)

**Comment by PalmerAL** [comment]
You'd probably need to add a platform definition [here](https://github.com/minbrowser/min/blob/master/scripts/createPackage.js#L43), probably like this:
```
  linuxia32: {
    name: 'min', // name must be lowercase to run correctly after installation
    platform: 'linux',
    arch: 'ia32'
  },
```

And then add a case in `toTarget`(https://github.com/minbrowser/min/blob/master/scripts/buildDebian.js#L7) that converts `x86` to `linuia32`.

I'm actually really surprised that this works, given that Chromium dropped support for it. It doesn't make sense to have prebuilt binaries for something that isn't supported, but it might be useful to document somewhere that it's possible to do this.

**Comment by 097115** [comment]
@ PalmerAL, Thanks, it worked! :)
