### ISSUE TITLE
Stop marketing this as a fast and minimal web browser

### ISSUE THREAD

**Issue by traffic-cone420** [minbrowser/min#1241]
# This web browser is basically the farthest you can get from fast or minimal.
This is one of the slowest and most bloated programs I have ever seen. I mean min literally uses electron. You are using what's considered a bloated web browser, to render your web browser. I swear the next release will be written in elisp serialized as xml jited to jvm running as an eclipse plugin on a mac running in a virtual pc in a xen instance on chromium. You can write slow bloated web browsers in electron all you like as long as you aren't marketing it as fast and minimal.

**Comment by gordonfreeman424** [comment]
I mean its faster than windows
go eat something

**Comment by PalmerAL** [comment]
A web browser is made up of two things:

* The rendering engine
* A UI layer on top of that

Electron is just Chromium + some APIs to access native platform features, and Min is just the UI layer on top of that, so the overall level of resource usage is (in theory at least) not significantly more than any other browser. In Firefox/Chrome/Safari/etc, you have a process running for each tab and a main process; Min uses the same architecture, except that there's one more process added to render the UI in.

If you have specific examples of situations where Min is using significantly more resources than other browsers, please open a more detailed issue for those.

Web browser resource usage can depend a lot on your specific usage patterns, and as a result it's hard to say if Chromium is really any more "bloated" than any other rendering engine, but if you feel that it is for your usecase, there are plenty of alternatives you can use.
