### ISSUE TITLE
Update Browser for Arch...

### ISSUE THREAD

**Issue by gray49** [minbrowser/min#1242]
Hello...I have been using Min for a while...Quite enjoy it...I am aware of the recent update, but have been unable to update because it doesn't seem to be available in the Arch repos for pamac or AUR...Just curious if there is a way to update or if it will be made available for Arch in the future...Thanks...Peace and health

**Comment by kodumbeats** [comment]
I'm working on a `PKGBUILD` file for Min 1.16.0. It installs correctly but still has a few kinks. Since the package exists in the [community repo](https://www.archlinux.org/packages/community/any/min/), I can't upload it to the AUR, per their rules.
Related discussion: #586

**Comment by gray49** [comment]
Thanks for the reply... I enjoy the browser very much and appreciate your efforts... I will keep using it and look for updates when available... Peace and health

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by kodumbeats** [comment]
I forgot to link the script, again🤦🏻 here you go:
https://github.com/kodumbeats/min-archlinux
