### ISSUE TITLE
Hover over download reveals detailed progress

### ISSUE THREAD

**Issue by kodumbeats** [minbrowser/min#1245]
For the tooltip, one thing I thought of is to make the file size number change to show the progress when you hover over it, like this:

normal:

<img width="365" src="https://user-images.githubusercontent.com/10314059/92034511-f2731f00-ed32-11ea-9752-84c5a95b6c76.png">

Hovering:

<img width="337" src="https://user-images.githubusercontent.com/10314059/92034484-ec7d3e00-ed32-11ea-9e20-84a340bf654b.png">

_Originally posted by @PalmerAL in https://github.com/minbrowser/min/issues/920#issuecomment-685988051_

**Comment by PalmerAL** [comment]
Sorry for the confusion, this was actually done in 36a4f03f875896a9ebefe353187aba78e3d84f2a.
