### ISSUE TITLE
Min Browser in Flatpak or AppImage instead of .rpm or .deb

### ISSUE THREAD

**Issue by diipe** [minbrowser/min#1249]
Please provide Min in **Flatpak** or **Appimage** for Linux, instead of RPM or DEB. 
This way, we will have no installation problems with unmet dependencies.

I'm an openSUSE TW user and I couldn't install Min due to the lack of these dependencies:
1. libdrm
2. ibxcb
3. mesa-libgbm 

greetings,
Diogo

**Comment by clyde5** [comment]
Opensuse has those packages but under different names, make sure they are installed then use rpmrebuild to remove those dependencies from the rpm or [download the one I made](https://siasky.net/AACmcPHVbA4fCdxbv55_pGdCedEW2Oz4X5H6hSw6EVcBpQ).
`c61ee77c30d5d42adeea71a16fda9b21adad5d431c3b3d079b6d65b0656d0979  min-1.16.0-1.x86_64.rpm`

https://software.opensuse.org/package/libdrm2
https://software.opensuse.org/package/libxcb
I couldn't find libgbm so it's probably already installed with some other wayland package

To make your own rpm without those dependencies using rpmrebuild if you don't trust me or min updates:

`rpmrebuild -ep min-1.16.0-1.x86_64.rpm`

scroll down to
```
Requires:      libdrm  
Requires:      libxcb  
Requires:      mesa-libgbm
```
and remove those lines

**Comment by clyde5** [comment]
But yeah if the creator wants to add appimages and other formats https://www.electron.build/ looks really useful

**Comment by diipe** [comment]
I was able to install it thanks to your help and goodwill. Thank you!
