### ISSUE TITLE
Sometimes tab title does not update when going back with mouse back button

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1259]
* **Min Version:** 1.16.0
* **Operating system:**  Arch Linux KDE

## Expected Behavior
page title should update when I press back button on the mouse

## Actual Behavior
nothing happens

## To Reproduce
go to this [website](http://nnmclub.to/) and click any post title. yeah, it is russian torrent website but couldnot reproduce on other websites easily. 

with xdotool if you dont have back button:
`sleep 2 && xdotool click 8`

**Comment by Syndamia** [comment]
I can easily reproduce it on YouTube by going on a video, from there going to the next video (`Shift + N`) and then going back (`Alt + LeftArrow`), the tab title doesn't correspond to the video I went back to.

Another way is to click on a file in a GitHub repo and then go back, the title doesn't get refreshed.

**OS**: Linux Mint 20 Cinnamon
**Min version**: 1.16.0 (although I think I've seen it in 1.15, it just didn't bother me enough to make an issue)

**Comment by PalmerAL** [comment]
Electron issue: electron/electron#21584

**Comment by shalva97** [comment]
any updates on this? the issue you linked is closed

**Comment by PalmerAL** [comment]
There's nothing in the linked issue that indicates this got fixed; however, I can't reproduce it anymore on either youtube or github. (Not gonna visit the torrent website, I don't want my ISP to ban me). Can you still reproduce in 1.20-beta?

**Comment by shalva97** [comment]
good good
