### ISSUE TITLE
Pinch to Zoom

### ISSUE THREAD

**Issue by Smona** [minbrowser/min#127]
The current zooming solution (cmd + scroll) is clunky and scrolls while zooming. Implementing pinch to zoom would make it much more intuitive for users of apple laptops.

**Comment by mobdiz** [comment]
I use Ubuntu 14.04. Ctrl + Scroll not working for zoom. Why?

**Comment by alpererm** [comment]
It does not work for me either. Linux Mint 17.3.

**Comment by PalmerAL** [comment]
Ctrl + Scroll is fixed in c527d529fe1a2a1a86ae49f6d7ea8b82ef1bd131.
