### ISSUE TITLE
Humble Request : Need Aur package

### ISSUE THREAD

**Issue by darkerhorses** [minbrowser/min#1272]
sir i love your work and browser but i cannot find it in **Manjaro Linux**.So can you help me,I am new and dont know how to get min browser as it only available for deb. and rmp

**Comment by PalmerAL** [comment]
There's an Arch package here: https://www.archlinux.org/packages/community/any/min/; will that work?

**Comment by kodumbeats** [comment]
It looks like the AUR repo is still behind a release. I've got a repo for this: 
https://github.com/kodumbeats/min-archlinux

**Comment by PalmerAL** [comment]
Yup, I asked the package maintainer and he said he's planning to update it soon:

> The new version of min is in [community-staging] now, and it will be released soon. The reason for the delay was that min, as well as other packages, still relies on Electron 9, while we are transitioning to 10, so I released a specific electron9 package.

**Comment by kodumbeats** [comment]
> The new version of min is in [community-staging] now

The link for min 1.16.0 in `community-staging`, for reference: 

https://www.archlinux.org/packages/community-staging/any/min/

Thanks for the update @PalmerAL - with that, I believe this should be good to close. 👍🏻
