### ISSUE TITLE
too many cache files

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1273]
* **Min Version:** 1.16.0
* **Operating system:** Arch

## Expected Behavior
there should be few cache files, probably few hundred maybe.... if i create git repo inside .configs folder `git` and other programs shouldnot lag.

## Actual Behavior
there is 107K files in .config/Min/ folder
that must be wrong right? there shouldnot be a cache folder containing 107K files, they are also aobut 12KiB in size...

i initialized git repo in my .configs folder. Gitkraken leaked memory to about 8GiB and crashed few times. using git from terminal is very slow.

on the left it is `ncdu` and on the right it is Gitkraken showing file counts in each folder
![image](https://user-images.githubusercontent.com/22417494/95489839-71015300-09a8-11eb-82ec-6a918adc2de6.png)

## To Reproduce
use Min browser every day for about 6 months and more

**Comment by PalmerAL** [comment]
Hmm, that does sound excessive. As a first step, I would try deleting the cache folder and see if the issue reoccurs after a while.

It's generally expected that you'll have a large number of files in the cache folder (although not quite that many). Right now, I have about 12,000 files in Min's cache folder - but I also have around 10,000 in Firefox's, and I use Min a lot more often. If you want to keep your profile data in a git repository, the best thing to do would probably be to add the cache folder to your `.gitignore` (although I'm not sure whether that would completely solve the performance issues or not).

**Comment by Milo123459** [comment]
Maybe a setting for cache sweeping? For example you can toggle how often you want the cache to be sweeped.

**Comment by shalva97** [comment]
deleted all that that cache files... i will close this now and later open if it will be again more than 100K
