### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by ritterob** [minbrowser/min#1274]
This is a beautiful project. I'd love to use this on my primary workstation running FreeBSD. There doesn't seem to be build support for it.

**Comment by kodumbeats** [comment]
It doesn't appear that Electron supports FreeBSD right now, so we won't be able to implement a FreeBSD build until this is addressed in upstream:
https://github.com/electron/electron/issues/3797
Sorry!

**Comment by ritterob** [comment]
Actually, the most recent electron officially supported in FreeBSD is 7.3.

**Comment by PalmerAL** [comment]
I suspect making a build would be fairly difficult given that electron-packager and related tools don't support it, and I don't think we want to distribute anything relying on older versions of Electron. However, what I think you could do is take a version of Min designed for Electron 7 (https://github.com/minbrowser/min/tree/1.12.x), and then once you follow the development instructions in the readme, you can run `electron /path/to/min` and it will work.
