### ISSUE TITLE
Min 1.16 impossible with vpn and proxy

### ISSUE THREAD

**Issue by antoineboy75** [minbrowser/min#1276]
* **Min Version:** 
1.16.0
* **Operating system:** 

 "Windows 10"
## Expected Behavior
impossible de surf when i am connected to the vpn and the proxy of my firm. 
I had to come back to 1.15

**Comment by PalmerAL** [comment]
Can you provide more information?

* How did you have your VPN and proxy set up before?
* What exactly happens when you use 1.16?
* Did you enable any of the proxy settings in Min?

**Comment by Milo123459** [comment]
@antoineboy75 Please update to the latest version and try again.
If that does not work, please create a new issue.
