### ISSUE TITLE
Hotkeys does not work in national keyboard layouts

### ISSUE THREAD

**Issue by agentgoblin** [minbrowser/min#1277]
Min 1.16.0
Ubuntu Linux 18.04

My PC have two keyboard layouts - RU and EN. By default Min uses EN hotkeys mapping. And when I'm switching to RU layout hotkeys does not work.

For switching layouts I'm using Xorg configuration:
```
XKBMODEL="pc105"
XKBLAYOUT="us,ru"
XKBVARIANT=","
XKBOPTIONS="grp:caps_toggle,lv3:ralt_switch,terminate:ctrl_alt_bksp,grp_led:scroll"
```

Then I'm tried to configure RU alternatives for hotkeys, but it also does not work. Sample for "Add Tab" action:
```
ctrl+t,ctrl+е
```

**Comment by agentgoblin** [comment]
Looks strange, but I'm tried again and manual remapping hotkeys now works for me:
```
ctrl+t,ctrl+е
```

**Comment by agentgoblin** [comment]
Okay, manual remapping to national alternatives works well. I think this issue done. Not sure if JS can work well with scancodes instead of character codes.

![20201013_171320](https://user-images.githubusercontent.com/9634572/95847896-80e9b000-0d77-11eb-8f63-bb6a062ce526.png)

**Comment by Syndamia** [comment]
I just want to mention that this is issue #675.
