### ISSUE TITLE
when selecting 1Password in preferences and clicking "not now" on the pop up it shows up again

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1278]
* **Min Version:** 1.16.0
* **Operating system:**  Arch

## Expected Behavior

> it should appear immediately on the next launch. You should never see the popup randomly while browsing - if you are, can you file a bug for it?

popups should never reappear by themselves....
 
## Actual Behavior
when i select 1Password autofill in preferences and press "not now" in popup it shows again in about 1 minute

## To Reproduce
just select 1Password in preferences, press "not now" and wait a bit

**Comment by PalmerAL** [comment]
I think I'm going to fix this by removing the "not now" option and just making the close button revert the setting.

**Comment by PalmerAL** [comment]
This is going to be fixed as part of #1283 (b5cf0649e1e7bf689b9ed6392769802796a780db).
