### ISSUE TITLE
A Javascript error occurred in the main process

### ISSUE THREAD

**Issue by m4r50n** [minbrowser/min#1288]
Hi,
   I'm having trouble using and also reinstalling the min browser. Using, when starting, the error message appears, the same when I try to reinstall it. During (re)installation, the same error message appears.

![MinBrowseError](https://user-images.githubusercontent.com/1416666/96749573-5fa14900-13a1-11eb-82ee-d275aed725f6.jpg)

I'm using it on a Windows 10 (2004 - 19041.572) at a Dell Computer Notebook core i5 (8th Gen).

**Comment by Syndamia** [comment]
This looks familiar to #325, so try to delete the file `\users\<your username>\appdata\roaming\min\windowBounds.json`. 

If that **doesn't** work, try deleting the `\users\<your username>\appdata\roaming\min` folder (although you should make a backup of it, if this fixes it you'll need to transfer some files to restore your settings, bookmarks, ...).

**Comment by PalmerAL** [comment]
> This looks familiar to #325, so try to delete the file \users\<your username>\appdata\roaming\min\windowBounds.json.

Also try the same thing with `settings.json` if that doesn't work.

**Comment by Milo123459** [comment]
@m4r50n Please read these soloutions.
If they don't work, please create a new issue.
