### ISSUE TITLE
Min 1.16 doesn't start anymore

### ISSUE THREAD

**Issue by PEPERSO** [minbrowser/min#1289]
* **Min Version:** 1.16
* **Operating system:** Lubuntu 18.04.5

## Expected Behavior
When clicking on the min icon, or running `min` in a terminal, it should open a min window

## Actual Behavior
Actually, when I do so, it opens min, then an error message appears, saying "An error has occurred. Close all windows and restart Min" (sorry it's in french for me, may be it is not the real error message since I translated it), then I click "Ok", and min closes. 
I tried to : 

- I close all other windows and restart Min : didn't work
- Restart the computer, didn't work 
- Remove all `/var/crash/` files, didn't work
- `sudo apt remove min` then install (with gdebi and apt), didn't work
- `sudo apt purge min` then install (with gdebi and apt), didn't work

The only other possibility I see is to build from source...

### Before the bug
This problem happened because I wanted to access about:config to disable dns prefetch, but it redirected me to about:blank#blocked (see [#issue-727173407](https://github.com/minbrowser/min/issues/1291#issue-727173407))
So I tried to run `sudo min`, an error message told me that min didn't support that without the `--no-sandbox`.
So I tried `sudo min --no-sandbox`, this launched min as expected, but about:config was still blocked.
I closed min and relauched it manually : here comes the bug.

### After the bug
Now, when I run `min` in a terminal, I get this error (in terminal):
`Gtk-Message: 19:17:56.430: GtkDialog mapped without a transient parent. This is discouraged.`
And Min launches, but with the error message translated above, and I can't do anything except closing it...

It still works like a charm with `sudo min --no-sandbox`, no warning or error...

Any idea ? :innocent:

**Comment by PEPERSO** [comment]
Found a way :smile: 
I removed `~/.config/Min`, andnow it starts again, as first time.
But, strange thing, `~/.config/Min/Crash Report` was empty...

I don't close the issue (because the bug is probably still here) but for me it is solved, close it if you want

**Comment by Syndamia** [comment]
A config/cache file was probably corrupt, you didn't need to delete the whole folder.

> I wanted to access about:config

There is no such page in Min, it is based on Electron (it does use Chromium's rendering engine, but that is about it), not Chromium. The closest thing is the preferences page.

> So I tried to run sudo min, an error message told me that min didn't support that without the --no-sandbox.

This is a chromium thing: https://bugs.chromium.org/p/chromium/issues/detail?id=638180.

**Comment by PEPERSO** [comment]
I supposed also that it wasn't the hole folder to delete, but I had searched before in .local and .cache, didn't find anything, so I deleted everything, but I'll remember if it happens gain.

Thanks for your explanation anyway :)

**Comment by PalmerAL** [comment]
Yeah, you'll get this error message if either you have multiple instances running at the same time, or if your history database gets corrupted (which I don't think I've seen happen before, so it's kind of strange you would run into that immediately). So I guess if it happens again, please open another issue.
