### ISSUE TITLE
Horizontal scrollbar in tab header

### ISSUE THREAD

**Issue by Smona** [minbrowser/min#129]
when scrolling the tab header (on osx), a scrollbar appears. This adds no functionality and obscures tab text.

**Comment by PalmerAL** [comment]
Are you using the latest version of min? This should be fixed in 1.2.1 by #76.

**Comment by PalmerAL** [comment]
I can't reproduce this in the latest version. If you can still reproduce, please re-open this issue.

**Comment by Smona** [comment]
Looks good in 1.2.2!
