### ISSUE TITLE
How do I...

### ISSUE THREAD

**Issue by iamdoubz** [minbrowser/min#1292]
Compile for Windows, but only x64?

Right now, it appears that the build script will package the app for ia32 and arm64 as well, but I am not interested in building those at this time. Is there a flag that I can pass to only build the win32 x64 package?

```
Packaging app for platform win32 ia32 using electron v9.2.1
Packaging app for platform win32 arm64 using electron v9.2.1
Packaging app for platform win32 x64 using electron v9.2.1
```

Thank you for a fantastic, minimalist browsing application.

**Comment by Syndamia** [comment]
I don't think you can do it just by passing an argument, but it should be possible by changing your local configuration. This is what I know: 
- [this script](https://github.com/minbrowser/min/blob/master/scripts/buildWindows.js) is used for building windows packages (you might be able to modify some parameters in it?)
- we use [Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows) and [electron-installer-windows](https://github.com/Squirrel/Squirrel.Windows) for the Windows package

I hope I was able to give some clues, but only @PalmerAL can say anything concrete.

**Comment by PalmerAL** [comment]
I think you probably want to add an `arch: 'x64'` entry to the options object in the installer script.

**Comment by iamdoubz** [comment]
@PalmerAL I was able to back trace to find that I needed to add `arch: 'x64'` in the `createPackage.js` win32 section. Thank you for your help... you to @Syndamia
