### ISSUE TITLE
Dark scrollbar

### ISSUE THREAD

**Issue by astier** [minbrowser/min#1293]
**Can you describe the problem you're facing?**

The scrollbar is white.

**What solution would you like?**

An option to make the scrollbar dark.  Maybe even the ability to define the color manually.

**Are there any alternatives you've considered?**

I googled for `min browser dark scrollbar` and searched for scrollbar-settings in `preferences`.

**Comment by Syndamia** [comment]
There **isn't** a setting for modifying the scrollbar. But there are [userscripts](https://github.com/minbrowser/min/wiki/userscripts) with which you can achieve it. [This userscript](https://github.com/ivancizik/min-css-scrollbar-userscript) changes how the scrollbar looks, you can easily change the color codes in the file so they match your needs.
