### ISSUE TITLE
Question: How much Min Browser handles with privacy.

### ISSUE THREAD

**Issue by manoger** [minbrowser/min#1296]
Hello.
Recently I've seen that opera browser offers a native and explicit vpn mode.
How Min browser handles with this level of security?

**Comment by PalmerAL** [comment]
We don't provide a VPN service, but if you set your operating system to use a third-party VPN, it will work in Min like it would in any other application.

If your question is about privacy more generally: We don't collect any of your browsing data, and we have built-in filtering for tracking requests.

**Comment by manoger** [comment]
I enjoy the built-in adblock.
Will the browser have a VPN service someday? (paid or free)

**Comment by PalmerAL** [comment]
Maybe, but there are no specific plans to at the moment.

**Comment by manoger** [comment]
Thanks.
