### ISSUE TITLE
Cannot install Min after upgrade to Ubuntu 20.10

### ISSUE THREAD

**Issue by tasteve** [minbrowser/min#1297]
Min requires gvfs-bin but this package has been dropped by Ubuntu in 20.10. Apparently it won't be added later. Looks as though this means Min cannot be installed on 20.10. The issue is similar to [this]( https://askubuntu.com/questions/1286781/atom-text-editor-gone-after-update-to-20-10-error-depends-gvfs-bin-but-it-is)

**Comment by adraguidev** [comment]
> Min requires gvfs-bin but this package has been dropped by Ubuntu in 20.10. Apparently it won't be added later. Looks as though this means Min cannot be installed on 20.10. The issue is similar to [this](https://askubuntu.com/questions/1286781/atom-text-editor-gone-after-update-to-20-10-error-depends-gvfs-bin-but-it-is)

I got the same error

**Comment by PalmerAL** [comment]
I'm assuming Electron doesn't actually need this package anymore, so I'm thinking that if we just removed it from the dependencies list [here](https://github.com/minbrowser/min/blob/master/scripts/buildDebian.js#L39) it should work. If you have time, could you try removing that line and re-building the package?

**Comment by PalmerAL** [comment]
Apparently Electron stopped requiring this package 2 years ago: https://github.com/electron/electron/issues/15011

So it's fine to just remove it.
