### ISSUE TITLE
add support for multiple windows

### ISSUE THREAD

**Issue by cryptobird** [minbrowser/min#130]
Earlier, with about 9 tabs open ( I was comparison shopping ), I hit ⌘N to open a new window, and wiped all of my shopping tabs. If not multiple window support, making it so ⌘N doesn't wipe all of your tabs would be excellent!

**Comment by PalmerAL** [comment]
Tasks are meant to be a replacement for windows, so I'm not sure about supporting multiple windows.

I filed another issue about changing the keyboard shortcuts: #149.

**Comment by cryptobird** [comment]
Yeah, tasks does replace windows effectively for many purposes. The main thing is the shortcuts for sure.

**Comment by lifow** [comment]
I realise this issue has been closed but I would like to point out a very common use case for multiple windows: Tasks are great, but if I have multipe workspaces open for different tasks, I very often want a browser window open in each space. I'd love to see the possibility of having multiple windows reconsidered. Maybe there's some way it could be worked in to the tasks framework already in place? "Open task in new window" or some such.
