### ISSUE TITLE
Can not download from facebook

### ISSUE THREAD

**Issue by bluethumb** [minbrowser/min#1304]
* **Min Version:** 
* **Operating system:** 
Linux hthome 5.8.10-arch1-1 #1 SMP PREEMPT Thu, 17 Sep 2020 18:01:06 +0000 x86_64 GNU/Linux
Min: Version                : 1.15.0-2

## Expected Behavior
Download file

## Actual Behavior
Gives " A Javascript error occurred in main process"

## To Reproduce
Download for random facebook page !?

**Comment by PalmerAL** [comment]
Duplicate of #1266 (fixed in the next release).

**Comment by bluethumb** [comment]
Almost fixed, now it open up two windows when I press a download link !!

**Comment by bluethumb** [comment]
Min 1.16.0  chrom v83.0.4103.122
