### ISSUE TITLE
tab closes when it shouldnot

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1310]
* **Min Version:** 1.16.0
* **Operating system:** Arch linux

## Expected Behavior
if i create a presentation and press "present" at top right corner, it should go full screen. and ESC should exit fullscreen

## Actual Behavior
it also closes current tab, which had presentation

## To Reproduce
go to [google slides](https://docs.google.com/presentation/u/0/?tgif=d ), create presentation and press "present". when you exit fullscreen with ESC, tab will close.

**Comment by BenStigsen** [comment]
I can confirm.
