### ISSUE TITLE
add some common cli arguments

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1320]
**Can you describe the problem you're facing?**
Min doesnot have any cli parameters...

**What solution would you like?**
add -v and -h arguments so one can easily find some general info

i imagine -v to show output like:

![image](https://user-images.githubusercontent.com/22417494/98420143-f8251200-209f-11eb-843e-d850d96f4613.png)

and the -h argument would show:

![image](https://user-images.githubusercontent.com/22417494/98421083-ffe5b600-20a1-11eb-8bb6-6a714dbd2c2f.png)

also im not sure how correct is the structure of the help text... couldnot find docs about writing  them.

**Comment by PalmerAL** [comment]
I added version info in 5e5cf34d32c178e1d4e98ba3b4748742b2df18ac.

Built-in docs seem like they would be harder to keep updated; I'm inclined to just direct people to the wiki for documentation.

**Comment by Milo123459** [comment]
Hey there, I'm completely happy to add a functioning CLI.
Just a question, how do you actually make the CLI work on windows?
min is not a recognised program apparently.

**Comment by shalva97** [comment]
@Milo123459 yeah, Windows cmd workd different. You have to have min's installation path added to environment variables, so it will be able to find the executable. On Linux it is added to Path by default so it is possible to do `min -v`

@PalmerAL I dont get it, why builtin docs will be hard to maintain. just a simple "hey u can pass a website argument like this" will be enough and easy to maintain, right?

**Comment by Milo123459** [comment]
Yes, I know, I've been trying, gonna look into how to copy files from /bin to AppData/Local/min/bin - Shall be a challenge!

**Comment by shalva97** [comment]
I guess there wont be updates on this.... will close

**Comment by PalmerAL** [comment]
I think we could at least show a wiki link when you start it with -h; that seems pretty simple to do.
