### ISSUE TITLE
Collapse task icon rotates at 180C

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1327]
* **Min Version:** 1.16.0
* **Operating system:** Arch

## Expected Behavior
when tab is collapsed, pressing the icon should rotate it at 90 C

## Actual Behavior
it rotates too much

## To Reproduce
collapse some task, close Task View, open it again and when you uncollapse it, icon will point to left. 

![image](https://user-images.githubusercontent.com/22417494/98734881-0afb5780-23bc-11eb-9dcb-d89ccd40c35e.png)

**Comment by PalmerAL** [comment]
Good catch!
