### ISSUE TITLE
support for open.spotify.com

### ISSUE THREAD

**Issue by sibeliusg** [minbrowser/min#1328]
**Can you describe the problem you're facing?**
yes. Spotify is not supported. Try to visit open.spotify.com

**What solution would you like?**
Support for Spotify Web player

**Are there any alternatives you've considered?**
using spotify client, but it is not really an option. Also other streaming services are no option for me

**Comment by PalmerAL** [comment]
Spotify requires a DRM plugin, which it isn't possible for us to support: https://blog.samuelmaddock.com/posts/google-widevine-blocked-my-browser/
