### ISSUE TITLE
tab dragging is too sensitive

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1341]
**Can you describe the problem you're facing?**
tab dragging is too sensitive

**What solution would you like?**
switch to them by keyDown events, just like any other browser

**Are there any alternatives you've considered?**
make tab dragging a bit less sensitive. sometimes im tired and my mouse accuracy is very low...

**Comment by Milo123459** [comment]
@shalva97 I'm a little confused what you mean, so - when you are trying to move a tab in front of another, it's too sensitive?

**Comment by shalva97** [comment]
sometimes its hard for me to keep mouse still and click tab to switch instead I trigger dragging.

In chrome it is easier because if mouse is moved a bit between keyDown and keyUp events it also triggers drag but still switches to the tab.

for example in firefox if you accidentaly drag tabs it detaches to new window and here are [people](https://bugzilla.mozilla.org/show_bug.cgi?id=727420) [suffering](https://bugzilla.mozilla.org/show_bug.cgi?id=479628) [a](https://www.reddit.com/r/firefox/comments/a5hjxl/firefox_640_sensitive_tabs/) [lot](https://www.reddit.com/r/firefox/comments/cwwy3o/how_to_reduce_sensitivity_of_drag_a_tab_into_a/). All of them ask to disable it or make it less sensitive.

Im asking same for Min, but of course it is not that bad as Firefox has :D
