### ISSUE TITLE
website favicons dont show up sometimes

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1344]
* **Min Version:** 1.16.0
* **Operating system:** KDE

## Expected Behavior
if i reopen browser and go through open tabs with keyboard shortcuts quickly to load them instantly, their favicons should also load

## Actual Behavior
some favicons dont show up

## To Reproduce
reopen browser with a task of 10 tabs. switch to all of them by ctrl+alt+right to load all of them, then open Task View and some favicons will be missing

**Comment by Milo123459** [comment]
Try upgrade to 1.17.1

**Comment by Syndamia** [comment]
I can reproduce, but I'm pretty sure this is just because the favicons haven't loaded yet. When you quickly switch between the tabs, the browser starts to load all of them at the same time. Do you get your favicons after waiting a bit for all the pages to load?

**Comment by shalva97** [comment]
nope, some of them doesnot load until manual refresh, but this seems to be random I cant reproduce this always

**Comment by shalva97** [comment]
this one was random and stopped happening at all.... will reopen if I find exact steps.
