### ISSUE TITLE
Add a setting which configures creating a new task on boot.

### ISSUE THREAD

**Issue by Milo123459** [minbrowser/min#1346]
When ever you launch min, a new task gets created.

I was wondering if anyone likes the idea of having a setting that can configure this, which can pick up from the last task or create a new one.

Do you like this idea? Please let me know and I'll work on a PR for it 👍

**Comment by Milo123459** [comment]
After looking at the code, I realised that it already does this.

**Comment by dimpogkas** [comment]
Could you explain how we can configure this? Thank you

**Comment by Milo123459** [comment]
It already does it by default.

**Comment by dimpogkas** [comment]
I meant, how to configure Min not to create a new task on boot.

**Comment by Milo123459** [comment]
Don't think you can.
