### ISSUE TITLE
Integrate HTTPS Everywhere

### ISSUE THREAD

**Issue by ghost** [minbrowser/min#135]
Could someone please integrate [HTTPS Everywhere](https://github.com/EFForg/https-everywhere)?

**Comment by PalmerAL** [comment]
I've been thinking about this, but I'm not sure how useful it actually is. A lot of sites redirect to HTTPS by default already - according to <a href="https://telemetry.mozilla.org/new-pipeline/dist.html#!cumulative=0&end_date=2016-05-02&keys=__none__!__none__!__none__&max_channel_version=release%252F46&measure=HTTP_PAGELOAD_IS_SSL&min_channel_version=nightly%252F46&product=Firefox&sanitize=1&sort_keys=submissions&start_date=2016-04-21&table=0&trim=1&use_submission_date=0">Firefox's metrics</a>, 45% of pageloads and <a href="https://telemetry.mozilla.org/new-pipeline/dist.html#!cumulative=0&end_date=2016-05-02&keys=__none__!__none__!__none__&max_channel_version=release%252F46&measure=HTTP_TRANSACTION_IS_SSL&min_channel_version=nightly%252F46&product=Firefox&sanitize=1&sort_keys=submissions&start_date=2016-04-21&table=0&trim=1&use_submission_date=0">70% of requests</a> are over HTTPS already. That percentage seems to be increasing over time, too - <a href="https://letsencrypt.org/2016/04/12/leaving-beta-new-sponsors.html">in 8 months, Let's Encrypt issued 1.6 million certificates.</a>

I'm not opposed to implementing this, but I'm also not sure there are that many sites out there that support HTTPS but don't enable it by default. It seems like most sites either support it completely, or not at all.

**Comment by wb9688** [comment]
For example StackExchange supports HTTPS, but doesn't enable it by default…
But indeed there aren't many of them…
