### ISSUE TITLE
Borderless focus mode option

### ISSUE THREAD

**Issue by wagam** [minbrowser/min#1352]
**Can you describe the problem you're facing?**
I discovered this project few days ago and really like it. 
I would like to use Min in a "borderless mode" when I'm in focus mode. 

**What solution would you like?**
Add an option to hide the top bar with the title and the close/reduce/full screen button to display only the page content similar to a "kiosk mode" when I am in focus mode.

**Are there any alternatives you've considered?**

**Comment by Syndamia** [comment]
Duplicate of #160. Also, #1011 has relevant discussion.

**Comment by wagam** [comment]
Ok. I did not found these other comments when I searched. Thanks
