### ISSUE TITLE
Error building Min for LinuxArm64

### ISSUE THREAD

**Issue by PEPERSO** [minbrowser/min#1356]
* **Min Version:** 1.17.1
* **Operating system:** Lubuntu 18.04
I was trying to build Min for Linux Arm64 to see if it would have an impact on #1348, but I had the following issue

## Expected Behavior
`npm run buildLinuxArm64` should build without issue.

## Actual Behavior
I had the following error: `TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined`

Complete log:
[2020-11-24T11_20_28_384Z-debug.log](https://github.com/minbrowser/min/files/5589505/2020-11-24T11_20_28_384Z-debug.log)

## To Reproduce
I did:

- `git clone $MIN`
- `cd min`
- `npm install` (no issue, two warnings, including `npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
`)
- `npm run buildLinuxArm64` : it started creating the package, and then showed the error...

**Comment by PalmerAL** [comment]
Yeah, this is kind of an annoying issue. You need to make this change in electron-packager (in node_modules) for it to work, at least until they release a new version: https://github.com/electron/electron-packager/pull/1191

**Comment by PEPERSO** [comment]
Perfect, this allowed me to build without issue. But it did not help me for #1348, since I'm on an x86_64 device (didn't know about that).
