### ISSUE TITLE
min doesnot open links in KDE from other applications

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1358]
* **Min Version:** 1.16.1
* **Operating system:** Arch KDE

## Expected Behavior
when I click links in other applications it should open in Min

## Actual Behavior
Min gets focus but website doesnot load

## To Reproduce
So on KDE we have `kioexec` that tries to figure out what type of links user clicks, then it can open links int browser, emils in email client and stuff...  But if Min is the default browser for some reason it first downloads whole web page and then opens it in Min.

I found similar issue [here](https://bugs.kde.org/show_bug.cgi?id=400006). They suggested to add %U at the Exec property, which I tried and worked.

This should be handled by the arch [package maintainer](https://www.archlinux.org/packages/community/x86_64/min/), but im not sure...

**Comment by PalmerAL** [comment]
This is part of the arch package: https://github.com/archlinux/svntogit-community/blob/packages/min/trunk/min.desktop

I don't know what the process is for reporting packaging issues, but I would imagine that's the best way to get this fixed. If that doesn't work, I can send the package maintainer an email.

**Comment by shalva97** [comment]
tried to report a bug on their bugTracker but there is "REPEAT: Do NOT report bugs for outdated packages!" written twice so I guess we should wait for now....

**Comment by shalva97** [comment]
they [fix it](https://bugs.archlinux.org/task/69029)
