### ISSUE TITLE
Crash on Google Login page

### ISSUE THREAD

**Issue by melgu** [minbrowser/min#1360]
* **Min Version:** 1.17.1
* **Operating system:** macOS 11.0.1 (20B29)

## Expected Behavior
Website is opened.

## Actual Behavior
Browser crashes.

```
Crashed Thread:        35  Dispatch queue: com.apple.root.default-qos

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace TCC, Code 0x0
```

## To Reproduce
Visit `http://accounts.google.com/`

**Comment by PalmerAL** [comment]
You can work around this by giving Min permission to access Bluetooth: https://mobile.twitter.com/iambudi4/status/1330165661591629828

For fixing this, we need this change: https://bugs.chromium.org/p/chromium/issues/detail?id=1126246
Electron-packager might need to be updated with the Bluetooth permission key as well.

**Comment by melgu** [comment]
May I ask, why the Google Login page requires Bluetooth?

**Comment by Milo123459** [comment]
@melgu Try asking google? I don't really know why that page would specifically ask for Bluetooth unless Google want's it, maybe a google home?

**Comment by melgu** [comment]
@Milo123459 Thanks for the quick reply. Seems kinda fishy.

**Comment by Milo123459** [comment]
Weirdd.... Have you got a google bluetooth device?

**Comment by Milo123459** [comment]
^ ie, google home

**Comment by PalmerAL** [comment]
> May I ask, why the Google Login page requires Bluetooth?

There's a good chance it's for fingerprinting; Google collects a lot of information on the signin page so they can uniquely identify your device and block signins based on that. But that's completely speculation on my part; I don't know the actual reason.

**Comment by melgu** [comment]
> Weirdd.... Have you got a google bluetooth device?

No, nothing like that. Especially nothing Google would require on login.
Only not so fishy thing I can think of: Are there Bluetooth 2FA-devices?

**Comment by Milo123459** [comment]
> > Weirdd.... Have you got a google bluetooth device?
> 
> 
> 
> No, nothing like that. Especially nothing Google would require on login.
> 
> Only not so fishy thing I can think of: Are there Bluetooth 2FA-devices?

Hmmm, fingerprinting probably

**Comment by PalmerAL** [comment]
This should be fixed by electron/electron#26730.

**Comment by Milo123459** [comment]
@PalmerAL Now that PR is merged, can this issue be closed?

**Comment by PalmerAL** [comment]
I'll leave it open until we release a version with the fix.
