### ISSUE TITLE
Make tab dragging easier

### ISSUE THREAD

**Issue by Syndamia** [minbrowser/min#1363]
**Can you describe the problem you're facing?**

When you want to rearrange tabs from the tab bar, you have to drag the tab completely over the other one.

![Peek 2020-11-27 08-56](https://user-images.githubusercontent.com/46843671/100420085-79176e00-308e-11eb-9520-b1c21a912bea.gif)

**What solution would you like?**

Make tab dragging work more like in other browsers, where the tab has to be about 50% over the other one to switch.

![Peek 2020-11-27 09-10](https://user-images.githubusercontent.com/46843671/100421126-70279c00-3090-11eb-9439-f725ec0c4873.gif)
*Tab dragging on Brave*

![Peek 2020-11-27 09-11](https://user-images.githubusercontent.com/46843671/100421215-9d744a00-3090-11eb-8f32-fe0ced8f558f.gif)
*Tab dragging on Firefox*

**Comment by PalmerAL** [comment]
I have a fix for this in https://github.com/minbrowser/dragula/commit/2f8f22a755abecf345a4621e7f5ac2fd63f9cc73, which will get merged as part of #1954.
