### ISSUE TITLE
[Bug] Focus mode does not prevent switching task with shortcuts

### ISSUE THREAD

**Issue by PEPERSO** [minbrowser/min#1367]
# Expected
* Open several tasks
* Mode focus on a task until it is finished
* Can't move to another

# Current
* Open several tasks
* Mode focus on a task until it is finished
* Using "Switch to next/previous task" keyboard shortcut changes task without problem, contrary to what is shown on the "Focus mode" message ("You can not create new tab or switch task")

By the way, using ctrl+t shortcut for a new tab is effectively prevented by focus mode.
Thanks for Min, I'm moving people around me to using it :)

**Comment by PalmerAL** [comment]
Good catch, thanks for reporting.

>  Thanks for Min, I'm moving people around me to using it :)

Nice!
