### ISSUE TITLE
 Need v1.17 32bit for my old PC

### ISSUE THREAD

**Issue by Crsmsg** [minbrowser/min#1369]

**Comment by Syndamia** [comment]
Quoting from the Discord server:

> Quick update on the 1.17 release: this release includes a native module that needs to be compiled for the first time, and I can't get cross compilation (building for a different architecture than the build machine) to work: electron/electron-rebuild#494
As a result, the Windows build for this release is going to be 64-bit only.
After this, I'm hoping to move the build process to github actions, which would allow us to add back 32 but windows builds and support ARM.

So, as it is right now, 1.17 can't have a 32bit Windows version.

**Comment by paul1149** [comment]
> Quoting from the Discord server:
> 
> > Quick update on the 1.17 release: this release includes a native module that needs to be compiled for the first time, and I can't get cross compilation (building for a different architecture than the build machine) to work: [electron/electron-rebuild#494](https://github.com/electron/electron-rebuild/issues/494)
> > As a result, the Windows build for this release is going to be 64-bit only.
> > After this, I'm hoping to move the build process to github actions, which would allow us to add back 32 but windows builds and support ARM.
> 
> So, as it is right now, 1.17 can't have a 32bit Windows version.

Is this also true of .deb linux? I would like to use it on an old netbook. Thanks.

**Comment by PalmerAL** [comment]
Chromium dropped 32-bit linux support a while ago, so there isn't a version of Min available for that. I think the last supported version was 1.9.2, but I also believe Firefox still supports 32-bit, so you're better off using that if you can get the latest version.

**Comment by paul1149** [comment]
Thanks for the quick reply. Nothing plays videos acceptably on these tiny units. I was happy to find Min 1.9 did so on Win7; it took up only 50% of CPU, whereas the other browsers push toward 100%.

I see Vivaldi, which uses a chromium base, still offers 32Bit linux. But Vivaldi is too heavy for these machines.

**Comment by PalmerAL** [comment]
Electron made a blog post a while ago about dropping support: https://www.electronjs.org/blog/linux-32bit-support, which is when I removed the build. But they still offer a 32-bit binary download of the latest version, so it may actually work if you try to run it: https://github.com/minbrowser/min#developing

**Comment by paul1149** [comment]
Thanks for that info. I'll consider giving that a try.
