### ISSUE TITLE
home page still links to PalmerAl github page

### ISSUE THREAD

**Issue by cryptobird** [minbrowser/min#137]
[home page](http://minbrowser.github.io/min/) still links back to [PalmerAl github page](https://github.com/PalmerAL/Min)

**Comment by PalmerAL** [comment]
Fixed in 79b3a61442b95ae17a67461431a95389ebd83b5b.

**Comment by PalmerAL** [comment]
Fixed the tour page links in 5157ca2ce6e6d51bcde450c221c30927fa7af472.
