### ISSUE TITLE
Getting error code -5 or -15 when launching Min

### ISSUE THREAD

**Issue by Wayott** [minbrowser/min#1375]
Hello,
I like Min very much and run it on Mac OS (Mojave and Big Sur). But on one of my mac's running Big Sur, I get a code error (-5) or (-15) and can't navigate. And I can't get rid off it even when thoroughly erasing Min from the hard drive or using a previous version of it.
Thank's for the help. Regards

**Comment by PalmerAL** [comment]
#1376.
