### ISSUE TITLE
do not take into account previous message about MIN NOT LAUNCHING 

### ISSUE THREAD

**Issue by Wayott** [minbrowser/min#1376]
Hi,
I left a message about having error -5 or -15 when launching MIN, but it was caused by a setting in Little Snitch that I wasn't aware if. I fixed it and Min is running smoothly now.
Keep up the good work. Thanks.

**Comment by PalmerAL** [comment]
I'm glad it worked! Just out of curiosity, what setting did you change? It would be useful to know if other people have the same problem in the future.

**Comment by Wayott** [comment]
Hi,

Thank you for reaching out to me about this matter.

I don't remember exactely what was blocked in Little Snitch (LS) that
prevented MIN browser to run properly, but this how I worked around the
error.

---

Form LS in the menu bar, roll out the pulldown menu and click on 'Turn Off
Network Filter' to stop LS from blocking outgoing traffic.

Then hit the combinaison keys 'Control+Option+Command+komma' or click on
"Show Network Monitor" in the same pulldoown menu of LS for the Network
Filter Window to pop up.

Now in in the navigation bar of MIN, type something to search for and if
MIN is blocked, it will show up in the Filter Monitor of LS (first line)
with a red flag while Min tries to connect to the Internet. Press on the
red flag to change its status to green. And that's it.

I hope it's clear.

Peace.
-- 
Jason


Le 12 décembre 2020 à 17:20:02, PalmerAL (notifications@github.com) a écrit:

I'm glad it worked! Just out of curiosity, what setting did you change? It
would be useful to know if other people have the same problem in the future.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/minbrowser/min/issues/1376#issuecomment-743779055>, or
unsubscribe

**Comment by PalmerAL** [comment]
Thanks for the details!
