### ISSUE TITLE
gmail issue

### ISSUE THREAD

**Issue by AlainBeuchee** [minbrowser/min#1377]
Minbrowser crashes when I try to login in gmail
-  Min Version: 1.17.1
- Operating system: mac0s Big Sur 11.0.1

**Comment by Syndamia** [comment]
Duplicate of #1360. Tl;dr right now there is only a workaround:
> You can work around this by giving Min permission to access Bluetooth: https://mobile.twitter.com/iambudi4/status/1330165661591629828
