### ISSUE TITLE
Build issues after recent lint commit

### ISSUE THREAD

**Issue by glitsj16** [minbrowser/min#1378]
- **Min Version:**
Latest git master.
- **Operating system:**
Arch Linux

## Expected Behavior
Succesful build produces a fully functional min browser.
## Actual Behavior
Error thrown during `npm run buildDebian`.
Build continues but the resulting min browser hangs (silently) on start.
## To Reproduce

```
$ git clone https://github.com/minbrowser/min.git
$ cd min
$ npm install
$ npm run buildDebian
[...]
Error while building: Parsing file /home/glitsj16/min/dist/build.js: Identifier 'webviews' has already been declared (728:6)
[...]
```

The problem started to show right after https://github.com/minbrowser/min/commit/0f49269090539a2de3d527c2ea30079089d7160c and when I revert that min builds and runs fine without hiccups.

**Comment by PalmerAL** [comment]
I've reverted that commit, so everything should work again. Explanation of what went wrong here: https://github.com/minbrowser/min/pull/1373#issuecomment-744136807
