### ISSUE TITLE
Custom URL Variables in URL box

### ISSUE THREAD

**Issue by mmccn** [minbrowser/min#1382]
I would like a way to set variables for the URL box, like if I set lb to equal to example.com, if I typed !lb in the URL box, it would bring me to example.com. This would require a settings menu to add or delete variables.

I have considered duckduckgo, but that doesn't allow for custom variables.

**Comment by Milo123459** [comment]
This works with the way we have integrated custom bangs, which would require a whole new re-design, maybe a settings option allowing you to add more?

**Comment by f-ionn** [comment]
Yeah that makes sense.
