### ISSUE TITLE
Windows XP support

### ISSUE THREAD

**Issue by Virgus** [minbrowser/min#1384]
Hello your project is awesome !
I just configured and tried on Win 7 and it's the fastest browser I've ever seen !

I just tried v 1.16.1 as I can see the exe icon displayed correctly but I got an error,
so I'm wondering: would it be possible to compile it to be used on older XP computers ?
I'd love to be able to use it on every Windows version I'm still using.

Thanks,
kind regards.
V.

**Comment by PalmerAL** [comment]
Chromium doesn't support XP, so it's not possible, sorry.

**Comment by Virgus** [comment]
Thanks for your prompt answer and have a nice day.
