### ISSUE TITLE
"Open in new tab" doesn't function in developer tools

### ISSUE THREAD

**Issue by clayton-grey** [minbrowser/min#1388]
- 1.17.1
- macOS 10.14.6

## Expected Behavior

Clicking "Open in New Tab" in the developer panel should open the resource in a new tab within the same task.

## Actual Behavior

No new tab is opened.

## To Reproduce

Right click a link within the developer tools and select "Open in new tab".

**Comment by PalmerAL** [comment]
Duplicate of #1034.
