### ISSUE TITLE
ad account settings in Facebook does not work

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1390]
- **Min Version:** 1.17.1
- **Operating system:** Arch KDE

## Expected Behavior
when i click Edit buttons on FB settings page it should allow me to edit

## Actual Behavior
nothing happens and there are some errors on console

## To Reproduce
go to facebook Settings page and click on this:
![image](https://user-images.githubusercontent.com/22417494/102711015-020d7800-42d0-11eb-8870-126ba58d3218.png)

**Comment by PalmerAL** [comment]
I think I've fixed this in c8795a07a7e7fa76f316e2a63cb822098ed3afb1. I don't have a Facebook account to test this with, so if you could confirm this works that would be great.

**Comment by shalva97** [comment]
it is almost worked. 
![image](https://user-images.githubusercontent.com/22417494/102989262-c1f80080-452e-11eb-93d9-d223e40475a5.png)

```
zOtG92ZXcH0.js?_nc_x=sAWtZ3AmHjc&_nc_eui2=AeECjd8cwFTTegtrFGcNCbVC_9JEqJzppKP_0kSonOmko0Zn5GMPkPGJeCCenjkJWJrpa-wWPijd79veNIqdhtwq:18 POST https://www.facebook.com/settings/advertising_email/add/submit/?new_email=asd%40asd.com net::ERR_BLOCKED_BY_CLIENT
```

**Comment by PalmerAL** [comment]
That might be an Easylist issue; the filter list has a filter that would block that request:
```
/advertising_$domain=~advertising.scoop.co.nz
```
("block anything with /advertising_, with the exception of scoop.co.nz")

The other request has an exception filter:
```
@@||facebook.com/ajax/settings/account/advertising_email.php$xmlhttprequest,domain=facebook.com
```

But that wouldn't match the /submit request.

Can you test this in another browser with an Easylist-based adblocker (such as ublock origin)? And if it doesn't work there, can you open an issue here: https://github.com/easylist/easylist/issues/new ?

**Comment by shalva97** [comment]
yeah, this is not our issue, it also doesnot work in Chromium with uBlock origin. maybe later if I wont feel lazy I will open issue there :D
