### ISSUE TITLE
when browser crashes there should be some logs

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1391]
- **Min Version:** 1.17.1
- **Operating system:** Arch KDE

## Expected Behavior
If browser crashes there should be logs somewhere, at least in Min/Crash Reports

## Actual Behavior
When browser crashes Min/Crash Reports folder is empty and there is not much I can diagnose.

## To Reproduce
crash the browser somehow

**Comment by PalmerAL** [comment]
I don't think this anything specific to Min, but rather a setting on your system. I haven't done this before, but I think you need to do something like this: https://stackoverflow.com/a/32461658

**Comment by shalva97** [comment]
ok I will be ready next time
