### ISSUE TITLE
Min crashes in 20-30 seconds when closing some websites on Arch Linux

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1392]
- **Min Version:** 1.17.1
- **Operating system:** Arch KDE

## Expected Behavior
it should not crash :D

## Actual Behavior
when I updated to 1.17.1 it started to crash randomly, at least once a day

## To Reproduce
not sure here, I was not doing anything new compared to what i was doing on 1.16.1

 stdout logs: 
 
![image](https://user-images.githubusercontent.com/22417494/102711257-9debb380-42d1-11eb-88d4-32a97a3b3d56.png)

**Comment by PalmerAL** [comment]
Were you able to get a crash report for this?

**Comment by shalva97** [comment]
nope, it stopped crashing when i posted this issue :D

maybe some packages where updated and fixed it... idk

**Comment by shalva97** [comment]
oh well, it crashed just now

here is the coredump
https://ufile.io/kivrmghk

**Comment by shalva97** [comment]
okay wait, I shoulnot post coredump here :D

**Comment by PalmerAL** [comment]
I got the core dump, but I think in order to actually read it you need the exact Electron binary: https://stackoverflow.com/a/8306805, which is going to be different than what I have because Arch recompiles it. You could try the instructions in the link to see if you can get a stack trace out of it.

Alternatively, based on the screenshot, it seems like the keychain service may not be working, and that could be causing crashes. Could you try disabling the built-in password manager for a bit and see if the crashes still happen?
(And does the password manager actually work if you try to save a password?)

**Comment by shalva97** [comment]
I had bad day today, got 3 crashes in a row :O

https://termbin.com/mo82
https://termbin.com/ppta
https://termbin.com/pkfj0

**Comment by shalva97** [comment]
it is becoming worse and worse. 5 crashes today :(

**Comment by shalva97** [comment]
I found a bit more info with gdb. Maybe it will help.
[out.txt](https://github.com/minbrowser/min/files/5754648/out.txt)

I will clean all the cache and configs, hopefully something will change...

**Comment by PalmerAL** [comment]
I think what we actually need is the function names from where the crash happened. I think it might work to attach gdb first and then wait for it to crash: https://www.repetier-server.com/knowledgebase/debugging-crashes-hangs-on-linux/, but I'm not sure since I haven't done this before.

Hopefully disabling the password manager works; that's the primary change in 1.17 that could cause this.

**Comment by PalmerAL** [comment]
Actually, I think there's a better way to do this. I've enabled Electron's crash reporting in a31b0c4d71d02f1fa782d6f85056a12735941080; if you run a build with that, you should get a crash report in `/home/username/.config/min/Crash Reports`, which [electron-minidump](https://github.com/nornagon/electron-minidump) should be able to extract function names from.

**Comment by shalva97** [comment]
okay I got some interesting stuff, will send crash report in discord and this is the stdout

![image](https://user-images.githubusercontent.com/22417494/103384820-45a68400-4b11-11eb-954d-0535ba9b8e12.png)

**Comment by shalva97** [comment]
I guess im getting 2 types of crashes. One sometimes happens when pressing CTRL + R twice and waiting about 30 seconds with SIGILL signal and Im not sure about seconds one with SIGTRAP. maybe later I will figure it out

**Comment by shalva97** [comment]
found a bit more simple way.

It happens about 1 in 3 tries when closing gmail.com tab and waiting about 30 seconds... will post more steps later if I find any...

**Comment by PalmerAL** [comment]
I was able to reproduce this with the double ctrl+r; I was running with the NPM version of electron, so it should be theoretically possible to get symbols for it. However, getting the symbols doesn't seem to be working; I've opened an issue for that: https://github.com/nornagon/electron-minidump/issues/5.

**Comment by shalva97** [comment]
It also crashes similar way on todoist.com

log in with facebook and logout in about 3-5 seconds, then wait 20-30 seconds and browser will crash

**Comment by shalva97** [comment]
found another weird behavior. sometimes it also crashes without internet and every tab has message "you are offline" except mail.google.com, it says "An error occurred -2"

do we treat mail.google.com differently?

**Comment by PalmerAL** [comment]
I don't think there's anything special about gmail, although it's interesting that happens. Maybe a difference between active / inactive tabs? Or maybe whether there are active network connections (gmail polls for new mail)? But I really have no idea.

-2 corresponds to "generic failure": https://source.chromium.org/chromium/chromium/src/+/master:net/base/net_error_list.h;l=32?q=Net%20error%20list&ss=chromium, so that isn't too informative unfortunately.

**Comment by shalva97** [comment]
is there any news about this?

it crashes at least twice everyday, becoming more and more annoying...

**Comment by PalmerAL** [comment]
I just spent 15 minutes opening and closing gmail and todoist in a loop and reloading, and didn't get any crashes, so I'm sort of mystified at this point...

How often do you use the double ctrl+r shortcut? That's the only way I've been able to reproduce this before, and if you're using that at any point, it's possible that's causing memory corruption that's leading to a crash later. If that's the case, we could try modifying the behavior of that shortcut to make it reload tabs but not the window itself, which might work better (we had a similar crash on Windows like 2 years ago: 4c24a569a649527c61a7487430f5e5e4c18c8380, so I think reloading browser windows isn't tested very well in Electron).

**Comment by shalva97** [comment]
okay, this crash is Arch Linux's Electron's fault. It has been long time I couldnot reproduce this crash with `npm run start` and now when I changed path to electron like this `"startElectron": "/usr/bin/electron . --development-mode",` it crashed on the first try.

> I just spent 15 minutes opening and closing gmail 

yeah. Its been one day and cannot even make it crash once.
On arch Min is installed to /usr/lib/min and doing `min/node_modules/electron/cli.js /usr/lib/min/` also fixes this issue.

I guess I should report to package maintainer... but i still cant figure out how to get stack trace... will try later again

**Comment by PalmerAL** [comment]
Well, it's good to know we're not at fault :)

But that is very strange. I'll send Nicola (the package maintainer) an email and see if he has any thoughts.

@flber Does cloning Min and running it in development mode fix the crashes for you as well?

**Comment by PalmerAL** [comment]
@shalva97 One thing Nicola suggested is that the Electron version installed from NPM is slightly older than the Arch package. If you run `npm install electron@11.2.1`, does it start crashing?

**Comment by shalva97** [comment]
well, still checked it but no, it doenot crash on any version of electron from npm.

it was crashing for me in November too, about 2-3 months ago. these crashes were on all versions both electron 9 and 11

**Comment by flber** [comment]
> @flber Does cloning Min and running it in development mode fix the crashes for you as well?

It does indeed! I've been running in development mode for quite a while now and I haven't had any crashes. I'm not entirely sure what that means, but at least it's more data.

**Comment by shalva97** [comment]
I do not know what changed, but it doesnot crash anymore :D
