### ISSUE TITLE
Bitwarden Integration not Working

### ISSUE THREAD

**Issue by gpioneer90** [minbrowser/min#1394]
- **Min Version: 1.17.3**
- **Operating system:**
Windows 10

## Expected Behavior
When clicking the key icon and inputting BW password, to login to website/open interface
## Actual Behavior
Asks for password over and over, as if it won't accept. No error message. Just click OK after inputting on the password window, and a new one pops up. Only way to now close this window is to leave password blank and click OK. And then BW doesn't pass login info to website.
## To Reproduce
Try to log in to a website using the BW module, input password->login loop

more details: when I tried installing the CLI tool by dragging it into the prompt, it was stuck at "installing" for a very long time for my system (30-45 seconds, nvme ssd, nothing really every takes longer than a second on the system). I clicked outside the UI and it closed the drag and drop install window and Bitwarden was selected. When I went to try to log in to a website the first time, it would accept my password but keep crashing the browser immediately afterwards. I then chose the no password manager option and then Bitwarden again in the settings. Afterwards, when trying to log in to websites, it gets stuck in login loop as mentioned above. I don't know how to "uninstall" the BW module now to try to reinstall it, which may or may not fix the issue.

**Comment by gpioneer90** [comment]
I have 2FA enabled on Bitwarden. Maybe that's why it doesn't work in Min? On Firefox on initial setup of BW it will request I enter a code sent to my email

**Comment by PalmerAL** [comment]
2FA isn't supported for now, which is #929.

My guess is that trying to sign in the first time left Bitwarden in an unexpected state; if you're comfortable disabling 2FA, you can do this:
1. Quit Min.
2. Go to `\Users\Username\AppData\Roaming\Min\tools`
2. Delete "bw.exe"
3. Restart Min.

And install it again.

**Comment by JackGFuller** [comment]
I have encountered a similar problem. And I did the process suggested by PalmerAL. When I log in to a website, the 'key' icon is shown in the UserName field, but it isn't filled in by Bitwarden. 

![image](https://user-images.githubusercontent.com/74563788/109093872-f1152480-76cd-11eb-9025-6a1f6c57246f.png)

Clicking on the 'key' icon results in no action.

**Comment by PanoptesDreams** [comment]
Also experiencing problem, unable to resolve.

Did a full reset of the browser and tried to re-add BW CLI, now I can't even add the CLI back to Min

Min 1.22.0
Win 10 1703 & 21H1

**Comment by aiyagari** [comment]
I ran into this problem too.  I noticed one reason this might be occurring - the "drag tool here" seems to corrupt the tool that is dragged.  I thought it was trying to ask for a pathname, so I dragged my /usr/local/bin/bw into there, and then I found that it became a zero-byte file and I had to reinstall it.

**Comment by PalmerAL** [comment]
@PanoptesDreams @aiyagari Can both of you try deleting `C:\Users\AppData\Roaming\Min\tools` on Windows or `/home/username/.config/Min/tools` in Linux and see if you can install after that?

If you already have Bitwarden installed globally, you shouldn't even be seeing the install dialog; I'm not sure why that would be happening at the moment.

**Comment by PanoptesDreams** [comment]
> @PanoptesDreams @aiyagari Can both of you try deleting `C:\Users\AppData\Roaming\Min\tools` on Windows or `/home/username/.config/Min/tools` in Linux and see if you can install after that?
> 
> If you already have Bitwarden installed globally, you shouldn't even be seeing the install dialog; I'm not sure why that would be happening at the moment.

Okay so; I've already added BW CLI to path (windows) which as you said fixes the issue, however you can not expect any end user to do this. 

Removing from path and reinstalling I observed; box is opened again asking for BW CLI, can you please add a "Browse" button, drag and drop is not always preferable. And now it's hanging on 'Installing' , it succeed in the background though (BW CLI is back in the tools folder) and the dialog box can be clicked off, so.. unresponsive UI / lack of feedback to user.

Now to signing in to a webpage, the key icon appears, click, turns red.
Yes I signed in to bitwarden when the box prompted me.
