### ISSUE TITLE
Disable tab dragging with left mouse button/improve dragging behavior 

### ISSUE THREAD

**Issue by theLucy** [minbrowser/min#1398]
**Can you describe the problem you're facing?**
More often than not when i try to switch tabs cause i move my mouse it ends up not opening it but counting it as tab drag even if i release it fast, so i have to hover a tab, stop and then click. its really annoying that browser is so fast but such a thing slows me down :/
**What solution would you like?**
option to enable dragging tabs only with right mouse button maybe cause currently right mouse button don't do anything, or perhaps dragging only with holding some modifier key on keyboard like alt or smth.
another solution would be to improve dragging behavior but i don't know how hard it would be.

**Comment by shalva97** [comment]
similar to #1341

**Comment by theLucy** [comment]
While feature is not improved i could live by only arranging tabs on task view screen or not all all. can someone help me remove dragging functionality for time being?
