### ISSUE TITLE
Freestance: Redirect youtube to invidio, twitter/nitter, reddit/teddit and instagram/bibliogram  

### ISSUE THREAD

**Issue by danrobi11** [minbrowser/min#1400]
@kssytsrk did a [freestance](https://github.com/kssytsrk/nx-freestance-handler) for the [nyxt](https://github.com/atlas-engineer/nyxt) browser. Its pretty neat!

I think a freestance like this would be a neat feature for min. 

Thank you for min!

**Comment by PalmerAL** [comment]
I think it would be pretty simple to do this as a userscript (directions: https://github.com/minbrowser/min/wiki/userscripts)

Here's an example of a userscript I use; you could probably just change the domain names involved to get what you want:
```
// ==UserScript==
// @name Redirect to old reddit
// @match http*://reddit.com
// @match http*://www.reddit.com
// @run-at document-start
// ==/UserScript==

window.location.hostname = 'old.reddit.com'
```

**Comment by danrobi11** [comment]
@PalmerAL Yep, working perfectly. Thank you for the support. Happy Holidays!

**Comment by PalmerAL** [comment]
I'm glad it worked! You could also add it to the userscripts wiki if you want so other people can use it.

Happy holidays to you as well!

**Comment by danrobi11** [comment]
@PalmerAL 
 > You could also add it to the userscripts wiki if you want so other people can use it

Good idea. But I dont want to mislead users. So far I got it to work by creating a separated script.js for each instance.
Is it possible to create only 1 script.js with every instance in it? I've tried and that didnt work. Although, might be cuz bad syntax.

**Comment by PalmerAL** [comment]
It should be possible if you check the value of location.hostname and set the `@match` rule correctly. Example:

```

// ==UserScript==
// @match *
// @run-at document-start
// ==/UserScript==

if (window.location.hostname === 'example1.com') { 
window.location.hostname = 'example2.com'
} else if (window.location.hostname === 'example3.com') { 
window.location.hostname = 'example4.com'
}
```

(Also, thank you!)

**Comment by danrobi11** [comment]
From everything I've tried, I cant get it to work all together in a single script.js 
All good tho, its not important. Thanks again!
