### ISSUE TITLE
small area near scroll bar is not clickable in Task View

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1402]
- **Min Version:** 1.17.3
- **Operating system:** Arch KDE

## Expected Behavior
scrollbar should be clickable everywhere

## Actual Behavior
it is not clickable on this area, arrow button is also unclickable
![image](https://user-images.githubusercontent.com/22417494/103096831-a9671380-461e-11eb-8d5f-f91bec7a7a31.png)

## To Reproduce
open Task View and try to drag scrollbar from the very top of it

**Comment by PalmerAL** [comment]
This is maybe the same issue as #1381 - if you try to drag the window in that area, does it move?

**Comment by shalva97** [comment]
no, it is definitely not that. All i was doing in that area was to drag scroll bar but nothing was happening, not even window dragging.

are you able to reproduce it? I have got Windows notebook, I may also test it there later

**Comment by PalmerAL** [comment]
OK, I can reproduce this on Ubuntu, it is a separate issue.

**Comment by PalmerAL** [comment]
Fixed in 6f2206ac51f3c6f1ff44af1ee6769ca3980ee9ff, thanks for reporting.

Until this is released, you can work around it by enabling the "use separate titlebar" option in the preferences, although that may be more annoying than the original issue.
