### ISSUE TITLE
autocompletion doesnot work in devtools

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1403]
- **Min Version:** 1.17.3
- **Operating system:** Arch KDE

## Expected Behavior
docuemnt. in devtools console should bring up autocompletions.
this is from Chromium:
![image](https://user-images.githubusercontent.com/22417494/103140890-9da24c80-4705-11eb-9093-57803ea1006b.png)

## Actual Behavior
it doesnot show any autocompletion

## To Reproduce
type document. in console and press CTRL + SPACE

**Comment by PalmerAL** [comment]
I see a slightly different variation of this - the autocomplete works as I type "document", but stops working as soon as I get to the "." character. This broke in a recent Electron upgrade, so I'm sort of hoping it'll be fixed the next time we upgrade. If it's not, I can look into it more.

**Comment by shalva97** [comment]
yeah, forgot to mention that. It also works for me before the first dot.

**Comment by shalva97** [comment]
works on electron v11.2.1
