### ISSUE TITLE
styles do not load for gs.statcounter.com

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1406]
- **Min Version:** 1.17.3
- **Operating system:** arch kde

## Expected Behavior
styles hsouldnot be blocked as in Chromium with uBlock Origin

## Actual Behavior
this is what it looks like Min vs Chromium uBlock:
please dont mind that Min is darker, it is visual effect from KDE
![image](https://user-images.githubusercontent.com/22417494/103303387-44952a00-4a1f-11eb-8987-c4efa9efd73d.png)

## To Reproduce
go to [gs.statcounter.com
](https://gs.statcounter.com/)

**Comment by PalmerAL** [comment]
Until this is fixed, adding a content blocking exception makes it work.
