### ISSUE TITLE
Allow users to change browser shortcuts

### ISSUE THREAD

**Issue by miere** [minbrowser/min#141]
I'm loving the Min experience but there is one thing that is anoying: "Ctrl + Left Arrow" to navigate back. 

Maybe, most of users didn't have the issues I've faced because of this shortcut, but I use this combination of keys to navigate between words on any text box. Often, when I'm using this key combination I have my tab navigated back and I lose the entire text I've wrote until then. Right now, while I'm writing this issue I've rewrote this text three times.

What you guys think about it? Would you consider a Shortcut Editor screen in order that I can fix this by my self? Or maybe, what I think would be the best solution, change this shortcut?

Regards! ;)

**Comment by PalmerAL** [comment]
A shortcut editor sounds interesting. However, fixing the existing shortcuts is probably a better option.

I think there was an issue open about this specific shortcut already, but I can't find it right now. What Firefox/Chrome/Safari all do is that this shortcut only goes back if focus is not on a text input. Min should probably do the same thing.

**Comment by sanderboom** [comment]
Bitten by this in the first 5 minutes I tried using Min.
Furthermore: the `cltr-d` shortcut to select the URL-bar is ingrained in my fingers. 

+1 for the shortcut editor :)

**Comment by PalmerAL** [comment]
@sanderboom The shortcut editor was added in #154, and will be included in 1.3.0

**Comment by sanderboom** [comment]
Awesome. Thanks for the fast move!
