### ISSUE TITLE
Launch problem, reboot resolves

### ISSUE THREAD

**Issue by Topnikov** [minbrowser/min#1410]
- **Min Version: 1.17.3**
- **Operating system: Windows 10 20H2 x64**

When I installed this browser, it does not start and gives a white screen. When I restart my computer, I open the browser and it starts up. When I close and restart it, it gives the same thing as after installing the browser.

![screenshot 2020-12-30 001](https://user-images.githubusercontent.com/26837675/103349493-00049f80-4aae-11eb-8641-516e3a9bca43.png)

**Comment by PalmerAL** [comment]
Does it work if you start Min from the command prompt (just drag the icon into the cmd window) with `--disable-gpu`?
