### ISSUE TITLE
Adblock

### ISSUE THREAD

**Issue by bakinazik** [minbrowser/min#1414]
I request a little improvement on ad blocker, because it is really weak at blocking many ads. I will be glad if you can answer thank you.

**Comment by PalmerAL** [comment]
Can you give examples of sites where it’s not working?

**Comment by bakinazik** [comment]
youtube ads are not block well enough
![screenshot](https://user-images.githubusercontent.com/61169988/103487916-cb7c4500-4e19-11eb-9454-49ca31052aea.jpg)

**Comment by Syndamia** [comment]
Duplicate of #1121, tl;dr [this userscript](https://greasyfork.org/en/scripts/407477-no-more-youtube-ads-updated/code) is a workaround for blocking all YouTube ads.
