### ISSUE TITLE
Issues with HTTP Authentication sites

### ISSUE THREAD

**Issue by semtize** [minbrowser/min#142]
Unable to access websites that require a login before loading the actual site. Typically in other browsers once you enter the website address, a popup will appear asking for login and password and will then load the page according to whether or not login information is correct.
Min doesn't display this popup so I am unable to enter my login and thereby unable to access the website.

**Comment by PalmerAL** [comment]
I think this is a duplicate of #140?

**Comment by simonhochrein** [comment]
Electron does have support for HTTP Basic Authentication.

This would be a great feature to add.

**Comment by dbfreem** [comment]
Since this is a duplicate of #140 closing

**Comment by PalmerAL** [comment]
(It's actually a duplicate of #174, I linked the wrong issue above)
