### ISSUE TITLE
tab height in Task View is different

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1420]
- **Min Version:**
- **Operating system:** 1.17.3

## Expected Behavior
all tabs in Task View should have same height

## Actual Behavior
on this [youtube video](https://www.youtube.com/watch?v=35XST4H9QfM) tab height is greater than others
![image](https://user-images.githubusercontent.com/22417494/103818373-d802d680-5081-11eb-9777-038c016b4cde.png)

## To Reproduce

go to this this [video](https://www.youtube.com/watch?v=35XST4H9QfM)(sometimes title doesnot update) and when the tab title changes its height will increase

**Comment by Syndamia** [comment]
For me it's fine, I think it might have to do with your fonts. My gut feeling is that the special characters in the title are, for some reason, taller than they should be, so the task view on that tab is taller, to accommodate the taller characters.
