### ISSUE TITLE
Embedded links within PDFs don't work

### ISSUE THREAD

**Issue by PalmerAL** [minbrowser/min#1422]
- **Min Version:** 1.17.3
- **Operating system:** all

## Expected Behavior

Links within PDFs should be clickable.

## Actual Behavior

Clicking on links does nothing.

## To Reproduce

Example file: https://www.antennahouse.com/hubfs/xsl-fo-sample/pdf/basic-link-1.pdf?hsLang=en

(original source: [Twitter](https://twitter.com/yurinural/status/1347862957393383424))

**Comment by Milo123459** [comment]
This is an issue with pdfjs right?

**Comment by PalmerAL** [comment]
PDFJS supports links, but Min has a custom viewer UI on top of that that we need to add support in.
