### ISSUE TITLE
search results flickering

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1423]
- **Min Version:** 1.17.3
- **Operating system:** Arch 

## Expected Behavior
highlighted search results shouldn't flicker

## Actual Behavior
when pressing down arrow they flicker

## To Reproduce
go to here https://api.flutter.dev/flutter/material/Icons-class.html and search for "save" then press down arrow in search bar and highlighted results will flicker

**Comment by Milo123459** [comment]
It flickers then stops for me, same for you?

**Comment by shalva97** [comment]
nope, every time I press down arrow it flickers once

**Comment by Sestowner** [comment]
I can't reproduce this.
**OS:** Arch Linux
**Min:** 1.17.3

**Comment by shalva97** [comment]
https://user-images.githubusercontent.com/22417494/108085546-e388ea80-708e-11eb-8bdc-f0341f4e35be.mp4

you can see they flicker every time I press down arrow

**Comment by Syndamia** [comment]
I also can't reproduce: Fedora 33 with Min 1.18.1
