### ISSUE TITLE
adding websites to filter exceptions but still getting BLOCKED BY CLIENT in console

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1428]
- **Min Version:** Arch kde
- **Operating system:** 1.17.3

## Expected Behavior
if I add some websites to exceptions I shouldnot see BLOCKED BY CLIENT in the console and the webpage must load

## Actual Behavior
website doesnot load and there are bunch of BLOCKED messages
![image](https://user-images.githubusercontent.com/22417494/104444107-c5702c00-55b0-11eb-97c8-5218638ca629.png)
this is what it should look like In Chromium:
![image](https://user-images.githubusercontent.com/22417494/104444569-62cb6000-55b1-11eb-94f2-585f0fddc0f9.png)

## To Reproduce
creating account on [firebase](https://console.firebase.google.com) is not easy, requires one to create android project and add some libraries to and then it will show dashboard.... so if screenshots wont be enough I can create some test account later

**Comment by PalmerAL** [comment]
What's the URL of the page, and what domain did you put in the exceptions list?

**Comment by shalva97** [comment]
https://console.firebase.google.com
![image](https://user-images.githubusercontent.com/22417494/104573479-5eb14800-566e-11eb-88bb-be50f17735ff.png)

**Comment by PalmerAL** [comment]
You need to remove the http:// from the front of the URL, then it should work.

We should probably detect this and handle it automatically.
