### ISSUE TITLE
Pop-up windows opens as about:blank#blocked

### ISSUE THREAD

**Issue by PEPERSO** [minbrowser/min#1432]
- **Min Version:** 1.17.3 (same behaviour before)
- **Operating system:** Lubuntu 18.04

## Expected Behavior
Go to [oui.sncf](oui.sncf), log-in ("Me connecter" in the upper left corner), okay, you're in

## Actual Behavior

- I enter log-in
- A new tab opens
- That's it, the tab stays there as about:blank#blocked

Ad blocker is disabled, scripts and images are accepted. On chromium (ungoogled-chromium v.84.0.4147.135, it connects to
https://connect.sncf.com/loginxxxx (xxxx stands for url details about my account)

## To Reproduce
You can try for yourself without needing an account, any email adress in the e-mail field triggers the new tab openning.

I'm sorry that it is quite specific, but I really need to book train tickets ;)

**Comment by PalmerAL** [comment]
Unfortunately, that's mostly a limitation of us not supporting popup windows very well: #140. It looks like Electron may provide better support for that in the future, but it's not clear yet.

Sometimes it's possible to write a workaround for individual sites. I've tried to do that here: https://github.com/minbrowser/min/commit/6965456cbef9f944726706a5cfcdcf21f97ec52c, and compiled a binary for Linux with that change: https://www.dropbox.com/s/if58vd0agxbmt2x/min_1.17.3_amd64-try-fix-sncf-1.deb. Can you try going through the login process with that and see if it works?

**Comment by PEPERSO** [comment]
I'll try it this weekend, thank you very much for your time !

**Comment by PEPERSO** [comment]
I've tried (nice buttons added on the welcome page), but now, when I click on the "Connect" button, nothing happens, not even the new tab oppenned...

**Comment by PalmerAL** [comment]
Hmm, that's unfortunate. I may look at this again at some point, but I suspect there's probably not much that can be done here.

**Comment by PEPERSO** [comment]
Yes, that's what I was expecting too infortunately... May be some day it will be fixed :)

**Comment by PalmerAL** [comment]
This should be fixed in 1.20 (released today) :) Let me know if it's not!
