### ISSUE TITLE
Min 1.17.3 fails to run

### ISSUE THREAD

**Issue by flber** [minbrowser/min#1434]
- **1.17.3**
- **Manjaro i3**

## Expected Behavior
Min should run when launched

## Actual Behavior
Min fails on launch, and shows a blank new tab page with a dialog box saying "An error occurred. Please close any other open instances and restart Min." 

## To Reproduce
While I'm not sure exactly what is causing this problem, it only started after I updated a large number of out-of-date packages on my machine. I have also restarted my laptop and reinstalled Min multiple to see if that helped.

**Comment by PalmerAL** [comment]
That's interesting, I haven't seen that before. That error message means that opening the database files caused an error, so they're probably either corrupted or inaccessible somehow.

If you're willing to delete your history and bookmarks, there's a really easy solution for this: delete your `/home/username/.config/Min` folder and restart.

If you aren't (which is understandable), the next thing I would try is to make sure there really are no other instances running: `lsof ~/home/username/.config/Min/IndexedDB/file__0.indexeddb.leveldb/LOCK`

One thing I have seen occasionally is that if you upgrade to a newer version of Min and then downgrade to an older one, Chromium will occasionally corrupt the database - it doesn't seem like happened here, since 1.17.3 is the latest version, but is there any possibility it did?

**Comment by flber** [comment]
Hmm, ideally I'd keep my bookmarks, but running `lsof ~/home/username/.config/Min/IndexedDB/file__0.indexeddb.leveldb/LOCK` returns `No such file or directory`, and while I don't think I've upgraded and then downgraded (and then upgraded again) it's not impossible.

**Comment by flber** [comment]
Would it be possible to save the bookmarks, then delete the config folder?

**Comment by PalmerAL** [comment]
Oops, I wrote the command incorrectly, it should be `lsof ~/.config/Min/IndexedDB/file__0.indexeddb.leveldb/LOCK`; do you get anything with that?

The bookmarks are stored in the database, so if you can't open the database, I'm not aware of any way to save the bookmarks unfortunately.

There's a tool here that supposedly restores leveldb databases: https://github.com/kesla/level-repair. I wasn't able to get it to install, but I think what you're supposed to do is:
```
npm -g install level-repair
cd ~/.config/Min/IndexedDB/file__0.indexeddb.leveldb/
level-repair
```

It might be worth trying (make a second copy of the database first), but I'm not sure if it will work.

Sorry I don't have a better solution :(

**Comment by PalmerAL** [comment]
Actually, we do have one other bug report from a few months ago with similar behavior: #1289, and according to that issue, running Min with `sudo min --no-sandbox` allows the browser to start normally. Maybe try that first?

**Comment by flber** [comment]
I don't get any output from that corrected command (`lsof ~/.config/Min/IndexedDB/file__0.indexeddb.leveldb/LOCK`), and running `sudo min --no-sandbox` does launch min without errors... but seeing as it doesn't load the settings.json file (the error is `ENOENT: no such file or directory, open '/root/.config/Min/settings.json'`) I'm not sure if that's better than just clearing my config file. 

And thank you, you've been very helpful!

**Comment by PalmerAL** [comment]
If you launch with `sudo min`, do your bookmarks show up?

**Comment by flber** [comment]
Running with sudo fails with `[63601:0115/124053.275631:FATAL:electron_main_delegate.cc(253)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.`

**Comment by PalmerAL** [comment]
Oh, I meant the `sudo min --no-sandbox` version.

**Comment by flber** [comment]
Ah, sorry. No, it does not, it looks like a new install.

**Comment by PalmerAL** [comment]
I'm out of good ideas here; my two remaining ones would be:
1. Check the permissions of a couple of the files in `~/.config/Min/IndexedDB/file__0.indexeddb.leveldb` and make sure you can access them.
2. Try the repair tool linked above.

Other than that, I'm not sure.

I'm sorry this happened!

From a design standpoint, we should probably consider having some kind of scheduled automatic bookmark backup (probably reusing the existing bookmarks export tool) to help recover from this.

**Comment by flber** [comment]
Oh well. I tried the level-repair tool (which was it's own struggle to install), but it didn't seem to change anything. I do have read and write access for all of the files in `~/.config/Min/IndexedDB/file__0.indexeddb.leveldb`, so that doesn't seem to be the issue either. Looks like I'll just delete the config folder and get a new start. 

Thank you for your help, I really appreciate it.
A scheduled bookmark backup in the future would be great, but for now I'm okay with just getting it working again. 

Also let me know if I should close this issue.

**Comment by PalmerAL** [comment]
Aw, sorry that didn't work! Please do let me know if that happens again. I'll close this and make a new issue for the automatic backups.
