### ISSUE TITLE
Twitter login

### ISSUE THREAD

**Issue by sospedra** [minbrowser/min#144]
For some reason I cannot log into Twitter. Maybe the no-tracking is being too aggressive?

**Comment by cakuki** [comment]
Post request to `https://twitter.com/sessions` is blocked even "Block trackers and ads" option is disabled for me.

**Comment by simonhochrein** [comment]
There should be a feature to whitelist domains from EasyList.

**Comment by PalmerAL** [comment]
@simonhochrein Can you file a separate issue for that?

(That isn't related to this issue, since this issue occurs even when content blocking is disabled).

**Comment by simonhochrein** [comment]
Oh sorry didn't notice that

**Comment by PalmerAL** [comment]
I've added a workaround for this in b72721e12f8d025e186dc047efa48d8f94a7079f. Would you be willing to try the master branch and see if it works?

**Comment by PalmerAL** [comment]
Closing as duplicate of #260.
