### ISSUE TITLE
MediaFire Issue

### ISSUE THREAD

**Issue by Ema-byte** [minbrowser/min#1446]
Hi, I found out that the COOKIES consent/deny pop-up in mediafire.com isn't clickable.

**Comment by Ema-byte** [comment]
> Hi, I found out that the COOKIES consent/deny pop-up in mediafire.com isn't clickable.

Experiencing this same issue with the same cookie's popup in other websites.

**Comment by Syndamia** [comment]
Duplicate of #1416, which in turn is a duplicate of #1381
