### ISSUE TITLE
redirection problems on litmy.ru

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1452]
- **Min Version:** 1.17.3
- **Operating system:** Arch KDE

## Expected Behavior
when clicking on a link it should redirect me to turbobit.net for file download

## Actual Behavior
it redirects me to litmy.ru main page

## To Reproduce
that site is for piracy so yeah... but the book i try to download is [this](https://litmy.ru/knigi/programming/389064-building-android-apps-in-python-using-kivy-with-android-studio-with-pyjnius-plyer-and-buildozer.html).

so on the bottom of the book's description it says download from turbobit
![image](https://user-images.githubusercontent.com/22417494/105412148-c3ac0580-5c4d-11eb-8bf9-87a88bc88d99.png)

and it redirects me to https://litmy.ru/ but if i try same link in Chromium it works and redirects me to turbobit.net

**Comment by shalva97** [comment]
https://user-images.githubusercontent.com/22417494/105412844-b17e9700-5c4e-11eb-8dfe-0a288c90002d.mp4

**Comment by PalmerAL** [comment]
That feels like it might be another popup window issue, but hard to say for sure. I don't have a VPN and I'm using a shared internet connection that's being monitored, so not sure I can debug this directly 🤷

**Comment by lubiedo** [comment]
Tested on 1.20.0-beta and working correctly. cc @shalva97

**Comment by shalva97** [comment]
can confirm, it works! nice
