### ISSUE TITLE
How to open new window

### ISSUE THREAD

**Issue by mfarooqi** [minbrowser/min#1453]
HI.
This is quite irritating when I want to open a new windows. I'm following a tutorial and for that I need two separate windows. 

1. from where i'm reading tutorial 
2. where i've to practice on. 

But I'm unable to open into a new window but only opening new "tasks" or "Tabs" and both are on the same window. 

Thank you

**Comment by Syndamia** [comment]
Right now, you can't, there is only one window. The feature request for multiple windows is quite old, #169. In short, the way the browser is coded, it doesn't really allow multiple windows.
