### ISSUE TITLE
better handling for tabs with about:blank#blocked 

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1455]
**Can you describe the problem you're facing?**
on some piracy sites many videos have adds on top of videos and if i want to play them multiple clicks are necessary. These clicks, of course, open lot of new tabs and all of them are about:blank#blocked, which requires me to close them one by one, click>close tab> go back>click>close tab and so on....

**What solution would you like?**
dont open those links. It will of course reduce the feedback that something happened, but will definitely be less annoying

**Are there any alternatives you've considered?**
open these tabs but do not switch, by default, to them, so there will be feedback for clicks. after few seconds Min could close them.

**Comment by PEPERSO** [comment]
Just for you to know, I've posted a very similar issue, see #1432 (I think it is an electron limitation, if I've undrestood well)

**Comment by Milo123459** [comment]
So you are proposing automatically closing about:blank#blocked?

**Comment by shalva97** [comment]
yeah, it will save me few clicks

**Comment by Milo123459** [comment]
Alright, I'll make a PR with a setting for that.

**Comment by Milo123459** [comment]
Happens with images as well, fantastic!

**Comment by PalmerAL** [comment]
@shalva97 If you get a chance, could you try the `window-open-fix` branch and see if that solves the issue?

**Comment by shalva97** [comment]
finally I found the link that would open as about:blank#blocked. If you compose a new email on gmail, then add a link to a text, hover that text and click on the popup, it will always open as blocked.
![image](https://user-images.githubusercontent.com/22417494/110859082-55420600-82d4-11eb-81b6-b2f7b2266d0a.png)

it does work, but it feels wrong. like you keep clicking on a link and nothing happens.... it feels like void... something missing.... 

if you also add some kind of feedback it would be better....

**Comment by shalva97** [comment]
any news here? I guess without feed back it would also be fine, its just annoying to switch to tabs that do not load....

**Comment by PalmerAL** [comment]
I think #1608 should fix this completely, assuming I can solve the other issues with it that prevent it from being merged.

Otherwise, the previous fix is probably the best option.

**Comment by shalva97** [comment]
we support popups so I will close this. Have not notices much popups from piracy websites too.... maybe later I will reopen if I find some really annoying website
