### ISSUE TITLE
use native titlebar in linux...

### ISSUE THREAD

**Issue by ergpopler** [minbrowser/min#1456]
**Can you describe the problem you're facing?**
the title bar is whatever bullshit comes as default, rather than using the same one every other application on my system uses.

**What solution would you like?**

an option to use the system theme, similar to how the chromium browser has this option

**Are there any alternatives you've considered?**
no.

![correct](https://user-images.githubusercontent.com/64165309/105495838-a8abb680-5c8a-11eb-9067-de8ad546c70d.png)
^^^^ is correct, what it should be.

![incorrect](https://user-images.githubusercontent.com/64165309/105495860-b103f180-5c8a-11eb-9739-24a12a23c6be.png)
^^^^ what it actually is :(

**Comment by shalva97** [comment]
Hey dont be so rude. have you tried Preferences > use separate title bar? at least it works on my KDE

**Comment by ergpopler** [comment]
> Hey dont be so rude. have you tried Preferences > use separate title bar? at least it works on my KDE

Oops, i missed that, sorry. 
I thought it meant using like another built in theme, LOL.
