### ISSUE TITLE
Hide <webview> with recommended approach

### ISSUE THREAD

**Issue by ghost** [minbrowser/min#146]
See [this](https://github.com/electron/electron/blob/master/docs/api/web-view-tag.md#css-styling-notes):

> `webview` has issues being hidden using the `hidden` attribute or using `display: none;`. It can cause unusual rendering behaviour within its child `browserplugin` object and the web page is reloaded, when the `webview` is un-hidden, as opposed to just becoming visible again. The recommended approach is to hide the `webview` using CSS by zeroing the `width` & `height` and allowing the element to shrink to the 0px dimensions via `flex`.
> 
> ```
> <style>
>   webview {
>     display:inline-flex;
>     width:640px;
>     height:480px;
>   }
>   webview.hide {
>     flex: 0 1;
>     width: 0px;
>     height: 0px;
>   }
> </style>
> ```

**Comment by PalmerAL** [comment]
I'm reluctant to change this, since the ```visibility: hidden``` method Min currently uses doesn't seem to have any problems. Display: none was causing a lot of problems (see electron/electron#4783), but after switching to the current method all of the problems went away.
