### ISSUE TITLE
App threw an error when running [TypeError: Cannot read property 'on' of undefined]

### ISSUE THREAD

**Issue by glensimister** [minbrowser/min#147]
Hi. After linking electron to min-master but getting the above error. I'm using Yosemite. Any ideas? Cheers

**Comment by PalmerAL** [comment]
When the error occurs, you should get a dialog box with the full error message and line number. Can you please post the contents of that dialog box?

**Comment by glensimister** [comment]
Yeh sure, sorry :) 

Uncaught Exception:
TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (/Users/home/Desktop/GiveMeCredit/min-master/main.build.js:89:4)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at loadApplicationPackage (/Applications/Electron.app/Contents/Resources/default_app/main.js:257:23)
    at Object.<anonymous> (/Applications/Electron.app/Contents/Resources/default_app/main.js:289:5)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)

**Comment by PalmerAL** [comment]
Hmmm, I have no idea why this is happening. This code loads the ```app``` module

```
const electron = require("electron");
const app = electron.app; // Module to control application life.
```

Except that ```app``` is undefined, which doesn't make sense because it is part of the electron module. The electron module definitely exists, or the ```require("electron")``` part would have thrown an error, but it's apparently missing some of the modules.

**Comment by PalmerAL** [comment]
Can you add a ```console.log(electron)``` to main.js (you will need to run ```grunt``` after doing that), and see what's actually being loaded?

**Comment by PalmerAL** [comment]
This looks like the same issue as electron/electron#5662 - did you install the electron module from NPM?

**Comment by glensimister** [comment]
Hi. Sorry for the late reply. I don't remember what i did as i deleted it. I downloaded min again and this time i was able to fire it up...although it doesn't work. There are no errors, just a blank browser page + two buttons (top right). 

i cloned the repo > npm install > grunt > /Path/To/Electron /Path/To/Min. Have i done something wrong again? 

Thanks

**Comment by wb9688** [comment]
What if you run `grunt build` instead of `grunt`, remove the min appdata
folder and then run the executable somewhere in `dist/app`?

**Comment by glensimister** [comment]
i tried 'grunt build' but i stopped it as it was taking too long to download the files and i don't have unlimited internet

**Comment by dbfreem** [comment]
Closing this since it hasn't had any comments since 2016.
