### ISSUE TITLE
cannot drag selected tab to another task

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1479]
- **Min Version:** 97d692d
- **Operating system:** Arch

## Expected Behavior
I should be able to drag selected tabs to another task

## Actual Behavior
when I drag them to another task and release mouse button nothing happens and cannot release current dragged tab, closing Task View at this moment deletes some tasks

## To Reproduce
try to drag selected tab to another Task and then reopen Task View. Be careful it might mess a lot of your tasks...

**Comment by shalva97** [comment]
https://www.youtube.com/watch?v=xoIeqAQThsk

**Comment by PalmerAL** [comment]
Sorry about that, should be fixed in 32229d24e5370fa3e3b48ec4b05ac4bed7dc86b3.

This code is kind of a mess, so let me know if you notice any more issues with it.

**Comment by shalva97** [comment]
> This code is kind of a mess

that sounds bad :fearful:
