### ISSUE TITLE
Min.exe isn't a valid Win32 application

### ISSUE THREAD

**Issue by wb9688** [minbrowser/min#148]
When I try to run [the latest release](https://github.com/minbrowser/min/releases/download/v1.2.2/Min-v1.2.2-win32-ia32.zip) on Windows XP I get the error `Min.exe isn't a valid Win32 application`:

![Screenshot](https://cloud.githubusercontent.com/assets/9780201/15255282/5ba71fce-193b-11e6-8868-7f140cf05542.JPG)

**Comment by PalmerAL** [comment]
Electron (and Chromium) only supports Windows 7 and higher. If you need to run Min on this computer, I think Virtualbox supports Windows XP, so you could install Ubuntu in a virtual machine and run Min in that.
