### ISSUE TITLE
cannot save video with direct link

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1480]
- **Min Version:** 97d692d
- **Operating system:** Arch

## Expected Behavior
if I have a direct video link that only plays video and I should be able to save it with CTRL + S 

## Actual Behavior
it saves just the html text

## To Reproduce
go to[ this video](https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/VCHXZQKsxil3lhgr4/videoblocks-man-scraping-with-a-plate-a-strawberry-cake-into-garbage-bin_rp1goa9vh__e0ac062029992e327636032b292c9019__P360.mp4) and press CTRL + S
it works fine in Chromium

**Comment by Milo123459** [comment]
Odd, let me see if this happens.

**Comment by Milo123459** [comment]
Yup, this happens, it "should be easy" as we can just check content types, does this also happen with images?

**Comment by shalva97** [comment]
not sure about images, I always right click -> save image or copy image

**Comment by Milo123459** [comment]
Let me see.

**Comment by Milo123459** [comment]
Happens for images as well, fun.
