### ISSUE TITLE
Hardcoded main menu hotkeys

### ISSUE THREAD

**Issue by Theliraan** [minbrowser/min#1486]
- **Min Version: 1.17.3**
- **Operating system: Windows 10 20H2**

Hotkeys in menu hasn't been updated after change and restart

## Expected Behavior
Hotkeys in top menu has been updated

## Actual Behavior
Hotkeys in top menu has not been updated

## To Reproduce
1. Open preferences via **Edit -> Preferences**
2. Change any hotkey that present in **main menu** (e.g. **Duplicate Page**)
3. Restart browser
4. Open **main menu** and observe changed hotkeys

## Attachments
![image](https://user-images.githubusercontent.com/3195612/106739872-bec25b00-662a-11eb-9e87-70757ae1aad8.png)

**Comment by Milo123459** [comment]
Does CTRL+D work? Trying to see if this is a visual issue or not.

**Comment by Theliraan** [comment]
> Does CTRL+D work? Trying to see if this is a visual issue or not.

Yes, it's totally visual issue: main menu hotkey strings not updates from config on restart

**Comment by Milo123459** [comment]
Alright, I'll have a look into it.

**Comment by Milo123459** [comment]
Lord, everything inside is fully hard coded, this shall be... fun?

**Comment by Theliraan** [comment]
> Lord, everything inside is fully hard coded, this shall be... fun?

Part of "startup boost" doctrine I believe :)

**Comment by Milo123459** [comment]
Fixed the duplicate tab, I mean, I'll be here a while fixing them all so I'll do that, I'll explain:
accelerator: settings.list?.keyMap?.duplicateTab?.replace('mod', 'CmdOrCtrl') || 'shift+CmdOrCtrl+d', 

We use that as the accelerator, we are trying to get the keyMap and replace mod with CmdOrCtrl so it doesn't just display D for example. If @PalmerAL has any comments, please let me know!
