### ISSUE TITLE
remove warning when launching min from cli

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1495]
- **Min Version:** 1.17.3
- **Operating system:** Arch
- 
## Expected Behavior
there should be no warnings, that are useless to users, in CLI

## Actual Behavior
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.

## To Reproduce
run min from CLI

**Comment by PalmerAL** [comment]
This should be fixed in 1.18, can you try updating the Arch package?

**Comment by shalva97** [comment]
It is weird. I have latest master branch, did `npm run build` but it still displays the warning and the version is still 1.17.3

shouldnot master branch be 1.18.1? anyways, Arch package doesnot show that warning.

**Comment by shalva97** [comment]
my bad, did `git pull` and did not read that it errored :D
