### ISSUE TITLE
Change the dock console position

### ISSUE THREAD

**Issue by sospedra** [minbrowser/min#151]
I don't know if it's me or this option is missing.

**In Min browser**
![image](https://cloud.githubusercontent.com/assets/3116899/15267349/0a64b22c-19c0-11e6-9c8b-2ef42f2e2f59.png)

**In Chrome**
![image](https://cloud.githubusercontent.com/assets/3116899/15267352/15366fb0-19c0-11e6-8cf4-a33dc768e129.png)

**Comment by simonhochrein** [comment]
Unfortunately, Electron does not support that functionality in webviews.

**Comment by PalmerAL** [comment]
This was fixed a while ago.
