### ISSUE TITLE
image background is black

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1514]
- **Min Version:** 1.18.1
- **Operating system:** Arch

## Expected Behavior
![image](https://user-images.githubusercontent.com/22417494/108568148-fc113300-7322-11eb-86d8-4a774accffdf.png)

## Actual Behavior
![image](https://user-images.githubusercontent.com/22417494/108568174-07645e80-7323-11eb-86f8-8d109f484594.png)

## To Reproduce
go to [this website](https://preview.redd.it/1krx669m5hi61.png?width=761&format=png&auto=webp&s=85d96c7b8d74c3e490dc63f2dffc73d6b44b7a0d)

**Comment by Syndamia** [comment]
That is some weirdness with default background color. Basically the page is this shade of black, but the actual picture (that is mostly transparent) doesn't have it's background color explicitly set, so Min just leaves it as is.

We should probably make it so images have a white background by default.

**Comment by PalmerAL** [comment]
I can reproduce this with Electron 11 but not in Electron 12, so I think it may be fixed in the next Chromium update. Can you wait for the next release and then see if this still happens?

**Comment by shalva97** [comment]
this now works okay, nice. probably that electron update fixed it
