### ISSUE TITLE
Protocol for contributing

### ISSUE THREAD

**Issue by cryptobird** [minbrowser/min#152]
What stuff is in progress and what stuff is up for grabs? 
I realize I in particular have been throwing a lot a of suggestions your way, and would love to help out. 
Is there anything in particular that I can jump into and lend a helping hand?

**Comment by PalmerAL** [comment]
Thanks for the help!

Pretty much everything is available if you want to work on it - if I'm working on something, I'll comment on the issue with a link to the branch.

The dilemma, though, is that I'm not sure how many features should be added to Min. Min is currently really lightweight and fast, and I'd like to keep it that way, but there are also a lot of features people are used to from other browsers that are missing in Min. In general, I'd like to avoid features that can't be implemented without reducing performance, or put them in extensions (when Min has support for that).

Some things that I plan on adding in 1.3 that you could work on if you'd like: #81, #91, #136. A lot of the stuff Min needs isn't actually in an issue, though. Some of the areas that need improvement:

* Simplifying the tabs code
* Reducing the startup time
* Improving the speed of the content blocker
* Other performance improvements

In general, fixing bugs and making Min faster is just as (or more) important than adding features, so improvements in that area are always good!

**Comment by plrenaudin** [comment]
Will you add some tests and continuous integration in the future?
That would help contributors to make sure that their PR are not introducing regressions.

**Comment by PalmerAL** [comment]
@plrenaudin Filed a separate issue about that: #157.

**Comment by wb9688** [comment]
Maybe we can use Waffle.io…

**Comment by plrenaudin** [comment]
Anything like this or Trello would be nice indeed.
