### ISSUE TITLE
Concurrent modification of "settings" object corrupts "settings.json"

### ISSUE THREAD

**Issue by yulucodebase** [minbrowser/min#1520]
- **Min Version:** 1.18.1
- **Operating system:** Raspberry Pi OS and should happen on all Linux

## Expected Behavior
Settings are correctly saved and the app can be restarted.

## Actual Behavior
**`settings.json`** (in user's data directory)** is **corrupted when the change requires restart**. The app crashes during restart due to the corrupted settings. The corrupted json file ends with an extra `}`. For example:

```JSON
{"restartNow":true,"clientID":"5525817712610477","installTime":1614348000000,"useSeparateTitlebar":true}}
```

Currently, I can only reproduce this when changing **"use separate title bar"** but in theory it should happen for any setting that requires restart (so "use a custom agent" should also has the issue but I haven't been able to reproduce it yet).

The possible cause of the issue is likely related to the following calls in **`pages/settings/settings.js`**:
```Javascript
separateTitlebarCheckbox.addEventListener('change', function (e) {
  settings.set('useSeparateTitlebar', this.checked)
  showRestartRequiredBanner()
})
```
Notices above, `settings.set()` will update the "settings" object and call the async file write (saving "settings.json"). 

It's possible that by the time`showRestartRequiredBanner()` is executed, the file operation hasn't completed yet. The trouble with this is that `showRestartRequiredBanner()` also modifies the `settings` object (it updates "restartNow" property) and write to the "settings.json" file. 

**Basically, it's a race condition between two file write operations (to the same file) with slightly different contents.**

_BTW, I found this issue while trying to enable **"use separate title bar"** for Mac OS, which is a work in progress (will raise separate pull request later)._

## To Reproduce
_As described above, this is a race condition issue. In order to reproduce it you might need to repeat the following steps multiple time since it's related to the timing of two concurrent operations._

1. Launch your app on Linux or Raspberry Pi.
2. Go to "settings" and just change "use separate title bar" setting.
3. Once the setting is changed and the "You need to restart to apply these changes" warning is displayed, check "settings.json ( this file is under user's data directory, for example, on my Raspberry Pi it's under `/home/{your user home}/.config/Min-development`).
4. Once confirmed the file content is corrupted, try to restart the app. It should crash.

**Comment by yulucodebase** [comment]
I can think of two ways to fix this:

1. Instead of saving `restartNow` property in `settings` object, just save it somewhere else and there's no need to persist it. It's only read back to display the "please restart the application" notification, if the user did not restart the app immediately after updating the settings.

2. Change `settings.set()` function to accept a third parameter to indicate if the change requires restart or not and update the `settings` object accordingly. `showRestartRequiredBanner()` function will no longer need to update the `settings` object hence it's no longer a race condition.

I feel the first approach is better as I can't see why `restartNow` needs to be saved in the same `setttings` object and persist between sessions. But I could be missing something important since I'm still quite new to JS and Min's source code.

**Comment by PalmerAL** [comment]
Oh, this is is a really good find. We've had occasional reports of the settings file becoming corrupted, but I've never connected it to multiple simultaneous writes. And that is indeed what the docs say:

 > It is unsafe to use fsPromises.writeFile() multiple times on the same file without waiting for the promise to be settled.

The restartNow changes make this easier to reproduce, but this can happen even without that - for example, there are settings that get updated in a setInterval that could overlap with another change. So I think we need a more general fix of adjusting the settings code to queue write operations. I should be able to get to that in the next few days, or you're welcome to work on it if you want.

The chance of reproducing this probably varies depending on IO speed as well - I've never been able to, but on a pi with an SD card it's probably more likely.

**Comment by yulucodebase** [comment]
Cool! I can reproduce the this issue on Mac (16' MBP 16GB) when updating "use separate title bar" option. I agree it's related to IO but not necessarily just on slow machines.

Please feel free to fix it the way you like it. I'm more than happy to help to test or review.
