### ISSUE TITLE
Custom Bangs allow text search

### ISSUE THREAD

**Issue by Zenyaria** [minbrowser/min#1528]
Simple suggestion, could there be some sort of regex system which allows searching or inputting text into bangs, like {query}.

Input url would be:
https://randomsite.com/?q={query}

!randomsite cats

redirects to

https://randomsite.com/?q=cats

**Comment by PalmerAL** [comment]
You can actually do this already, I think I just forgot to document it. You would use %s (same as for custom search engines), so the redirect URL would be https://randomsite.com/?q=%s

**Comment by PalmerAL** [comment]
Added documentation: https://github.com/minbrowser/min/wiki/Home/_compare/ed699472d6818e9970739dfae5782729a73b136e
