### ISSUE TITLE
Chrome Extensions

### ISSUE THREAD

**Issue by AdityaCyberSafe** [minbrowser/min#1529]
Hi PalmerAL,
Is there a way we could add support for Chrome extensions in Min?
I've heard of electron-extensions by sentialx.

**Comment by Syndamia** [comment]
Already discussed in #1 ([this](https://github.com/minbrowser/min/issues/1#issuecomment-674125940) comment):

> Extension support in Electron is still incomplete as far as I know.
> 
> The electron-extensions library won't work because of this: https://github.com/sentialx/electron-extensions/blob/master/PATENTS
> 
> So it's unlikely to happen soon unless someone wants to write another extension library - if that's something you'd be interested in doing, let me know!
> 
> Expanding the capabilities of userscripts is probably a more viable path forward.
