### ISSUE TITLE
I can't download files

### ISSUE THREAD

**Issue by ghost** [minbrowser/min#1532]
Hi! In browser Min (I use russian version) I need to download a file (png in google) and I can't download :(

**Comment by PalmerAL** [comment]
* What URL is this happening on?
* What exactly happens when you try to download the file?

**Comment by Kepler-69c** [comment]
The author of the issue is probably referring to the lack of a "Save Image (as)" option in the context menu on Google (and some other sites) - see #2160.
Close the issue as stale, as the author has not replied for two years.
