### ISSUE TITLE
splash tab telling me I've updated Min and advertising a survey, despite no update and auto checks for updates being turned off

### ISSUE THREAD

**Issue by davidn73** [minbrowser/min#1544]
- **Min Version: 1.18.1**
- **Operating system: Windows 10**

## Expected Behavior

not to tell me I've updated to a new version seemingly randomly, then asking for a survey, when I've turned off automatic checking for updates

## Actual Behavior
Min told me I've updated to a new version seemingly randomly, then asked for a survey, despite having turned off automatic checking for updates

## To Reproduce
no clue, been using the same version for a few weeks, and there doesn't appear to have been an update

Steps I took: opened Min, as I've done every other day of use

**Comment by PalmerAL** [comment]
I think I've seen a few reports of this before, and the cause has been that the localStorage database gets corrupted, so Chromium deletes it automatically. That makes Min act like it's being run for the first time after an upgrade even though it isn't.

If you close the survey prompt, does it keep coming back, or does it stay gone?

**Comment by davidn73** [comment]
hasn't returned yet, so I guess it's a feature rather than a bug?
