### ISSUE TITLE
Choose a code style

### ISSUE THREAD

**Issue by PalmerAL** [minbrowser/min#155]
<a href="https://github.com/feross/standard">standard</a> or <a href="https://github.com/beautify-web/js-beautify">js-beautify</a> maybe?

**Comment by plrenaudin** [comment]
StandardJS seems a good start.

Otherwise it would be good to implement JSHint with their default config file: https://github.com/jshint/jshint/blob/master/examples/.jshintrc

**Comment by wb9688** [comment]
+1 for StandardJS. Can I make a PR which changes the code to that style?

**Comment by PalmerAL** [comment]
@wb9688 I'm going to leave this open for another day or two to see if there are any other opinions. After that, and after #154 is merged, a PR would be great.

**Comment by wb9688** [comment]
@PalmerAL Let me now when I can submit a PR…

**Comment by PalmerAL** [comment]
@wb9688 I guess it's OK to change the style now that #154 has been merged.

**Comment by PalmerAL** [comment]
This has been fixed.
