### ISSUE TITLE
Can't share screen on Discord

### ISSUE THREAD

**Issue by w3slley** [minbrowser/min#1554]
Is Min capable of allowing the share screen functionality in websites like Discord? I tried to do just that but when the share screen button is pressed nothing happens. I noticed that whenever a browser permission is required, an icon appears at the left side of the website's title. I have enabled permission for notifications, audio and video, but whenever I try to share the screen, no permission is required and no icon appears in the tab. I tried to look for issues with similar problems but was not able to find anything like this.
Thanks!

**Comment by Syndamia** [comment]
> Is Min capable of allowing the share screen functionality in websites like Discord? 

Nope, but it's a known issue: https://github.com/minbrowser/min/issues/972
