### ISSUE TITLE
cannot block website with customFilters.txt

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1555]
- **Min Version:** 1.18.1
- **Operating system:** arch

## Expected Behavior
if I write the text below in the filers file it should block twitch completely

```
https://*.twitch.tv/*
```

## Actual Behavior
network tab shows 200 OK status
![image](https://user-images.githubusercontent.com/22417494/113333034-0287c700-9333-11eb-8b14-f047f6eb62b3.png)

and this is my complete filters file with websites I hate. Is this correct?
```
// do not show "people also search"
https://www.google.*/xjs/*

// block reddit live videos
https://watch.redd.it/*
https://www.redditstatic.com/desktop2x/img/rpan-loading.gif

// fuck twitch and their 4K autoplay adds
https://*.twitch.tv/*

// other random crap
https://jsonformatter.curiousconcept.com/*
http*://www.linuxquestions.org/*
http*://www.ultrabookreview.com/*
http*://alli-ti-cod.com/*
```
## To Reproduce
write that to the filters file and try to load twitch. it will still load.

**Comment by PalmerAL** [comment]
If I enable "block all ads", and then add this to my filters:
```
https://*.twitch.tv/*
```
I get this:

<img width="1088" alt="Screen Shot 2021-04-01 at 11 41 54 PM" src="https://user-images.githubusercontent.com/10314059/113381165-e50f2900-9343-11eb-8488-8604d949b580.png">

If I also add a second filter:
```
https://*.twitchcdn.net/*
```

I get this:

<img width="1088" alt="Screen Shot 2021-04-01 at 11 42 47 PM" src="https://user-images.githubusercontent.com/10314059/113381198-fc4e1680-9343-11eb-9984-6384a8bc1d55.png">

It's not currently possible to block the main HTML response (so you're going to see _something_, but it should be possible to block all the subresources and get a non-functioning, almost-blank page like the last image.

Does that match what you see with those filters?

Also, do the other filters you have listed work (i.e. is the customFilters file being loaded?)

**Comment by shalva97** [comment]
yeah, it is working just as you described. Before that websites were in DNS filter, so I would never accidentally open them. decided to put them in the customFilters.txt file, which would simplify sharing these blacklists via Github. This might sound weird like why I want it... because 1 or 2 months later I will forget the problems there was with that websites and will suffer again.

> It's not currently possible to block the main HTML response

if that filters just break  these websites and thats how it is designed it is enough for me... but it would be nice to block them completely. I mean they are called filters and thats what they should do...

**Comment by lubiedo** [comment]
I guess what you are looking for is a DNS sinkhole. The filters from AdBlock are going to block resources loaded by the page only. If it's an emergency you can add `0.0.0.0 twitch.tv www.twitch.tv` to your hosts list (`/etc/hosts` in Linux and macOS and `C:\Windows\System32\Drivers\etc\hosts` on Windows).
