### ISSUE TITLE
Crashes after turning off "Send usage statistics"

### ISSUE THREAD

**Issue by Raghav-Dixit** [minbrowser/min#1580]
- **Min Version: 1.19.0**
- **Operating system: macOS 11 (Intel Processor)**

Whenever I try to turn off "send usage statistics" in settings, Min starts to take up 100% CPU.  I can't switch tabs, or go to a new webpage. I can't quit the app like I normally can, either. If I force quit and relaunch, it does work, but some of my settings (like dark mode) go back to default. Also, the "send usage statistics" button does not change after relaunching.

**Comment by PalmerAL** [comment]
This was fixed in 1.19.1 and later, please try updating.

**Comment by Raghav-Dixit** [comment]
Okay, thanks!
