### ISSUE TITLE
Unable to make Min default Browser in macOS

### ISSUE THREAD

**Issue by Raghav-Dixit** [minbrowser/min#1583]
- **Min Version: 1.19.2**
- **Operating system: macOS 11 (Intel)**

## Expected Behavior
I wanted ot make Min my default browser on macOS.

## Actual Behavior
Does not list the browser in the dropdown.

## To Reproduce
1. Go to System Preferences > General.
2. Click on the default browser dropdown.

For me, Min is not listed.

**Comment by dyogurt** [comment]
Hello @Raghav-Dixit, this behaviour was also experienced by me. There is a workaround using homebrew described by @iambudi in issue #1354.

Hope it helps :)

**Comment by Raghav-Dixit** [comment]
Okay, I will try that.

**Comment by Raghav-Dixit** [comment]
What command should I use? I tried "brew reinstall --cask min", "brew uninstall --cask min; brew install --cask min", and "brew upgrade min" to see if there were any updates that fixed the problem. None of these work.

**Comment by dyogurt** [comment]
What I did:

1. Uninstall Min
2. Install Homebrew
3. Run the code bellow like @iambudi mentioned

```
brew install defaultbrowser
defaultbrowser min
```

4. Restart the computer

The general settings still won't show Min as the default (at least not for me) but the links now open on Min.

**Comment by Raghav-Dixit** [comment]
Thanks! This solution works.
