### ISSUE TITLE
Prompts to save password but it isn't a password

### ISSUE THREAD

**Issue by lepicsaintloup** [minbrowser/min#1605]
- **Min Version: 1.19.2**
- **Operating system: Windows 10**

## Expected Behavior
It shouldn't offer to save a password for this field as it is a 'tax' field automatically calculated

## To Reproduce
Not sure whether it is only this site.
![Snipaste_2021-05-13_16-38-30](https://user-images.githubusercontent.com/43662321/118088674-bee0ac80-b40a-11eb-950b-981f9f6adcaa.png)

**Comment by PalmerAL** [comment]
Can you do this?

1. Right-click on the tax field (the one with 2.40 in it)
2. Choose "inspect element"
3. You should see a window appear with the `<input>` field highlighted. Take a screenshot of that and post it here.

**Comment by Sestowner** [comment]
This also happens when I submitting 2FA code on GitLab, because the `<input>` field includes the `user` in the `name` attribute.

```<input class="form-control gl-form-input" required="required" autofocus="autofocus" autocomplete="off" title="This field is required." data-qa-selector="two_fa_code_field" type="text" name="user[otp_attempt]" id="user_otp_attempt">```

**Comment by lepicsaintloup** [comment]
Just in case you still want to see:
<input type="text" name="rwTotalTaxUser[]" id="rwTotalTaxUser[]"
value="0.00" class="rwTotalTaxUser invoiceInput validMoney"
onkeyup="updateOverTypedTaxRows(1, this);" onkeypress="return
allowInput(event, this);" onfocus="this.select()"
onblur="formatNumericUserInput2dp(this);" style="background-color: rgb(255,
255, 255);">

**Comment by PalmerAL** [comment]
Thanks, that is helpful.

This has the same issue as Gitlab, which is that "user" is in the field name. I was wondering if there was a way to fix our field detection to not detect this, but it looks like there's probably not, so Sestowner's solution is probably the best one.
