### ISSUE TITLE
"save page as" adding html tags and .html extension in file

### ISSUE THREAD

**Issue by Kungfu-ckoder** [minbrowser/min#1613]
"save page as" adding html tags and .html extension in file after original extension. lets say i want to download this samba config file (smb.conf.default), from : 
https://git.samba.org/samba.git/?p=samba.git;a=blob_plain;f=examples/smb.conf.default;hb=HEAD

when i do "save page as" it adds html tags in file and .html extension (smb.conf.default.html)

i don't know if this is bug or feature 

Thanks in advance

**Comment by shushtain** [comment]
Well, the page you are on is an html page with the code wrapped in "<pre>" tags, so it's not like a plain text file you could expect to download. So the feature seems to work correctly. If the original file is not html file, it may be a feature of git/github to let you preview the contents on the web. So download the file from the directory, without previewing it first.

**Comment by Kungfu-ckoder** [comment]
okay, looks like its a feature. closing this issue
Thanks
