### ISSUE TITLE
1Password does not work

### ISSUE THREAD

**Issue by eneskutlay** [minbrowser/min#1626]
- **Min Version: 1.19.2**
- **Operating system: Windows 10**

## Expected Behavior
1password form filling feature should work.

## Actual Behavior
Although I typed my master password correctly, nothing happens and it asks for my master password again.

https://user-images.githubusercontent.com/59585311/119834004-3da81000-bf08-11eb-9ef0-b30dbe539355.mp4

**Comment by DavidHornDesign** [comment]
Am using Version 1.25.1 and 1Password is not working.  

https://www.dropbox.com/s/wjfx4tv5u9f9u5g/min-1password.mp4?dl=0

**Comment by juancwu** [comment]
I am having the same issue, any updates?

**Comment by sppfly** [comment]
Same issue on here

**Comment by mentionmenot** [comment]
Same problem here. 
MacOS High Sierra.
Min 1.29.0 (I cannot use 1.30.0 because it's not support High Sierra).
Issue: 1Password does not show auto-fill after I enter master password.

@PalmerAL could you please take a look for us.

**Comment by tconroy** [comment]
+1 - same issue. Ongoing convo over in #2151 on the same category of issue so just linking that here if it helps.

**Comment by PalmerAL** [comment]
I'm going to close this issue in favor of #2151. It's not clear to me whether there's one issue or multiple issues going on here, but hopefully we can figure it out there.
