### ISSUE TITLE
Provide a Flatpak as software package

### ISSUE THREAD

**Issue by x80486** [minbrowser/min#1631]
[Flatpak](http://docs.flatpak.org/en/latest/introduction.html) is a technology for building, distributing, installing and running applications – primarily targeted at the Linux desktop and desktop applications.

Currently, [almost](https://flathub.org/apps/details/org.mozilla.firefox) [all](https://flathub.org/apps/details/io.gitlab.librewolf-community) [major](https://flathub.org/apps/details/org.chromium.Chromium) [browsers](https://github.com/flathub/com.google.Chrome) [are](https://flathub.org/apps/details/org.gnome.Epiphany) on Flathub already, so `Min` would definitely benefit from this.

**Comment by Syndamia** [comment]
Duplicate of #750, which is answered by [this](https://github.com/minbrowser/min/issues/735#issuecomment-485219682) comment.

**Comment by wommy** [comment]
i think this should be reopened

https://github.com/minbrowser/min/issues/735#issuecomment-1075627286
