### ISSUE TITLE
scrolling mouse while hovering close button closes the tab

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1639]
- **Min Version:** 1.19.2
- **Operating system:** Windows 10

## Expected Behavior
when scrolling and hovering anywhere on tabs, they should not close

## Actual Behavior
they close

## To Reproduce
create new tab, hover your mouse to X icon and scroll

**Comment by lubiedo** [comment]
I believe this is a feature. See: https://github.com/minbrowser/min/blob/master/js/navbar/tabBar.js#L114-L128
If you scroll down it should show the task list.

**Comment by shalva97** [comment]
oh well... thats sad
