### ISSUE TITLE
Page history - back and forward buttons

### ISSUE THREAD

**Issue by ep1955** [minbrowser/min#1646]
I notice there is still no page forward button to go with the page backward button.  Would be a really great feature to have since in a browser your hand is typically on the mouse anyway.  Can't be any more difficult than a back button, any chance we'll see one soon?  I can't be the only user that would like to see this.  Thanks!

**Comment by lubiedo** [comment]
I second this and would like to propose a solution: what if the back button is transformed to the forward button if the meta key is pressed?

Like this:

![image](https://user-images.githubusercontent.com/63729414/121922262-0652a500-ccf7-11eb-9633-7e1d98f9fea0.png)

**Comment by lubiedo** [comment]
Merged on #1665.
