### ISSUE TITLE
wrong page loads for the url

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1654]
- **Min Version:** 1.20.0-beta
- **Operating system:** Windows 10

## Expected Behavior
it should show a graphics card being sold
![image](https://user-images.githubusercontent.com/22417494/122196226-1958a700-cea8-11eb-901c-96c4f0d2a0d3.png)

## Actual Behavior
it loads main page
![image](https://user-images.githubusercontent.com/22417494/122196293-2bd2e080-cea8-11eb-913e-ace17def87ce.png)

## To Reproduce
try[ this link](https://l.messenger.com/l.php?u=https%3A%2F%2Fm.mymarket.ge%2Fka%2Fpr%2F21391677%2FvideobaraTi%2FGtx-960-2-GB-Evga&h=AT1JmdVzK6EnUpnklQ06UcE8LHCfz3rR31dkBe0lGXbWJc4P5uXf6iLjm_YpqRRI8TXyBcx6YQLh5xdM1dAFuSO3EU3f1BiZr7iGqt7egBcxKB9VhrluFREmY8sbFxF7zgLcug)

**Comment by PalmerAL** [comment]
I'm assuming this is only an issue when opening the link from messenger? I get sent to a login page if I open it, and I don't have a facebook account.

**Comment by shalva97** [comment]
okay something is different with that link now. maybe they updated it? it no longer redirects to homepage....
