### ISSUE TITLE
Tasks/Session import

### ISSUE THREAD

**Issue by theverahman** [minbrowser/min#1656]
Good day developers!

I just wanna ask or suggest, it could be convenience if user can export>import task or browsing session which could be opened later.

Regards,
Your supportive software user

**Comment by PalmerAL** [comment]
There isn't really an export feature, but the task list is just a JSON file, stored here:

~/library/application support/min on macOS
\users\username\appdata\roaming\min on Windows
/home/username/.config/Min on Linux

Called sessionrestore.json. You could save that and write to it if you want.

What would you use this feature for?

**Comment by theverahman** [comment]
It's just my bad habit. I am usually open a bunch of tutorial, article, and reference pages and sometimes need to reopen it at the same pace in other pc. I am using v7 Session plugin on Opera before and it support export-import session and send it through mail to reopen it on other PC. 

Thank you for your information. I could use simple script to copy sessionrestore.json and send it to other PC.


![image](https://user-images.githubusercontent.com/43458924/122500727-82156000-d01d-11eb-92f5-015f3681c2c0.png)

**Comment by shalva97** [comment]
Git is also good for this. I have C:\users\username\appdata\roaming\min in Git and every week I do `git commit` and `git push`. 

my versioned files are:
`customFilter.txt` which contains rules to block some websites
`userscripts/*` folder
`sessionRestore.json` here are all the tabs and tasks
`settings.json` here are preferences
