### ISSUE TITLE
Add shortcuts to switch between tabs

### ISSUE THREAD

**Issue by rafaelrinaldi** [minbrowser/min#166]
One thing I miss a lot is the ability of switching between active tabs using `⌘⇧[` (previous) and `⌘⇧]` (next) which is the way I do in Safari, Google Chrome and also iTerm2.

If you feel like adding this, I can open a PR. Just wanted to check with you first.

Thanks!

**Comment by plrenaudin** [comment]
It is already implemented in ctrl+tab and ctrl+shit+tab.
Those keybinding will be customizable once #154 is merged

**Comment by rafaelrinaldi** [comment]
@plrenaudin yay, thanks!
