### ISSUE TITLE
Minimize and maximize don't work

### ISSUE THREAD

**Issue by Thireb** [minbrowser/min#1662]
Hi, first of all I'll say that min is one hell of a browser. Now to the bugs, once I open the browser and resize the window and go to any website, browser won't maximize when I click maximize button, same with minimize button. 
When browser is in blank state, meaning when I've freshly opened it, minimize and maximize will work fine, but right after opening any URL, it won't.

**Comment by PalmerAL** [comment]
Please follow the issue template - which OS is this on?

**Comment by murty2** [comment]
For me too: Minimize, Maximize button won't work. I also cannot drag the browser window. Where is the drag area actually? I am using on Fedora 34 64-bit with LXQT Desktop
![min](https://user-images.githubusercontent.com/34612184/123677214-d89b4f00-d812-11eb-98a2-8632b0ca7765.png)

**Comment by PalmerAL** [comment]
OK thanks. It looks like this is caused by this Electron issue: https://github.com/electron/electron/issues/28699. I think we can probably work around it though.

(It looks like this was actually broken in 1.19.2 too, though, so I'm not sure why it's just being reported now).

**Comment by Thireb** [comment]
Linux, Manjaro Kde, kernel version 5.10.42
