### ISSUE TITLE
Right-Clicking a [Nested] Link Is Buggy

### ISSUE THREAD

**Issue by thrifus** [minbrowser/min#167]
I've noticed that on OS X, right clicking on a link that is nested or part of a different element (such as an `<img>` or `<b>` / `<strong>` element, or an element that looks like a button) does not show the "Open in New Tab," "Open in New Private Tab,"  or "Copy Link" in the context-menu and instead it shows either "Copy" or "Inspect Element." Sometimes when clicking on a link that is part of an `<img>` element, it will show the correct context-menu items, but it will be linked to the image instead of the actual link.

This can be somewhat avoided by right-clicking somewhere on the farthest area of the element, but does not always work (like when right clicking on suggested videos on YouTube).

![nfdwwx](https://cloud.githubusercontent.com/assets/9729078/15377985/62bfa72a-1d25-11e6-9be6-7f816e8295a5.gif)

**Comment by PalmerAL** [comment]
I think this is fixed in 2e59d420c8114db8093348b1a407ca72bfcdb5b2, which will be in 1.6.1.
