### ISSUE TITLE
Don't encourage people to discard OS level security for Min

### ISSUE THREAD

**Issue by wezm** [minbrowser/min#168]
The installation instructions guide new users to circumvent the security mechanisms built into OS X in order to use Min:

![screen shot 2016-05-19 at 10 54 14 am](https://cloud.githubusercontent.com/assets/21787/15379415/523929ea-1db0-11e6-8fcb-967ead00a4c3.png)

This is weakening people's computers and is unnecessary. Alternatives include:
1. Sign the binary with with a developer identity
2. If you are opposed to this for some reason, advise users to circumvent the code signing check (just for Min) by:
   - Right clicking on Min
   - Choose Open from the menu
   - If a warning dialog is shown, click Open: ![screen shot 2016-05-19 at 11 00 28 am](https://cloud.githubusercontent.com/assets/21787/15379471/055edf38-1db1-11e6-9f1e-90b5f863b26e.png)
   - This will only needs to be done the first time you run Min

**Comment by PalmerAL** [comment]
I think the "open anyway" button only applies to Min - after selecting that, attempts to open another application without a certificate (such as http://www.audacityteam.org/download/mac/) still get blocked.

Changing the instructions to use the second method is definitely a good idea though, since it prevents people from accidentally allowing all apps (and it's less complicated).

**Comment by wezm** [comment]
> I think the "open anyway" button only applies to Min - after selecting that, attempts to open another application without a certificate (such as http://www.audacityteam.org/download/mac/) still get blocked.

Yep that's right and I think that's a good thing. It means you have to explicitly run apps that aren't signed so you still get protection from auto-running, unsigned malware.

**Comment by PalmerAL** [comment]
Instructions updated in 351900bd4dcb5ca71c3007c84cd6e851f191e8a4.

**Comment by kOoLiNuS** [comment]
Today I couldn't launch the latest release. It did not work overwriting the (working) 1.2.2 release and after a clean install. This is an excerpt from my Console log:

`04/06/16 20:23:27,016 com.apple.xpc.launchd[1]: (com.electron.min.69472[4264]) Could not find and/or execute program specified by service: 2: No such file or directory: /Applications/Min.app/Contents/MacOS/Electron`

**Comment by PalmerAL** [comment]
@kOoLiNuS Can you file a separate issue about that?
