### ISSUE TITLE
Min fails to launch with Italian system language

### ISSUE THREAD

**Issue by macmau74** [minbrowser/min#1681]
I encountered an issue with the latest version of Min 1.20.0 on MacOs 10.14 Mojave on my iMac intel.
Min starts up, menus activate but without working. I can't type in the address bar and I can't navigate.

**Comment by lubiedo** [comment]
Hi @macmau74, this happens on version 1.20.0-beta or 1.19.2? Also, if you open the Inspector console for the browser (Option + Cmd + Shift + i) do you see any kind of error?

**Comment by macmau74** [comment]
Hi
I’m on iMac intel, I have installed Min-v1.20.0-darwin-x64.
This is the report of the Inspector console for the browser:

Uncaught TypeError: Cannot read property 'addEventListener' of null
    at Object.initialize (bundle.js:3236)
    at Object.27.browserUI.js (bundle.js:3375)
    at o (bundle.js:1)
    at bundle.js:1
    at Object.3.passwordManager/managerSetup.js (bundle.js:334)
    at o (bundle.js:1)
    at bundle.js:1
    at Object.1.autofillSetup.js (bundle.js:236)
    at o (bundle.js:1)
    at r (bundle.js:1)
bundle.js:1615 Uncaught TypeError: Cannot read property 'getSelected' of undefined
    at EventEmitter.<anonymous> (bundle.js:1615)
    at EventEmitter.emit (events.js:315)
    at Object.onMessage (electron/js2c/renderer_init.js:93)
bundle.js:2161 Uncaught TypeError: Cannot read property 'get' of undefined
    at bundle.js:2161
bundle.js:1623 Uncaught TypeError: Cannot read property 'getSelected' of undefined
    at EventEmitter.<anonymous> (bundle.js:1623)
    at EventEmitter.emit (events.js:315)
    at Object.onMessage (electron/js2c/renderer_init.js:93)
bundle.js:9791 Uncaught TypeError: Cannot read property 'get' of undefined
    at captureCurrentTab (bundle.js:9791)
    at bundle.js:10271
captureCurrentTab @ bundle.js:9791
(anonymous) @ bundle.js:10271
2bundle.js:2161 Uncaught TypeError: Cannot read property 'get' of undefined
    at bundle.js:2161
(anonymous) @ bundle.js:2161
bundle.js:9791 Uncaught TypeError: Cannot read property 'get' of undefined
    at captureCurrentTab (bundle.js:9791)
    at bundle.js:10271
captureCurrentTab @ bundle.js:9791
(anonymous) @ bundle.js:10271
2bundle.js:2161 Uncaught TypeError: Cannot read property 'get' of undefined
    at bundle.js:2161
(anonymous) @ bundle.js:2161
bundle.js:9791 Uncaught TypeError: Cannot read property 'get' of undefined
    at captureCurrentTab (bundle.js:9791)
    at bundle.js:10271
captureCurrentTab @ bundle.js:9791
(anonymous) @ bundle.js:10271
2bundle.js:2161 Uncaught TypeError: Cannot read property 'get' of undefined
    at bundle.js:2161
(anonymous) @ bundle.js:2161
bundle.js:9791 Uncaught TypeError: Cannot read property 'get' of undefined
    at captureCurrentTab (bundle.js:9791)
    at bundle.js:10271
captureCurrentTab @ bundle.js:9791
(anonymous) @ bundle.js:10271
2bundle.js:2161 Uncaught TypeError: Cannot read property 'get' of undefined
    at bundle.js:2161
(anonymous) @ bundle.js:2161
bundle.js:9791 Uncaught TypeError: Cannot read property 'get' of undefined
    at captureCurrentTab (bundle.js:9791)
    at bundle.js:10271
captureCurrentTab @ bundle.js:9791
(anonymous) @ bundle.js:10271
2bundle.js:2161 Uncaught TypeError: Cannot read property 'get' of undefined
    at bundle.js:2161
(anonymous) @ bundle.js:2161
bundle.js:9791 Uncaught TypeError: Cannot read property 'get' of undefined
    at captureCurrentTab (bundle.js:9791)
    at bundle.js:10271
bundle.js:2161 Uncaught TypeError: Cannot read property 'get' of undefined
    at bundle.js:2161
bundle.js:2161 Uncaught TypeError: Cannot read property 'get' of undefined
    at bundle.js:2161
(anonymous) @ bundle.js:2161
requestAnimationFrame (async)
refresh @ bundle.js:2160
bundle.js:9791 Uncaught TypeError: Cannot read property 'get' of undefined
    at captureCurrentTab (bundle.js:9791)
    at bundle.js:10271
captureCurrentTab @ bundle.js:9791
(anonymous) @ bundle.js:10271
2bundle.js:2161 Uncaught TypeError: Cannot read property 'get' of undefined
    at bundle.js:2161
(anonymous) @ bundle.js:2161
requestAnimationFrame (async)
refresh @ bundle.js:2160
bundle.js:9791 Uncaught TypeError: Cannot read property 'get' of undefined
    at captureCurrentTab (bundle.js:9791)
    at bundle.js:10271
captureCurrentTab @ bundle.js:9791
(anonymous) @ bundle.js:10271
2bundle.js:2161 Uncaught TypeError: Cannot read property 'get' of undefined
    at bundle.js:2161
(anonymous) @ bundle.js:2161
requestAnimationFrame (async)
refresh @ bundle.js:2160
bundle.js:9791 Uncaught TypeError: Cannot read property 'get' of undefined
    at captureCurrentTab (bundle.js:9791)
    at bundle.js:10271
captureCurrentTab @ bundle.js:9791
(anonymous) @ bundle.js:10271
2bundle.js:2161 Uncaught TypeError: Cannot read property 'get' of undefined
    at bundle.js:2161
(anonymous) @ bundle.js:2161
requestAnimationFrame (async)
refresh @ bundle.js:2160
bundle.js:9791 Uncaught TypeError: Cannot read property 'get' of undefined
    at captureCurrentTab (bundle.js:9791)
    at bundle.js:10271
captureCurrentTab @ bundle.js:9791
(anonymous) @ bundle.js:10271
2bundle.js:2161 Uncaught TypeError: Cannot read property 'get' of undefined
    at bundle.js:2161
(anonymous) @ bundle.js:2161
requestAnimationFrame (async)
refresh @ bundle.js:2160
bundle.js:9791 Uncaught TypeError: Cannot read property 'get' of undefined
    at captureCurrentTab (bundle.js:9791)
    at bundle.js:10271
captureCurrentTab @ bundle.js:9791
(anonymous) @ bundle.js:10271
bundle.js:2161 Uncaught TypeError: Cannot read property 'get' of undefined
    at bundle.js:2161
(anonymous) @ bundle.js:2161
requestAnimationFrame (async)
refresh @ bundle.js:2160
bundle.js:1655 Uncaught TypeError: Cannot read property 'add' of undefined
    at EventEmitter.<anonymous> (bundle.js:1655)
    at EventEmitter.emit (events.js:315)
    at Object.onMessage (electron/js2c/renderer_init.js:93)
(anonymous) @ bundle.js:1655
emit @ events.js:315
onMessage @ electron/js2c/renderer_init.js:93
bundle.js:1640 Uncaught TypeError: Cannot read property 'getSelected' of undefined
    at EventEmitter.<anonymous> (bundle.js:1640)
    at EventEmitter.emit (events.js:315)
    at Object.onMessage (electron/js2c/renderer_init.js:93)
(anonymous) @ bundle.js:1640
emit @ events.js:315
onMessage @ electron/js2c/renderer_init.js:93
bundle.js:2161 Uncaught TypeError: Cannot read property 'get' of undefined
    at bundle.js:2161
(anonymous) @ bundle.js:2161
requestAnimationFrame (async)
refresh @ bundle.js:2160
bundle.js:9791 Uncaught TypeError: Cannot read property 'get' of undefined
    at captureCurrentTab (bundle.js:9791)
    at bundle.js:10271
captureCurrentTab @ bundle.js:9791
(anonymous) @ bundle.js:10271
bundle.js:2161 Uncaught TypeError: Cannot read property 'get' of undefined
    at bundle.js:2161
(anonymous) @ bundle.js:2161
requestAnimationFrame (async)
refresh @ bundle.js:2160
bundle.js:1594 Uncaught TypeError: Cannot read property 'getSelected' of undefined
    at EventEmitter.<anonymous> (bundle.js:1594)
    at EventEmitter.emit (events.js:315)
    at Object.onMessage (electron/js2c/renderer_init.js:93)
(anonymous) @ bundle.js:1594
emit @ events.js:315
onMessage @ electron/js2c/renderer_init.js:93
bundle.js:2161 Uncaught TypeError: Cannot read property 'get' of undefined
    at bundle.js:2161
(anonymous) @ bundle.js:2161
requestAnimationFrame (async)
refresh @ bundle.js:2160
bundle.js:9791 Uncaught TypeError: Cannot read property 'get' of undefined
    at captureCurrentTab (bundle.js:9791)
    at bundle.js:10271
captureCurrentTab @ bundle.js:9791
(anonymous) @ bundle.js:10271
2bundle.js:2161 Uncaught TypeError: Cannot read property 'get' of undefined
    at bundle.js:2161
(anonymous) @ bundle.js:2161
requestAnimationFrame (async)
refresh @ bundle.js:2160




maurizio martinetti
***@***.***

**Comment by PalmerAL** [comment]
I can reproduce; this happens if you have your operating system language set as Italian. One of the translations in #1616 is formatted incorrectly, and I didn't test it before merging :(

I'll make a fix for this soon; in the meantime, you can:
1. Install the previous version of Min, which doesn't have this problem: https://github.com/minbrowser/min/releases/tag/v1.19.2
2. Change your operating system language to something other than Italian (I know this isn't a good workaround).

**Comment by macmau74** [comment]
Hi thanks for the quick reply! While waiting for the next update I'm going back to using Min 1.19.2.
Thank you very much, Martin



> Il giorno 18 lug 2021, alle ore 00:57, PalmerAL ***@***.***> ha scritto:
> 
> I can reproduce; this happens if you have your operating system language set as Italian. One of the translations in #1616 <https://github.com/minbrowser/min/pull/1616> is formatted incorrectly, and I didn't test it before merging :(
> 
> I'll make a fix for this soon; in the meantime, you can:
>

**Comment by PalmerAL** [comment]
The new beta release from today should fix this: https://github.com/minbrowser/min/releases/tag/v1.21.0-beta
