### ISSUE TITLE
Problem using the microphone on certain websites

### ISSUE THREAD

**Issue by Olius** [minbrowser/min#1685]
I cannot seem to use my microphone through Min on [Duolingo](http://duolingo.com). I have pressed the button to activate it (upper left in tab bar), but when I press the website's button which should allow me to speak,
![Screen Shot 2021-07-17 at 14 48 26](https://user-images.githubusercontent.com/13313908/126037598-dd909aec-3ef4-499b-bd68-c187cf43e216.png)
it immediately fails before allowing me to speak.
![Screen Shot 2021-07-17 at 14 49 04](https://user-images.githubusercontent.com/13313908/126037611-4d72d017-79c9-459f-bf55-ed63286c79b8.png)

Everything works as expected on some other websites though, for example [this one](http://mictests.com).

**Comment by lubiedo** [comment]
This seems to be an issue in Chromium and there seems to be no solution for this unless Min transcribes the audio. Please, check out [this issue](https://github.com/brave/brave-browser/issues/3725) on Brave.

@PalmerAL might want to weigh on this one?

**Comment by PalmerAL** [comment]
Yup, the speech recognition in Chromium happens on Google's servers, and you need an API key for it. In the past, it wasn't possible to get an API key at all; I think it might be possible to get one now if you pay for it, but I don't want to do that anyway.

**Comment by Olius** [comment]
Ah I see, the speech recognition does not happen on Duolingo's side, and it thinks I am using Chrome which can do the speech recognition itself (through Google's servers).

Thanks for having looked into this!
