### ISSUE TITLE
Password Manager Issue

### ISSUE THREAD

**Issue by gray49** [minbrowser/min#1689]
Hello...Hope all is well in your world..Using Fedora 34...I just reinstalled Min after not having used it in a while...I use the Bitwarden  password manager and after  installing it  have found it is not working...I can install Bitwarden and sign in, but the keyboard shortcut or the right click in the password area does nothing...Properly signed in and having used it all before, something seems to be amiss...Thanks...Peace

**Comment by PalmerAL** [comment]
Do you have Bitwarden installed globally, or did you install it inside Min? To find out, look in /home/username/.config/Min/tools; if there's a "bw" executable in there, try deleting that and reinstalling.

If that doesn't help, then I guess the next step is for me to see if I can reproduce this on Linux.

**Comment by gray49** [comment]
Hello...
Hope all is well...
Thanks for your quick reply...
I installed Min through the browser and also have it downloaded as an app...
I deleted the "bw" reinstalled Min and tested several times...
Signed into Bitwarden in the browser...Tried the right click and ctrl \ shortcut and Min would not enter the passwords...
Nothing more I can do...
I hope the issue will be resolved shortly either on my end or your's as I truly enjoy using Min...
Thanks for your effort...
Much appreciated...
Peace...
Stuart

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by PalmerAL** [comment]
If you go to menu > developer > inspect browser > console, are there any error messages listed there?

I just tried setting up Bitwarden again inside Min on Ubuntu, and everything worked, so I don't think there's a general issue; I'm not sure what could be going wrong for you specifically though.

You could also try deleting Bitwarden's config data: `~/.config/Bitwarden CLI/`, and reinstalling again. Not sure if that would help or not, but it might be worth trying.

Also, if you have two-factor auth enabled on your Bitwarden account, it won't work in Min: #929.

**Comment by myravian** [comment]
I don't know if this is the right place to mention this but so far the only reason that prevents me from using Min on a daily basis is that I browse many websites that require identification and when I click on the key icon to get the Bitwarden entries, all I see is the list of logins, which is not so helpful (it would be nice to get the name of the entry instead/in addition to).
