### ISSUE TITLE
Spelling Check not showing list of suggestions

### ISSUE THREAD

**Issue by andrewccl** [minbrowser/min#1693]
- **Min Version: 1.20.0
- **Operating system: Windows 10 Pro 21H1 Build 19043.1110

Provide list of suggestions for spelling

Spelling is highlighted (underlined), when right clicking for options, shows Add to Dictionary 

On any website that has a form and miss type a word

Typing notes in ConnectWise and not getting corrections for spelling errors
![min_AkwXZBwcMn](https://user-images.githubusercontent.com/70671424/126734786-7818f2d2-e001-42d8-a189-34b87f3797ed.png)
![min_Jb9W4bIwIZ](https://user-images.githubusercontent.com/70671424/126734794-d2c80ab0-f1ca-4ea3-9449-1f8337e75929.png)

**Comment by PalmerAL** [comment]
Thanks for reporting. This is most likely due to this Electron bug: https://github.com/electron/electron/pull/29690, so it should be fixed the next time we upgrade to a new version of Electron.
