### ISSUE TITLE
Please Add Support For Pi-camera

### ISSUE THREAD

**Issue by Painadath** [minbrowser/min#1695]
I Am Really amuzed of min which can run google meet even in my pi 3b so the problem is now i am using it on my pi 4 on 64 bit os
and i have a pi-camera.i want to attend online class so if min adds support for pi-camera it will be a great help
ps:There is already a couple of node modules for it
ThankYou
White Lizard

**Comment by PalmerAL** [comment]
It's great that the browser is running well! Camera support is implemented in Chromium; I'm not sure why Chromium doesn't support the Pi Camera, but there most likely isn't anything we can do about it. Sorry!
