### ISSUE TITLE
Provide a way for the user to go back?

### ISSUE THREAD

**Issue by CameronBanga** [minbrowser/min#17]
Maybe I'm crazy and or stupid, but don't see how I can go back a page after clicking on a url.

**Comment by bradens** [comment]
You're right.  The only way is the default shortcut of `⌘+←`

**Comment by CameronBanga** [comment]
This makes sense. An easy quick fix would probably just be to add "Back  ⌘+←" to the edit menu panel. 

Ideally, it would be a button in the tab header for the active tab, but if minimal is the goal, shortcut only is probably tolerable for a browser targeted at more advance users.

**Comment by PaulBGD** [comment]
I'm not sure if this deserves an additional issue, but the back/forward buttons on my mouse don't work either.

**Comment by PalmerAL** [comment]
@PaulBGD Can you please file a separate issue for that?

**Comment by wb9688** [comment]
Can you also add <kbd>Alt+left/right</kbd> for Windows?

**Comment by PalmerAL** [comment]
A back button has been added in #421, which will be included in 1.7.0 (also, there's back and fordward buttons in the right-click context menu how).
