### ISSUE TITLE
Maximize button don't work properly on RPi4 Ubuntu.

### ISSUE THREAD

**Issue by lee-yunseok** [minbrowser/min#1702]
- **Min Version: 1.20.0**
- **Operating system: RPi4 Ubuntu(arm64)**

## Expected Behavior
When Min is windowed or full screen mode, the maximize button should work its function to maximize or window.

## Actual Behavior
In this case above, maximize button doesn't work.

## To Reproduce
**Maximize button** work and main window switches to windowed mode when Min is maximized, **but it doesn't work when Min is windowed or full screen mode.**

**Added: The button work properly if enable 'Use separate title bar'**

**Comment by PalmerAL** [comment]
I think this is the same as #1662 - Electron has a bug in recent releases that makes our custom titlebar not work correctly. I added a workaround in #1672 that fixes this in most cases, but I think we need to wait on Electron for a complete fix.

**Comment by lee-yunseok** [comment]
Thank you for confirm. Closed.
