### ISSUE TITLE
On discord with mint is dont working screen share

### ISSUE THREAD

**Issue by Whtery1087** [minbrowser/min#1707]
On discord with mint is dont working screen share

**Comment by Milo123459** [comment]
Needs more info. Please follow the template for bug report.

**Comment by Whtery1087** [comment]
Use min browser and make a call on discord and use screan share and a frame dont works is bug

**Comment by Whtery1087** [comment]
> Needs more info. Please follow the template for bug report.

Btw sorry for my english but i am czech :D

**Comment by Milo123459** [comment]
Please follow the template and make a new issue.. This isn’t enough information still.
