### ISSUE TITLE
-

### ISSUE THREAD

**Issue by Whtery1087** [minbrowser/min#1708]
- **Min Version:** 1.21.0-beta
- **Operating system:** WINDOWS

## Expected Behavior
Go on discord make a call and click on button screan share
## Actual Behavior
The scren share is dont show frame to select game or screen to screen share
## To Reproduce
1. Go on Discord
2. Go on call in discord
3. Click on Screenshare button
4. Frame the select game or screan dont show

1. Go on Discord
2. Go on call in discord
3. Click on Screenshare button
4. Frame the select game or screan dont show

**Comment by Milo123459** [comment]
Please try and not submit random stuff
