### ISSUE TITLE
Discord Screenshare problem

### ISSUE THREAD

**Issue by Whtery1087** [minbrowser/min#1709]
- **Min Version:** 1.21.0-beta
- **Operating system:** WINDOWS

## Expected Behavior
Go on discord make a call and click on button screan share
## Actual Behavior
The scren share is dont show frame to select game or screen to screen share
## To Reproduce
1. Go on Discord
2. Go on call in discord
3. Click on Screenshare button
4. Frame the select game or screan dont show

1. Go on Discord
2. Go on call in discord
3. Click on Screenshare button
4. Frame the select game or screan dont show

**Comment by Milo123459** [comment]
Have you allowed Min to capture your screen?

**Comment by Milo123459** [comment]
And Discord for that matter

**Comment by Whtery1087** [comment]
ok

**Comment by Whtery1087** [comment]
> Have you allowed Min to capture your screen?

i am dont give warning

**Comment by Whtery1087** [comment]
> Have you allowed Min to capture your screen?

Well nothing happened I looked at the share screen button but nothing happened as if you clicked on a button on the web that did nothing

**Comment by Milo123459** [comment]
Not a bug, see #972
