### ISSUE TITLE
Cannot use "copy" button on Github to copy code snippets

### ISSUE THREAD

**Issue by marizmelo** [minbrowser/min#1710]
- **Min Version:**
1.20
- **Operating system:**
Debian 10

## Expected Behavior
code is copied to my clipboard and I can paste in terminal or another text based application
## Actual Behavior
nothing is copied to the clipboard
## To Reproduce
I went to the NVM node package repository and tried to copy the installation code from there

**Comment by shalva97** [comment]
duplicate of #1706

**Comment by marizmelo** [comment]
> plicate of #1706

Thanks
