### ISSUE TITLE
ctrl + s on github raw files doesnot work correctly

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1717]
- **Min Version:** 1.20.0
- **Operating system:** Windows 10

## Expected Behavior
when I press ctrl + s on raw files they should be saved without html and with correct extension

## Actual Behavior
![image](https://user-images.githubusercontent.com/22417494/129573222-7f0c9567-5670-4b7d-827d-01a668de137d.png)
index.html name is completly different and downloaded files get prepended with 
```
<!-- saved from url=(0126)https://raw.githubusercontent.com/shalva97/windows-reg-configs/master/create-emulators.ps1?token=AFLBAVRFLGYB3KFAVINRU5DBEO4 -->
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">
```

## To Reproduce
https://raw.githubusercontent.com/minbrowser/min/master/index.html and press ctrl+s

**Comment by shalva97** [comment]
any news on this. for some reason on this file https://raw.githubusercontent.com/jeffmer/micropython-ili9341/master/ili934xnew.py it doesnot show file save dialog at all

**Comment by PalmerAL** [comment]
The root issue is that Electron doesn't have a good API for figuring out the content type of the file and changing the download behavior based on that, but it's possible there's a workaround that will work better than what we have. I'll look soon.
