### ISSUE TITLE
when downloaded file name is changed, it doesnot update in downloads panel

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1720]
- **Min Version:** 1.21.0
- **Operating system:** Windows 10

## Expected Behavior
it should show the name I write in save dialog

## Actual Behavior
it shows old file name

## To Reproduce
download some file, change name on save dialog, and it will show old name in the panel

**Comment by lubiedo** [comment]
Thanks @shalva97. I was able to reproduce the issue and created PR https://github.com/minbrowser/min/pull/1721 for this one.

**Comment by lubiedo** [comment]
Issue was fixed with #1721.
