### ISSUE TITLE
Search/url bar abandons search engine and reads query as url

### ISSUE THREAD

**Issue by Hunter-Guimont** [minbrowser/min#1734]
Pretty much any search longer than one word is read as a url, which results in a server error when that url doesn;t actually exist.

What should be happening, is that if the search is not formatted like a url, then It should be read as a search.

**Comment by PalmerAL** [comment]
Can you give an example? Also, what do you have the search engine set to in the Min preferences?

**Comment by Hunter-Guimont** [comment]
http://arch%20dpms/

This for example. I'm using Duck Duck Go

**Comment by PalmerAL** [comment]
Meaning that you're searching for "arch dpms" and it's loading that URL instead?

That definitely shouldn't be happening; can you post a screenshot of the search engine section of the preferences?

**Comment by Hunter-Guimont** [comment]
Yeah, it happened quite frequently. If I recall correctly, it did the same with Google set as the search engine at times. I'm sorry but Im no longer using min, so I can't really send anymore specific info.

**Comment by PalmerAL** [comment]
OK, feel free to make a new issue if you run into this again.
