### ISSUE TITLE
Min does not support HTTP authentication

### ISSUE THREAD

**Issue by plrenaudin** [minbrowser/min#174]
It directly goes 401 without displaying a popup for login

**Comment by wb9688** [comment]
Do you mean that Min doesn't support HTTP Authentication?

**Comment by plrenaudin** [comment]
Yes, in this website for example: http://www.pagetutor.com/keeper/http_authentication/
Click on "My Secret Stuff" link.

**Comment by ChristiaanLock** [comment]
Related to #142

**Comment by wb9688** [comment]
No, I don't think so. I think he's refering to [HTTP basic access
authentication](https://en.m.wikipedia.org/wiki/Basic_access_authentication)
and not to not having support for `window.opener`…

**Comment by ChristiaanLock** [comment]
I think #142 has nothing to do with 'window.opener' and that he is talking about the HTTP basic auth login form, not an actual popup window. Browsers should show the login form automatically when the servers sends a 'WWW-Authenticate' header. 
Therefore, imho, the issues described in #174 and #142 are related.

**Comment by wb9688** [comment]
Indeed, but I accidentally pressed the #140 link in #142, so I thought you
said that it's related to #140…

**Comment by talentlessguy** [comment]
Looks like it is still an issue, neither Github auth, nor Google login work

**Comment by PalmerAL** [comment]
@talentlessguy Google login is different from HTTP auth, can you clarify what isn't working for you?

**Comment by talentlessguy** [comment]
@PalmerAL "Login with Google" doesn't work. In Figma at least. Looks like tabs can't exchange information.

**Comment by PalmerAL** [comment]
@talentlessguy That's probably #140..

**Comment by PalmerAL** [comment]
This has been fixed in #969.
