### ISSUE TITLE
Adding Shortcut keys similiar to vim keys

### ISSUE THREAD

**Issue by tsjazil** [minbrowser/min#1759]
Adding bindkeys similar to vim keys will be helpful  

And also Better to make in dark every were in dark mode

**Comment by Syndamia** [comment]
You can already do that with a [userscript](https://github.com/minbrowser/min/wiki/userscripts): [PalmerAL/min-vim-mode](https://github.com/PalmerAL/min-vim-mode). Also, duplicate of #37.
