### ISSUE TITLE
update website to reflect availability of win32 build

### ISSUE THREAD

**Issue by mailinglists35** [minbrowser/min#176]
download page says only osx or ubuntu

**Comment by PalmerAL** [comment]
The windows build doesn't really work yet... the EXE is in a folder with a bunch of resource files, and you can't move it out of the folder. Also, it doesn't create shortcuts yet.

I was working on this in the <a href="https://github.com/minbrowser/min/tree/windows">```windows```</a> branch, but it didn't work completely.

There's already an issue for Windows support, #43, so I'm closing this.
