### ISSUE TITLE
Unmet dependencies in ubuntu

### ISSUE THREAD

**Issue by SweepingBishops** [minbrowser/min#1762]
dpkg: dependency problems prevent configuration of min:
 min depends on libsecret-1-dev; however:
  Package libsecret-1-dev is not installed.
 min depends on gconf2; however:
  Package gconf2 is not installed.
 min depends on gconf-service; however:
  Package gconf-service is not installed

**Comment by EduardGol** [comment]
I have the same issue, how you have resolved ?
