### ISSUE TITLE
Once I close the browser it becomes unusable

### ISSUE THREAD

**Issue by M4nty** [minbrowser/min#1784]
- **Min Version:**
Latest
- **Operating System and Specifications :**

- Windows 10
- CPU = i3 9100F
- GPU = AMD Radeon HD 5450
- RAM = 8GB
- Running it on a SSD

## Expected Behavior
Normally I should be able to close the browser and open it again.It works on my virtual machine if it helps

## Actual Behavior
When I close it once I cannot use it again because the browser becomes a white window and only if I start a new session it works again but the problem persists.

## To Reproduce
Close the browser after you run it.

https://user-images.githubusercontent.com/44327262/139703924-1546ba56-6e13-4c43-99a2-d2011f7e6df9.mp4

**Comment by Syndamia** [comment]
This reminds me of #256. You can try running it with the `--disable-gpu` flag.

Right-click on the desktop shortcut, click "Properties", from there navigate to the "Shortcut" tab and add ` --disable-gpu` (with a space before --) at the end of the "Target" box (if there is a bracket at the end, add it before the bracket). Click Ok and try to launch it again.
![image](https://user-images.githubusercontent.com/46843671/140181461-50ebc989-44ec-4304-b575-7c64474a6b4b.png)

**Comment by M4nty** [comment]
Yup that fixes it now.
Thanks.
