### ISSUE TITLE
I would like support with translation into Spanish

### ISSUE THREAD

**Issue by jgjimenez** [minbrowser/min#180]
Greetings from Venezuela,

Install the application and has potential but I would love to translate it into Spanish

**Comment by devgar** [comment]
+1

**Comment by kOoLiNuS** [comment]
Count me in for the Italian translation …

**Comment by wb9688** [comment]
I can do the Dutch translation…

**Comment by burnoutberni** [comment]
Same here for German

**Comment by osha-p** [comment]
I can make localization for Russian language.

**Comment by PalmerAL** [comment]
I've started working on this in issue #396.

**Comment by PalmerAL** [comment]
It's possible to add translations for Min now, see the instructions in the readme: https://github.com/minbrowser/min#contributing-translations.
