### ISSUE TITLE
How to change search engine?

### ISSUE THREAD

**Issue by whyhellobradley** [minbrowser/min#181]
Either with code or a setting, how do I do this?

**Comment by PalmerAL** [comment]
A setting for this was added a few days ago, in 1e156d57fe8eebd0030fec33ef1648821e9913f0. 1.3.0 will be released later today, and will include the fix for this.

(I am going on vacation for the next few days, so I may not respond to this until next week).

**Comment by whyhellobradley** [comment]
Okay, thank you for the quick response!

**Comment by PalmerAL** [comment]
I'm not going to have time to release 1.3 today, it will probably be on Tuesday instead.

**Comment by whyhellobradley** [comment]
Awe, okay. Since I don't get notifications from Min about updates, could you send me a message on here when you do? I really appreciate it! And good work so far on everything.

**Comment by PalmerAL** [comment]
1.3 has been released, you can download it here: https://github.com/minbrowser/min/releases/tag/v1.3.0
