### ISSUE TITLE
Amazing

### ISSUE THREAD

**Issue by armandaneshjoo** [minbrowser/min#1815]
Ingenious, slim, sufficient.

I tried ungoogled chromium, but its neither installed nor portable. acts up.
I tried Colibri but I couldn't add common extensions like ublock, privacy badger, dark reader or user agent switcher.
I've been using LibreWolf as a minimal browser. It has the right tools, but the top bar is large.
I tried to cut down Vivaldi toolbars, but they kept showing up.

I finally has a new default browser pinned to taskbar.

**Comment by PalmerAL** [comment]
Thank you!
