### ISSUE TITLE
Can't pass URL to executable

### ISSUE THREAD

**Issue by happydemic** [minbrowser/min#183]
Congratulations on this very neat little browser. Thank you!

Currently, you can't pass a URL to the executable. The min executable ignores any arguments which are passed to it. So 
```min http://github.com/minbrowser``` does not open the page, and appears to have the same result as ```min```.

Passing a URL appears to be an intended feature, because the ```Exec``` key in ```min.desktop``` includes the parameter to pass URLs as arguments: ```Exec=min %U```.

**Comment by PalmerAL** [comment]
This was implemented in facf72152968a709b484892b217dcbcb398be81f, and will be included in the next version (1.3.0).
