### ISSUE TITLE
Zoom in Reader Mode

### ISSUE THREAD

**Issue by asoymos** [minbrowser/min#1833]
Hi! The title says it all. Thanks for such a simple concept for navigation.

**Comment by PalmerAL** [comment]
Hi, you should be able to zoom in reader mode with the standard browser controls (ctrl+ / -). Does that work for you?

**Comment by asoymos** [comment]
Yes, ctrl-/+ in the numeric keys don't work, but ctrl+- and ctrl++(but is ctrl+shift++ because my keyboard layout is latam) in alphanumeric keys do work. Didn't think of that because of the mouse wheel didn´t work as in normal navigation. Sorry closing this one. Thanks

**Comment by asoymos** [comment]
Probably should be mentioned in the Keyboard Shorcuts page.

**Comment by asoymos** [comment]
As a comment for the two open issues about keyboard shorcuts: I am used to open source apps not being very standard, is common that each follow their own preference, that is why I didn't found wrong in Min a different set of keys. But as you mentioned the standard behavior I want to note a few differences, at least from Firefox and Chrome:

In those alt+# change to # tab, Min has another approach with ctrl+# to the right and ctrl+shift+# to the left
Firefox history: alt+arrows; Min ctrl+arrows
Firefox switch to next/back tab: ctrl+pageup/pagedown; Min ctrl+tab/ctrl+shift+tab

again I don't find it wrong to do things differently, just don't know if this is the intended behavior

thanks again for this more simple paradigm of navigation, when I was searching for firefox alternatives found the sad history that most good browsers are large company managed in the way of 'everything for everyone' that sometimes cut off freedom and simplicity in benefit of ease of use. I am grateful of having good alternatives
