### ISSUE TITLE
Ctrl+Shift+Click don't open in new tab with focus

### ISSUE THREAD

**Issue by asoymos** [minbrowser/min#1835]
Hi, I am having this problem with shift and left click not opening links in new tab with focus, instead open a new window.

Min v1.22.1
Chromium v94.0.4606.81
ArchLinux

Thanks.

**Comment by asoymos** [comment]
oh sorry just saw the preference to open new tabs in the foreground. Is this the intended behaviour? Isn't easier to open them like shift click new tab focus, ctrl click new tab background, shift+ctrl new window?

**Comment by PalmerAL** [comment]
Shift+click opening a new window is definitely a bug; going to reopen this until that's fixed. For the other part, I think our behavior follows other browsers - Firefox has a "When you open a link, image or media in a new tab, switch to it immediately" setting, for example.

**Comment by asoymos** [comment]
Was using firefox for a while before I got tired of the not customizable ui, there the behavior is: ctrl+click open a new tab in the background, shift+click open a new window, ctrl+shift+click a new tab with focus. In min ctrl+click open a new tab in the background, shift+click open a new window, **but ctrl+shift+click also open a new window.** Sorry I mistaken the one that didn't work, changed the tittle accordingly.

**Comment by asoymos** [comment]
That is based on Firefox behavior, but Min keyboard shorcuts page says that shift+click open in new tab with focus, then that isn't working as it open a new window. Should I change the tittle back?

**Comment by PalmerAL** [comment]
I think I've fixed this in 961e8e1e:

* cmd+click - depends on whether "open new tabs in foreground" is enabled
* shift+click - always opens in the foreground
* shift+cmd+click - always opens in the foreground

Min doesn't support multiple windows, so keys that open a new window in Firefox should open a tab in Min.

**Comment by asoymos** [comment]
Ok thanks. I don't know much of github source process so I will wait until release to feedback. Just an opinion: if shift+click always open on the foreground why is the preference option for?

**Comment by asoymos** [comment]
(I never used the open in new window feature anyway)

**Comment by PalmerAL** [comment]
The preference controls what cmd+click does. I think it still makes sense to have, because people seem to use cmd+click a lot more, and don't know about shift+click.

**Comment by asoymos** [comment]
ok Thank you

**Comment by asoymos** [comment]
Hi @PalmerAL, I found a different bug with this. Shift+click now work well but Shift+enter open new tab in foreground but the parent tab also changes to new address.

**Comment by asoymos** [comment]
Edit: Only happens in duckduckgo: search for something and go down the options with keyboard, choose anyone with Shift+enter. In other sites with good old shift+tab to keyboard driven interaction work as expected.

**Comment by asoymos** [comment]
Sorry, looks like it's more about duckduckgo own keyboard shorcuts (I don't know if conflicting with min's). If I use Ctrl+Shift+enter it work as expected. Thank you.
