### ISSUE TITLE
task-related !bangs isAction: false ?

### ISSUE THREAD

**Issue by cfuendesign** [minbrowser/min#1839]
While working on https://github.com/minbrowser/min/discussions/1795, I noticed that some of the custom !bangs which perform actions related to tasks on [customBangs.js](https://github.com/minbrowser/min/blob/65b71f01de8245d18962b36a626ba66e89af67f8/js/searchbar/customBangs.js) have the "isAction" parameter set to false in their registerCustomBang() function (`!task`, `!movetotask`, `!closetask`, and `!nametask`).

https://github.com/minbrowser/min/blob/65b71f01de8245d18962b36a626ba66e89af67f8/js/searchbar/customBangs.js#L96

`!newTask` is true, but the rest of the !bangs related to tasks aren't. Is this an error? And if not, why is this?

**Comment by PalmerAL** [comment]
There's a comment describing this here: https://github.com/minbrowser/min/blob/master/js/searchbar/bangsPlugin.js#L12, but it's worded badly and not very useful.

isAction: true means the bang is a simple "action" that does something. !settings opens the settings page, !newtask creates a task, etc.

isAction: false means the bang performs a search or a more complex action that requires search text. !nametask needs a task name (like `!nametask example`), !movetotask needs the name of an existing task (although it will create a new task if you leave it blank). !bookmarks needs some text to search for after the bang.

What the parameter actually affects is that if isAction is true, and you enter the bang in the searchbar with no text after it (!settings) and press enter, the action will be performed immediately. If you set isAction: false, the searchbar will insert a space and wait for you to type text after the bang.

**Comment by PalmerAL** [comment]
It would probably make more sense to rename this to "requiresSearchText" or something.
