### ISSUE TITLE
How to: Privacy settings in Linux?

### ISSUE THREAD

**Issue by baldrick-nz** [minbrowser/min#184]
Love your work, but for the life of me I can't work out how to get to the privacy settings!
In your 'tour' it says to "Edit menu > Privacy Preferences on Linux", but where is this?? 

I've tried right-clicking all over the page, clicking whatever Min icon I can see, but nothing seems to get me there. Please advise how to get there, I'm using Linux Mint 17.3 Cinnamon.

Thanks in advance,

Baldrick.

**Comment by wb9688** [comment]
If you press `Alt` a menu in the top. It's somewhere in that menu…

**Comment by baldrick-nz** [comment]
thanks for that. 
Once ticked, is the adblock option under privacy supposed to remain ticked while browsing? Because mine doesn't. Do I need to file a bug report on this?

Cheers.

**Comment by PalmerAL** [comment]
@baldrick-nz I've filed a separate issue about that, #188.
