### ISSUE TITLE
Question: Raspberry pi 32? 

### ISSUE THREAD

**Issue by asoymos** [minbrowser/min#1840]
Hi, just saw the release notes and wondered if this support is for the official 32 bit operating sistem or for the development 64 bit (saw in the download that the .deb package is 64). Thanks

**Comment by PalmerAL** [comment]
The armhf file is the one for 32-bit pi; the other one should work as well if you have a 64-bit pi though.

**Comment by asoymos** [comment]
Ok thanks (as a note the download options in https://minbrowser.org/ only showed the .deb and rpm 64 bit options, probably detecting my browser system, but would be good an option to show the other files as I was searching for something for another system)
