### ISSUE TITLE
What does 'text' do?

### ISSUE THREAD

**Issue by cfuendesign** [minbrowser/min#1842]
Sorry for the silly question, but I can't understand the relation between the 'text' parameter and bang.redirect in bangsPlugin.js
What is the text param for? Why is bang.redirect being replaced by it?

https://github.com/minbrowser/min/blob/65b71f01de8245d18962b36a626ba66e89af67f8/js/searchbar/bangsPlugin.js#L223
https://github.com/minbrowser/min/blob/65b71f01de8245d18962b36a626ba66e89af67f8/js/searchbar/bangsPlugin.js#L224

**Comment by PalmerAL** [comment]
It's the search text that was typed after the bang, and it's replacing the "%s" string in the redirect URL if one exists. So for example, I have a `!min` bang set up with a URL of `https://github.com/minbrowser/min/search?q=%s`. If I type `!min bang.redirect`, the URL that gets loaded is `https://github.com/minbrowser/min/search?q=bang.redirect`.
