### ISSUE TITLE
Building on M1 Issues (potentially NOOB)

### ISSUE THREAD

**Issue by flightmansam** [minbrowser/min#1850]
Okay so I'm trying hard to build after doing a fresh clone from gh. I am using nvm to manage a Node v16 environment. I'm trying to install the dependencies (npm install). It seems to first break when trying to install lzma-native? It's trying to install it from this url https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-darwin-arm64.tar.gz, but failing because that URL doesn't exist (only a darwin-x86 version exists). But also a bunch of XCode toolchain problems, following that but I think those are co-morbid. Is the solution as simple as manually installing lzma_native (x86) and allowing it to run in Rosetta 2? I don't know much about npm (mostly a python guy), but does npm search globally before it builds dependencies? If anyone could share their M1 npm setup I would be greatly appreciated. I have attached the log for anyone with enough caffeine to check it out. I am certain it is a problem on my end with how I have set up NVM/NPM/??.

I'll also try it out on a windows PC.

[2022-01-07T14_24_34_264Z-debug.log](https://github.com/minbrowser/min/files/7829476/2022-01-07T14_24_34_264Z-debug.log)

**Comment by PalmerAL** [comment]
Hm, I haven't seen that one before. There's an issue about this in lzma-native: https://github.com/addaleax/lzma-native/issues/118 - it looks like it might have to do with other libraries you installed? The comment in that issue isn't too specific, but if you've modified your xcode setup before you can see if some part of that applies to you.

> Is the solution as simple as manually installing lzma_native (x86) and allowing it to run in Rosetta 2?

Possibly - there's some other dependencies that are native code as well, and you might run into issues compiling those as well. I think if you install an x86 version of node/npm and run that in rosetta, it will install x86 dependencies for everything. I'm not entirely sure though.

---

If you get lzma-native to compile, one other issue you might run into is that one of the other dependencies doesn't compile with recent versions of node: https://github.com/atom/node-keytar/issues/386. Either node 15.7.0 (the version in the nvmrc) or 14.17 (which is what I have installed) should work.

Thanks for sponsoring BTW!

**Comment by flightmansam** [comment]
@PalmerAL Problem solved. Setting up a Node environment as per the nvmrc is literally the only change I made. This must be due to Node < 16 still being mostly x86 binaries as mentioned somewhat in the [nvm git](https://github.com/nvm-sh/nvm#Troubleshooting-on-macOS). Might have to cross this road again later if this project changes its minimum Node version, but for now the lazy option is successful so we can get back to the fun stuff.

Thanks for your help, and fantastic work on this browser. It's for sure going to be my daily driver.

**Comment by PalmerAL** [comment]
Hm, I wonder if node v15 is just running in rosetta then. Like you said, hopefully it won't be an issue by the time we need to upgrade.

Glad you like it!
