### ISSUE TITLE
Request: need to have a shortcut

### ISSUE THREAD

**Issue by baronleonardo** [minbrowser/min#186]
Could you please make ctrl+PgDn ctrl+PgUp acts like go to the right and the left tabs ?
It will bee better if we could customize the shortcuts ourselves.

**Comment by hot-leaf-juice** [comment]
as far as I can tell (haven't actually got round to compiling it yet) custom keyboard shortcuts are implemented in the latest version: https://github.com/minbrowser/min/pull/154

**Comment by PalmerAL** [comment]
@hot-leaf-juice Yes, they are. This will be included in 1.3.0.

**Comment by PalmerAL** [comment]
Fixed in e0b0811291c79507f7afa9df4298dd416ff04d01.

**Comment by PalmerAL** [comment]
1.4.0, which includes the fix for this, has been released. You can download it from here: https://github.com/minbrowser/min/releases/tag/v1.4.0
