### ISSUE TITLE
Enhancement request: Retain window size+position on exit

### ISSUE THREAD

**Issue by we3geeks** [minbrowser/min#187]
Retain window size and position on exit, and use that when application restarts (rather than always starting maximized).

**Comment by wb9688** [comment]
That's already implememted…

**Comment by we3geeks** [comment]
I'm not seeing it with v1.2.2 on OS X. The app always opens maximized.

**Comment by PalmerAL** [comment]
This was fixed in 41aaaa498b666f2db1864f44caa247b44bf5983d, but it wasn't included in 1.2.2. It will be in 1.3.0.
