### ISSUE TITLE
Make it clearer that alt shows the menu bar on Linux and Windows

### ISSUE THREAD

**Issue by PalmerAL** [minbrowser/min#188]

**Comment by AllanDaemon** [comment]
Yeah. I spent a lot of minutes lost with this. I was searching for a IRC channel to ask this. It's more like a hidden feature than a menu bar. Putting it in the tour guide already would be very helful.

**Comment by PalmerAL** [comment]
@idle-zealot Is there a good way to make this more obvious? It's good to be able to hide the menu bar, but I'm wondering if it should be shown by default?

**Comment by idle-zealot** [comment]
I agree that the menu bar should be visible by default, with an option to hide it. That's how most programs on Linux handle it.

**Comment by PalmerAL** [comment]
OK, I'm going to revert #68 for now, and then add back pressing the alt key to hide the menu later.

**Comment by alpererm** [comment]
After  1.3.1 update, I cannot toggle the menu bar by pressing Alt key. It is always visible. I am on Linux Mint 17.3.

**Comment by PalmerAL** [comment]
@alpererm That was intentional. The problem is that it wasn't clear that there was a menu bar, so many people didn't realize there was one.

It seems like the best solution is to show the menu bar by default, but pressing the alt key will hide it. That's not build into Electron, so there wasn't time to include that in the 1.3.1 release. I think it will be in 1.4.0.

**Comment by AllanDaemon** [comment]
Maybe a simple and yet effective way is showing a overlay (a la popup) saying to press alt to show the menu bar with a "Got It" button on the first use, just like many Android APPs and other Google products when open for the first time or introduces new features. Adding it to the Getting Started page is also good.

**Comment by PalmerAL** [comment]
@AllanDaemon Good idea! The getting started page could use a redesign anyway, so this could be part of that.

**Comment by Sestowner** [comment]
@PalmerAL I think this can be closed, is it?

**Comment by PalmerAL** [comment]
Yup, Linux and Windows both use a menu button rather than a bar now, so this isn't an issue.
