### ISSUE TITLE
Error when installing on M1 Mac 

### ISSUE THREAD

**Issue by pao0j** [minbrowser/min#1891]
Getting this error:
“Min” is damaged and can’t be opened. You should move it to the Trash.

M1 Mac Mini 8gb

Downloaded Zip
Extracted file
Moved to Applications folder
Opened file
Error pops up

**Comment by technovangelist** [comment]
I am also getting this error. Tried installing with Brew and from the webpage. Running on a 16" mbp m1 pro

**Comment by technovangelist** [comment]
The solution is here: https://github.com/minbrowser/min/issues/1633#issuecomment-882006927

**Comment by PalmerAL** [comment]
If you get a chance, can you try this build: https://workdrive.zohoexternal.com/file/pwyo73a711a47d7a9420598d976b33eda07f2 and let me know if that fixes the issue?

**Comment by technovangelist** [comment]
Yes, that appears to work perfectly

**Comment by PalmerAL** [comment]
Thanks! I'll make a new release tonight with that fix.

**Comment by PalmerAL** [comment]
https://github.com/minbrowser/min/releases/tag/v1.23.0

**Comment by pao0j** [comment]
Confirming that worked for me as well. Awesome, thank you so much!
