### ISSUE TITLE
Tab reordering

### ISSUE THREAD

**Issue by jasonlagaac** [minbrowser/min#19]
I think a pretty standard feature would be tab reordering :)

**Comment by PalmerAL** [comment]
You can drag and drop to rearrange tabs if you open the expanded tab mode (swipe down on the tabstrip, or press shift+command/control+e). Rearranging tabs without opening the expanded mode probably should be added, but is currently blocked by electron/electron#3009.

**Comment by umpc** [comment]
Is this still an issue that still cannot be fixed, even with something like a keyboard shortcut + click?

Aside: I just found this browser while reading HN. It's been excellent so far! Thank you @ contributors!

**Comment by PalmerAL** [comment]
I think this is still an issue in Electron, but since this issue was opened we've added the tasks overlay (click the three bars in the upper-right corner or press shift+cmd+e), and you can drag-and-drop tabs from there.
