### ISSUE TITLE
On certain NYT articles, scrolling doesn't work.

### ISSUE THREAD

**Issue by blheath22** [minbrowser/min#1909]
Hey. New to this, but I like the look of min so I thought I'd try to help. Certain New York Times articles don't function as intended. I can't scroll down past the title and picture.

Here are two examples:
https://www.nytimes.com/2019/12/26/world/americas/nicaragua-ortega-protests.html
https://www.nytimes.com/2022/02/07/opinion/culture/casual-workplace-remote-office.html

This is a cool browser, though. Best of luck.

**Comment by PalmerAL** [comment]
Those links don't work in Chrome either for me; can you try it there?

**Comment by blheath22** [comment]
When I tried the links on Chrome, an ad/pop-up-thing asking me to create a NYT account showed up. (I wasn't using any ad blocker or anything on Chrome.) So my guess is that pop-up kept me from reading the article on min and Chrome, but min also blocked the pop-up from showing up at all. Wild!

**Comment by PalmerAL** [comment]
Yup I think that's what happened.
