### ISSUE TITLE
Translation in Min

### ISSUE THREAD

**Issue by FairTechnology** [minbrowser/min#1913]
You asked for feedback on Argos Translate. The translation (into Dutch) is not bad really, but (till now) it cannot compete with Deepl. For example: under "Other Changes" you mention "various other bug fixes¨, Which gives (in the Dutch translation translated back to English) ¨horrible other insects¨. Quite funny. Like this there are more examples. The direct translation is okay, but understanding which word to use in different circumstances that look like another seems to be still a problem. But that will get better in time.

**Comment by PalmerAL** [comment]
Thanks for letting me know! There isn't a lot we can do about it right now, but it's good to know where the issues are.

Mozilla is developing a client-side translation technology that could potentially improve this. It only supports a few languages (https://github.com/mozilla/firefox-translations-models), and it's not clear if they plan to support it long-term, but when I experimented with it before the quality seemed a lot better than Argos Translate, so hopefully we'll be able to improve in the future.
