### ISSUE TITLE
Suggestion: A real kicker... Native support for Flash-based OnDemand streams

### ISSUE THREAD

**Issue by baldrick-nz** [minbrowser/min#192]
Adobe ditching Linux support, and more ondemand options popping up, having a one-stop for VOD services would be a definite 'opt-in' advantage for Min.

Currently only Chrome offer in-built native support for Netflix, but sadly this doesn't extend to other services as well.

**Comment by PalmerAL** [comment]
Min is unlikely to support Flash anytime soon, but in the long-term it probably won't be necessary. There are now HTML5 alternatives for flash, and a lot of sites are moving to those. <a href="http://www.tomshardware.com/news/chrome-to-block-flash-content,31807.html">Chrome is blocking all Flash content by the end of the year</a>, with only a few sites given a temporary exemption. Adobe has mostly stopped development on Flash Player, and it's becoming less and less common to see sites that use it.

Netflix actually doesn't use flash player - it uses a different plugin, widevine (which Min also doesn't support: see #161).

**Comment by PalmerAL** [comment]
There is a JS-based flash player, <a href="https://github.com/mozilla/shumway">shumway</a>, that could be integrated into Min, but it looks like it's been abandoned, and I don't think it supports video anyway.

**Comment by dbfreem** [comment]
Since Flash isn't really support be by alot of other browsers and this is from 2016, closing.
