### ISSUE TITLE
Min not running on Windows 11 VDI 

### ISSUE THREAD

**Issue by sa1xx** [minbrowser/min#1928]
Min Version: 1.23.1
Operating system: Windows 11 21H2

I'm using Windows 11 and Windows 10 in an VDI. So the system is running in an VM.
Min is installing fine but when you launch it, it only shows an white window. 
Anything required in an VM to get this running?

**Comment by PalmerAL** [comment]
Try editing the shortcut properties and adding `--disable-gpu` to the end.

**Comment by sa1xx** [comment]
Thanks, that works. 
Runs fine even without GPU.
