### ISSUE TITLE
Suggestion: spell checker

### ISSUE THREAD

**Issue by baldrick-nz** [minbrowser/min#193]
Maybe incorporated as a right-click option? Imported code from LibreOffice maybe?

**Comment by wb9688** [comment]
LibreOffice uses [LanguageTool](https://languagetool.org/), which is
written in Java and we probably don't want Javaa as a dependency…

**Comment by Honason** [comment]
There are good options for Electron:

[electron-spell-check-provider](https://www.npmjs.com/package/electron-spell-check-provider)
[simple-spellchecker](https://github.com/jfmdev/simple-spellchecker)

**Comment by PalmerAL** [comment]
Basically, there are two types of spellcheckers:

* Native node modules that use the platform's API. The advantage to this is that the dictionary is comprehensive, it works for any language, and it doesn't use much memory. However, it makes the build process a lot more complicated.
* Pure JS spellcheckers using a custom dictionary. I actually wrote one of these (palmeral/spellcheck.js) for a different project. The disadvantage of this approach is that a dictionary for every supported language would have to be included in the Min binary. Also, the dictionary would have to be loaded into memory for every tab, which would slow down the page load time and increase memory usage.

**Comment by Honason** [comment]
@PalmerAL I have implemented native spellchecker module in one of my projects recently, and build process is manageable - both locally and perhaps on Jenkins, if you use it. 

It is just important to have Electron and Node versions aligned in dev and build environment, or use one of these:
- https://github.com/electron/electron-rebuild
- https://github.com/juliangruber/require-rebuild

**Comment by PalmerAL** [comment]
@Honason Once you build native modules once, can you use them on any platform, or do you have to build them for each platform?

**Comment by Honason** [comment]
@PalmerAL Good question, I used it in OSX only app. But from looking at https://travis-ci.org/atom/node-spellchecker/ and https://github.com/atom/node-spellchecker, to me it looks like you build once, and binding to native libraries happens on runtime. But I'm not 100% sure.

By the way, Min looks like an awesome project and initiative, and if it's welcome, I'd like to contribute some code and thoughts :-)

**Comment by PalmerAL** [comment]
> But from looking at https://travis-ci.org/atom/node-spellchecker/ and https://github.com/atom/node-spellchecker, to me it looks like you build once, and binding to native libraries happens on runtime. But I'm not 100% sure.

OK, I'll try it and find out.

> By the way, Min looks like an awesome project and initiative, and if it's welcome, I'd like to contribute some code and thoughts :-)

Contributions are definitely welcome!

**Comment by PalmerAL** [comment]
Electron recently added built-in support for spellchecking, and the context menu items for it were added to Min in 2fdee3dfc957f5d3ae245dd13076f81176245355, so this should be fixed in the next release.
