### ISSUE TITLE
Cannot use Mubi.com

### ISSUE THREAD

**Issue by ashis0013** [minbrowser/min#1931]
- **Min Version:*Latest*
- **Operating system:Windows 10**

## Expected Behavior
Mubi should play the videos I want
## Actual Behavior
The player is not starting. showing the following message
```
Sorry something isn't right.
MUBI support has been notified.
Please try:
Checking your internet connection.
Checking you have no browser extension installed that might block our player.
Upgrading you browser to one we support. (Chrome 95 and above, Firefox 90 and above, Safari 13 and above and Edge 96 and above)
Error code:
6001 - 0
```
## To Reproduce
1. Open mubi.com
2. Login and play a movie

**Comment by ashis0013** [comment]
<img width="912" alt="Screenshot 2022-03-08 at 4 07 14 PM" src="https://user-images.githubusercontent.com/31564734/157220315-94f1b940-2ee1-48b8-aa29-95e7f6578dbf.png">

**Comment by PalmerAL** [comment]
This is most likely because we don't support Widevine DRM: https://github.com/minbrowser/min/issues/641. Not easily fixable unfortunately.
