### ISSUE TITLE
Getting this error on first install and every time I go to a url or search for something

### ISSUE THREAD

**Issue by rp1231** [minbrowser/min#1932]
- **Min Version:1.23.1**
- **Operating system:**
<Windows 11>

## Expected Behavior
Should work as a normal browser
## Actual Behavior
Getting this error every time I search for something

![min_AhIuW9Hp2Q](https://user-images.githubusercontent.com/47380919/156903574-d17da256-dacf-48bc-aae5-81fbfb0ad2b8.png)

This error occured on first run after install as well.

**Comment by PalmerAL** [comment]
1. Does this happen if you go to any webpage, or just to a search engine page?
2. Does your windows username have any special characters (anything other than A-Z) in it?

**Comment by rp1231** [comment]
The error disappeared after I restarted my laptop......

**Comment by PalmerAL** [comment]
Oh, interesting. Let me know if it happens again.
