### ISSUE TITLE
A Javascript error occurred in the main process

### ISSUE THREAD

**Issue by emremigh** [minbrowser/min#1946]
- **Min Version: v1.23.1**
- **Operating system: Win 11**

![Screenshot_1](https://user-images.githubusercontent.com/74157586/158021768-7ca7acda-14c4-4f5b-8d94-52f548c44245.png)

Hey i downloaded this program to try it out but i had this problem.
I've tried solutions that you've offered them before but it didnt work for me.

**Comment by PalmerAL** [comment]
When does this happen - as soon as you open Min, or sometime else?

**Comment by aaronlosiukwan** [comment]
![Screen Shot 2022-03-13 at 04 27 52](https://user-images.githubusercontent.com/9790298/158033941-f7403107-6134-474e-8f01-af0636ecea09.png)

same here

**Comment by emremigh** [comment]
![min-browser-error](https://user-images.githubusercontent.com/74157586/158035757-2e28e322-d355-4655-b9ff-6366ada0ed1e.gif)

thank you for responding quickly this is how my problem works

**Comment by PalmerAL** [comment]
I can't reproduce this problem, but it'll be pretty simple to ignore invalid URLs instead of showing an error.

**Comment by emremigh** [comment]
> I can't reproduce this problem, but it'll be pretty simple to ignore invalid URLs instead of showing an error.

I dont understand your answer.

C:\Users\id\AppData\Local\min\app-1.23.1\resources\app\main

do I need to change the contents of the file in ? If so, I tried and it still doesnt work.

**Comment by PalmerAL** [comment]
You don't need to do anything, I'm just describing what I did to solve the issue. You can edit the file in `C:\Users\id\AppData\Local\min\app-1.23.1\resources\app\main.build.js` to have the changes from cc764208903310736d3040c35f3fd41ab7bbc0e0 if you want, or you could wait until the next prebuilt release.

**Comment by emremigh** [comment]
I want to experience this browser without any problems so I will prefer to wait to decide. Good luck ✨

**Comment by PalmerAL** [comment]
If you previously had this issue, could you:

1. Install the latest release: https://github.com/minbrowser/min/releases/tag/v1.24.0 and confirm that it's fixed?
2. (Optional) start Min from the terminal (`open /Applications/Min.app` on macOS, or drag Min into the command prompt on Windows), perform a search like before, and post any error messages you see here.
(I've added some logging that should show the cause of the issue, I'm interested to see what URL was causing the error)

**Comment by emremigh** [comment]
this version works without problems. GJ
