### ISSUE TITLE
Changing position of tabs.

### ISSUE THREAD

**Issue by MaximFedarau** [minbrowser/min#1949]
- **Min Version:** latest
- **Operating system:** macOS Big Sur 11.6.2

## Expected Behavior
Changing position of the tabs by hold and drag.
## Actual Behavior
Changing the position of the whole window.
But when I tried to change the position of tabs in Kali Linux (latest version of OS and browser) everything worked good.

**Comment by PalmerAL** [comment]
This was fixed in the latest release; you can hold cmd while dragging on macOS to rearrange tabs now.
