### ISSUE TITLE
Issue: List of search engines on Preferences page is empty

### ISSUE THREAD

**Issue by we3geeks** [minbrowser/min#195]
It isn't just that nothing is selected, but rather that the list is empty so there is nothing to be selected. Search still defaults to DuckDuckGo.

Min v. 1.3.0 on OS X 10.11.5

![min-20160601a](https://cloud.githubusercontent.com/assets/2390335/15708255/d4391e50-27ba-11e6-8a55-6b8b02bfbd79.png)

**Comment by PalmerAL** [comment]
I can't reproduce this, in a new install or an install upgraded from Min 1.2.2.

If you open the devtools for the settings page (Developer > Inspect page), are there any errors in the console?

**Comment by we3geeks** [comment]
This is an install upgraded from v. 1.2.2.

Console shows the following:
database opened  538.6800000000001 database.js:27
database error occured TypeError: Cannot read property 'trackers' of undefined(…) database.js:31

![min-20160601a](https://cloud.githubusercontent.com/assets/2390335/15731222/9fc58070-2830-11e6-8884-d709a592b52c.png)

**Comment by PalmerAL** [comment]
Is this fixed in 1.3.1? I think 5ec0e40f2c956b881b5c0c336fa2ae8de3072fa7 fixed this, and that was supposed to be included in 1.3.0, but looking at the build it seems it wasn't.

**Comment by we3geeks** [comment]
Will check and let you know later today...

**Comment by we3geeks** [comment]
Fixed in 1.3.1. Thanks!
