### ISSUE TITLE
Windows 11 ugly title bar

### ISSUE THREAD

**Issue by Nexer8** [minbrowser/min#1951]
Hello, I would love to get rid of the white title bar appearing on Windows 11 as shown in the screenshot. Is it possible? If not, are there any plans to make it look better?

![image](https://user-images.githubusercontent.com/47852977/158496320-6e0c2e6c-0b33-4f22-a87b-e3bf5ba85651.png)

**Comment by PalmerAL** [comment]
It shouldn't look like that by default; do you have "use separate titlebar" enabled in preferences?
