### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by koendv** [minbrowser/min#1960]
I'd like to thank you for making this browser available. It's a breath of fresh air; a browser that has just what is needed, and nothing more.

A side note: raspberry pi os now has a 32-bit and a 64-bit version ; the 64-bit version needs to be compiled with _npm run buildLinuxArm64_.

**Comment by PalmerAL** [comment]
Glad you like it!

Fixed the documentation in 9686c6010baf72804730a0e2b5e4f8d6d7853c50.
