### ISSUE TITLE
Open tab(s) in Background 

### ISSUE THREAD

**Issue by bonnebulle** [minbrowser/min#1962]
A great option : "make tab open in background" or not focus on middle-clic...
If you open a few tab from the same page it's a great feature !
Thx for all, good Chrome Browser alternative

**Comment by PalmerAL** [comment]
This should be the default already, do you have "open new tabs in the foreground" enabled in settings?

**Comment by PalmerAL** [comment]
Oh, I think I see the problem - the [French translation](https://github.com/minbrowser/min/blob/master/localization/languages/fr.json#L159) for this setting is "Ouvrir les nouveaux onglets en arrière-plan", which I believe translates into "Open new tabs in the background". That should say "foreground" - would you be willing to translate that the correct way?

**Comment by bonnebulle** [comment]
Merci (;
It looks like I already checker this option (am on Linux)
I will try later
thx for your quick tips

**Comment by bonnebulle** [comment]
Ok . I juste test, the option in french is inversed . 
When uncheck... it open tabs in backgroud "arriere plan" .
Need a fix (and check if am right)
Thx again

**Comment by PalmerAL** [comment]
Yup, that's what I was noticing. Can you tell me what the right translation for "Open new tabs in the foreground" is so that I can update the translation file?

**Comment by bonnebulle** [comment]
Salut
 "Open new tabs in the foreground" == "Ouvrir les nouveaux onglets **au premiers plan**"
 best saying : "Basculer vers l'onglet **à sa création**" 
Firefox long say / meaning ; 
https://support.mozilla.org/fr/kb/parametres-preferences-onglets : 
"À l’ouverture [...d']un nouvel onglet, **basculer vers** celui-ci immédiatement" 
( "On new tab opening, switch immediately to it" )
