### ISSUE TITLE
Pressing escape key make the screen flash white

### ISSUE THREAD

**Issue by carlosqsilva** [minbrowser/min#1966]
- **Min Version:** 1.23.1
- **Operating system:** MacOS Monterey 12.3

## Expected Behavior
Screen should not flash white
## Actual Behavior
Pressing escape key makes the screen flash white, is also possible to see this white flash when change tabs

https://user-images.githubusercontent.com/19891059/160719677-382f091c-925d-4546-b1a8-0a2a4af58bde.mp4

## To Reproduce
Press escape key in any tab

**Comment by LeviOP** [comment]
It also makes the text cursor disappear on the Discord website. Haven't seen it with any other sites but it's really annoying considering how often I use the escape key.

**Comment by PalmerAL** [comment]
Thanks, fixed in 792451e366889cc61786069fe4ed8236b057e3d4.
