### ISSUE TITLE
Opening new windows on min browser.

### ISSUE THREAD

**Issue by OlifBece** [minbrowser/min#1979]
Right now I don't seem to find a way to open two windows at the same time, I would like to know if there is a way to open two windows or tile two tabs at the same time.

**Comment by flightmansam** [comment]
#1982

**Comment by OlifBece** [comment]
Thank you for your answer, that is way better than what I asked for!.

**Comment by a13ph** [comment]
As multiple windows are in the released version now, this issue may be closed, imo

**Comment by PalmerAL** [comment]
Yup, thanks.
