### ISSUE TITLE
Preference view overlapped

### ISSUE THREAD

**Issue by tubaxenor** [minbrowser/min#200]
![image](https://cloud.githubusercontent.com/assets/1394393/15813430/83137f8a-2bf1-11e6-98c1-8f9254006384.png)

Also happens when scroll down:
![image](https://cloud.githubusercontent.com/assets/1394393/15813449/ae7d2478-2bf1-11e6-9019-9d82002dc30d.png)

I am using OSX 10.09

**Comment by PalmerAL** [comment]
Does this happen every time you open the preferences view?

This looks like a Chromium bug, but I can't reproduce it. If you copy the URL of the preferences page, and open it in Chrome, does this still happen?

**Comment by tubaxenor** [comment]
> This looks like a Chromium bug, but I can't reproduce it. If you copy the URL of the preferences page, and open it in Chrome, does this still happen?

Nope, it works fine on Chrome:

![image](https://cloud.githubusercontent.com/assets/1394393/16106557/04172e32-33c8-11e6-8aa3-55af2c35804b.png)

**Comment by PalmerAL** [comment]
Is this still an issue in the latest version of Min?
