### ISSUE TITLE
Question: What determines TabBar color?

### ISSUE THREAD

**Issue by du64** [minbrowser/min#2001]
I'm developing a mobile browser in Flutter, and I'm curious how you're picking the color to use in the Tab Bar. It changes with each site, and looks really nice. What exactly is it looking for in the site, so I can recreate it on mobile?

**Comment by PalmerAL** [comment]
It looks for a `<meta name="theme-color">` tag, and then for the main colors in the favicon image if there isn't one: https://github.com/minbrowser/min/blob/master/js/navbar/tabColor.js
