### ISSUE TITLE
Reorder tasks

### ISSUE THREAD

**Issue by leandrobrunner** [minbrowser/min#201]

**Comment by PalmerAL** [comment]
9ef2c11f67fe4c4b7bf96bd1b3784f0f6f0d693c added support for this in ```syncStateAndOverlay```, so reordering the DOM elements will update the task list. However, Dragula doesn't support nested containers, so Min will have to switch to another library before adding this to the UI.

**Comment by PalmerAL** [comment]
It turns out it's possible to do this in Dragula. This has been added in 15e45a3620326a958e2cdeea1776a36f0d4f8a27; it will be included in the 1.7.0 release.

**Comment by PalmerAL** [comment]
The 1.7.0 version that includes this fix has been released, you can download it from here: https://github.com/minbrowser/min/releases/tag/v1.7.0.
