### ISSUE TITLE
It is impossible to enter the Google account

### ISSUE THREAD

**Issue by zerosharp291** [minbrowser/min#2014]
Min Version:1.24.7
Operating system: Windows 10

I really like your browser but it is much problem for me. 

![image](https://user-images.githubusercontent.com/91559709/173775160-e1e0663c-cfa4-49d1-82ca-25ed6a440198.png)

**Comment by sndrkrly** [comment]
Maybe, check [issues#868](https://github.com/minbrowser/min/issues/868), whether the solutions described there work for you.

**Comment by zerosharp291** [comment]
> Check [issues#868](https://github.com/minbrowser/min/issues/868), maybe one of the solutions described there will work for you.

Thank you, it really helped (I copied UA from  UAswitcher.js
