### ISSUE TITLE
Un-bookmark?

### ISSUE THREAD

**Issue by freefalleen** [minbrowser/min#2020]
Discovered and tried Min browser today. The super minimal and clear interface made the browser feel very spacious - was great! 
Have a question though - bookmarking is something i'm extremely attached to, was testing out the function and realize i can't seem to unbookmark something. Clicking on the star button once more does not undo the bookmark. Is the function accessible somewhere else that i'm not seeing?

Thank you!

**Comment by sQur1** [comment]
I'm experiencing the same issue. I'm on the latest version of MacOS (M1).

**Comment by PalmerAL** [comment]
CC @flightmansam  - I think this is a regression from https://github.com/minbrowser/min/pull/1992; the `carbon:delete` icon doesn't exist any more somehow, and so the button to delete bookmarks isn't visible.

I'll fix this soon if you don't get to it.

**Comment by PalmerAL** [comment]
@freefalleen @sQur1 Until we fix this bug, there's a (rather silly) workaround - if you place your mouse just to the right of the tag input, a little circle will show up where the button is supposed to be. Click on that and the bookmark will be deleted:
<img width="1551" alt="Screen Shot 2022-06-24 at 12 07 22 AM" src="https://user-images.githubusercontent.com/10314059/175423408-4a172e4d-a5fb-4940-add2-16203d241c8b.png">

**Comment by flightmansam** [comment]
> CC @flightmansam  - I think this is a regression from https://github.com/minbrowser/min/pull/1992; the `carbon:delete` icon doesn't exist any more somehow, and so the button to delete bookmarks isn't visible.
> 
> I think it has been renamed to trash-can
> 
> I'll fix this soon if you don't get to it.

**Comment by PalmerAL** [comment]
Thanks for the quick fix!

**Comment by flightmansam** [comment]
@PalmerAL No worries! Just note I did dig a little further and I am pretty sure the updated icon files do not affect any other references in min. https://github.com/minbrowser/min/pull/2025#issuecomment-1164993170
