### ISSUE TITLE
"app.invalidateCurrentActivity is not a function" & "app.setUserActivity is not a function"

### ISSUE THREAD

**Issue by KaKi87** [minbrowser/min#2022]
- **Min Version:** 1.25.0
- **Operating system:** Linux Mint 19.3

## Expected Behavior

No error is thrown

## Actual Behavior

Two errors are thrown :

![Screenshot from 2022-06-23 13-35-55](https://user-images.githubusercontent.com/21284089/175290970-c5b20970-7542-482c-bb7a-67d2fb2d2869.png)
![Screenshot from 2022-06-23 13-34-16](https://user-images.githubusercontent.com/21284089/175290976-bb2e881c-9668-44e2-9b7d-42df35b1b29b.png)

## To Reproduce

1. Open the app
2. Notice first error thrown multiple times
3. Open a new tab in the app
4. Notice second error thrown multiple times

---
Thanks

**Comment by PalmerAL** [comment]
Oh, that's not good. I'll release a new build soon to fix this.
