### ISSUE TITLE
Windows 64bit portable version not in v1.25.0 release

### ISSUE THREAD

**Issue by tech189** [minbrowser/min#2026]
In https://github.com/minbrowser/min/releases/tag/v1.25.0, the latest release, there is no longer a 64bit portable zip for Windows. Previous releases contained a file such as https://github.com/minbrowser/min/releases/download/v1.24.0/Min-v1.24.0-win32-x64.zip. Now only a 32bit version is being released: https://github.com/minbrowser/min/releases/download/v1.25.0/Min-v1.25.0-ia32.zip

**Comment by PalmerAL** [comment]
Fixed in 1.25.1 ("-windows.zip" is 64-bit now), can you confirm that it works?

**Comment by tech189** [comment]
Yes, it's fixed now, thank you.
