### ISSUE TITLE
Min 1.25 Windows show app title bar

### ISSUE THREAD

**Issue by chenelias** [minbrowser/min#2029]
**system: windows 11**
**Min browser: v1.25.1**

>Us you can see it show default windows title bar. 
>Is there any way to fix it like the second image?

**on my computer**
![image](https://user-images.githubusercontent.com/76611085/175769732-430b0019-7cb6-4562-8079-5d3f3a97f5b9.png)

**fix like this**
![image](https://user-images.githubusercontent.com/76611085/175769981-00c8fa37-026b-4d14-a32f-ae438d239b7c.png)

**Comment by PalmerAL** [comment]
Try going to menu > settings > uncheck "use separate title bar". Does that work?

**Comment by chenelias** [comment]
> Try going to menu > settings > uncheck "use separate title bar". Does that work?

Yes it work ,Thank you so much!
