### ISSUE TITLE
Wrong title in tab

### ISSUE THREAD

**Issue by soxft** [minbrowser/min#2030]
- **Min Version:** 1.12.5
- **Operating system:** MacOS 13 Beta2

## Expected Behavior

When I Open Google, the title in tab is Google, and then i open the website which din't have the <title> tag in <head>, the browser title still be the old one (google)

## Actual Behavior

I think when a website does’t contain the title tag, just show the url in Browser tab

**Comment by djtech-dev** [comment]
I'll work on it 😁
