### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by CasCodes** [minbrowser/min#2040]
The **'this list'** link in the readme under `Contributing to Min -> Contributing Translations`
leads to a page not found. The electron wiki doesn't seem to have a page for country codes anymore, so it could be replaced with e.g. https://www.loc.gov/standards/iso639-2/php/code_list.php

**Comment by CasCodes** [comment]
Thanks! Am I supposed to close the issue now or should I make a push request with the fixed link? (First time doing this stuff)

**Comment by takomine** [comment]
Just wait for them to edit the README, it's just a link issue. Or make a PR yourself if you want to

**Comment by PalmerAL** [comment]
I think this link would be best to use, since it exactly matches what Chromium allows? Although its a bit hard to read: https://source.chromium.org/chromium/chromium/src/+/main:ui/base/l10n/l10n_util.cc;l=55

You're welcome to make a PR if you want, or I'll change it if not.

**Comment by takomine** [comment]
Yeah it looks confusing to look at. Maybe include both links since they're just both displaying the same values though it's more complete on the chromium page

**Comment by PalmerAL** [comment]
I went with @CasCodes PR, with just the first link; I think it's probably fine, particularly with instructions about which part of the file to look at. We can see if people get confused and change if necessary.
