### ISSUE TITLE
TypeError: Error processing argument at index 1

### ISSUE THREAD

**Issue by naelxd** [minbrowser/min#2045]
- **Min Version: 1.25.1**
- **Operating system: Fedora 36**

While watching videos on site (https://animego.org/anime/van-pis-65) and selecting AniMedia to the right of video, I had this exception (pinned picture below)
![Screenshot from 2022-07-15 15-53-21](https://user-images.githubusercontent.com/45898878/179186627-b105d3c5-ad01-419d-9e91-9400a4038c4f.png)
This from console:
`[1] [45276:0715/164205.036101:ERROR:stun_port.cc(100)] Binding request timed out from [0:0:0:x:x:x:x:x]:44279 (any)
[1] [45276:0715/164205.036347:ERROR:stun_port.cc(100)] Binding request timed out from [0:0:0:x:x:x:x:x]:55334 (any) 
[1] [45276:0715/164205.036437:ERROR:stun_port.cc(100)] Binding request timed out from [0:0:0:x:x:x:x:x]:39688 (any)
[1] [45276:0715/164205.036567:ERROR:stun_port.cc(100)] Binding request timed out from [0:0:0:x:x:x:x:x]:46574 (any) 
`

**Comment by djtech-dev** [comment]
Did the browser/the tab crashed?

If it didn't, could you retry disabling the integrated adblocker and anti-tracker from Min's settings?

**Comment by naelxd** [comment]
> Did the browser/the tab crashed?
> 
> If it didn't, could you retry disabling the integrated adblocker and anti-tracker from Min's settings?

Thanks! Allowing all ads and trackers solved this mistake.

**Comment by PalmerAL** [comment]
This still shouldn't happen even with adblocking enabled, so I'm going to reopen though. That's a good hint to the problem though!

**Comment by PalmerAL** [comment]
I think this was probably fixed in 7aba03fb645334366f9ec71867e36fc6fbf4ee15; can you try again after the next release and let us know if it still happens?

**Comment by naelxd** [comment]
> I think this was probably fixed in [7aba03f](https://github.com/minbrowser/min/commit/7aba03fb645334366f9ec71867e36fc6fbf4ee15); can you try again after the next release and let us know if it still happens?
Yes, shure

**Comment by naelxd** [comment]
I don't have this error after update
