### ISSUE TITLE
How to manipulate bookmarks in Min?

### ISSUE THREAD

**Issue by 3oheicrw** [minbrowser/min#2048]
I exported the bookmarks from Firefox to HTML and imported it in Min. The problem is I can't move bookmarks outside of the bookmark folder (Bookmark Bar to be clear). There is also no way to delete bookmark folder (Mozilla Firefox folder to be clear). I can only delete the bookmarks inside it but not the bookmark folder itself.

**Comment by 3oheicrw** [comment]
I will close all of my submitted issues since the developer is obviously don't care and will not answer me. What a waste of time!

**Comment by PalmerAL** [comment]
Added an option to delete folders: #2058 
You can remove a tag from a bookmark by hovering over it > click the pencil > click on the tag to remove.
