### ISSUE TITLE
Random crash error while running min

### ISSUE THREAD

**Issue by Midnight1938** [minbrowser/min#2052]
- **Min Version:** 1.25.1
- **Operating system:** Fedora 36, i3 wm

## Expected Behavior
Open the webpage?

## Actual Behavior
White page with the error

## To Reproduce
Opened [embibe](https://www.embibe.com) and my [linux foundation portal](https://trainingportal.linuxfoundation.org) websites

## Error: 
<img src="https://i.ibb.co/km2TFyc/Min-error-07-20-16-37.png">

**Comment by djtech-dev** [comment]
Try disabling/enanbling the Min's adblocker/anti-tracker.

If it doesn't work, please send a screenscot of any error that are present in the web browser's console.

**Comment by Midnight1938** [comment]
Ive tried disabling Min's ad blocker to no avail. The issue seems to be with sites that require a login. Will post console log soon

**Comment by PalmerAL** [comment]
I can't reproduce it on those sites, but I've seen this error occasionally also. The error is from here:

https://github.com/minbrowser/min/blob/master/main/viewManager.js#L108

So we're recieving a message from a frame, but somehow the `senderFrame` object is referencing a frame that's already been destroyed. It should probably suffice to check for that and ignore the message in that case.
