### ISSUE TITLE
Can't use google credentials

### ISSUE THREAD

**Issue by pedromadethis** [minbrowser/min#2054]
Its not a safety browser to use google services, i received the prompt after tried a youtube acess.

![Captura de Tela 2022-07-22 às 06 12 26](https://user-images.githubusercontent.com/7057728/180406530-c6add3fb-dfb0-45c6-a189-5bff2562c14e.png)

Message: 

**Could not login**
This browser or app may not be secure. know more
Try using another browser. If you're already using a supported browser, try logging in again

**System: Mac OS 10.14. Mojave**

**Comment by takomine** [comment]
Duplicate issue with #868
