### ISSUE TITLE
Linux: Menu bar shows on full screen

### ISSUE THREAD

**Issue by baldrick-nz** [minbrowser/min#206]
Maybe this will be resolved when one can toggle the menu under Linux? But needs to be resolved if not. (was a YT video playing).

Min has become my browser of choice, just needs minor refinements such as this before I feel comfortable enough to recommend to others. Love the direction it's headed though!

![screenshot from 2016-06-19 18-56-59](https://cloud.githubusercontent.com/assets/4667405/16175842/5542a82e-3650-11e6-95f9-ecb5cc59fcf1.png)

**Comment by masnormen** [comment]
Same here. For such a "minimal" web browser, a menu bar can be distracting (and aesthetically ugly). It would be nice if there's an option to toggle menu bar on Linux.

**Comment by PalmerAL** [comment]
@masnormen Adding a toggle for the menu bar is a separate issue: #188. This issue is about not showing the menu bar in fullscreen, which I think should be the default.

**Comment by masnormen** [comment]
@PalmerAL Sorry, my bad. But yeah, I agree with this.

**Comment by code-hunger** [comment]
I don't have this problem. E.g., https://davidwalsh.name/demo/fullscreen.php, if I do "Launch fullscreen", the electron menu is hidden no matter whether it was visible or not before. I can always show/hide it using single `alt` press.

**Comment by Syndamia** [comment]
Closing, because now Linux uses a menu button instead of a bar.
