### ISSUE TITLE
GPU acceleration

### ISSUE THREAD

**Issue by azisaka** [minbrowser/min#2060]
Hi! 

I'm using Min on Linux. I want to enable the hardware video decoding. Is there a way to do it? The flags ` --enable-accelerated-video --ignore-gpu-blacklist` does not seem to work.

**Comment by PalmerAL** [comment]
Also try checking `chrome://gpu` with and without those flags - it's possible you may have it enabled already.

**Comment by azisaka** [comment]
Thanks for trying to help me. I guess it won't work on Linux thought. Not a huge problem, I will try it again in the future.

**Comment by Flashwalker** [comment]
try also these flags:
```
--enable-features=UseSkiaRenderer,Vulkan,VaapiVideoDecoder --use-gl=egl
```

**Comment by azisaka** [comment]
Yep, confirmed! Works on amdgpu too!
