### ISSUE TITLE
Update Electron version to 20.0

### ISSUE THREAD

**Issue by CaptainBeidou** [minbrowser/min#2065]
Min is currently using the 19.0.5 version of Electron, need to update to version 20.0

**Comment by PalmerAL** [comment]
I usually update to the latest version of Electron right before each release; not sure when that will be exactly.

**Comment by traumweh** [comment]
On arch, because the min-package doesn't ship its own Electron-Binary, some packages cannot be upgraded as they require Electron 20 and that would break the dependency of min.

**Comment by PalmerAL** [comment]
@traumweh From what I can tell, the dependency is `electron19`, so it should be possible to upgrade everything else without Min breaking: https://archlinux.org/packages/community/x86_64/min/ . Did it fail for you?

**Comment by FF-AntiK** [comment]
I had to install `electron19` manually. Thanks for the Hint 👍🏼

**Comment by traumweh** [comment]
You are totally right, I forgot that the old electron versions get packaged separately. Thanks!

**Comment by flightmansam** [comment]
Electron >= 19 has an ongoing bug with PiP playing of videos.

**Comment by PalmerAL** [comment]
Link to the issue Sam mentioned: https://github.com/electron/electron/issues/34406

Looks like it should get fixed soon (but we'll upgrade to whatever the latest version is regardless).

**Comment by CaptainBeidou** [comment]
Installing and replacing electron with electron19 manually solve the problem. Thanks!
