### ISSUE TITLE
Can't connect to the internet

### ISSUE THREAD

**Issue by JiantingFeng** [minbrowser/min#2092]
Hi, I just start to use minbrowser, but I can't open any website within it.

<img width="480" alt="image" src="https://user-images.githubusercontent.com/36693163/190661643-a2b3f956-10be-4f08-8af9-d4f976664122.png">

Other browsers, like Safari, Chrome, work well on my Mac. I don't know how to fix it.

Is there anyone has same issue with me?

**Comment by PalmerAL** [comment]
That is very odd. Do you have any kind of proxy / VPN set up?

**Comment by JiantingFeng** [comment]
Yep, thank you for your suggestion, I configured HTTP proxy in the browser and it was solved!
