### ISSUE TITLE
Missing new tab background

### ISSUE THREAD

**Issue by zenpeaky** [minbrowser/min#2120]
- **Min Version:**
1.24
- **Operating system:**
macOS 13

## Expected Behavior
console is clear when using inspect

## Actual Behavior
JS excp missing newTab background

## To Reproduce
I use localhost for developing an web app (no error on other browser)

<img width="275" alt="Screenshot 2022-10-29 at 11 01 33" src="https://user-images.githubusercontent.com/47457477/198796548-2771b5ba-550f-4935-ab6d-8855284e856c.png">

**Comment by PalmerAL** [comment]
For web development, you want to use the other console ("inspect page", not "inspect browser").

We probably should fix this at some point, but there isn't really any impact otherwise.

**Comment by zenpeaky** [comment]
thanks for the information
