### ISSUE TITLE
'Search' operators

### ISSUE THREAD

**Issue by ravirathore** [minbrowser/min#2123]
Hi,

Thanks for building this browser.

Just wanted to know regarding, how to search text in history/pages.

If someone searches for 'blue label' :
1. Does the 'search' searches for both different words separately and combine the results?
2. How to search with AND, OR operators between words? 

Please advise.

Thanks,

**Comment by PalmerAL** [comment]
The search is all AND-based.

Can you give an example of how you would use an OR search?

**Comment by ravirathore** [comment]
Hi.
Thanks for clarification. Sorry for the delay in response.

Just wanted to check if comma(,) act as OR operator? And, if one wants to search for a phrase, that phrase should be in quotes?

thanks,
