### ISSUE TITLE
two simple feature requests concerning the tabs

### ISSUE THREAD

**Issue by complxalgorithm** [minbrowser/min#213]
I love this browser, but I think it would be a great move to offer the option of staying on the same tab when one opens a link in a new tab (with right click). If this actually becomes a feature it will make my life.

**Comment by complxalgorithm** [comment]
One more thing; it would be even better if you also allowed for one to move the tabs around, i.e. organize them to their desire. That, too, would make my life.

**Comment by PalmerAL** [comment]
You can drag tabs around by opening the tasks panel (click on the menu icon in the top right).

**Comment by hughwilliams94** [comment]
Can't you just Ctrl+Left Click to open the tab in the background?

**Comment by Syndamia** [comment]
I'm not exactly sure when those were implemented, but right now, you can `Ctrl+Left Click` to open a tab in the background and you can rearrange the tabs in the navbar (like in other browsers).
