### ISSUE TITLE
Is there a way to set the default download folder?

### ISSUE THREAD

**Issue by juancwu** [minbrowser/min#2143]
I want to change the download location, however, I do not see any option to do so on the preferences page.

**Comment by edudebortoli** [comment]
it'll always ask, the location is where the last download was saved.

**Comment by juancwu** [comment]
Can it be set to a default location to not make me confirm every time?

**Comment by Kepler-69c** [comment]
So far (version 1.27.0) there is no possibility to save downloads to a default folder. However, the save dialog will always open in the directory where something was previously downloaded.

**Comment by juancwu** [comment]
Thanks for the responses. I guess it is not a deal breaker to wait for the dialog and click save.
