### ISSUE TITLE
Failed to download pdf

### ISSUE THREAD

**Issue by yougotwill** [minbrowser/min#215]
Firstly this browser if fantastic! One small problem though is that when I click the download button to download pdf's from my university site it keeps opening it in a new tab and not downloading it. 

Keep up the good work. :)

**Comment by PalmerAL** [comment]
Thanks for reporting this!

This should be fixed in c3cade5bf4c64642191196b27f165f3106bfe090, which will be included in 1.5.0. In the meantime, it should work if you wait until the PDF has finished loading before clicking the download button.

**Comment by PalmerAL** [comment]
This should be fixed now, feel free to reopen if it's not.
