### ISSUE TITLE
Unable to Download images directly from Google

### ISSUE THREAD

**Issue by Matheus2323** [minbrowser/min#2160]
When I right-click an image in google images, there is no option to save it in my computer...

**Comment by Kepler-69c** [comment]
Can Confirm the issue still exists. It probably has to do with Google wrapping a link around the images. Work is currently underway in the [context-menu-image-options](https://github.com/minbrowser/min/tree/context-menu-image-options) branch to fix this.

**Comment by PalmerAL** [comment]
Fixed.
