### ISSUE TITLE
Can't hide menu bar in Linux (non-Unity)

### ISSUE THREAD

**Issue by jlnxr** [minbrowser/min#217]
I understand this isn't an issue in OSX and Unity(Ubuntu) as they have global menus, but for those of us who don't, it would be nice to have a way to toggle the menu bar so it isn't taking up useless space up there.

**Comment by GarthTheChicken** [comment]
I would second this please. I'm using i3 and having the bar visible doesn't look right

**Comment by sro5h** [comment]
I`m using i3 too and i too would love to hide the menubar

**Comment by sigrob** [comment]
+1 same problem on openbox

**Comment by hughwilliams94** [comment]
+1 same issue Kubuntu 16.04

**Comment by finnwiley** [comment]
While this is the best minimalistic browser I've come across, the always-visible menubar detracts from the minimalism imo.
+1

**Comment by PalmerAL** [comment]
The previous behavior was to auto-hide the menubar, but it wasn't clear that there was a menu bar, so many people didn't realize that you could press ```alt``` to show it.

Probably, the solution here is to use the patch in #227, and add a prominent section in the tour stating that the menu bar can be shown by pressing the alt key.

**Comment by PalmerAL** [comment]
Actually, Electron has a <a href="http://electron.atom.io/docs/api/browser-window/#winsetmenubarvisibilityvisible">setMenuBarVisibility</a> API. This would make it possible to show the menu bar by default, and hide it when the alt key is pressed. Additionally, a setting could be added so that Min remembers whether or not the menu bar should be hidden.

**Comment by GarthTheChicken** [comment]
Maybe have an indicator in the top left overlaying the first tab to show there's something hidden. The indicator could expand on click or keyboard event showing the menubar or hide when the menubar is in view. I'm using the arc dark theme so I've made the background match the theme. Doing this would help visually tie the indicator to the menubar.
![min-browser](https://cloud.githubusercontent.com/assets/16607045/17642230/5da7d6f0-6135-11e6-9015-1dbaaef2ccd0.jpg)

**Comment by PalmerAL** [comment]
@GarthTheChicken That's a good idea!

**Comment by PalmerAL** [comment]
I'm thinking this options is best, since it most closely matches what other apps do:

> Actually, Electron has a setMenuBarVisibility API. This would make it possible to show the menu bar by default, and hide it when the alt key is pressed. Additionally, a setting could be added so that Min remembers whether or not the menu bar should be hidden.

**Comment by GarthTheChicken** [comment]
Any chance you can make the shortcut configurable? Alt is the primary mod key in i3 and while we can change the mod key it would take a bit to get used to.

**Comment by PalmerAL** [comment]
@GarthTheChicken Sure.

**Comment by PalmerAL** [comment]
This is fixed in b6c4b1df5f569ac19d9b8aa7c69e22884844e4c4.

@GarthTheChicken I added an entry in the preferences for this, so you can change the keyboard shortcut to something other than the default ```alt```.

**Comment by jlnxr** [comment]
I had a hell of a time getting the most current min source to build on Debian stable, mainly relating to nodejs being extremely outdated and having to break (and then after I was done, unbreak) dependencies to get a newer version. But, min sure looks a lot better with no menu bar! I'd say I'm easily 50% min and 50% firefox on a daily basis now- it's a great little browser, fast and light on resources. Thanks for making this work!
