### ISSUE TITLE
Min 1.27.0 is not compatible with MacOS Big Sur

### ISSUE THREAD

**Issue by balduinofernando** [minbrowser/min#2170]
Hello everyone.

SInce version 25, I can't update the Min Browser to newer versions, so I'm stuck in 1.24.0.
I have a MacOS with and Intel CPU, but I cant see the x64 version, so I downloaded the arm64 and x86 but I have a "**Bad CPU Type**" error message, as you can see in the images below.

![Screen Shot 2023-01-18 at 10 51 14](https://user-images.githubusercontent.com/20538071/213139527-d5207c24-6056-429e-ab8a-788b7d23a2db.png)

![Screen Shot 2023-01-18 at 10 48 26](https://user-images.githubusercontent.com/20538071/213139223-83f3c27c-03df-4cb2-9fa0-883f1e6eca2b.png)

What can I do to run the 1.27.0 in my computer?
These are my specs:

![Screen Shot 2023-01-18 at 10 52 58](https://user-images.githubusercontent.com/20538071/213139954-0ee708f9-b20d-4095-9520-7f4409ae1ed4.png)

**Comment by PalmerAL** [comment]
The "bad CPU type" error is with which download?

The right version should be this: https://github.com/minbrowser/min/releases/download/v1.27.0/min-v1.27.0-mac-x86.zip - what happens when you run that?

**Comment by balduinofernando** [comment]
> The "bad CPU type" error is with which download?
> 
> The right version should be this: https://github.com/minbrowser/min/releases/download/v1.27.0/min-v1.27.0-mac-x86.zip - what happens when you run that?

I'll look into it and give you an answer. But is it okay to install 32 bits app on a 64 processor? Is it performant?
I'll give you the feedback soon.

**Comment by balduinofernando** [comment]
Looks like it worked, but some user scripts are not working, but i'll look into it another time.

**Thanks @PalmerAL**

**Comment by PalmerAL** [comment]
Glad it worked! 

> But is it okay to install 32 bits app on a 64 processor? Is it performant?

The mac builds are all 64-bit, so it doesn't matter.
