### ISSUE TITLE
When right clicking Gmail it shows two menus.

### ISSUE THREAD

**Issue by camilosampedro** [minbrowser/min#218]
When I right click on a Gmail mail item, it should only show the mail menu, but it shows also the usual Inspect Element option.

![11](https://cloud.githubusercontent.com/assets/8657866/17183706/55934f48-53ee-11e6-8de6-ec5a59e7c672.png)

**Comment by razzintown** [comment]
As a developer, I prefer that the browser's right-click menu not be hidden by a web page. I suggest that if this must be changed, that a setting should allow the current behavior.

**Comment by PalmerAL** [comment]
As of 915aba848204993d02dbcfd6a545dc02586e83e5, right-clicking shows the page context menu, and holding shift while right-clicking shows both menus. I think this works well enough for both usecases (and it pretty closely matches what Firefox does), although we can consider adding a setting in the future if enough people want it.
