### ISSUE TITLE
Expanding Youtube on lokal html file

### ISSUE THREAD

**Issue by RealVegOs** [minbrowser/min#2200]
- **Min Version: 1.27.0**
- **Operating system: Debian 11**

I have a local html file with an embeddet Youtube video. If I click to expand it to fullscreen, it does not, even with the allowfullscreen attribute in the iframe of Googles embedding code.

Should expand to fullscreen and this works with regular Chromium and many other browsers.

Create a simple HTML file, put the embed code from Google in it, load it with min. Click the expand to fullscreen icon.

**Comment by Sestowner** [comment]
Closing this in favor of #2209
