### ISSUE TITLE
Can't do full screen on some of the sites.

### ISSUE THREAD

**Issue by Gauthamsudo** [minbrowser/min#2209]
I've been using Min Browser for some months and I began to receive bugs only after updating to the new version. 

I visit the site zoro.to to Watch anime and visits some other sites. When I watch anime on this site, I can't do Full Screen. I just didn't find any solutions for this. 

Please fix this Issue as soon as possible.

O.S : Ubuntu 22.04

**Comment by Sangresz** [comment]
this also seem to happen on windows 10

**Comment by RubenSmn** [comment]
Related to #2200

**Comment by PalmerAL** [comment]
I have a fix for this; waiting for https://github.com/minbrowser/min/pull/2237 to be merged first.
