### ISSUE TITLE
Cannot print PDF documents directly from Min PDF viewer

### ISSUE THREAD

**Issue by devgocri** [minbrowser/min#2220]
- **Min Version:** 1.27.0
- **Operating system:** macOS 13.0

## Expected Behavior
When having a PDF document open in Min and the key combination `Command+p` is pressed or the print option is selected from the title bar, a print dialogue should open which will allow the user to then print the document out, similar to the behaviour of attempting to print web pages. 

## Actual Behavior
Upon request to print the document, instead of carrying out the expected behaviour outlined above, Min resizes the content of the PDF within the PDF viewer (as demonstrated in attached images), and does not open the system's print dialogue. The PDF preview within Min can be restored by refreshing the page.

Before requesting to print the file:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/70841501/231727034-c90521d7-9555-4892-a0bf-2a7e38f677db.png">

After requesting to print the file:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/70841501/231727118-d44efe45-4cd1-4127-970b-d17e182384e6.png">

## To Reproduce
1. Open a PDF file in Min Browser.
2. Try to print the file from inside Min Browser's PDF viewer.

**Comment by devgocri** [comment]
Forgot to mention: The page's DevTools console gives this error.

pdf_viewer.js:3996 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'style')
    at PDFPageView.cssTransform (pdf_viewer.js:3996:12)
    at viewer.js:594:28
    at viewer.js:418:15

**Comment by PalmerAL** [comment]
Fixed, thanks for reporting this.
