### ISSUE TITLE
Webcam is not working

### ISSUE THREAD

**Issue by birobirobiro** [minbrowser/min#2226]
- **Min Version: 1.27.0**
- **Operating system: macOS 13.3.1**

## Expected Behavior
Webcam works

## Actual Behavior
![image](https://user-images.githubusercontent.com/22185823/233805743-e97c31e3-f50f-4635-b296-66a47584b907.png)

## To Reproduce
- Access this site: https://webcam-capture-beta.vercel.app/
- Select the desired webcam in the input

**Comment by Oleksandr0118** [comment]
The same problem, the microphone and camera do not work in the newest version, download the previous version 1.26.0

**Comment by anhood** [comment]
See ticket 1874
https://github.com/minbrowser/min/issues/1874

**Comment by Kepler-69c** [comment]
closed as a duplicate of #1874
