### ISSUE TITLE
Update README.md to reflect current state on Arch Linux.

### ISSUE THREAD

**Issue by mortyr45** [minbrowser/min#2227]
As mentioned by the following issues: #2224 #2216 #2213, the `min` package has been dropped from the community repository on Arch Linux.

At the moment, Min is available in the AUR in two forms:
- `min` as a build from source package.
- `min-browser-bin` as a repackage from, from the official Debian package.

As multiple issues have been opened for this change, it might be good to reflect this current state on the `readme` file. If I make a pull request concerning this, would it be merged? Or if that is more appropriate, someone more involved could make this small change perhaps.

@PalmerAL I'm sorry for the direct ping, but maybe it's the most efficient if you make a decision here. :)

**Comment by PalmerAL** [comment]
Which of the two options (build from source or repackage) is more commonly used? My understanding is that the first option more closely matches how other Electron apps are distributed, but is there a reason to prefer the second one?

**Comment by Trit34** [comment]
> Which of the two options (build from source or repackage) is more commonly used? My understanding is that the first option more closely matches how other Electron apps are distributed, but is there a reason to prefer the second one?

If your PC is old enough for compiling it from the source is a big PITA (mine are both bought in 2009, and Celestia takes 5 minutes to be compiled on the most performant of the two, which has a Core 2 Quad CPU), the repackaged version would be useful, being quicker to compile and install.

**Comment by mortyr45** [comment]
As far as I know, arch prefers building from source.

As @Trit34 said, repackaging takes less resources, but if any of the packages will make it back to the official repositories, it will probably be the one built from source.

**Comment by PalmerAL** [comment]
Ok, thanks for the response! Lets go with the build-from-source option as the default in the README then.
