### ISSUE TITLE
Unconventional taskbar shortcut on windows

### ISSUE THREAD

**Issue by lampysprites** [minbrowser/min#2249]
- **Min Version: 1.27.0**
- **Operating system: Windows 10 Pro 21H2**

## Expected Behavior
Taskbar launcher turns into application icon on the taskbar after launch. It happens regardless of whether the program is started with the shortcut, or somehow else.

## Actual Behavior
Launched application becomes a new icon on task bar.

Somehow, winkey + number (here, winkey+1) still brings min window on top as expected.

## To Reproduce

- Install Min
- Open start menu, and type "min"
- Click "Add to taskbar" on the side
- Click on the new icon
- Look at it

## Screenshot
Firefox icon demonstrates correct behavior.
![image](https://github.com/minbrowser/min/assets/49268426/c7aa68f7-8b6f-4d02-9b0f-2c847d0200e5)

Thanks for your hard work.

**Comment by MohitBansal321** [comment]
@PalmerAL 
I guess its not anymore present in min

**Comment by PalmerAL** [comment]
OK, if it's not reproducible I'll close the issue. If either of you see it again let me know.
