### ISSUE TITLE
Browser doesn't fully close when trying to close (beta)

### ISSUE THREAD

**Issue by chloecdn** [minbrowser/min#2259]
- **Min Version: 1.28.0 beta**
- **Operating system: Windows/Arch Linux (present on both)**

## Expected Behavior
Browser Closes when clicking on either the X, or closing it from taskbar.

## Actual Behavior
Doesn't fully close (only the actual window closes) causing it to not open again until the task is closed manually.

## To Reproduce
- Open Browser.
- Close Browser.
- Try to re-open browser, nothing happens (Still opened in Task-Manager/htop).

## Additional Information
It seems to be an issue related to the multi-window update, because it's also an issue in both the normal and v2 mw-branches.
In the normal browser versions (before 1.28) it works perfectly fine.

**Comment by PalmerAL** [comment]
Thanks for reporting! Can you try this branch? https://github.com/minbrowser/min/tree/window-close-fix

**Comment by chloecdn** [comment]
Hey, yes, that branch fixes the issue on Windows.
I don't have an arch-os right now, so i cannot test it on arch, but i suppose it would also be fixed on that platform.

thanks!

**Comment by PalmerAL** [comment]
Thanks!
