### ISSUE TITLE
Key combo to exit (or enter) fullscreen mode

### ISSUE THREAD

**Issue by gayprogrammer** [minbrowser/min#226]
I was browsing to http://ultimatewalrus.com/ (beware if you are using min), and it automatically activates fullscreen mode when you first click on the page, but I was thereafter stuck in fullscreen mode. I am able to close the tab with the keyboard, but the browser continues to hide the menu bar (and the web page hides the tab bar while the page is open). 

Pressing the Esc key does not work. I think that other browsers (such as Chrome/Chromium) implement Esc to exit fullscreen.

I did not investigate what code the site uses, but I thought I should first address the issue with min, that there is no key-combo to handle fullscreen mode.

**Comment by vinayh** [comment]
This also occurs with YouTube videos on fullscreen. In the first few seconds afer enabling fullscreen I can usually press "F" to exit the YouTube video **if it is paused**, but after that time or if the video is playing there is no key combo I have found to exit fullscreen mode. I resort to clicking the button in the player.

**Comment by Sestowner** [comment]
This should be fixed now, feel free to reopen if it's not.
