### ISSUE TITLE
`forward button` is hide

### ISSUE THREAD

**Issue by KAROTT7** [minbrowser/min#2261]
- **Min Version: 1.28.0-beta
- **Operating system: macOS Monterey 12.4

## Expected Behavior
`forward button` is hide

## Actual Behavior
`forward button` is show

## To Reproduce
1. clone codes
2. npm install
3. npm run start
4. enter an URL

**Comment by PalmerAL** [comment]
The button should appear when you hover and there is a page to go forward to:

https://github.com/minbrowser/min/assets/10314059/2fa21fe0-0502-4b1a-9500-2db8a2fe0a5c

If you don't see that, can you post a video?

**Comment by KAROTT7** [comment]
https://github.com/minbrowser/min/assets/21054747/b3229040-6948-448e-94f3-47e71fe9d361

These are my system infos:

System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 257.70 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /opt/homebrew/opt/node@18/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn    `<- used`
    npm: 9.5.1 - /opt/homebrew/opt/node@18/bin/npm
  Browsers:
    Chrome: 114.0.5735.106
    Safari: 15.5

**Comment by PalmerAL** [comment]
No worries.
