### ISSUE TITLE
Building binaries npm run buildWindows,Error running setup

### ISSUE THREAD

**Issue by kepler820** [minbrowser/min#2268]
![QQ截图20230615144809](https://github.com/minbrowser/min/assets/136681190/1f2120e1-c00a-49da-9710-65068f55bb29)

**Comment by kaptcha0** [comment]
Same on Fedora
![image](https://github.com/minbrowser/min/assets/50426223/5bffb0b1-4e9b-4ea7-9d18-44cd37aa3cf9)

**Comment by kepler820** [comment]
did you find a solution？

**Comment by kaptcha0** [comment]
Nope

**Comment by PalmerAL** [comment]
@kepler820  - if you look in the installed directory (C:\Users...resources\app\node_modules) - do you have a `debug` module folder in there?

If I understand correctly, you're running `npm run buildWindows`, installing the result, and then running that? Does it work if you run `npm run start`?

@kaptcha0 Same question - what set of commands are you running to get this error?

**Comment by kaptcha0** [comment]
@PalmerAL Last time, I ran it with `npm run buildRedhat`, then went into the `dist/app` directory and installed the built rpm (`sudo rpm -i  ./min-1.28.0-beta-x86_64.rpm --ignoreos`). From there, I tried to launch it normally, without the CLI, but it didn't work. When I ran the `Min` command from the terminal is when I got the error mentioned above.

Running `npm run start`, however, works with no issues. I checked the `/opt/Min/resources/app/node_modules` for the `debug` directory, only to find it exists.

**Comment by kepler820** [comment]
No debug module found

`npm run start` can run

**Comment by PalmerAL** [comment]
I finally was able to build an RPM package inside a VM (it required some changes since I'm running on ARM), and it works fine for me, which isn't very helpful.

I'm assuming you both have recent versions of nodejs etc?

Has this worked in the past for you, and if so in which version?

**Comment by kaptcha0** [comment]
I'm running `Node v18.16.0`. I can't say it worked before, since this is the first time I've tried to build and run from source. The only reason I tried it is because the rpm for `Min v1.27.0` wasn't running after installation. It was always giving the same error as above.

**Comment by kepler820** [comment]
I'm also using `Node v18.16.0`
my first attempt at compiling `Min`

**Comment by PalmerAL** [comment]
Two more questions:
1. Are there any files in the `/opt/Min/resources/app/node_modules/debug/` directory? It should be like this (minus maybe readme) - are they all there?
<img width="731" alt="Screenshot 2023-06-19 at 7 11 06 PM" src="https://github.com/minbrowser/min/assets/10314059/c550a26b-80d9-4f7f-88b3-ff473de63d35">

2. If you delete all the lines starting with exclamation marks here: https://github.com/minbrowser/min/blob/master/scripts/createPackage.js#L47-L66 and then rebuild, does that help?

**Comment by PalmerAL** [comment]
That's very strange; I wonder if putting "-beta" in the version string causes problems. Anyway, glad it worked!

@kaptcha0, let me know if it's still not working for you.

**Comment by kaptcha0** [comment]
@PalmerAL Unfortunately, no. It is still not working with the same error as last time.
