### ISSUE TITLE
Fix to autohide the menubar in Linux

### ISSUE THREAD

**Issue by finnwiley** [minbrowser/min#227]
Patch: https://gist.github.com/finnwiley/d88709ed0091c70d991676e72b4d9e94

**Comment by hughwilliams94** [comment]
Great works excellently and so simple!

**Comment by baldrick-nz** [comment]
So how does one apply this patch to 1.4.1?

Thanks on advance.

**Comment by finnwiley** [comment]
@baldrick-nz First, clone this repository and download my patch into the same folder.  Next, use the command 'git apply --stat [name of patch without brackets]'.  Next, you can follow the instructions in the readme file to either test-run Min using electron, or to build a .deb package (to build .deb file, use 'grunt linuxBuild' instead than 'grunt build' recommended by the readme).

**Comment by queq** [comment]
Hey, I ran your instructions but the following error appears
`fatal: corrupt patch at line 24`

Still, I made the changes manually but can't build the packages. I did `npm install` first, then
```
grunt linuxBuild
Running "concat:browser" (concat) task
File dist/build.js created.

Running "uglify:browser" (uglify) task
>> 1 file created.

Running "concat:webview" (concat) task
File dist/webview.js created.

Running "uglify:webview" (uglify) task
>> 1 file created.

Running "concat:main" (concat) task
File main.build.js created.

Running "electron:linuxBuild" (electron) task
Packaging app for platform linux ia32 using electron v1.2.7
Packaging app for platform linux x64 using electron v1.2.7

Running "electron-installer-debian:linux32" (electron-installer-debian) task
Creating package (this may take a while)
>> Error creating package: Error reading package metadata: ENOENT: no such file or directory, open 'dist/app/Min-linux-ia32/resources/app/package.json'
Warning: Error reading package metadata: ENOENT: no such file or directory, open 'dist/app/Min-linux-ia32/resources/app/package.json' Use --force to continue.

Aborted due to warnings.
```

Am I missing something? Any help is appreciated

**Comment by finnwiley** [comment]
@queq You can fix it by renaming the 'min-linux-...' folders in dist/app so that the 'm' is captalized.
