### ISSUE TITLE
High CPU usage (80%) of Min Helper (renderer) 

### ISSUE THREAD

**Issue by dvijeniii05** [minbrowser/min#2275]
- **Min Version:**
- **Operating system:**

## Expected Behavior

I was expecting Min to optimise CPU better than chrome at least lul. However, 28 tabs of Chrome use 4% of CPU whereas 4 tabs of Min use 80% + (nothing special in the tab, notion, figma and 2 ADO's)

## Actual Behavior

Too much CPU is used by 'Min Helper (renderer)' process as can be seen on the screenshot below:

<img width="1022" alt="Screenshot 2023-07-05 at 20 05 39" src="https://github.com/minbrowser/min/assets/67027576/547c66ff-e5bc-4c7d-a933-6343c5c405b8">

## To Reproduce

Install Min Browse, open 4 Tabs, lul.

My hardware:

MacBook Pro on M1
RAM - 16GB
macOS Monterey

Any advice or help is much appreciated :)

**Comment by PalmerAL** [comment]
It's possible that one of the pages you have open is doing something weird. Start with trying to close each tab one at a time, and see if the high CPU usage disappears. If it does, does it come back when you reopen the tab?

If the high CPU remains with all of your tabs closed, go to developer > inspect browser > performance, and click the record button. Wait ~10 seconds, then stop the recording, click export (upwards arrow in the top-left corner), and upload the file here. Thanks!
