### ISSUE TITLE
Paste and match style

### ISSUE THREAD

**Issue by devgocri** [minbrowser/min#2283]
Hey I would really love it if you could add the "Paste and match style" which the other browsers have :D

<img width="242" alt="image" src="https://github.com/minbrowser/min/assets/70841501/a5cb607e-b867-4720-8dc7-b882d16935b7">

**Comment by sndrkrly** [comment]
What is this for?

**Comment by devgocri** [comment]
@sndrkrly It's basically for pasting clipboard content without formatting.

For example, if you're copying and pasting a ChatGPT response into Google Docs, if you paste normally, it will paste with the grey background, a different font, font size and color. If you use paste and match style instead, it will use the font, color and size the text in the document already has.
