### ISSUE TITLE
Error message on start

### ISSUE THREAD

**Issue by baldrick-nz** [minbrowser/min#229]
Hi all,

Using Min 1.4.1 on LM17.3 64bit, I get this pop up message more often than not on starting Min.

`A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Cannot read property 'length' of undefined
    at matchesFilters (/usr/share/min/resources/app/ext/abp-filter-parser-modified/abp-filter-parser.js:408:43)
    at Object.matches (/usr/share/min/resources/app/ext/abp-filter-parser-modified/abp-filter-parser.js:505:9)
    at Function.handleRequest (/usr/share/min/resources/app/main.build.js:576:16)`

I have to clear several instances before Min bemomes usable. 

To clarify, Min does start, but intill I clear the pop-ups, I can browse anywhere.

Cheers.

**Comment by PalmerAL** [comment]
It appears that network requests are being made before the content blocking filters have loaded, which causes this issue.

**Comment by code-hunger** [comment]
@PalmerAL, Is this the function which checks the filters for each request? If so, then it should be trivial to fix this.

https://github.com/minbrowser/min/blob/212fb573da11862ffd4ae941b8b0fd71eef0471f/ext/abp-filter-parser-modified/abp-filter-parser.js#L580-L585

I got this error, too, a few minutes ago.

**Comment by PalmerAL** [comment]
@code-hunger Yes, it is. You're right that fixing this should be fairly easy, I'll add a fix right now.
