### ISSUE TITLE
Cmd+A is recognised as cmd+Q when using AZERTY layout.

### ISSUE THREAD

**Issue by britthubs** [minbrowser/min#2301]
- **Min Version:**
Version 1.28.1 (1.28.1)
- **Operating system:**
macOS 13.4.1 

## Expected Behavior
When using cmd + A to select all text in a text box, it selects all of the text. (using a keyboard with AZERTY layout)
## Actual Behavior
When using cmd + A to select all text in a text box, Min quits. (the cmd + A somehow performs as cmd + Q, as if it suddenly recognises the keyboard as QWERTY)
## To Reproduce
Using an AZERTY layout, stand in a text input field. (For example text input field for a username on a login screen)
- type something
- press cmd + A to select all text
- watch min perform the cmd + Q command instead

**Comment by PalmerAL** [comment]
Thanks for reporting. I think I've fixed this here: https://github.com/minbrowser/min/tree/keyboard-layout-fix, if you have a chance could you try running it with the instructions in the readme?

**Comment by britthubs** [comment]
That appeared to have fixed it, thanks! :)

**Comment by PalmerAL** [comment]
Thanks!
