### ISSUE TITLE
What kind of kernel browser is this? Is it Chrome or Firefox?

### ISSUE THREAD

**Issue by FanXiangTM** [minbrowser/min#2308]
What kind of kernel browser is this? Is it Chrome or Firefox?

**Comment by PalmerAL** [comment]
It's Chromium (Electron).

**Comment by ioc2e3** [comment]
Sorry,can't find a place to ask...

Why WebKit-based browsers

Not running on Windows anymore?

**Comment by PalmerAL** [comment]
> Why WebKit-based browsers Not running on Windows anymore?

* Chrome is the most popular browser, you get better site compatibility by using it.
* My understanding is that Chrome is easier to embed in an application than webkit. We use ElectronJS, which combines native APIs and Chromium to let us make this app; there isn't an equivalent project for webkit.
