### ISSUE TITLE
Ctrl-a makes min browser quit

### ISSUE THREAD

**Issue by NBaH2** [minbrowser/min#2317]
- **Min Version: 1.28.1**
- **Operating system: Arch Linux \ Xorg (fr-latin9) spectrwm**

## Expected Behavior
select all
## Actual Behavior
quits min browser
## To Reproduce
hit Ctrl-a

I tried to select all from a web page as I do  on any other window.
Ctrl-q makes min quit too.

**Comment by PalmerAL** [comment]
Thanks for reporting. This was reported in #2301 already, and will be fixed in the next release.
