### ISSUE TITLE
(Right click menu) Add option to "Copy image"

### ISSUE THREAD

**Issue by outwork** [minbrowser/min#232]
The title says everything. Can you add this feature? It would be awesome.

**Comment by PalmerAL** [comment]
Electron <a href="https://github.com/electron/electron/pull/6619">Just added</a> an API to do this, so it shouldn't be too difficult.

**Comment by PalmerAL** [comment]
I completely forgot about this issue, but it's finally fixed: 8077d4032baf38dbf21a4b5d96fe8ce91e228709.
