### ISSUE TITLE
Deb package depends on gconf2 and gconf-service

### ISSUE THREAD

**Issue by crshrprt** [minbrowser/min#2324]
- Min Version: 1.29.0
- Operating system: Debian Sid (unstable)

Min .deb package is not installable anymore on Debian testing and unstable since gconf2 and gconf-service have been removed from the repos: [gconf](https://tracker.debian.org/pkg/gconf).

**Comment by PalmerAL** [comment]
Looking at https://github.com/electron/electron/issues/2727, it seems there's no replacement needed and we can just remove it from the requirements. Do you know if that's correct?

**Comment by crshrprt** [comment]
I don't know if that's correct (I'm not a dev), but seeing what others project are doing it seems to be the case.

**Comment by PalmerAL** [comment]
Great, thanks for testing, I've made that change.
