### ISSUE TITLE
My changes not included in buildWindows

### ISSUE THREAD

**Issue by tahaontech** [minbrowser/min#2338]
- **latest Min Version:**
- **Windows 11**

I use your source code for a university project and I have a problem with the build.

I added a few lines of code and a few events inside 'viewManager.js' these changes work perfectly in development but when I build the app with buildWindows command these changes do not work in production.

**Comment by PalmerAL** [comment]
That's strange; what's the exact sequence of steps you're performing?

**Comment by mohammadhasanii** [comment]
> That's strange; what's the exact sequence of steps you're performing?

For example, I used axios and I am making a request to a certain place, but no request is given at all. Of course, I use const. Is it because of this?

**Comment by PalmerAL** [comment]
Are you related to the issue author?

Anyway, 1) how are you compiling and installing the app - are you sure you're running the version with your changes? 2) try opening the browser dev tools (inspect browser) and debug what's happening.

**Comment by mohammadhasanii** [comment]
fixed.
I found the problem. Thank you for your answer

**Comment by mohammadhasanii** [comment]
You can done the issue
This is my friend's account
We are both working on a project
