### ISSUE TITLE
Ubuntu Ubuntu 22.04.3 LTS new version is not working

### ISSUE THREAD

**Issue by pawelzjezdzalka** [minbrowser/min#2339]
- **Min Version: min-1.29
- **Operating system:22.04.04 LTS

## Actual Behavior

After installing with sudo apt install min-1.29.amd64.deb (I tried also with sudo dpkg -i ... and the result is the same) I can't use min. It colapses when I trie to use it e.g.: I tire to click on tab / write some url adress and min stops to respond. Version min-1.28.1 works perfect.

**Comment by PalmerAL** [comment]
I think this is the same problem as #2321. If you're able to, could you try the instructions there to install a newer Electron version, and see if that helps?
