### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by LucasBoberg** [minbrowser/min#235]
### First of love the min browser!

But there are some features I would love to have.
First of I would love to have a back and forward button in the navbar so I don't have to use the keyboard and correct me if I'm wrong but there seemes like there already is a function to do that and the only thing left for it to happen is just to map it to a button in the navbar. I thought that if there is a reason for it to not be there would it not be possible the make it a choice in the settings to display it or not.

The second thing is I would love there to be support for both WidevineCdm and flash, and I found [link about WidevineCdm](https://github.com/electron/electron/blob/master/docs/tutorial/using-widevine-cdm-plugin.md) and [link about Flash](https://github.com/electron/electron/blob/master/docs/tutorial/using-pepper-flash-plugin.md), what I understand it would not be super hard to implement, but I know next to nothing about electron so I might be wrong.

Thank you for taking my suggestion into consideration.

**Comment by PalmerAL** [comment]
> there already is a function to do that and the only thing left for it to happen is just to map it to a button in the navbar

That's correct. Mainly the reason to not have it was to not add extra clutter to the navbar, but I can definitely see how it would be useful, and it's probably something that should be added.

I'm not sure implementing Flash is a good idea. Flash is slow and insecure, and both Firefox and Chrome are planning to remove it. #192 has more information on this.

Implementing widevine makes sense, but I'm not sure what the licensing on widevine is. According to the Electron docs, "Electron doesn't ship with the Widevine CDM plugin for license reasons", so I"m not sure that Min is able to either.

**Comment by wb9688** [comment]
If you add WideVine, can you also make a WideVine-less download?

**Comment by PalmerAL** [comment]
@wb9688 Sure. Alternatively, Widevine could be an optional download, with a prompt to download it when you visit a site that uses it.

However, I don't think Widevine support will be added anytime soon, since it's unclear what the licensing is.

**Comment by rtauziac** [comment]
Having navigation buttons will be very useful for sure, but I would like it to be a setting. I love when Min is displaying minimal UI. We still have `⌘+←` or `!back` and the swipe from left for navigation, which I think is way sufficient.

**Comment by Syndamia** [comment]
Closing this issue since:
1. Forward button development is worked on in #1646, and currently awaits merge of #1665
2. DRM is mainly discussed in #641
3. Flash support has been [completely removed from Chrome since January 2021](https://www.chromium.org/flash-roadmap#TOC-Flash-Support-Removed-from-Chromium-Target:-Chrome-88---Jan-2021-) and [Electron follows](https://github.com/electron/electron/blob/main/docs/tutorial/using-pepper-flash-plugin.md#using-pepper-flash-plugin).
