### ISSUE TITLE
Extention and Translation

### ISSUE THREAD

**Issue by oneoff23** [minbrowser/min#2354]
Hello, I would love to translate your browser to other languages to help you guys reach a broader user audience.  Don't hesitate to contact me if you require my help in this regard. 

Quastion about extention. 

Is there an extension support for min browser and if so where and how can I get extensions?

**Comment by PalmerAL** [comment]
> Hello, I would love to translate your browser to other languages to help you guys reach a broader user audience. Don't hesitate to contact me if you require my help in this regard.

We take community contributions for translations; if you're interested in doing that, there are instructions listed here for how you can contribute: https://github.com/minbrowser/min#contributing-translations. However, we're not able to pay for professional translations at this time.

> Is there an extension support for min browser and if so where and how can I get extensions?

There's no extension support, but we do support userscripts, which can do some of the same things: https://github.com/minbrowser/min/wiki/userscripts
