### ISSUE TITLE
Move tab to a new window

### ISSUE THREAD

**Issue by Apis035** [minbrowser/min#2357]
Hi!
First of all, thank you for creating this browser! I found this project after the recent update to Chrome that makes the UI wide, more rounded, and eats a bit more of vertical space and driven me to search for an alternative with minimal-looking interface.

One particular issue I had after using this for several days is the inability to split/ move tab into a new window. On Chrome and other browsers, this behaviour can be achieved by dragging a tab up/down from the tabs row and it will be placed into a new window.

I have looked at the preferences settings and the wiki for a way to doing this but found none. Is this feature not supported (yet)?

**Comment by PalmerAL** [comment]
The current way to do this is sort of roundabout:

1. Open a new window
2. Open the task overlay
3. Drag the tab from the old window's task to the new window's task

Electron doesn't have good APIs for dragging, so I think that will be difficult to support. What do you think about a context menu (right-click on the tab > "move to new window")?

**Comment by Apis035** [comment]
I think a context menu is better. Something like "Right click on a tab > Move tab to task/window 1/2/3/4"
