### ISSUE TITLE
Mouse interaction completely blocked on https://djblue.github.io/portal

### ISSUE THREAD

**Issue by adamdavislee** [minbrowser/min#2361]
## Problem

Very strangely, the mouse doesn't work on this site, full stop.  It's as though the mouse events are being sent straight through to the browser window (as in the OS window), itself.

## Repro

1. Open [djblue.github.io/portal](djblue.github.io/portal)
2. Try to click _anything_

## System

<img width="257" alt="image" src="https://github.com/minbrowser/min/assets/8780347/e2ebe674-ad11-44ac-bad3-1b0e940f40ce">

**Comment by PalmerAL** [comment]
For some reason, they have this CSS on the root element:

```
.G__5 {
  -webkit-app-region: drag;
```

In Chrome, this does nothing, but in Electron, this turns the element into a dragging handle for the window instead. (It's probably not ideal that we expose this to webpages, but I don't think it's actually a problem, and I don't see an option in Electron to turn it off).

Perhaps open an issue with the author?

**Comment by adamdavislee** [comment]
Ope!  Completely missed your reply.

Ahh… so that's why.  Thanks, @PalmerAL.

> Perhaps open an issue with the author?
Dumb question—who's the "author"?  Is this not the minbrowser source repo?

**Comment by PalmerAL** [comment]
Oh, I mean the author of the website, to ask them to change their CSS: https://github.com/djblue/portal/issues

**Comment by adamdavislee** [comment]
Oh!  I understand now, thank you 👍

**Comment by adamdavislee** [comment]
Would you like me to close this issue?

**Comment by PalmerAL** [comment]
Sure, I don't think we're going to be changing anything with this.
