### ISSUE TITLE
Drag min window randomly not working at all

### ISSUE THREAD

**Issue by RobinRuf** [minbrowser/min#2367]
- **Min Version:** 1.31.0
- **Operating system:** MacOS 14.1.1

## Expected Behavior
The min browser window should be able to drag (relocate) freely.

## Actual Behavior
Sometimes, pretty random, I am unable to drag the browser window and change its position at all.
Today, I got this behavior after restarting my macbook, a few days ago I got this after logging back in (before in sleep mode), but sometimes also without doing something (the whole time in the min browser).

## To Reproduce
Unfortunately, because it appears not everytime in the same scenario, I am not sure what's wrong or how to reproduce this.. Does nobody else got this behavior, because I didn't see any open issues about this specific bug? 

Sometimes it is enough to quit and reopen the app. Sometimes it is even possible to solve this bug by minimize and re-open it. Sometimes it needs a restart of the system. And sometimes, like now, I can do whatever I want and nothing seems to be helpful.

**Comment by PalmerAL** [comment]
Silly question perhaps, but which part of the window are you dragging? There's an invisible line separating the draggable from the non-draggable area; the draggable regions are these:

![Screenshot 2024-01-13 at 8 58 56 AM](https://github.com/minbrowser/min/assets/10314059/8ae5d61e-9839-47ec-96ab-2988c3603533)

**Comment by RobinRuf** [comment]
> Silly question perhaps, but which part of the window are you dragging? There's an invisible line separating the draggable from the non-draggable area; the draggable regions are these:
> 
> ![Screenshot 2024-01-13 at 8 58 56 AM](https://private-user-images.githubusercontent.com/10314059/296498682-8ae5d61e-9839-47ec-96ab-2988c3603533.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxNjU0MTYsIm5iZiI6MTcwNTE2NTExNiwicGF0aCI6Ii8xMDMxNDA1OS8yOTY0OTg2ODItOGFlNWQ2MWUtOTgzOS00N2VjLTk2YWItMjk4OGMzNjAzNTMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDE2NTgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1YjdlOWVlM2FiMWU2ZGRlNzg2NWMzZjc1MTExMmQxMWExNjkyNDJiMjU2MDlhYTNhNmY5MGZmYzc3NGYwY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CR5RSqQclb97BgHme-42_cPOv1KeAX1gw3E9vL20kH8)

I know, I always use the top left part next to the buttons to move the window around.\
Also interesting is, that if I try to drag the window directly in the edge, where I normally would resize it, I can resize it, but if I drag into the opposite direction (in which you should not can to resize (on the left edge, drag to top or bottom instead of to the left or right to resize)), then I can move the window. But just there and with this method.

<img width="188" alt="Screenshot 2024-01-13 at 18 02 49" src="https://github.com/minbrowser/min/assets/39103327/46c012f2-ab30-4c24-bae1-3d1bb6be6f64">

**Comment by Jagoche** [comment]
Same problem here... Suddenly I cannot drag the Min window any longer.
Min: 1.31.1, Mac OS: 10.15.7

**Comment by bogdanmaris** [comment]
Windows 11 is also affected by this, can't seem to drag the window with min-1.31.0. Don't know if it ever worked or not, I freshly installed Min to give it a go.

**Comment by PalmerAL** [comment]
For anyone with this issue (either on macOS or Windows), could you try this if you have a chance:

1. Install nodejs, clone the Min repository, and run `npm install`.
2. Run `npm install electron@29.0.0-alpha.7`
3. Run `npm run start` and see if you can drag the window.

Thanks!

**Comment by VoxAndrews** [comment]
There also seems to be an issue on Ubuntu 22.04.3 (Under VirtualBox 7.0.10 r158379 (Qt5.15.2)), although I am unsure if this is to do with VirtualBox or how I have Ubuntu configured. Will try to test on hardware soon to see if this is just a VirtualBox thing or not, although dragging worked in the previous version

**Comment by RobinRuf** [comment]
> For anyone with this issue (either on macOS or Windows), could you try this if you have a chance:
> 
> 1. Install nodejs, clone the Min repository, and run `npm install`.
> 2. Run `npm install electron@29.0.0-alpha.7`
> 3. Run `npm run start` and see if you can drag the window.
> 
> Thanks!

Hey @PalmerAL, tried that.
I cannot tell if this will fix the problem permanently, because I also sometimes can drag the Min browser as expected and 5 mins later, it doesn't work anymore - but yeah, after the start, I tested it out a bit with minimize, maximize, opened a few tabs, switched tasks and so on, and the drag action still worked.

So maybe this could solve the problem, but you only can tell if a fix is a permanently fix after a few weeks of testing.

Quick side note: We (I think this works for everyone) still can drag the min browser. But just at the edges, when the cursor changes to the "resize"-cursor, when you drag then in the opposite direction (so if you try it on the top or bottom edge and drag it in vertical direction for example) you can drag the browser instead of resize. So it is still possible - but this should not be the only way we can drag it, of course. Just as a small side info.

**Comment by PalmerAL** [comment]
@RobinRuf Thanks for testing that.

I've published a new release that downgrades Electron to the last-working version. This should at minimum fix the issue that several people have reported that window dragging does not work at all on Windows or Linux.

Since the issue on macOS is reported to be intermittent, I'm not sure if it's the same root cause or not. However, downgrading Electron also fixes the issue for me, so I believe it is.

There is currently a PR open in Electron to address this issue: https://github.com/electron/electron/pull/41030
Once this is merged, I am hopeful that both issues will be fixed.

Thanks everyone for reporting this.

**Comment by RobinRuf** [comment]
> @RobinRuf Thanks for testing that.
> 
> I've published a new release that downgrades Electron to the last-working version. This should at minimum fix the issue that several people have reported that window dragging does not work at all on Windows or Linux.
> 
> Since the issue on macOS is reported to be intermittent, I'm not sure if it's the same root cause or not. However, downgrading Electron also fixes the issue for me, so I believe it is.
> 
> There is currently a PR open in Electron to address this issue: [electron/electron#41030](https://github.com/electron/electron/pull/41030) Once this is merged, I am hopeful that both issues will be fixed.
> 
> Thanks everyone for reporting this.

Thank you @PalmerAL, for now, it seems that this solves the issue on macOS too.
I tried it now for a few hours and it looks good till this moment.
So, I think I can close down this issue.
