### ISSUE TITLE
Cannot Download PDF from Min Browser - Windows 11

### ISSUE THREAD

**Issue by VoxAndrews** [minbrowser/min#2369]
- **Min Version:**
1.31.0

- **Operating system:**
Microsoft Windows 11 Pro (Version 10.0.22621, Build 22621)

## Expected Behavior
When I click on the download button in the bottom right corner, it should open the file browser, allow me to select where I want the file to go and download it.

## Actual Behavior
When I click on it, my setting for the background colour just reverts back to white, and the download doesn't start. This continues to happen and I cannot download a PDF.

https://github.com/minbrowser/min/assets/26544407/42816f77-9d0c-420a-9391-78a44fc0f6ac

## To Reproduce
1. Open Min Browser
2. Navigate to a PDF Page
3. Try to download the PDF (It does not seem to matter what type of PDF it is, it will not download, and I have confirmed these files download in other browsers)

**Comment by PalmerAL** [comment]
Thanks for reporting! I've fixed this in fbab15afea43577fc500eb01d97dcd71e9a58e2f; I'll post a new release within the next few days.
