### ISSUE TITLE
Window refuses to move

### ISSUE THREAD

**Issue by sage-etcher** [minbrowser/min#2373]
- **Min Version:** 1.31.0
- **Operating system:** Windows 10

## Expected Behavior

When the application is in windowed mode, the window should move when you click and hold on the top padding.

## Actual Behavior

The window stays put and does nothing. As of the most recent update, the browser resizes fine, but refuses to move.

## To Reproduce

1. Run Windows 10 
2. Open the browser 
3. Make sure you are in windowed mode 
4. Try to move it

## Demo

https://youtu.be/os4rhnzgLvg

**Comment by PalmerAL** [comment]
I'm assuming you figured this out since you closed the issue, but updating to 1.31.1 will fix this. Sorry for the trouble.

**Comment by sage-etcher** [comment]
> I'm assuming you figured this out since you closed the issue, but updating to 1.31.1 will fix this. Sorry for the trouble.

yes I did, thank you
