### ISSUE TITLE
Blank Tab when opening github repo page

### ISSUE THREAD

**Issue by iambudi** [minbrowser/min#2377]
- **Min Version:** Version 1.31.1 (1.31.1)
- **Operating system:** macOS Sonoma 14.3

## Expected Behavior
Display github page normally
## Actual Behavior
When navigating to github pages often time min tab just blank, i though this was my internet connection but opening in another browser the issue does not exist. This happened since two days ago. I don't know if there's update in github that prevent min to correctly render the page.
## To Reproduce
Just open any kind of github page, navigate several source pages.

**Comment by iambudi** [comment]
I can add more info, in worse case when switching to tab with any github page, it's blank automatically and min browser can't even be closed unless i do force quit. The page back to normal after restart. After sometimes, it would be blank again.

**Comment by flightmansam** [comment]
I also had this issue. No matter what I did anything on Github would quickly show the page and then be completely blank white. I downgraded to the latest stable electron (23.2.1) and this issue went away (I think? will edit if it does)

**Comment by PalmerAL** [comment]
@flightmansam If you switch to the latest 29.x Electron (currently 29.0.0-beta.5), what happens?

I have almost the same configuration (still on macOS 14.2) and I haven't seen this ever. I wonder what the difference is.

**Comment by flightmansam** [comment]
> @flightmansam If you switch to the latest 29.x Electron (currently 29.0.0-beta.5), what happens?
> 
> I have almost the same configuration (still on macOS 14.2) and I haven't seen this ever. I wonder what the difference is.

Aaaah this was a red herring. I’ll send more info when I can.

**Comment by J-Siu** [comment]
I ran into this today and it is getting more strange now.

Part 1:

I installed Min through brew and properly went through a update.

I have the following in customFilter.txt:

```txt
@@||https://accounts.google.com/v3/signin/_/AccountsSignInUi/browserinfo
@@||https://www.googleapis.com/
```

If I comment or remove the second line, github.com load normally.

Part 2:

I just try reinstalling Min doing following:
1. brew uninstall min
2. rm -rf `~/Library/Application Support/Min`
3. brew install min
4. Open Min and go to github.com <-- Issue happen without customFilter.txt

So github.com flash to white before any customization or visiting any other website.

Is there any other folder I can delete other than "~/Library/Application Support/Min"?

**Comment by PalmerAL** [comment]
> Is there any other folder I can delete other than "~/Library/Application Support/Min"?

No, that has everything.

This is very strange. @flightmansam Did you figure out anything else?

**Comment by flightmansam** [comment]
Haven’t found it yet. I’ll start by going from a version of min that I know didn’t have this effect (although it could be something new on the github side of things too?).

**Comment by J-Siu** [comment]
I cloned the repo, switched to tag v1.31.1 and followed readme to do the test, following is output when I go to github.com:

```txt
js@mba2 2024-02-5 14:15:45.607 ~/code/test/min ‹ec5bf358›
$ npm run start

> min@1.31.1 start
> npm run build && concurrently "npm run watch" "npm run startElectron"


> min@1.31.1 build
> npm run buildMain && npm run buildBrowser && npm run buildBrowserStyles && npm run buildPreload


> min@1.31.1 buildMain
> node ./scripts/buildMain.js


> min@1.31.1 buildBrowser
> node ./scripts/buildBrowser.js


> min@1.31.1 buildBrowserStyles
> node ./scripts/buildBrowserStyles.js


> min@1.31.1 buildPreload
> node ./scripts/buildPreload.js

[1]
[1] > min@1.31.1 startElectron
[1] > electron . --development-mode
[1]
[0]
[0] > min@1.31.1 watch
[0] > node ./scripts/watch.js
[0]
[1] [0205/141623.994284:WARNING:in_range_cast.h(38)] value -634136515 out of range
[1] [18340:0205/141623.837906:ERROR:ax_object.cc(3073)] Check failed: !IsMissingParent(). Missing parent: "\"Dialog\" axid#1697 node#48 <dialog.Overlay Overlay-whenNarrow Overlay--size-medium Overlay--motion-scaleFade#custom-scopes-dialog> isIgnored isHiddenViaCSS #children=3 hasDirtyDescendants isMissingParent missingLayout"
[1] [0205/141624.153022:WARNING:in_range_cast.h(38)] value -634136515 out of range
```

**Comment by PalmerAL** [comment]
> [1] [18340:0205/141623.837906:ERROR:ax_object.cc(3073)] Check failed: !IsMissingParent(). Missing parent: "\"Dialog\" axid#1697 node#48 <dialog.Overlay Overlay-whenNarrow Overlay--size-medium Overlay--motion-scaleFade#custom-scopes-dialog> isIgnored isHiddenViaCSS #children=3 hasDirtyDescendants isMissingParent missingLayout"
> [1] [0205/141624.153022:WARNING:in_range_cast.h(38)] value -634136515 out of range

Ah, thanks; it's crashing when accessibility support is enabled. I can reproduce this if I turn VoiceOver on.

If you don't have VoiceOver on, you probably have another application running that has accessibility permissions. You can find out in system settings > privacy > accessibility.

At least for me, upgrading to Electron 29.0.0-beta.5 fixes the crash. @J-Siu Can you try that as well? In the repository, open `package.json`, find-and-replace `29.0.0-alpha.7` with `29.0.0-beta.5`, then run `npm install && npm run buildMacIntel` (or `buildMacArm`) and see if running that binary fixes it.

**Comment by J-Siu** [comment]
> If you don't have VoiceOver on, you probably have another application running that has accessibility permissions. You can find out in system settings > privacy > accessibility.
> 

I remember I turned on a few things due to others apps/tool. But I forget exactly which one I turned on manually.

> At least for me, upgrading to Electron 29.0.0-beta.5 fixes the crash. @J-Siu Can you try that as well? In the repository, open `package.json`, find-and-replace `29.0.0-alpha.7` with `29.0.0-beta.5`, then run `npm install && npm run buildMacIntel` (or `buildMacArm`) and see if running that binary fixes it.

Yes. That fixed the issue.

**Comment by Faetu** [comment]
So, I need to install min from the source code instead of homebrew to get github showing up?
Is there a fix on the way?

**Comment by PalmerAL** [comment]
You could either install from source and build with a newer Electron version (the instructions above), or disable any applications using accessibility permissions (by looking in the macOS settings).

I'll make a new release soon.

**Comment by J-Siu** [comment]
A "side" question: Why github.com trigger this and not other web site?

**Comment by PalmerAL** [comment]
I assume something specific to the way they have the dialog element set up triggers this. The markup is quite complex - the `<dialog>` element is wrapped in multiple custom elements, each of which have various callbacks attached to them. And using a dialog element already isn't super common. I spent a little bit of time trying to write a testcase for this but wasn't able to. If it comes back in a future Electron version I'll try harder :)

**Comment by iambudi** [comment]
I don't see the issue on latest version of Min. So far so good. I can close the issue. 

Thank you so much @PalmerAL
