### ISSUE TITLE
Min new tab page is white.

### ISSUE THREAD

**Issue by rafsanislam09** [minbrowser/min#2378]
Hello, I am new in Min. I saw that the new tab page is just white. I got no option in settings so I've decided that I will edit build Min from source. But the problem is that i am feeling difficulty where is the exact new tab page. If anyone could help with it, i would like to design a new tab page for Min. Thank you!

**Comment by PalmerAL** [comment]
You could change this line: https://github.com/minbrowser/min/blob/master/js/tabState/tab.js#L15

To:
```
tab.url || "<new tab url>"
```

Also, you can set an image background if you want - there's a camera button in the bottom-right corner of the new tab.

**Comment by rafsanislam09** [comment]
Thank you. I am currently developing new tab page, and hoping I will commit this change in the repository, so everyone could use it.
