### ISSUE TITLE
Can't disable spell check

### ISSUE THREAD

**Issue by nightingale1917** [minbrowser/min#2379]
I'm from Brazil and I write, mostly, in portuguese. Min has a spell check but it doesn't appear on preferences or any other place (or, at least, I haven't found it). I need to disable it or at least change to a portuguese dictionary.
That's my only issue 'til now. I really like the browser.

Thanks for everything!

**Comment by PalmerAL** [comment]
Which language(s) do you have configured in your OS, and which languages does the spellcheck work in?

I think that by default, the spell checking should follow the same language settings as your OS, so I'm wondering if that's working or not.

**Comment by nightingale1917** [comment]
Portuguese. Tried tweaking on OS configs but Min haven't changed.

Em sex., 2 de fev. de 2024 às 02:01, PalmerAL ***@***.***>
escreveu:

**Comment by PalmerAL** [comment]
Does your OS display the UI in Portuguese or English? Which OS is this?

**Comment by nightingale1917** [comment]
My OS displays on english, but I write mostly in portuguese. It's Windows
11.

Em sex., 2 de fev. de 2024 às 14:46, PalmerAL ***@***.***>
escreveu:

**Comment by PalmerAL** [comment]
OK, thanks. One more question: can you go here: https://jsfiddle.net/9jp24ohx/, and tell me what the output in the bottom-right box is?

**Comment by nightingale1917** [comment]
It was that, Palmer. Because the UI was in english, the spell checker on
the app also was. Although, I wish that you could choose the language of
the spell checker directly on the app, or could disable it in the app.
Well, the issue is solved! Thank you for your help. A great weekend to you!

Em sáb., 3 de fev. de 2024 às 02:24, PalmerAL ***@***.***>
escreveu:

**Comment by PalmerAL** [comment]
Great!

I'm not planning to add app language settings right now, but will keep that in mind.
