### ISSUE TITLE
Extensions - Dashlane/vimium/devtools

### ISSUE THREAD

**Issue by tommdq** [minbrowser/min#2380]
Hey there! I was checking Min and loved it! I was wondering if there was extensions support on 2024 roadmap or if is there any workaround to get some devtools extensions, vimium or dashlane ( password manager ) working in min.

Thanks!

**Comment by PalmerAL** [comment]
There's no plans for extensions support; really it's only going to happen if someone volunteers to build it (it's a ton of work to implement and maintain). However, there is a userscript you can install that does many of the same things as vimium: https://github.com/palmeral/min-vim-mode
