### ISSUE TITLE
Bookmark key command in main dropdown menu is incorrect

### ISSUE THREAD

**Issue by cOborski** [minbrowser/min#2381]
![Screenshot 2024-02-01 145304](https://github.com/minbrowser/min/assets/5460210/53637c09-73b7-4f19-bf13-505c520b95b1)

## System
I'm using the latest version of Min on Windows 11

## Issue
- `control + b` does not open bookmarks (fill in !bookmarks)
- `control + shift + b` does
- The [keyboard shortcuts page](https://github.com/minbrowser/min/wiki#keyboard-shortcuts) also lists `control + b` as the bookmarks shortcut, ~~but it is missing a reference to using `control + shift + h` to open history~~

**Comment by cOborski** [comment]
I added the history action and the `mod` `shift` `h` keyboard shortcut to the table on the [keyboard shortcuts page](https://github.com/minbrowser/min/wiki#keyboard-shortcuts).

I didn't change the keyboard shortcut listed for bookmarks though, because I'm not sure what the intended shortcut is supposed to be.

**Comment by PalmerAL** [comment]
I think it's supposed to be `shift+ctrl+b`: https://github.com/minbrowser/min/pull/1473#issuecomment-772690305

**Comment by PalmerAL** [comment]
PR to fix the inconsistency: #2383

**Comment by PalmerAL** [comment]
Thanks for reporting this.
