### ISSUE TITLE
Allowing Google sign in customFilters.txt stop github.com from loading

### ISSUE THREAD

**Issue by J-Siu** [minbrowser/min#2385]
- **Min Version:**
1.31.1

- **Operating system:**

macOS 14.2.1

## Expected Behavior
github.com load normally

## Actual Behavior
Min just display a white page and can't even open inspector.

## To Reproduce

1. Add following line in customFilters.txt
```txt
@@||https://accounts.google.com/v3/signin/_/AccountsSignInUi/browserinfo
@@||https://www.googleapis.com/
```
2. Restart Min
3. Go to https://github.com/

The two lines are for allowing webapp that use google login.

The issue is caused by the 2nd line `@@||https://www.googleapis.com/`. Once that line is in, github.com no longer load.

**Comment by PalmerAL** [comment]
Thanks for the detail. Unfortunately I can't reproduce with those steps, on either the logged-in or logged-out homepages. Are there any other settings you have that are different from the defaults?

This has been reported by other people as well: #2377. @iambudi @flightmansam do you have any similar content blocking rules set up?

**Comment by J-Siu** [comment]
It look exactly the same. I will close this continue in #2377. Thank you!!

**Comment by J-Siu** [comment]
It look exactly the same. I will close this continue in https://github.com/minbrowser/min/issues/2377. Thank you!!
