### ISSUE TITLE
Permission pop up for Google Meet or Zoom not Showing

### ISSUE THREAD

**Issue by agimbudiman** [minbrowser/min#2387]
Hi i've been using the latest version of Min browser but i found this permission icon not showing when im using Meet or Zoom, but its showing in another link or other website that uses camera and microphone, how i can fix this?

**Comment by aiyagari** [comment]
This used to work -- but now for some reason the little icon in the title bar showing the camera and microphone doesn't show, so there's no way to trigger the permission request.

**Comment by Kepler-69c** [comment]
duplicate of #1874
