### ISSUE TITLE
Ctrl + '+' Keybinding is not working.

### ISSUE THREAD

**Issue by JaySabva** [minbrowser/min#2389]
- **Min Version:**
- **Operating system:**

## Expected Behavior
Ctrl + '+' should Zoom in page.
## Actual Behavior
but Ctrl + '+' is not doing anything even after Pressing Ctrl + '-' Zoom Out and then even.

**Comment by PalmerAL** [comment]
I think I have a fix for this: https://github.com/minbrowser/min/tree/alt-zoom-shortcut
