### ISSUE TITLE
This is not an issue, but a thank you

### ISSUE THREAD

**Issue by papioara** [minbrowser/min#2398]
A big Thank You for Min to the develpers. I am just testing it out of curiosity, and all I can say is that I am very happy with it. Once you have learned to operate Min which is different from what you are used to from other current browsers in order to keep the interface clean and lean, Min provides a wonderfully relaxed browsing experience: no ads at all, just the content you want to see. Fantastic! And fast it is, too!

**Comment by PalmerAL** [comment]
Thank you!
