### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by dabeegmon** [minbrowser/min#241]
Just found you - - - so far so good.
Looking for an alternative to FF as its driving me absolutely bannanas!!
Two things - - - is there any way to keep a window to part of a screen?
   I have a window that spans 2 screens and that makes for awkward reading and would appreciate this         different.
Secondly - - I have found that I use a 'save page as' function a lot. Its a great way of archiving information.
Is there any way that this could be included?
TIA

**Comment by PalmerAL** [comment]
Hi, sorry for the late response.

> is there any way to keep a window to part of a screen?

Can you explain this a bit more? You should be able to resize the window to any size you want, just like any other application. Do you mean the ability to view multiple tabs next to each other?

> Secondly - - I have found that I use a 'save page as' function a lot. Its a great way of archiving information.
> Is there any way that this could be included?

It definitely could. Actually, Min already saves every page you visit, so I'm wondering if this could be a feature in Min. How do you typically use this feature (how do you organize saved pages, etc.)? Is the benefit to saving pages that you can organize important pages, that you can see what content a page had at a certain point in time, or something else?

**Comment by dabeegmon** [comment]
On Wed, Aug 24, 2016 at 8:07 PM, PalmerAL <notifications@github.com> wrote:

> Hi, sorry for the late response.
>
> is there any way to keep a window to part of a screen?
>
> Can you explain this a bit more? You should be able to resize the window
> to any size you want, just like any other application. Do you mean the
> ability to view multiple tabs next to each other?
>
I have 4 monitors, 3 landscape and 1 portrait. Portrait for pdfs and the
other 3 for whatever. They are arranged as 2 virtual screens, 1 is 3840 (h)
x 1020 (IIRC v) and the other is 3000 (h) x 1920 (v). This means that there
is a part of the virtual screen that is NOT visible on the monitors without
changing the monitor relationships to each other. Somehow I also cannot
change the size of the window either. It opens to full screen and there is
NO way to change it (have tried!! may be something I haven't found yet!).
Can see multiple tabs - - - one of the reasons I'm trying Min is because FF
hates to have lots of tabs open!!

> Secondly - - I have found that I use a 'save page as' function a lot. Its
> a great way of archiving information.
> Is there any way that this could be included?
>
> It definitely could. Actually, Min already saves every page you visit, so
> I'm wondering if this could be a feature in Min. How do you typically use
> this feature (how do you organize saved pages, etc.)? Is the benefit to
> saving pages that you can organize important pages, that you can see what
> content a page had at a certain point in time, or something else?
>
I save pages into various folders. (Sorry, I'm a serious info junkie.)
Haven't really organized things in the folders but all the pages are on the
same topic, sort of like everything for renewable energy system batteries
goes into the same folder (it also has sub folders for the specific
technologies). With me using different folders I would rather not just have
things go to a general say 'downloads' folder because that get loaded with
all kinds of stuff.
(Collected about 80 GB of data (almost no pics or movies mainly just text)
in about 26 months.)

Thanks for considering the questions.

**Comment by PalmerAL** [comment]
An option to save the current page was added in 01a2924b136dedd1e25b57de6bfb85f2e0732b21, which should solve the second issue.

**Comment by dabeegmon** [comment]
On Fri, Sep 30, 2016 at 8:32 PM, PalmerAL <notifications@github.com> wrote:

> An option to save the current page was added in 01a2924
> <https://github.com/minbrowser/min/commit/01a2924b136dedd1e25b57de6bfb85f2e0732b21>,
> which should solve the second issue.
>
>
>
Thank you very much!!

Dee

**Comment by Sestowner** [comment]
I think this can be closed.
