### ISSUE TITLE
Can't connect to any account after deleting cookies in the installation folder

### ISSUE THREAD

**Issue by jstnthrsrnm** [minbrowser/min#2411]
Translation of my report posted [there](https://support.google.com/accounts/thread/266091912?hl=fr)

> Subject: connection with Min browser
> 
> Hello,
> 
> On the Min browser, a Google Docs error page said to delete cookies, doing so logged me out of my account, then when I entered my associated gmail address to reconnect, it sent me to a page saying address not found, incorrect information and "we advise you not to try again", and since then when I enter the address nothing happens, no Google applications page seems to respond. Thanks for reading if you can help...
> 
> ---
> 
> Same for pinterest and x accounts (not linked to google), pages don't display...

Thank you.

**Comment by PalmerAL** [comment]
Try this:
1. In the searchbar, click the history icon
![Screenshot 2024-03-27 at 12 42 08 PM](https://github.com/minbrowser/min/assets/10314059/982af012-9fa7-4e63-b078-c148760b7fb9)

2. Choose "Clear all history" ("Vider l'historique")
3. This will delete your browsing history and cached data.
4. Reload the page that isn't working

> it sent me to a page saying address not found, incorrect information and "we advise you not to try again",

If you see this page again, can you post a screenshot and the URL where it occurred?

**Comment by jstnthrsrnm** [comment]
Actually the first error page gave 3 steps, delete history and cache, delete cookies and reload the page.

I deleted the cookies and reloaded the page ignoring cache (ctrl+f5). I didn't change anything to the history because I use it very often in fact... and by the way, I just requested Min a google login page and the first result was unexpectedly yet precisely the page you asked for...

![min bug ggl](https://github.com/minbrowser/min/assets/47748438/78c92964-d1bc-4f52-bfba-95d9064080cd)
https://accounts.google.com/signin/oauth/consent?as=S-251326375:1709499736655774&authuser=0&client_id=368264585230.apps.googleusercontent.com&flowName=GeneralOAuthFlow&hl=en&part=AJi8hAMxmzTiwjCCVU9cg7o5PmCa-W8GRgaYoOUZHwJI2G5YpNjkiXMe0UNhc97DaPS3XAS6XngToL9BfAN4J1OtIdPcuQIqhiNrheLdpCep4qShzQ_B-xzv7RaYspOrFXbbj_ExGk-JdvtepphSMJ1Q-_UlH5XzNK5blNBXxN16zgqh0k1NNXPYJs3nN0O4PEbwtYEK8ZspxycxZI_ja1w8f94SbP8fJAopU7DWPyCED7Y4dCK0VTNkrj0KMldfRzjTai-4SO5yQlMkHbeEelPrD7cgFuUdg43Ez1r6rthY8xTYh9NDEgS-ZnRprA_bieAIUsErtEsnzEV5F6G87Mlc2SDf5WJ0XZwhr_HztZkiC80MX21sajvc2mExWFZX0sY-wIBrZ3-39ir8KR6uNIA9HkqZll_KDyJZ3owKE4Ug-FDRzvSiNfm2CFQLxEZQgNIa9Zd0nqYzF9ZdI4wK_2J68kkVf5WZebH0c6bMZr4Vw6P1c8HNIVLmHSpDyqqE3j2ecVVfBMtMD6UGdNxTGlFMUGTNSkl--DCS7zWLAWlJjMBZr0LiBMMR1prqOfTw5X8xL52MhTeF7D-bEo5WU7TbMhl_qODZzwjGVVeORCiedezG1BO06BqSGRKJGGry9lWKaQnNyFNR&rapt=AEjHL4NOE7gW3fAc2CaTnnDlFOGn0r-uMmlJXms4zq5ryARj3rQy0rhnJuUV7AQ3XWGA5dfMdWWOOwP4IF-kj9hp96saQJAqOSxbUv2qbxF1zQOSxYTwipc&theme=glif

---

![min bug ggl 2](https://github.com/minbrowser/min/assets/47748438/d55e4c8d-8946-430b-98e5-29f8145fb7d5)

![min bug x](https://github.com/minbrowser/min/assets/47748438/73a19085-0b30-4bf2-ab18-3dd3e095acd6)

![min bug pnt](https://github.com/minbrowser/min/assets/47748438/d0f58f5b-8812-4d3e-99e1-9e9ca2076993)

**Comment by jstnthrsrnm** [comment]
Now I get to this page:

![image](https://github.com/minbrowser/min/assets/47748438/4ad0c181-bd6b-491c-b8c4-0ab5ca915e8d)

"This browser or application may not be secure. Learn more
Try in another browser. If you are already using a compatible browser, you can try to log in again."

**Comment by jstnthrsrnm** [comment]
Still can't connect to google account and the other linked accounts, trying here just reloaded the google error page.

![min bug ggl 5](https://github.com/minbrowser/min/assets/47748438/5d6baac6-816a-4818-9f5c-2f9abbd69248)

---

Surprisingly I have no problem with this account it seems, for some reason there I haven't been logged out...

![min bug ggl 4](https://github.com/minbrowser/min/assets/47748438/f6dd973c-ea73-4c57-9fbf-d81b3c00f4b8)

**Comment by PalmerAL** [comment]
OK. 

1. What steps did you follow originally to delete cookies?
2. Is everything working now aside from the Google screenshot?
  * If so, that's a known, separate issue: #868. You can try going into settings, and setting your user agent to the one in this comment: https://github.com/minbrowser/min/issues/868#issuecomment-1901278410

**Comment by jstnthrsrnm** [comment]
I deleted the 2 files in my user data folder for Min.
As I don't recall having this 2d issue, it must be that
I never logged out from google while using Min yet...
I simply solved it by deactivating the blocker.
All should be right now, thanks for all you're a champion.

**Comment by PalmerAL** [comment]
OK, great, glad everything's working!
