### ISSUE TITLE
Tabs closing but menu page not responding to changes

### ISSUE THREAD

**Issue by 0tist** [minbrowser/min#2420]
- **Min Version:** Latest stable release
- **Operating system:** MacOS Sonoma 14.3

## Expected Behavior
Im closing tab with command + w shortcut in menu mode which makes the tab disappear. Essentially, cmd + w -> disappear tab.

## Actual Behavior
after using the shortcut, the tab can still be viewed in the menu mode unless i exit and enter the menu mode, then the tab is disappeared

## To Reproduce
 go to menu mode.
hover over a tab of your choice with up or down key
use cmd+w to close the tab(it will close but you would still be able to view it)
exit the menu mode by going to some other tab
go back to the menu
try to find the tab(you won't coz its closed)

**Comment by PalmerAL** [comment]
I actually started working on a fix for this already as part of https://github.com/minbrowser/min/discussions/2404; I'll open a PR.

**Comment by PalmerAL** [comment]
This is fixed in 1.32.
