### ISSUE TITLE
Running Min natively on Wayland?

### ISSUE THREAD

**Issue by yu-kiat** [minbrowser/min#2429]
Hello, I was wondering if you could run Min natively on Wayland (so no XWayland). I would prefer if it could, as running things natively usually results in a performance increase.

**Comment by yu-kiat** [comment]
Thanks, it works now. However for some reason Min still runs XWayland even though it's running natively on Wayland. (I killed the XWayland process and it still worked.)

**Comment by PalmerAL** [comment]
It looks like there's been some discussion about enabling this by default in Electron: https://github.com/electron/electron/pull/35630

Does anyone know why Chromium doesn't enable it by default - are there compatibility issues?
