### ISSUE TITLE
Clicking on link in Thunderbird opens new window with all existing tabs

### ISSUE THREAD

**Issue by zoof** [minbrowser/min#243]
When I click on a link in Thunderbird (Icedove), min opens a new window with each of the existing tabs. What I expect is either 1) a new tab in the existing window or 2) a new window with a single tab.

**Comment by Tichy** [comment]
I can confirm that this happens with every other applications, even launching min passing an url from the command line.
It opens a new window with the tabs of the alredy opened window and the menu bar that can't be hidden (usually, I keep it hidden).

Using it with Arch Linux. Electron version: 1.4.8

**Comment by steve-1776** [comment]
I had this problem using the official Arch package, but this issue too was fixed for me by replacing with the AUR version. Links now open as expected for me at least

**Comment by manuelmazzuola** [comment]
Same issue on archlinux, min version 1.7.0

**Comment by PalmerAL** [comment]
This is fixed in d3f199c92ccb557155b4ac600122c953d37861e8, which will be included in 1.9.0.
