### ISSUE TITLE
Extensions?

### ISSUE THREAD

**Issue by veryraindrop627** [minbrowser/min#2432]
Just downloaded Min today and I am absolutely in love with the minimalist design of it. My only complaint is the (as far as I can tell) inability to add browser extensions. Is this something that’s in the works? I mainly just want to be able to use dark reader, so an in-app implementation of a forced dark mode would be enough for me. I love the simplicity though, really well done.

**Comment by PalmerAL** [comment]
I just wrote an FAQ on this :) https://github.com/minbrowser/min/wiki/FAQ

But you can try this: https://github.com/PalmerAL/min-dark-mode-userscript

**Comment by veryraindrop627** [comment]
perfect, thanks.
