### ISSUE TITLE
Syntax Unexpected token

### ISSUE THREAD

**Issue by AnthonyInMath** [minbrowser/min#2439]
After computer was shutdown abruptly from power loss, min no longer functions, starting the application show the following error message.
A javascript error occured in the main process
Uncaught Exception:
SyntaxError: Unexpected token '

The issue persists after trying to reinstall the program, with the installer having the same issue and deleting the AppData files of Min

- Min Version: 1.32.1
- Operating system: Windows 11

**Comment by PalmerAL** [comment]
Sorry for the late response. It sounds like you already tried this, but did you delete the following files:

* `AppData\Local\min` (actual source files)
* `AppData\Roaming\Min\windowBounds.json`

If that doesn't help, does it work if you install 1.32.0?

**Comment by AnthonyInMath** [comment]
Deleting AppData\Roaming\Min\windowBounds.json solved the issue
