### ISSUE TITLE
update electron version or provide an Arch bulid on binaries

### ISSUE THREAD

**Issue by Redoxahmii** [minbrowser/min#2440]
Currently to install this browser on Arch from AUR it requires cloning the chromium mirror for electron 24 which is about 30 gb and then it installs which is way too much to download and compile just for a browser.

30GB download aside the compilation time also then takes an obscene amount of time.
A prebuilt binary would be nice but due to the rolling releases i could understand why it would be not be included.

**Comment by PalmerAL** [comment]
That doesn't sound right. First of all, it looks like we've somehow ended up with two different packages in AUR:
https://aur.archlinux.org/packages/min
https://aur.archlinux.org/packages/min-browser-bin

Only the second one is current. But both depend on the -bin versions of Electron, so you shouldn't need to compile anything.

Anyway, we don't directly maintain these packages - can you raise this issue on AUR or contact the package maintainers?

**Comment by Redoxahmii** [comment]
So apparently the link that is provided in the README.md point to
https://aur.archlinux.org/packages/min 
Which i would assume is the stable version but on this it requires downloading the whole chromium for compilation from source for electron24.
They do have raised flags on the this pkg for bumping electron24 to electron29 which would then use it from the Arch current version but seems like there isn't any response to that.

Using the secondary `min-browser-bin` pkg it compiles from the .deb file instead and took barely a minute.
You should change the link in the README.md to point to the second pkg.

**Comment by Redoxahmii** [comment]
Created [pull](https://github.com/minbrowser/min/pull/2443) to update it to other pkg.

**Comment by PalmerAL** [comment]
I sent an email to the maintainers of both packages to try to figure out the situation; I'll wait a bit for a response before changing the link.

**Comment by Redoxahmii** [comment]
> @Redoxahmii Perhaps you haven't carefully checked the dependency list, the package (https://aur.archlinux.org/packages/min) depends on `electron24` or `electron24-bin`. If you have `electron24-bin` installed before you install the package, you don't need to download over 30G's files.

What's the point of the make BUILD on the AUR then if i have to manually find first the dependencies install them and then use it?
The `min` pkg defeats the purpose of it if i have to find and install these myself so it would be better to just use yours at least for Arch Systems as most are updated to the latest `extra` repo.

If it is still preferred to keep the `min` pkg for it then it should atleast fetch and install `electron24-bin` instead of manually building when you use the `electron24`.

**Comment by Redoxahmii** [comment]
If the maintainer of `min` pkg is actually active and can change the dependency to `electron24-bin` instead of `electron24` it would resolve this issue but in my suggestion it would still be better to use `min-browser-bin` as it uses the latest pkg of `electron` in the official repos and is mostly likely the easiest way to ensure a better experience.
Rest is the decision of the maintainers.

**Comment by PalmerAL** [comment]
@zxp19821005 Thanks for the comments. If I'm understanding correctly:

1. It makes sense to have both `min` and `min-browser-bin`.
2. `min` should continue building from source.
3. We should direct people to `min-browser-bin` by default, as that is the only one that is likely to be runnable without compilation.

Is that correct?

**Comment by Redoxahmii** [comment]
Yes this would be the better approach.

**Comment by PalmerAL** [comment]
Thank you both. I've merged the PR from @Redoxahmii to update our package link. Hopefully the `min` package can be updated soon; I haven't received a response from the maintainer yet.
