### ISSUE TITLE
Import bookmarks file not working

### ISSUE THREAD

**Issue by Silver25** [minbrowser/min#2444]
Hi Palmer,

I've been using browser Min 1.32.0 for a few weeks now (both Win 10 and 11).
Till then I didn't even know about this browser.
My main use of a lightweight browser is to play music from 1000oldies.de, love that,
and simple surfing/browsing, opening pages with articles I need at the moment.
Was a really nice surprised when finding that Min can start temp WordPress setups
on "zipwp.com" and "wpsandbox.net".
I can say that I really love your browser.
As you find in Title of this msg I can't import bookmark files from Edge, Chrome or Brave.
The second issue is not possible to open a local file(drag and drop or with address c: c:/ c:\ or file:///C:)

Appreciate any help or information.
Greetings!
Silvio

**Comment by goesbyabhi** [comment]
Same here. Currently on Windows 11. I've followed the instructions, but it just can't import the bookmarks.

**Comment by PalmerAL** [comment]
@Silver25 Thanks for reporting! @goesbyabhi has fixed the bookmark issue.

>  The second issue is not possible to open a local file(drag and drop or with address c: c:/ c:\ or file:///C:)

Do you see an error message of any kind when you do this? The `file:///C:` variant works for me.

**Comment by Silver25** [comment]
@goesbyabhi I don't get any info/error, the page is completely blank.

**Comment by AstringentBeet** [comment]
Currently using version 1.32.1 on MacOS (intel), and am experiencing the same issue.

**Comment by PalmerAL** [comment]
@AstringentBeet I just published a new release that includes the import bookmark fix, sorry for the delay.

@Silver25 I don't have any further ideas regarding the local file issue unfortunately.
