### ISSUE TITLE
Google accounts does not allow signing - This browser or app may not be secure.

### ISSUE THREAD

**Issue by yenaingtun-dev** [minbrowser/min#2447]
- **Min Version:**
- Min Version 1.32.1 (1.32.1)
- **Operating system:**
- macOS 10.15

## Expected Behavior
- Google account signing form

## Actual Behavior
- This browser or app may not be secure.
![Screen Shot 2024-05-30 at 8 39 36 PM](https://github.com/minbrowser/min/assets/59411234/e1992227-3cc2-4356-a4bd-d1365e6161ca)

**Comment by lunatic-gh** [comment]
Hit "Try Again" and... well, try again. After trying some times (for me it was the 3rd one) it just works. It's just google being google.

**Comment by PalmerAL** [comment]
Changing the user agent also works most of the time: #868

**Comment by yenaingtun-dev** [comment]
I will try that.
