### ISSUE TITLE
Please add extensions

### ISSUE THREAD

**Issue by COWANBAS** [minbrowser/min#2448]
This is the best browser I've ever seen but unfortunately it has a lot of ads on YouTube. I would like you to try adding extensions to the browser, then you could use the ad removers on the Google Extensions website.

**Comment by mabequinho** [comment]
There are some custom scripts regarding such site specific ad-blocking.

https://github.com/alisanoelia/yt-block

https://github.com/minbrowser/min/wiki/userscripts

**Comment by PalmerAL** [comment]
https://github.com/minbrowser/min/wiki/FAQ#does-min-support-extensions
