### ISSUE TITLE
Feature Request: Download?

### ISSUE THREAD

**Issue by PandawanFr** [minbrowser/min#245]
Hey! 

So firt of all, I love Min, such a good app! I really like it's style and how everything is so simple!

One thing that was a bit annoying is whenever I try to download a file, I get (ofc) the basic "save as" dialog, but was was annoying is there was no download progress bar, nothing, I had no way to know whether my file had finished downloading...

Do you think you could (somehow) make that? 

Thanks!

**Comment by wb9688** [comment]
Duplicate of #91

**Comment by PalmerAL** [comment]
Closing this in favor of #91.

Also, I'm not really sure what the design for this should be, so if you have suggestions, please add a comment to that issue.
