### ISSUE TITLE
unable to start min, "js error"

### ISSUE THREAD

**Issue by jstnthrsrnm** [minbrowser/min#2451]
old recurrent issue on my installation
this time restart won't correct it
after reinstalling:
v1.31.1 runs, not 1.32.1
with factory settings

each time min.exe, its installer or uninstaller is launched this dialog displays, once or twice

![min err](https://github.com/minbrowser/min/assets/47748438/48dbe8a2-c71f-41d4-a13a-5ba6070f1aa1)

![Img20240611095537](https://github.com/minbrowser/min/assets/47748438/caf70a26-6092-424d-afeb-8c759092bcb0)

**Comment by jstnthrsrnm** [comment]
today on pc startup
trying to launch min
error dialog shows
min window shows
with default settings
all pages are blank
closing the window
restarting min (1.31.1)
shows a short list of urls
first is option to restore open tabs
which works but still on default settings

**Comment by jstnthrsrnm** [comment]
just did the last Windows update
and min started correctly, as when
has not closed unexpectedly before

**Comment by PalmerAL** [comment]
If I'm understanding, everything works now? If so, great!

**Comment by jstnthrsrnm** [comment]
Not certain, because the second eventuality i mentioned often occurs when
my pc takes advantage of being in sleep mode to shut down unexpectedly.

**Comment by jstnthrsrnm** [comment]
For a long time now min is used to displaying the dialog and reverting to factory settings when the pc unexpectedly shuts down. Yet twice now since v1.32.1 i've had to reinstall v1.31.1 to get only it to work. And today it had shut down abruptly in sleep mode again, but it started normally this time. Must wait if it's confirmed. I'm not very keen on reinstalling and running v1.32.1 to see if that one's fixed too. Thanks in the meantime.

**Comment by PalmerAL** [comment]
Are you saying that initially, you have to install 1.31, but after that, you can install 1.32 and it works?

If you're losing settings and open tabs, it sounds like those files are getting corrupted as they're written to disk. That could possibly be a hardware problem - do you know why your computer is turning off unexpectedly?

**Comment by jstnthrsrnm** [comment]
"to get only it to work" is about v1.31.1 (I use a translator).

App(s) downloaded from the store regularly tried connecting to the Internet at night around 3 a.m., bringing the computer out of sleep mode. Most of the time, the task failed, and they were programmed to keep trying until success, causing the PC to shut down automatically due to a system setting. The malfunctions with the many js alerts occurred following that.

This hasn't happened for some time now, so I hope I've fixed --and described-- the problem sufficiently.

Sorry I didn't get your reply before, and thanks.

**Comment by PalmerAL** [comment]
I fixed a similar issue in the latest release (#2488), which I'm guessing will solve your issue as well. If it happens again after updating, let me know!

**Comment by jstnthrsrnm** [comment]
when running the installer i got thought these steps

![image](https://github.com/user-attachments/assets/40fa75c4-0cca-4c6b-9bbe-1478ba1beb6b)

it said unknown publisher and proposed to execute anyway
instead of launching the app it showed a js prompt saying there was an error and proposing to open a log

i tried to launch the previous working version and i got this
![image](https://github.com/user-attachments/assets/af5ae1a5-d5a3-453f-8f75-f0f2062177f7)

i relaunched the installer and 1.33.0 seems to work with my custom settings
