### ISSUE TITLE
Min.app cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by jfabriciovr** [minbrowser/min#2482]
Hello,

I have a MacBook Pro 2017, with macOS Ventura 13.4.1 and Intel Core i5.

I was trying to update Min browser to the latest version, so I downloaded the app and replaced the old one in Applications. But when I try to run it I get the error:

Min.app cannot be opened because the developer cannot be verified.
macOS cannot verify that this app is free from Malware.
![Screenshot 2024-08-11 at 17 08 59](https://github.com/user-attachments/assets/e12fc4ca-f1fd-4a56-95e6-6aa47ce5cfaa)

The version of Min is 1.32.1 mac-x86.

I tried to change chmod for the executable with the same result.

I love this browser and hope I have enough knowledge to contribute to the project someday. Congrats!

**Comment by PalmerAL** [comment]
This happens because I haven't paid for an Apple signing certificate; if you right-click you should get an "open anyway" option. Alternatively you can do this:

```
xattr -d com.apple.quarantine /Applications/Min.app
```

> I love this browser and hope I have enough knowledge to contribute to the project someday. Congrats!

Thanks!
