### ISSUE TITLE
JavaScript Error

### ISSUE THREAD

**Issue by Edward-Lucas** [minbrowser/min#2483]
- **Min Version: 1.32.1**
- **Operating system: Windows 11 Pro**

## Expected Behavior
Select the program and run it.

## Actual Behavior
Execution is not possible.

## To Reproduce
All have to do is execute.

All have to do is execute.
![image](https://github.com/user-attachments/assets/7ac7b19c-b831-4fd0-8b1b-17f09551777c)

**Comment by PalmerAL** [comment]
Could you try deleting this file: `\Users\<username>\AppData\Roaming\min\settings.json` and let me know if that fixes it?

**Comment by Edward-Lucas** [comment]
Thank you! It's solved.

**Comment by PalmerAL** [comment]
Thanks for testing; I've improved this in ca9c3801fedd9c2e6017c94bbd1e417d1d7d531f so it shouldn't happen again.
