### ISSUE TITLE
How to set the 'Enable User Scripts' option to be enabled by default?

### ISSUE THREAD

**Issue by XSNOW917X** [minbrowser/min#2487]
I want a completely new user of minBrowser to be able to use the scripts I've written as soon as they start the browser for the first time.

**Comment by PalmerAL** [comment]
I guess the easiest way would be to remove this check: https://github.com/minbrowser/min/blob/ca5e9659d3591c0457a48a2c07cccc8730d6eb2c/js/userscripts.js#L206
