### ISSUE TITLE
The latest version

### ISSUE THREAD

**Issue by Unixten** [minbrowser/min#2492]
dear Min team,
trying to download the latest version from minbrowser.org hitting the "download" button starts the downloading of version 1.32 but the most recent version here on Github releases is 1.33...
Could you, please, clarify? Which one is actual?

**Comment by PalmerAL** [comment]
Hi, sorry for not documenting this anywhere. I noticed this issue shortly after the release: 714f56a, so my plan was to write a fix and test it for a few days, then make a 1.33.1 before updating the website.
