### ISSUE TITLE
Any plans to add integration with Google Password Manager/iCloud keychain?

### ISSUE THREAD

**Issue by jeepjeepbeepbeep** [minbrowser/min#2512]
I totally understand reasons to not include compatibility with either of these services, but it would be super convenient if they were. Are they they being considered or are they intentionally not added?

**Comment by PalmerAL** [comment]
The existing password manager integrations use the CLI tools provided by those services; Google and iCloud don't provide one.

For iCloud particularly, the better long term solution is that Electron adds support for webauthn/passkeys, but I don't think that's likely to happen any time soon: https://github.com/electron/electron/issues/24573
