### ISSUE TITLE
Doesn't start, if there is no sound device in the system

### ISSUE THREAD

**Issue by yaroslav-nakonechnikov** [minbrowser/min#2532]
- **Min Version:** 
1.33
- **Operating system:**
Ubuntu 24.04

## Expected Behavior
it starts without issues

## Actual Behavior
```
~$ min
min: symbol lookup error: min: undefined symbol: snd_device_name_get_hint, version ALSA_0.9
```

## To Reproduce
install from deb in the system without any sound device

**Comment by PalmerAL** [comment]
Does this also happen if you run [electron-quick-start](https://github.com/electron/electron-quick-start)? If so, could you please open an issue [here](https://github.com/electron/electron/issues/new/choose)?

**Comment by yaroslav-nakonechnikov** [comment]
@PalmerAL  thanks, i've rechecked it as well, and managed to solve it by installing:
`sudo apt-get install libasound2t64`
