### ISSUE TITLE
why i cant use addons?

### ISSUE THREAD

**Issue by sorryimstoned** [minbrowser/min#2536]
for example i wanna use socks5 proxy, i cant do it 
for it i could use extension but, i cant
why?

**Comment by kepler-69c** [comment]
FAQ: https://github.com/minbrowser/min/wiki/FAQ#does-min-support-extensions

Min is based on electron, not chromium, and therefore does not support extensions (add-ons). It is possible that support will be added in the future, but it is currently a long way off. (see #1)

**Comment by ioc2e3** [comment]
That ...

Are there any updates on this ?

.
