### ISSUE TITLE
app_id is null

### ISSUE THREAD

**Issue by Andreaworld** [minbrowser/min#2538]
- **Min Version:**
Installed from the AUR repository. Current version is 1.33.1-1.

- **Operating system:**
EndeavourOS, an arch linux distro. It is rolling release, so no version number, just the latest update.

## Expected Behavior
I'm using swayfx as my Windows Manager. In my config, I want to add a line that inhibits idling when min is in fullscreen. To do this directly requires referencing the app id. The expected behaviour should be I guess that when executing swaymsg -r -t get_tree to show me the app id for min

## Actual Behavior
It doesn't list an app_id. When using swaymsg -r -t it lists it as null.

## To Reproduce
I don't think I have done anything special to get this result. As far as I know this is just how the current version of min is, at least the version on AUR.

The relevant JSON  from swaymsg -r -t, or as relevant as I can tell. I can get more if needed:

"name": "Min",
"window": 14680068,
"nodes": [],
"floating_nodes": [],
"focus": [],
"fullscreen_mode": 0,
"sticky": false,
"pid": 93146,
"app_id": null,
"visible": true,
"max_render_time": 0,
"shell": "xwayland",
"inhibit_idle": false,
"idle_inhibitors": {
  "user": "none",
  "application": "none"
}

I have found a work around in the meantime to my original issue, I just thought the background might help.

**Comment by PalmerAL** [comment]
Do you know what the expected format of this ID is?

I think the corresponding option in the build config is probably https://www.electron.build/interfaces/electron_builder.linuxconfiguration#appId, but the docs seem to say it may only apply to Windows and Mac.

On Mac, it seems to use the default of `com.electron.min`, which isn't ideal, but I'm not sure what the consequences of changing it would be.

**Comment by Andreaworld** [comment]
> Do you know what the expected format of this ID is?
My terminal emulator Kitty as a comparison has the app_id "kitty", if that is what you mean. 

> I think the corresponding option in the build config is probably https://www.electron.build/interfaces/electron_builder.linuxconfiguration#appId, but the docs seem to say it may only apply to Windows and Mac.
Where would I find this on my system? I'm not building it manually.

**Comment by Andreaworld** [comment]
They likely aren't the same thing, since this is a wayland specific
property, the equivalent on X11 being WM_CLASS.

There is 2022 closed issue that was exactly about this, and it was solved
back then. Cross referencing that would likely be good.

https://github.com/minbrowser/min/issues/2042#issue-1303386818

From what I can tell, it was an issue on electron's side. They fixed it by
bringing it in line with what they did woth X11 - if there isn't a
desktopName in the package.json, get the name of the .desktop file. I don't
have an idea why this isn't working anymore, but adding that property tp
the package.json won't hurt.

I'll test it out myself when I get access to my laptop again.

**Comment by Andreaworld** [comment]
Wait, nevermind. The problem is that Min by default is running in Xwayland, not Wayland for some reason. When I get Min to run in Wayland with --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform-hint=auto (found here --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform-hint=auto) it does have an app_id.

Sorry, guess there was no bug/issue after all. Now I just need to find out how to make Min do this by itself without me running it myself in the command line each time with those arguments
