### ISSUE TITLE
License to make a rebranded browser and chrome extension support

### ISSUE THREAD

**Issue by oazabir** [minbrowser/min#2539]
Hi Palmer,
What a wonderful project Min browser is! We absolutely love it!

We would like to build a rebranded browser using it and add some AI
features on it ourselves. It will be free to use. But there will be
some ads on it.

I was wondering if you would allow us to do that?

And, would you be willing to add chrome extension support to it? We
would be happy to pay for the work.

**Comment by PalmerAL** [comment]
Hi Omar - I just replied to your email!
