### ISSUE TITLE
Not an issue. How to save a page????

### ISSUE THREAD

**Issue by wavic** [minbrowser/min#254]
Hello! I am opening the browser for the first time. I like it. 
But how to save a web page?
Not in the menu. CTRL+S does nothing. I have tried !save but nothing appears. No kayboard shortcuts in !settings. All page are saved but where and I don't whant that as default. I am asking here because I don't know where else. And how to hide the menu bar? Linux Mint

**Comment by PalmerAL** [comment]
There's currently no way to save a webpage. This should be fairly easy to add, so it can probably be included in the next release. This is also related to #241, which discusses alternatives to saving pages.

> No kayboard shortcuts in !settings. 

I'm not sure I understand this. What action do you want a keyboard shortcut for? Or is that section of the settings missing entirely?

> All page are saved but where and I don't whant that as default. 

Currently, the HTML of webpages are saved to the database that holds all of your data (settings, history, reading list items, etc.) There's currently no way to turn this off, although it might be a good idea to add a setting for that.

> And how to hide the menu bar?

In 1.4, there isn't a way to do that. In 1.5 (which will probably released in a few days), you will be able to press the ```alt``` key to hide or show the menubar.

**Comment by wavic** [comment]
Hello! Thanks for the responce!
I mean shortcut for saving pages like CTRL+S for example.
I am aware that this is a new project

**Comment by PalmerAL** [comment]
I've added a menu item to do this in 01a2924b136dedd1e25b57de6bfb85f2e0732b21.

**Comment by PalmerAL** [comment]
This has been released in 1.5.

**Comment by wavic** [comment]
Good :)
