### ISSUE TITLE
Building windows version

### ISSUE THREAD

**Issue by LeOS-GSI** [minbrowser/min#2544]
I have succesful build the deb version. now I want build the windows version with my linux building mashine. But how should I installe Visual Studio on Linux ??

So is there a way to build windows .,exe on linux ?

**Comment by LeOS-GSI** [comment]
OK, I have found the visual studion build tools. But after build is finished, I can't find any mi.exe or mi.msi file ?

**Comment by PalmerAL** [comment]
It should end up in one of the subdirectories of `/dist/app`.

I haven't tried to cross-compile in several years; I believe I had to install wine to make it work when I last did. It might be easier to use Github actions to build on Windows (this is how the official binaries are built).

However, I'm happy to accept PRs to make cross-compiling easier if you run into any specific issues with solutions.

**Comment by LeOS-GSI** [comment]
In /dis/app/ are several files, but no .exe or msi (installer). 

And yes, Win and Mono installation was needed for building the win version.

I like the browser very much, but with https://privacytests.org/me.html I have found to much privacy related issues. That's why I can't go further with it. 

But anyway, thx for the good work
