### ISSUE TITLE
Sometmes, Min does not show me the page content

### ISSUE THREAD

**Issue by gbad8** [minbrowser/min#256]
Some times when i write the URL and click ENTER, min doesn't load the page image. I can feel the links in the page but the page remains blank.Exemple: In youtube, i can click in a video and hear it but the page remains blank.
![screenshot from 2016-10-01 11 53 53](https://cloud.githubusercontent.com/assets/22562300/19014827/d50014ec-87cd-11e6-84de-b7e2b7ec5952.png)
 I found a post talking about Min in www.diolinux.com.br and i just love min right now, but this bug is taking me back to chromium. :'-(

**Comment by PalmerAL** [comment]
Hmm, I've never seen that before. When this happens, is there anything that makes the page display again (switching tabs, reloading the page, etc.)?

It looks like some people are having a similar issue with Brave, so this is probably a Chromium bug: https://github.com/brave/browser-laptop/issues/1471

According to https://github.com/electron/electron/issues/6139, disabling GPU acceleration prevents this from happening, so you could try doing that, although it will make Min a bit slower.

**Comment by Tichy** [comment]
I can confirm that pages aren't blank when launching min with the --disable-gpu workaround

**Comment by Sestowner** [comment]
I think this can be closed. Feel free to reopen this if you have the problem again.
