### ISSUE TITLE
min gets stuck on loading runeaudio.local (or it's ip address)

### ISSUE THREAD

**Issue by pppov** [minbrowser/min#257]
Hi, really love Min. But it refuses to fully load runeaudio.local (see picture Midori on the left, Min on the right). Same thing when I type in the ip address runeaudio is using, Min seems to find runeaudio, but it refuses to fully load. It stay in that state forever.

(I use a raspberry Pi 3 with IQaudio Pi-dac with runeaudio for playing music. Sounds great, by the way.)

Runeaudio loads in all browsers, also in mpdclients like Cantata, except for MIn.

I would love to have this fixed, as I find Min the best. I like the distract free browsing...
![min not loading runeaudio](https://cloud.githubusercontent.com/assets/18084725/19030837/b563e972-8950-11e6-9ada-d8d824394312.png)

**Comment by PalmerAL** [comment]
@pppov Did you intend to close this?

**Comment by pppov** [comment]
Yes, it was just the script setting in preferences that blocked runeaudio.local from loading. (Once I closed the thread I didn't know how to reopen it to comment on it...)
