### ISSUE TITLE
Pages Not Loading

### ISSUE THREAD

**Issue by al-jshen** [minbrowser/min#258]
Very frequently, pages don't load. Moving the mouse around on the blank white page still changes the mouse when it goes over a hyperlink, for example, but nothing shows up. Just a blank page. Happens every other new tab. Reloading the browser using the option built into the browser causes the tabs to disappear like the pages. A full restart of the browser is required. Rather annoying.

**Comment by PalmerAL** [comment]
This sounds like the same issue as #256. Can you try running Min with the ```--disable-gpu``` flag and see if this still happens?

**Comment by AL-JShen** [comment]
Sorry it took so long to reply. Using `--disable-gpu` does not fix the problem.

**Comment by AL-JShen** [comment]
The browser works fine in Windows. Almost all pages don't load on my Arch machine, though.

**Comment by mthomas7** [comment]
I'm having the same problem - but unchecking "block scripts" seems to fix it for me (arch linux). The block scripts checkbox is causing a lot of pages, duckduckgo included, not not load.

**Comment by PalmerAL** [comment]
@mthomas7 Having "block scripts" enabled is going to cause pages that require JavaScript to not work correctly... for duckduckgo, you can use duckduckgo.com/html instead.

**Comment by PalmerAL** [comment]
I think some of this may be the result of electron/electron#8505, in which case 251a4601825675272949fb50416339f0a6f82d3f should help reduce the frequency with which this occurs. Some of it sounds like a GPU issue as well though.

**Comment by Sestowner** [comment]
I think this can be closed.
