### ISSUE TITLE
Login to Twitter

### ISSUE THREAD

**Issue by zderi** [minbrowser/min#260]
I normaly open www.twitter.com and enter my credentials. But when I press enter or click to login button nothing happens. After a few seconds when I clik to random link on page then it redirects me to my Twitter page. Everything else works fine (I mean other web pages I visit).

Debian 8 Jessie, 64 bit.

Thanks :)

**Comment by PalmerAL** [comment]
I'm not really sure why this is happening. With javascript disabled, the login works fine, but I'm not sure what part of their code is causing this.

Also, adding a ```webview``` to the electron-quick-start app and loading https://twitter.com/login in it does the same thing, but it works fine in Brave, which is also using webviews to display pages. It would be helpful to know what Brave is doing differently that makes the login work.

**Comment by whitestone8214** [comment]
As far as I remember Brave developers use Electron that are slightly or heavily modified by them, not the original one.
(I used Brave until some monthes ago)

**Comment by PalmerAL** [comment]
I've added a workaround for this in b72721e. Would you be willing to try the master branch and see if it works?

**Comment by whitestone8214** [comment]
Still not working. Inspect Page says

"Failed to load resource: net::ERR_NAME_NOT_RESOLVED" (Address is https://t.tellapart.com/twitterinitmatch?tpm_cb=partnerIdSyncComplete&guest_id={number1}&_={number2}, transcribed as twitterinitmatch)

when I opened https://twitter.com/.

**Comment by PalmerAL** [comment]
@whitestone8214 Are you using the development version of Min from the master branch, or the release version of Min from the releases page? The fix for the issue mentioned above isn't included in the latest release; it should be in the next one (1.7.0).

**Comment by whitestone8214** [comment]
I'm sorry, the code I cloned at that time was https://github.com/minbrowser/min/commit/43f9186f1c1f8fe42976adc9879daa350be14591, but https://github.com/minbrowser/min/commit/b72721e12f8d025e186dc047efa48d8f94a7079f was not included in it;;; Weird...

Anyway retried just now with https://github.com/minbrowser/min/commit/b72721e12f8d025e186dc047efa48d8f94a7079f. Now it works. Thank you so much XD

**Comment by PalmerAL** [comment]
Could you try again with the latest version of the master branch, and see if it still works? The reason I ask is that a few days agao I added a second commit (dea966c00519734eba33f5bac0ed2c04314f25b9) to simplify the workaround from b72721e12f8d025e186dc047efa48d8f94a7079f, and I'm wondering if that's what made it not work for you.

**Comment by whitestone8214** [comment]
Sorry for late testing because I was very busy these times ^_^;

Yes, Twitter login works properly with master branch (At least for me) ;)

**Comment by PalmerAL** [comment]
Great!

**Comment by whitestone8214** [comment]
...wait, I tried to log in Twitter again just now and it does not log in again. This time console says when I opened Twitter:

> Refused to load the script 'https://cdn5.userzoom.com/files/js/{string}.js?t=uz_til&cuid={string}' because it violates the following Content Security Policy directive: "script-src https://connect.facebook.net https://cm.g.doubleclick.net https://ssl.google-analytics.com https://graph.facebook.com https://twitter.com 'unsafe-eval' https://*.twimg.com https://api.twitter.com https://analytics.twitter.com https://publish.twitter.com https://ton.twitter.com 'nonce-{string}==' https://syndication.twitter.com https://www.google.com https://t.tellapart.com https://platform.twitter.com https://www.google-analytics.com blob: 'self'".
> Failed to load resource: net::ERR_BLOCKED_BY_CLIENT (https://analytics.twitter.com/tpm/p?_={number})
> Failed to load resource: net::ERR_BLOCKED_BY_CLIENT (https://www.google-analytics.com/analytics.js)
> Failed to load resource: net::ERR_BLOCKED_BY_CLIENT (syndication)

**Comment by PalmerAL** [comment]
Interesting, maybe there's a timing issue. Can you try again with 212fb573da11862ffd4ae941b8b0fd71eef0471f? (I don't think the errors in the console are related, the first one appears to be a Twitter bug and the other ones are because you have content blocking enabled).

**Comment by whitestone8214** [comment]
Cloned https://github.com/minbrowser/min/commit/212fb573da11862ffd4ae941b8b0fd71eef0471f, and now I tried these on both 'Block trackers and ads' **enabled** and **disabled**.

1. Clear all history(rm -rf ~/.config/Min) -> launch Min -> login to Twitter
2. Close Min without closing Twitter tab -> relaunch -> login to Twitter on existing Twitter tab
3. Close Twitter tab -> close Min -> relaunch -> open new Twitter tab -> login to Twitter

Still same results. All of these sometimes works, sometimes doesn't, irregularly...

* Also tried with the latest commit (https://github.com/minbrowser/min/commit/b741c6aab6de751c360e1046c8133aae563549dd) and got same results.

**Comment by whitestone8214** [comment]
And now Brave does not use pure Electron, instead it uses the toolkit named Muon that they forked from it.

https://github.com/brave/muon

**Comment by PalmerAL** [comment]
It stops working if I enable network throttling in the devtools, so I'm guessing there's a timing issue that occurs depending on when the original response from the server is received, but so far I can't come up with a good workaround for it. We should probably just wait for Electron to fix it, although it doesn't look like that's happening soon.

**Comment by AngeloR** [comment]
This no longer seems to be an issue and can probably be closed.
