### ISSUE TITLE
 switch layout falls down menu 'File'

### ISSUE THREAD

**Issue by osha-p** [minbrowser/min#262]
Every time I switch layout (Alt-Shift for example) keyboard falls down menu 'File', which is impeding work. OS - linux.

**Comment by PalmerAL** [comment]
I'm not sure I understand the issue. Can you make a video showing what is happening?

Also, which linux distribution are you using?

**Comment by osha-p** [comment]
Just add any layout keyboard and try to switch it in different input text fields. I sometime see falldown menu "File". Isn't it? Distribution: archlinux,DE: openbox, Version of Min: 1.4.1-1

**Comment by osha-p** [comment]
Finaly, I find out what is problem of change layout! when I press alt+shift simultaneously all is fine. But If I press at first alt and then add shift  - in this case I see falldown menu 'File'. Please, try it. And I not found keymap ' alt+shift' in preferences which may call that menu.

**Comment by osha-p** [comment]
My fall. Try it on other machines - problem not exist.

**Comment by PalmerAL** [comment]
Can you try changing the shortcut for "show and hide menu bar" in preferences to something else, and see if this still happens?

**Comment by tivasyk** [comment]
i've changed the "show/hide menu bar" hotkey combination to something else than _alt_, but _alt+shift_ still opens menu > file! **p.s.** _ctrl_, _shift_ and _alt_ are supposed to be _modifier_ keys meaning they should modify function of other keys, not perform any action on their own. facepalm.

**Comment by KenSv** [comment]
I'm using Alt+Shift combination for switching language on keyboard, but first pressing Alt+Shift always opened File menu. I blocked settings for Show And Hide Menu Bar but with no result

**Comment by PalmerAL** [comment]
@KenSv How did you disable it? Assuming you deleted the "alt" entry from the settings page, I can't immediately think of any reason why it would still be opening. (Also, which OS and keyboard layout are you using?)

**Comment by KenSv** [comment]
@PalmerAL I tried to delete  the "alt" entry from the settings page and tried to change it to another combination. My OS - Debian Buster (XFCE Desktop), keyboard layouts - Russian & English

**Comment by PalmerAL** [comment]
Oh, actually it looks liks this issue is unrelated to that setting, there's an explanation of what's happening here: https://github.com/jiahaog/nativefier/commit/a27bb0fd352b75e48f1715607395feb6e406969e. It looks like we need to do something similar to that and define letter shortcuts for each menu.

**Comment by userkilled** [comment]
With the active input window, when I press Alt + Shift, the "File" menu opens.

**Comment by Sestowner** [comment]
Electron issue: https://github.com/electron/electron/issues/28088.

**Comment by PalmerAL** [comment]
I think this is fixed now; please let me know if not.
