### ISSUE TITLE
How can I change the width of the scrolling bar?

### ISSUE THREAD

**Issue by framesGist** [minbrowser/min#265]
Hello,
How can I change the width of the scrolling bar?
I've tried adding the following style:

::-webkit-scrollbar {
width: 6px;
}

Re-opended the editor, but no change.

What am I missing? Thanks!

**Comment by PalmerAL** [comment]
This should increase the size of the scrollbar:

```
.tab-group #tabs::-webkit-scrollbar {
	height: 6px;
}
```

Let me know if that works correctly!

**Comment by framesGist** [comment]
Hi,
I set  the width to 3px(I like more thin), but still can't change the scrollbar width.
![scroll](https://cloud.githubusercontent.com/assets/13857382/19803994/05408a12-9d0c-11e6-9476-a515ff812334.png)
I want make scrollbars more thin:
![scroll-thin](https://cloud.githubusercontent.com/assets/13857382/19804404/61a14e20-9d0e-11e6-9ad2-d538da9228c4.png)

Thanks!

**Comment by PalmerAL** [comment]
Oh, I thought you were talking about the scrollbars in the tabstrip.

To change the webpage scrollbars, you can add this code to the end of <a href="https://github.com/minbrowser/min/blob/master/js/webview/default.js">```js/webview/default.js```</a>:

```
document.addEventListener('DOMContentLoaded', function () {
  var styleElement = document.createElement('style')

  styleElement.innerHTML = '::-webkit-scrollbar {width: 3px;height:3px}::-webkit-scrollbar-track {background-color: rgba(0, 0, 0, 0.1);}::-webkit-scrollbar-thumb {	background-color: rgba(0, 0, 0, 0.3);}'

  document.body.appendChild(styleElement)
})
```

If you change the scrollbar size, you'll need to change both the ```width``` and ```height``` properties (for horizontal and vertical scrollbars).

**Comment by framesGist** [comment]
Hi, 
I followed your suggestion, added the code to the end of js/webview/default.js, but no luck.
Any thoughts?

Thanks!

**Comment by PalmerAL** [comment]
After you add the code, you'll need to run ```grunt``` to re-build the ```webview.min.js``` file.

If you'd rather not do that, you can just add the above code to ```dist/webview.min.js```.

**Comment by framesGist** [comment]
Solved!!
Thanks PalmerAL!!

**Comment by PalmerAL** [comment]
Glad it worked!

**Comment by doreminiature** [comment]
Hello,
Changing scrollbar style using suggested method brings brief flashing when visiting a new web page.
Looks like electron default scrollbar being rerendering with new CSS styles on DOMContentLoaded is the cause of the flash.
Maybe there is way to customize Chromium with that modern Chrome(54) thin scrollbar style?

**Comment by doreminiature** [comment]
So yes we can turn Chrome style scrollbar:

// we set new attribute for getWebviewDom () in webviews.js {
w.setAttribute('blinkfeatures', 'OverlayScrollbars')
___
«blinkfeatures:
<webview src="https://www.github.com/" blinkfeatures="PreciseMemoryInfo, CSSVariables"></webview>
A list of strings which specifies the blink features to be enabled separated by ,. The full list of supported feature strings can be found in the RuntimeEnabledFeatures.in file.»
