### ISSUE TITLE
Pages not loading

### ISSUE THREAD

**Issue by jerone** [minbrowser/min#271]
I'm running the [binary version](https://github.com/minbrowser/min/releases/tag/v1.5.0) on Windows and non of the pages are loading.

![2016-11-08 16_51_27-min](https://cloud.githubusercontent.com/assets/55841/20105871/8aff2116-a5d3-11e6-9946-f6fd92c32d94.png)

_Windows 8.1_
_Node.js v6.9.1_

**Comment by PalmerAL** [comment]
If you click on the searchbar to view the URL, you should see the string ```?ec=<number>``` somewhere in the URL. Can you check what that number is?

**Comment by jerone** [comment]
[**@PalmerAL**](https://github.com/PalmerAL) commented on [9 nov. 2016 03:54 CET](https://github.com/minbrowser/min/issues/271#issuecomment-259322952 "2016-11-09T02:54:51Z - Replied by Github Reply Comments"):
> If you click on the searchbar to view the URL, you should see the string `?ec=&lt;number&gt;` somewhere in the URL. Can you check what that number is?

This is the url thats loaded when I start the application:

`file:///C:/Users/<name>/Desktop/Min-win32-x64/resources/app/pages/error/index.html?ec=-138&url=https://palmeral.github.io/min/tour`

**Comment by jerone** [comment]
So reading `https://github.com/electron/electron/issues/6410` it appears to be a firewall issue. In Windows I've added Min to the "Allowed apps and features" list.

Do you know which ports the app is using?

**Comment by PalmerAL** [comment]
> Do you know which ports the app is using?

I think just the standard HTTP and HTTPS ports (80 and 443) are used.

**Comment by jerone** [comment]
> I think just the standard HTTP and HTTPS ports (80 and 443) are used.

Yeah, I thought so too, combined with the standard protocol. Those are all allowed, because Chrome, Firefox and IE run fine.

I thought it was maybe an issue with Kaspersky, but other colleagues don't have the same issue.

I'm going to close it because it appears to be only an issue on my pc
