### ISSUE TITLE
Scrolling with touchpad accidentally goes back/forth in history

### ISSUE THREAD

**Issue by orschiro** [minbrowser/min#274]
Hi all, 

Occasionally when scrolling up or down with my touchpad, I trigger a go back / forth in history action.

Can I disable this behaviour somehow?

**Comment by PalmerAL** [comment]
The swipe gestures are being redesigned as part of #264, which should result in fewer accidental navigations. Can you try out the <a href="https://github.com/minbrowser/min/tree/swipe-gestures">swipe-gestures</a> branch and see if that works correctly for you?

**Comment by orschiro** [comment]
Unfortunately, I do not find the time to test this at the moment.

I am sorry...

**Comment by dimaursu** [comment]
I have this issue as well, and it drives me mad. Can I disable it completely? I have a Lenovo X200, and I use the middle button to scroll.

**Comment by PalmerAL** [comment]
@dimaursu @orschiro  Are you still experiencing this issue in the latest version of Min?

**Comment by orschiro** [comment]
I am no longer able to test and report back, sorry! 😞

-

**Comment by PalmerAL** [comment]
OK, if anyone else is still experiencing issues with this, please create a new issue.
