### ISSUE TITLE
How to share my bookmarks between min, Chrome and others?

### ISSUE THREAD

**Issue by orschiro** [minbrowser/min#275]
Hi all, 

Does anyone have a solution how to sync and share bookmarks between min and the other major browsers?

**Comment by PalmerAL** [comment]
This isn't currently possible, and will likely be difficult to implement. Each browser has its own, often quite complicated, format for storing this data, and they don't all store the same data. There is more discussion about this in #28, but it's unlikely that this will be implemented.

**Comment by orschiro** [comment]
I see. Thank you for your reply.

**Comment by Docbroke** [comment]
You could use a common bookmarks file, and a script to use it with any browser you use. like
https://github.com/okraits/boosta
https://github.com/Docbroke/w3m-dmenu/blob/master/dmenu-browse
