### ISSUE TITLE
Problems with podparadise.com

### ISSUE THREAD

**Issue by orschiro** [minbrowser/min#278]
![image](https://cloud.githubusercontent.com/assets/170947/20671370/7283cd4e-b57d-11e6-90e5-f7e5a61343ba.png)

https://www.podparadise.com/Podcast/Listen?i=896657073&d=1480313426&o=0

**Comment by PalmerAL** [comment]
The reason for this is that the webpage is HTTPS, but the image and audio files are HTTP. The default in Electron is to block mixed content, so the files don't load.

Electron provides an <a href="http://electron.atom.io/docs/api/web-view-tag/#webpreferences">option</a> to match what other browsers do. I can't think of any downsides of doing that, although it is slightly less secure.

**Comment by PalmerAL** [comment]
This was fixed in an Electron update (I forget which one exactly).
