### ISSUE TITLE
Support for Hangouts?

### ISSUE THREAD

**Issue by orschiro** [minbrowser/min#280]
Just noticed that Hangouts is not fully supported. 

Can anyone reproduce issues with Google Hangouts?

**Comment by PalmerAL** [comment]
I'm guessing this is because Min doesn't support websites asking for permission to use the camera and microphone. Right now, <a href="https://github.com/minbrowser/min/blob/master/js/webviews.js#L30">every request is blocked</a>.

**Comment by Sestowner** [comment]
I think this can be closed.
