### ISSUE TITLE
Feature request : How about a shortcut to switch tasks ?

### ISSUE THREAD

**Issue by thomasgrnr** [minbrowser/min#281]
Wdyt ?
Great app btw 👍

**Comment by PalmerAL** [comment]
Good idea!  What should the default shortcut for this be? There were some ideas in #149, but I'm not sure which one's best.

**Comment by PalmerAL** [comment]
Fixed in 258eae1e9230717558be7be08f0e4a6a2bfd8510. The default is mod+[ to go to next task, shift+mod+[ to go to previous, but you can modify them in settings.
