### ISSUE TITLE
Console logging of min

### ISSUE THREAD

**Issue by thomhos** [minbrowser/min#282]
Hello!

I am wondering if there's a way to remove the console logging that min does in the inspector? Right now it usually logs the phishing scan results etc.

Maybe there could be a verbosity setting somewhere in the preferences for this?

Cheers!

**Comment by PalmerAL** [comment]
Thanks for noticing that, that shouldn't be enabled by default!

Fixed in 2912364a4c18c9718a4913154d7063569775ce8d.
