### ISSUE TITLE
Build binaries on Windows

### ISSUE THREAD

**Issue by Pietrafixa** [minbrowser/min#285]
Hi how to build the Min Browser on Windows? In README.md it is described only how to build with OS X.

**Comment by PalmerAL** [comment]
You can run ```grunt windowsBuild``` to get a folder with an EXE that you can run. (The ```windows``` branch has a script to generate an installer, but I'm not sure if it still works)

**Comment by Pietrafixa** [comment]
Thanks so much. I just compiled binaries for Windows, I have not had any problems. **It all works to perfection.** I used the "Master" of the branch code. I replaced "`grunt-electron-debian-installer 0.3.0`" with "`grunt-electron-installer-windows `0.2.0`" in **package.json**. The same thing I did in "Gruntfile.js". It seems to work great.

**Comment by PalmerAL** [comment]
> A curiosity,but your browsing history has not been implemented?

Do you mean a page to view history? That hasn't been added yet, since searching for history works as well or better in most cases, but I can see how it would be useful.
