### ISSUE TITLE
reading view without dark mode not working

### ISSUE THREAD

**Issue by osnabryg** [minbrowser/min#286]
I appreciate the reader mode as a possibility to make websites readable for me, but it seems that I can't have the bright mode anymore. Even after reinstalling Min(browser) I always get the dark mode when toggling to the reading view.

Any advice?

Joachim Osnabryg

osnabryg@gmail.com

**Comment by PalmerAL** [comment]
Is the clock on your computer set correctly? Min will automatically switch to the dark mode at night (between 10 PM and 6 AM), so if the time on your computer is incorrect, it might cause the dark theme to be enabled.

**Comment by osnabryg** [comment]
Thank you very much for answering!

> Am 22.12.2016 um 23:15 schrieb PalmerAL <notifications@github.com>:
> 
> Is the clock on your computer set correctly?

Yes, the computer clock always shows the the correct time.

> Min will automatically switch to the dark mode at night (between 10 PM and 6 AM)

As far as I remember I tested it between 6 AM and 10 PM, with the result that in reader view I had always white on black (or dark mode). 

Moreover, in the options I did not enable dark mode.

I’ll test it again next day (i.e. later today), i.e. in day time after your definition, and write you again what’s happening in the „reader view".

By the way: I never want the dark mode, I have enormous difficulties to read white on black (or dark). 

Wait my next writing!

joachim

**Comment by osnabryg** [comment]
Am 23.12.2016 um 00:38 schrieb ich:

> As far as I remember I tested it between 6 AM and 10 PM, with the result that in reader view I had always white on black (or dark mode). 

Probably I remembered wrong, in „night time“ I saw the dark mode, and was incensed about the loss of the black-on-white view … 

> I’ll test it again next day (i.e. later today), i.e. in day time after your definition, and write you again what’s happening in the „reader view“.

And now - in day time - the reader view is (b)right and correct! At least it is black on white/bright. The problem is, that not all web pages can be depicted in reading view, sometimes despite that the icon for reader view is displayed in the tab header. OK, one can live with that …

But what do you say to my other argument:

> Moreover, in the options I did not enable dark mode.


I just learned by trial and error that this option indeed means to toggle the reader view - but consequently done only in day time. I would have expected, that this should also work in night time:

- reader view dark (white characters on black/dark) when this option is enabled;
- reader view bright (black/dark characters on white/bright) if „dark mode" is disabled.

This would be more consequentially and would really solve my problem:

> By the way: I never want the dark mode, I have enormous difficulties to read white on black (or dark). 

So, I’am still hoping that the Min(browser) application will be changed in that aspect … albeit by letting fall the option of dark mode.

May I finally take the liberty to add another proposal for readabilitie's sake?

Although the characters of almost all web pages are too small for my eyes and brain, I have to enlarge and enlarge every single page each time visiting by the shortcut. How much time I could save if I had the option to enlarge all pages to a certain amount or to set a freely choosen minimum character size!

**Comment by PalmerAL** [comment]
You're right, those should probably both be options.

**Comment by PalmerAL** [comment]
This is fixed in the latest release.
