### ISSUE TITLE
Feature request : A bolder page loading bar?

### ISSUE THREAD

**Issue by ashishwadekar** [minbrowser/min#287]
The page loading bar is very diffucult to spot. If it is made bolder i.e. thicker by 25%, that would be great from UX point of view.

**Comment by PalmerAL** [comment]
Currently, there's no page loading bar at all. Some websites (such as GitHub) include their own loading bar, which is possibly what you're seeing.

The issue for adding a loading bar is #52.

**Comment by ashishwadekar** [comment]
@PalmerAL Thanks fo the response whill check into issue #52
