### ISSUE TITLE
Access to all bookmarks

### ISSUE THREAD

**Issue by Cocophotos** [minbrowser/min#296]
Hi everyone,

Thanks for developing Min, it's really a great app!

I'm looking for the way to view all the bookmarking pages. I've basically looked everywhere with no success.

Could you help me with that, please?

Thanks a lot,

Best regards,

-- 
Corentin

**Comment by PalmerAL** [comment]
There isn't currently. Maybe a !bookmarks command, with a "Bookmarks" option in the View menu?

**Comment by skycrash** [comment]
The best browser until now, but a bookmark list is very helpful!!!

Great works
