### ISSUE TITLE
disable message: sites detected as malicious

### ISSUE THREAD

**Issue by skycrash** [minbrowser/min#315]
A option to disable or change page message, to a alert in the bottom or top page.
It's very boring many sites alerting.

Thank you

**Comment by PalmerAL** [comment]
Can you share examples of sites that this is happening on? It probably does make sense to make the warning less intrusive, but the warning shouldn't be showing at all on sites that aren't malicious.

**Comment by PalmerAL** [comment]
This feature has been removed in newer versions of Min.
