### ISSUE TITLE
Windows build?

### ISSUE THREAD

**Issue by Kasimirsuterwinter** [minbrowser/min#316]
I do not know how to make a windows build myself, but this project looks really cool!! I would love to use it. Thanks!

**Comment by PalmerAL** [comment]
Min mostly works on Windows, there just isn't packaging for it yet. You can download a Windows build from https://github.com/minbrowser/min/releases/tag/v1.5.1, and launch the Min.exe file to run it.

Please file bug reports for any bugs you find! Everything should work, but there's probably at least a few things that don't.

**Comment by Kasimirsuterwinter** [comment]
Thanks!

**Comment by dbfreem** [comment]
Windows builds are available so closing this issue.
