### ISSUE TITLE
Feature request: Back button, the ability to copy and paste

### ISSUE THREAD

**Issue by TinCan-Assassin** [minbrowser/min#319]
I was trying to copy and paste a link into Facebook and got a box that only says "Inspect element in both instances. Also, currently there is no way to go "back" to the page you were previously on.

**Comment by abejfehr** [comment]
For both of these things you can use the keyboard shortcuts. Copy and paste can be accomplished, on a Mac for example, using ⌘+C and ⌘+V respectively, and navigating backwards and forwards can be done with ⌘+← and ⌘+→.

Normally, "Copy" is present in the right-click menu when there's text selected, but there's a chance you could also be experiencing some of the "inconsistencies" mentioned in #55, in which case you should just try restarting the browser.

**Comment by abs-zero** [comment]
What is the keyboard shortcut for navigation for linux?

**Comment by code-hunger** [comment]
There is a 'Copy' option in the context menu now and a back button left of the tab list. I guess this can be closed already.
