### ISSUE TITLE
URL in tab doesn't update quickly enough on a single page site

### ISSUE THREAD

**Issue by abejfehr** [minbrowser/min#320]
To reproduce:

1. Visit this YouTube channel (for example): https://www.youtube.com/user/foodwishes/videos
2. Go to any one of his videos
3. Click on the tab to see the address (and attempt to share with friends) and notice that it's the same URL as from step 1
4. Click on a recommended video (on the right side)
5. Click on the tab to see the address, and see that it's now the URL of the video you were previously on, and not the current video

**Comment by PalmerAL** [comment]
Fixed in dc46adf08ed6c6077ef7d5b7df6630dae1d9caad.
