### ISSUE TITLE
Can't change preferences of swyping two fingers to get previous page or go next page.

### ISSUE THREAD

**Issue by antondexter** [minbrowser/min#322]
I can't navigate through large landscape pages with two fingers because MIN recognizes it as swipe gesture to get the previous page or go next page. Changing of system preferences of touchpad gestures on MacOSX to three fingers swipe doesn't work. MIN ignores system preferences of a touchpad.

**Comment by vinayh** [comment]
I would also like to request this preference. On a ThinkPad, it can be easy to trigger horizontal scrolling with a TrackPoint (red pointing stick).

**Comment by PalmerAL** [comment]
#284 should fix most of the accidental swipe gestures (A preference is still a good idea though).

**Comment by PalmerAL** [comment]
This has been fixed in #358.
