### ISSUE TITLE
Reader mode not working correctly on an article (1.5.1)

### ISSUE THREAD

**Issue by vinayh** [minbrowser/min#323]
I hope that this is the right place to report a site that does not fully work with the reader mode.

Version: 1.5.1
OS: Arch Linux (64-bit)
Website URL: http://www.telegraph.co.uk/technology/2017/02/16/yahoo-hack-warning-happened-should-worried/

Probably due to a box ("At a glance | High profile hacks") in the middle of the article, the reader mode only catches the first few paragraphs, until:
> "Based on the ongoing investigation, we believe a forged cookie may have been used in 2015 and 2016 to access your account."

The rest of the article is not captured by the reader mode, which makes it less than useful.

**Comment by PalmerAL** [comment]
Sorry for taking so long to respond to this! The content detection for reader view is based on Mozilla's <a href="https://github.com/mozilla/readability">readability</a> library. Since this seems to happen in Firefox's reader view as well, you should probably report it there.

**Comment by PalmerAL** [comment]
This appears to be fixed in the latest version of Min (which has an updated version of Readability).
