### ISSUE TITLE
Hello from Miniature web browser.

### ISSUE THREAD

**Issue by doreminiature** [minbrowser/min#324]
Just wanted to say hello and thank you for opportunity to build our ideas on top of your project, PalmerAL.
https://github.com/doreminiature/miniature

**Comment by PalmerAL** [comment]
Miniature looks interesting! I'll be interested to see what ideas you come up with.

**Comment by doreminiature** [comment]
Hello, @PalmerAL 
I am designer myself, learning to program currently. If you are interested in quick chat about the project, please write me a greeting message at doreminiature@gmail.com.
