### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by balbooaaa17** [minbrowser/min#325]
Ubuntu 16.04 32bit
Hello there , when i try to open min 1.5.1-1  after installing i get 

Uncaught Exception:
SyntaxError: Unexpected token } in JSON at position 40
    at /usr/share/min/resources/app/main.build.js:49:25
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)

**Comment by PalmerAL** [comment]
Sorry for reponding so late to this! Can you try deleting the file ```/home/<your username>/.config/Min/windowBounds.json``` and restarting Min?

**Comment by balbooaaa17** [comment]
Thank youuuuuuuuu dudeee , i had installed in my laptop and loved it , and when i tried to install it in another one it would show this error , naah bro , you're not late , it doesn't matter cuz i know u might have been bussy with stuffs , thanks a lot again and i'm in love this awesome&light  browser . Peace and out .

**Comment by PalmerAL** [comment]
Glad it worked!
