### ISSUE TITLE
Forward/Backward swiping not working

### ISSUE THREAD

**Issue by cgm707** [minbrowser/min#329]
This app is frustrating. Many times, I cannot go back to the previous page, or forward. Swiping does nothing. There should be another option to move around between web pages

**Comment by z3t0** [comment]
It just seems that it requires a fairly long swipe

**Comment by z3t0** [comment]
https://github.com/minbrowser/min/blob/d1db4753aff7f4a8c038c1ef54371714e95a6cc9/js/webview/swipeEvents.js#L21

**Comment by PalmerAL** [comment]
The swipe gestures have been completely rewritten in the unreleased master branch, so the code @z3t0 linked above isn't the same as what's included in 1.5.1.

@cgm707 Could you try installing the master branch of Min and seeing if that works better?

**Comment by Syndamia** [comment]
This seems to be fixed in the new version(s), can you confirm @PalmerAL?
