### ISSUE TITLE
Request: allow user to change search engine

### ISSUE THREAD

**Issue by bcooney** [minbrowser/min#33]
While I love your UI, DDG is blocked in my country (China)

`PING duckduckgo.com (93.46.8.89): 56 data bytes`
`Request timeout for icmp_seq 0`
`Request timeout for icmp_seq 1`
`Request timeout for icmp_seq 2`
`Request timeout for icmp_seq 3`

It would be great to be able to change to the search engine of my choice.

**Comment by PalmerAL** [comment]
Fixed in 1e156d57fe8eebd0030fec33ef1648821e9913f0. The search engines that are currently included are:

* DuckDuckGo
* Google
* Bing
* Yahoo
* Baidu
* StartPage
* Wikipedia
* None (everything entered in the searchbar gets treated as a URL)

Are there any other major search engines I left out?

**Comment by PalmerAL** [comment]
Closing this since it's been fixed.

**Comment by wb9688** [comment]
You left out Yandex, not that I use it…

**Comment by PalmerAL** [comment]
@wb9688 Added in 01d8b7ddee15bcbf8c8e4175d1d589402fed4ad0.
