### ISSUE TITLE
Scrolling with touchpad triggers back/next

### ISSUE THREAD

**Issue by Docbroke** [minbrowser/min#330]
While I scroll on webpage using twofinglescroll, as soon as I reach top of the page it triggers back, and previously used page loads automatically. Similary next page loads when scrolled to the bottom. This is very annoying as this back and next page loads are not intended mostly.

**Comment by PalmerAL** [comment]
This should be fixed by #284.

**Comment by malbiruk** [comment]
It didn't help me. I tried to redesign the swipe gestures by copying file from your link to js/webview/swipeEvents.js. Am I doing something wrong?
