### ISSUE TITLE
use bing search engine error

### ISSUE THREAD

**Issue by handelxh** [minbrowser/min#333]
when i search "struct mt_chip_conf " in bing engine. The return is nothing like the result that search by using chrome.
url "http://cn.bing.com/"

**Comment by PalmerAL** [comment]
I don't think this is a bug in Min. This is probably the result of a couple of things:
 - Bing is likely tracking what searches you've made previously and using that to adjust the results. If you've searched using Bing in Chrome previously, that will change the results you get.
 - Bing seems to randomize their results. If I open multiple private tabs in Min, or create multiple private windows in Chrome, the order of the results changes each time.
