### ISSUE TITLE
Windows build icon not defined 

### ISSUE THREAD

**Issue by dreamfliper** [minbrowser/min#334]
I download version 1.5.1. It seems windows build is electron default icon, not Min icon.
![2017-04-07 11 16 22](https://cloud.githubusercontent.com/assets/7656086/24784231/b0c4f382-1b83-11e7-99ea-1e9180bf87ff.png)

**Comment by DylanC** [comment]
+1 Also have this issue.

**Comment by PalmerAL** [comment]
This has been fixed for a while now.
