### ISSUE TITLE
Sometimes only one tab is working. 

### ISSUE THREAD

**Issue by lolAJhere** [minbrowser/min#345]
This is a weird problem i am getting consistently.
I am using one tab for surfing web then i open a new page in new tab, the page loads, title also shows.
i could click on the new page links, but nothing shows up.

**Comment by PalmerAL** [comment]
What operating system/version are you using? Also, how are you opening a new tab (context menu, ctrl+click, new tab button, etc.)? When you click a link, does the current page disappear or freeze (like a new page is loading) or does nothing happen? Also, could you open the console (Developer menu > Inspect browser > Console tab), and copy-paste (or take a screenshot of) any errors that show up? Thanks!

**Comment by lolAJhere** [comment]
I am using Manjaro Linux, I downloaded min from aur. The min version is 1.5.1-1.
I found that when i play video in one tab then try to opening any new tab by any method doesn't work(I mean the page loads, I could click the links in the invisible page etc). If I didn't watch any videos(like video from youtube, or any other site ) then it works fine, but once I watch one video then it doesn't work.
Let me get errors if I get any.
Thanks for reply.

**Comment by lolAJhere** [comment]
![image](https://cloud.githubusercontent.com/assets/18498932/25338635/a2d752c0-291f-11e7-991a-ef8dd4667b67.png)
As you can see in the image above, I watched the first tab video, then I right clicked the recommended channel and chose open in new tab, the new tab loads completely even plays video(How do I know?
I can hear sounds.) Then I open inspect browser, Even this tab doesn't show up.

**Comment by PalmerAL** [comment]
I think this is probably the same issue as brave/browser-laptop#1471 (and #223, #256). Can you try running Min with the ```--ignore-gpu-blacklist``` flag, or if that doesn't work, ```--disable-gpu```.

**Comment by lolAJhere** [comment]
@PalmerAL Both Flag Works. Thanks for the tip.

**Comment by lolAJhere** [comment]
How do you mark this thread as duplicate?

**Comment by PalmerAL** [comment]
Good to know! BTW, using ```--ignore-gpu-blacklist``` is probably better than ```--disable-gpu```, since the second option will disable hardware acceleration completely and make Min slower.

GitHub doesn't have a specific "mark as duplicate" function - you can just close this issue using the "close issue" button at the bottom. If you mention another issue with a # sign (like in the comment above), a link to this issue will show up in the other issue.

**Comment by lolAJhere** [comment]
yeah, I am using `--ignore-gpu-blacklist` because its better to remember.
Peace.
Thanks.
