### ISSUE TITLE
Shortcuts for tasks managing

### ISSUE THREAD

**Issue by malbiruk** [minbrowser/min#346]
It would be amazing, if you add a possibility to close, rename and switch tasks via shortcuts.

**Comment by malbiruk** [comment]
Oh yeah, and search for tabs.

**Comment by PalmerAL** [comment]
`!closetask` and `!task` shortcuts were added a while ago; I've just added a `!nametask` shortcut in d780446fb9cc1a361fbf6b8419dfca7a5d0dbdc0. You can search for tabs from the searchbar by just typing part of the name; they'll show up near the bottom of the list.
