### ISSUE TITLE
Hidden menu bar unhides when exiting fullscreen on media

### ISSUE THREAD

**Issue by CherryMan** [minbrowser/min#348]
When I exit fullscreen on platforms like youtube or twitch, the menu bar, which was previously hidden, reappears. I have to manually hide it again every time which can get annoying. I'm running min on Linux.

Could there also be an option to permanently hide the menu bar?

**Comment by Syndamia** [comment]
@CherryMan do you remember what distro (and desktop environment) were you using at the time?

Also, if you still use Min, are you having this issue?

**Comment by CherryMan** [comment]
Not sure what my setup was at the time, but probably some tiling window manager on either Arch, Void, or Gentoo. I don't use min anymore, but I just tried it and can't seem to reproduce the error so it might have been fixed, as I'm running a similar setup (bspwm on Arch).

**Comment by PalmerAL** [comment]
Yeah, this was fixed in f50853a438664038de16363786b9c2c1300ee333.
