### ISSUE TITLE
Dark mode for tabs?

### ISSUE THREAD

**Issue by egordorichev** [minbrowser/min#350]

**Comment by PalmerAL** [comment]
Have you enabled the dark mode in preferences > appearance? That should make the tab colors darker:

<img width="1440" alt="screen shot 2017-05-04" src="https://cloud.githubusercontent.com/assets/10314059/25728089/9403304a-30f2-11e7-8858-0a85bc1511c9.png">
<img width="1440" alt="screen shot 2017-05-04-2" src="https://cloud.githubusercontent.com/assets/10314059/25728088/93fe79d8-30f2-11e7-86b8-5b030f2d6ba1.png">

New tabs are still white though, which should probably be fixed.

**Comment by razzintown** [comment]
I think that new tabs should be dark in dark mode.

**Comment by PalmerAL** [comment]
@razzintown This was actually fixed starting in 1.6.1 (which was released yesterday):

![screen shot 2017-09-06](https://user-images.githubusercontent.com/10314059/30136576-354e7894-9325-11e7-8f76-7308aa1fa428.png)

Thanks for reminding me to close this issue!
