### ISSUE TITLE
Can't play youtube videos 

### ISSUE THREAD

**Issue by neymarsabin** [minbrowser/min#353]
I am using min browser in my Arch Linux. Everything seems to work fine but i cannot play youtube videos. Whenever i try to play one it gets stuck in the loading screen. And it gets stuck forever.

**Comment by code-hunger** [comment]
I think I had the same problem in qutebrowser which uses webkit, too, and the solution was to install some GStreamer plugins:
http://stackoverflow.com/a/30163950
I hope this will work for you, too.

**Comment by neymarsabin** [comment]
Thanks for the answer @code-hunger but that didn't help.

**Comment by AJgotBeard** [comment]
I got same problem. I didn't notice till I saw your issue.
(I don't use youtube much so.)

**Comment by hippylover** [comment]
After trying to recompile every damn lib electron and min depends upon i finally fixed it by downloading min from aur instead of repo and/or recompiling & installing http-parser. So it was 1 of those that fixed it.

**Comment by neymarsabin** [comment]
Downloding min from AUR worked for me too...Thanks for the information @hippylover

**Comment by hippylover** [comment]
@code-hunger That might work, i wouldn't know. If you look at the PKGBUILD from aur, he just downloads the deb file from github and unpacks that.

**Comment by coreymwamba** [comment]
I have a smiliar issue. The page loads, but the video displays an error. 
Here's a sample video's debug info:
``
{
  "ns": "yt",
  "el": "detailpage",
  "cpn": "tY9C2d31dXvLWKwb",
  "docid": "DEUKM-n3dq8",
  "ver": 2,
  "cmt": "0",
  "plid": "AAVUgRybLIDutdRu",
  "ei": "hpVsWe3QMNCgWr7fgbgG",
  "fmt": "242",
  "fs": "0",
  "rt": "65.42",
  "of": "02cLPHQoDjwshX8aM1L68A",
  "euri": "",
  "lact": 2,
  "cl": "161729839",
  "mos": 0,
  "state": "c9",
  "vm": "CAMQABgB",
  "volume": 100,
  "c": "WEB",
  "cver": "1.20170712",
  "cplayer": "UNIPLAYER",
  "cbr": "Chrome",
  "cbrver": "53.0.2785.143",
  "cos": "X11",
  "hl": "en_GB",
  "cr": "GB",
  "len": "3253.961",
  "fexp": "9413138,9419451,9422596,9431012,9434289,9444442,9446364,9447922,9449243,9453897,9457141,9457285,9463594,9466593,9466793,9466795,9466797,9467217,9468797,9468799,9468805,9471161,9471430,9474357,9475003,9476492,9477080,9477460,9478685,9480475,9480535,9481734,9482647,9483356",
  "afmt": "251",
  "vct": "0.000",
  "vd": "NaN",
  "vpl": "",
  "vbu": "",
  "vpa": true,
  "vsk": false,
  "ven": false,
  "vpr": 1,
  "vrs": 0,
  "vns": 0,
  "vec": null,
  "vvol": 1,
  "debug_error": {
    "errorCode": "fmt.unplayable",
    "errorDetail": "mediaElem.1",
    "message": "An error has occurred. Please try again later.",
    "messageKey": "YTP_ERROR_GENERIC_WITHOUT_LINK"
  },
  "ismb": 18940000,
  "relative_loudness": "-6.599",
  "optimal_format": "240p",
  "user_qual": "auto",
  "debug_videoId": "DEUKM-n3dq8",
  "0sz": false,
  "op": "",
  "yof": false,
  "dis": "",
  "gpu": "Mesa_DRI_Intel(R)_Ironlake_Mobile_",
  "cgr": true,
  "debug_playbackQuality": "small",
  "debug_date": "Mon Jul 17 2017 11:47:37 GMT+0100 (BST)"
}
``

**Comment by PalmerAL** [comment]
@coreymwamba How did you install Min?

**Comment by coreymwamba** [comment]
@PalmerAL through the Arch Community repository (i.e. an official one).

**Comment by neymarsabin** [comment]
@coreymwamba installing from Arch User Repository solved my problem back then... I used yaourt. You should try it too.

**Comment by coreymwamba** [comment]
So - does this mean that the official package is incorrectly packaged? Because then that needs reporting.

**Comment by coreymwamba** [comment]
Now reported at https://bugs.archlinux.org/task/54869

**Comment by neymarsabin** [comment]
nice job @coreymwamba !! Do u still have  the problem? or is it solved??

**Comment by coreymwamba** [comment]
@neymarsabin I installed from the AUR and it works. The size of the package was 155MB - over ten times the size of the community package (15MB) - so I think there is a packaging error in Arch's community repository.

**Comment by neymarsabin** [comment]
There might be one... @coreymwamba i think, size does not matter when you are getting the latest release.Glad that your problem was solved.

**Comment by wh75er** [comment]
Downloading min from AUR helped me
I didnt watch any videos from the internet cause of that standard package
Thank you for this issue

**Comment by neymarsabin** [comment]
Glad to be of help @wh75er

**Comment by anko** [comment]
I also have this problem, having downloaded the current `master` at e5963ec7c1dfe67be171fe7f7271617b8610aaa5 and built it myself according to the readme instructions.

How it looks:

![1505054887_d60d8a47](https://user-images.githubusercontent.com/5231746/30250000-7fc4895a-963f-11e7-9b65-91ce53958a25.png)

```
$ uname --operating-system
GNU/Linux
$ node -v
v8.4.0
$ electron -v
v1.6.11
```

No errors in the console, except from Google ads being blocked.

**Comment by gerbensewuster** [comment]
Same problem and error message as anko.
same electron version

**Comment by steve-1776** [comment]
Confirming here on Arch I just removed the Min from the official package and installed from AUR and numerous issues have cleared up, including youtube video playback, which now works.

**Comment by dbfreem** [comment]
Does anyone know if the playback issue still exist for Arch?

**Comment by KagamineP** [comment]
I think this outdated, so I close this now. Feel free to reopen.

**Comment by St-Galaad** [comment]
Hi, 
On my Win7 x64, I've an issue with "Min" when loading à Youtube video, a Dailymotion video, etc.
I tested on "Min-v1.22.1_(GitHub)_[15-11-2021]" and the latest "Min-v1.22.2_(GitHub)_[27-12-2022]", both make the same result; "Min" close suddenly ! No error message, nothing. After the Min's window closed I can reopen it with no difficulty and try to play another Youtube video until "Min" crash.
The isssue came only when I start to play the video after it have been loaded without a pb.
I read a lot of descriptions of issues and this title "Can't play youtube videos" match to my pb.
I've no more idea of the origin of this crash so i post here, maybe it's related to Win7 ?
If someone have an explanation, a solution, I take it.
Thanks.
