### ISSUE TITLE
How the settings work?

### ISSUE THREAD

**Issue by code-hunger** [minbrowser/min#354]
Looking at the settings object, if I want to add a new setting, I need the `set` and `get` methods. I'm confused because both methods receive a callback.

I added a new checkbox in the settings page, called `#x`. Now I want to do four things:

1. Set a callback for when the setting is changed
2. Have a function to change browser state (e.g. do something with the DOM)
3. Set the value of the setting, true or false
4. Call the setting function on checkbox change
```
var checkbox = ....selectById('x')
checkbox.onclik ( ... settings.set('x', this.checked) ... )
function doX (value) { ... act according to value ... }
settings.set( x, doX  )
```
Once I need to set the callback (line 4), and another time - set the value (line 2). But `.set()` needs both a value and a callback; these two actions are somehow combined. What do I do then?

**Comment by PalmerAL** [comment]
The callback for set() is optional; if you give a callback, it will run after the value has been written to the database, but you can just do set(key, value) if you don't need to do anything. 

To add a checkbox to the settings page, you could do something like this:

```
var checkbox = document.getElementById('example');

//set the initial value of the checkbox

settings.get('example', function (value) {
    if(value === null || value === undefined) {
        value = true; //default to true if the user has never changed the setting
    }
    checkbox.checked = value;
});

//update the setting when the checkbox state is changed

checkbox.addEventListener('change', function() {
    settings.set('example', this.checked)
});
```

I think on line 4 in your example, you want to get the value and update the checkbox based on that, so you would use ```settings.get(key, function(value) { //do something });```.

**Comment by code-hunger** [comment]
Ok, so we use `.get(` to *set* the callback? But then how do I trigger it here:
```
checkbox.addEventListener('change', function() {
    settings.set('example', this.checked)
    // trigger the callback here - looking at the source this is not done automatically,
    // and the callback is an anonymous function. I should probably make it a normal function and both pass it to .get() and call it here.
});
```

**Comment by PalmerAL** [comment]
I'm not sure I understand your question.

get() gets the value of a setting. It takes three arguments:

* the name of the setting
* a callback to run that is given the value of the setting

So in this code:

```
settings.get(key, function(value) {
    //do stuff
});
```

The setting with name ```key``` will be read, and the function will be run. When the function is run, ```value``` will be equal to the value of the setting.


set() sets the value of a setting. It takes three arguments:
* The name of the setting
* The value to set the setting to
* An optional function that will run once the setting has been saved

So in this code:

```
settings.set(key, value, function() {
    
});
```

The the value ```value``` for the setting ```key``` will be written to the database, and then the function will be called.

In your example, if you wanted to run a callback after the value has been updated, you would do this:

```
checkbox.addEventListener('change', function() {
    settings.set('example', this.checked, function() {
        //this will run once the new value has been written to the database
    })
});

**Comment by code-hunger** [comment]
Got it! I had totally different assumptions about how a settings object should work.

I thought I set a callback once in the beginning, which would be called everytime the setting was changed.
Then, `.set(` was used to change the value. (no callbacks here)
Finally, `.get(` to receive the value where I'd needed. (just `value = settings.get('prop')`)

Now as I understand it, the call to `get()` (and to the database, respectively) is asynchronous and there's no way get the value immediately (i.e. via return) and that's why we need a callback.
Thanks!

**Comment by PalmerAL** [comment]
OK, I see why that makes sense! (I've actually been thinking about adding something like ```settings.listen(key, callback)``` that would be run when the setting changes like you describe, since eventually it would be nice to support changing settings without a restart).
