### ISSUE TITLE
mod+w from the task overlay doesn't work correctly

### ISSUE THREAD

**Issue by PalmerAL** [minbrowser/min#357]
This should close the tab and update the overlay.

**Comment by code-hunger** [comment]
(let me call the task overlay *TO*)
There's a more general problem with the TO currently: keyboard events are sent to the browser "*behind*" it and not to the TO itself.

For example, if you press Ctrl+Tab in the TO you'll switch to the next tab "*behind*".
Or, if you open a youtube video and open the TO, pressing "k" will stop the video.

This behaviour is undesired - I think the TO should be a standalone tab-like page with its own keyboard shortcuts. This will fix the issues above and will allow a much easier impl of keyboard control of the TO (which, in turn, will close a number of issues).

**Comment by code-hunger** [comment]
I just noted another similar bug and fixed it in https://github.com/minbrowser/min/pull/352/commits/897d6e0bed37c1c7b61901d464ec82c1b0fc4437
Ctrl+Tab now updates the focused tab element successfully.

**Comment by PalmerAL** [comment]
Rather than adding code for each individual listener, I think it would be better if tabState had a way to listen for changes to the tab state. Then the task overlay could just listen for changes and update its contents whenever the state changes. That would reduce a lot of duplication, and fix all of these bugs without adding too much complexity.

**Comment by code-hunger** [comment]
Looking at the [MDN Guide](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events) is should be pretty simple to implement this.

For example, for all close buttons we can add this:
```
var tabClosedEvent = new CustomEvent('tabClosed', {
  task: task,
  tab: tab,
  source: /* e.g. TaskOverlay or NavbarTabs */
});
document.dispatchEvent(tabClosedEvent);
```
Then we could create various listeners for this event, like:
```
// in taskOverlay:
document.addEventListener('tabClose', function(e) { taskOverlay.update(t.task); });
// in navbarTabs:
document.addEventListener('tabClose', function(e) {
  destroyTab(e.tab);
  // remove navbar tab element
});
```

**Comment by PalmerAL** [comment]
It would probably be even simpler to have something like ```tasks.listenForChanges(callback)``` that would be called whenever the state of a task or its tabs change.  Then the task overlay could re-render the task element corresponding to the task that was changed.

**Comment by Syndamia** [comment]
@PalmerAL is this still relevant? Also, I'm not sure I understand what the issue is.

**Comment by PalmerAL** [comment]
Yup, nothing's really changed regarding this.

To reproduce the issue, open the task overlay, and then press cmd+w to close the current tab, or cmd+t to create a new tab. The changes should be reflected in the overlay, but they aren't.
