### ISSUE TITLE
2 finger swiping to go back/forward on mac is buggy

### ISSUE THREAD

**Issue by schu34** [minbrowser/min#36]
If I swipe right to go back a page, Min goes back 2 pages in my history. For example if if I'm on site A and I leave that site to search for somthing and click a link in the search results then swipe to go back, I'll end up back on site A instead of back on the search results page.

**Comment by PalmerAL** [comment]
The swipe gesture system was rewritten a while ago to be more accurate, and I haven't seen this issue since then. If you notice this again in a newer version of Min, please feel free to open a new issue.
