### ISSUE TITLE
Escape key behaviour

### ISSUE THREAD

**Issue by owlas** [minbrowser/min#363]
Ubuntu 16.04

After pressing escape, I can no longer interact with the page with my keyboard: arrows do not move page, space bar does not scroll. This is a particular problem when using jupyter notebooks and other web apps that use escape as a command.

Current workarounds:
 - Pressing tab initiates highlighting of fields and I can interact again (but will scroll back to the top of the page!)
 - Command keys still work. E.g. I can switch away from the tab and back again and then I can interact again.

**Comment by PalmerAL** [comment]
Apparently there's a bug in Electron where focusing a webview that is already focused causes it to act as if it isn't focused. I've added a workaround for this in bbc2df6db22ad8bb70a0af83744f6d9bb3f52923. Thanks for reporting this!

**Comment by owlas** [comment]
That's a record breaking response time!

Thanks for the fix.
