### ISSUE TITLE
Shortcut for reload the browser

### ISSUE THREAD

**Issue by tunnckoCore** [minbrowser/min#365]
Would be good, for keyboard-oriented people.

**Comment by AJgotBeard** [comment]
Check the min shortcuts [here](https://github.com/minbrowser/min/wiki#keyboard-shortcuts).

> reload tab	       ⌘ r      	quickly press twice in succession: reloads all tabs

**Comment by 3rdey3** [comment]
Ctrl-R is not working on windows. F5 works. Is there any reload button or menu item? I don't see one.

**Comment by PalmerAL** [comment]
@3rdey3 No, there's not.

**Comment by Sestowner** [comment]
I think this can be closed.
