### ISSUE TITLE
Creative commons download page does not shown properly

### ISSUE THREAD

**Issue by somenxavier** [minbrowser/min#368]
See [this](https://creativecommons.org/about/downloads/). The icons are not shown

**Comment by code-hunger** [comment]
Do you mean these? I don't see any problem.
![icons screenshot](https://user-images.githubusercontent.com/11772321/27240516-b07d1d1e-52dd-11e7-8699-420d5e7cc075.png)

**Comment by somenxavier** [comment]
Yes I meant that.
