### ISSUE TITLE
gmail display weird notification

### ISSUE THREAD

**Issue by jsavalle** [minbrowser/min#374]
Gmail display systematically:
"This version of Chrome is no longer supported. Please upgrade to a supported browser. Dismiss"

Leave alone the fact that this is not Chrome - what is triggering this notifcation?

**Comment by PalmerAL** [comment]
I think it's because Min is using an old version of the Chromium engine - I am planning on releasing a new version later this week that should make the message go away.

**Comment by dbfreem** [comment]
Duplicate #485
