### ISSUE TITLE
Refresh cache

### ISSUE THREAD

**Issue by jerryskye** [minbrowser/min#381]
It seems like neither refreshing a single tab nor reloading the entire browser refreshes cache. The only way to do this is to browse privately. Btw, I love your browser guys 😄

**Comment by PalmerAL** [comment]
Reloading a tab uses the <a href="https://github.com/minbrowser/min/blob/master/js/keybindings.js#L344">reloadIgnoringCache</a> method, so I'm guessing this is a bug in Electron. Is there a way to consistently reproduce this so it can be reported to them?

**Comment by jerryskye** [comment]
I was just developing a webapp and I noticed that the updates in my static files didn't show up in the browser, because it was loading an earlier version of the document from cache.

**Comment by WebShapedBiz** [comment]
Same here, version 1.7.1. on Linux, cannot force it to load an updated hero picture on the web page.

**Comment by PalmerAL** [comment]
The latest release added a keyboard shortcut for this.
