### ISSUE TITLE
很多快捷键在linux上无效

### ISSUE THREAD

**Issue by AlexanderIssacs** [minbrowser/min#382]
many keyboard shortcuts doesnt work in linux,like "back",the very important shortcut.

**Comment by PalmerAL** [comment]
The "back" shortcut works for me in an Ubuntu VM. Have you changed any of the shortcut settings? What Linux distribution are you using? What keyboard layout do you have?

**Comment by AlexanderIssacs** [comment]
kali rolling and windows laptop keyboard layout.i never change any shortcut settings,eh.....im using enter “!back” in address bar to back.

**Comment by dbfreem** [comment]
There haven't been any other reports of this. Also it was reported two years ago. If the issue persist this issue can be reopened
