### ISSUE TITLE
PDF Viewer

### ISSUE THREAD

**Issue by sumozski** [minbrowser/min#389]
All PDFs that i open go to this pdf with title "Trace-based Just-in-Time Type Specialization for DynamicLanguages"

**Comment by PalmerAL** [comment]
Sorry about that! What you're seeing is the default PDF that pdf.js uses as a demo; this was fixed to show the correct PDF file 1355fcec342c8ffa7a13ee1a94cd5caef70092a3. I should have time to release 1.6.1 with the fix for this by the end of this weekend.

**Comment by PalmerAL** [comment]
1.6.1 has been released, you can download it from here: https://github.com/minbrowser/min/releases.
