### ISSUE TITLE
File Download

### ISSUE THREAD

**Issue by sumozski** [minbrowser/min#392]
I can't download a file from a .jsf script link. And i think some download manager to notificate a finished download is necessary

**Comment by Malmsten94** [comment]
Agreed!

**Comment by bedartha** [comment]
I have been using Min for a week or so now on macOS and I love it 👍 

I also noted a strange discrepancy with file downloading - the "Save As" pop-up window manages to detect the filename but removes the file extensions. This leads to problems when I myself do not know what the extension is supposed to be. E.g., in download the installer for an app it could be either ".dmg" or ".pkg" and I don't know which and the browser also does not tell me.

**Comment by code-hunger** [comment]
@bedartha If it's an executable - just run it no matter of the extension; if it's a document open it with your document reader, for an image use your image viewer - an extension is just for your convenience but you should know what you're downloading anyway, so in your case it shouldn't be a problem.

It's min's job to fix these extensions, though, I agree, so can you give an example where it doesn't work?

E.g. if I try to download your profile pic it works as expected (i.e. the jpg ext is put in the Save-as box): https://avatars1.githubusercontent.com/u/4247812?v=4&s=400

**Comment by bedartha** [comment]
@code-hunger but it doesn't really work for me. (Or am I missing something here?)
Let's take the example of my profile pic, so when I follow the link in your post and on the image, I do: Right-click -> Save Image As, I get this dialog:
![screen shot 2017-09-28 at 10 10 28](https://user-images.githubusercontent.com/4247812/30955881-8e177e0a-a435-11e7-9622-9477a766f832.png)
and after saving it, the file in my Downloads folder appears as:
![screen shot 2017-09-28 at 10 10 42](https://user-images.githubusercontent.com/4247812/30955901-9d49abb4-a435-11e7-82d0-b9853892375f.png)
So, I think, in my case, Min is failing to detect the "jpg" file extension.
I can of course now append the extension to the file name and it will work fine, but as I pointed out in my earlier comment, in cases when I am downloading an app from its homepage where it simply says "Click here to download the app" or something like that, I might not know beforehand whether the app is being distributed as a "pkg" or as a "dmg".

**Comment by PalmerAL** [comment]
@code-hunger The bug mentioned above only happens on macOS, which is probably why you're not seeing this. On macOS at least (not sure about other operating systems?), your default apps won't be used until you add a file extension.

**Comment by PalmerAL** [comment]
I've released a 1.6.3 build that includes the latest version of Electron, which should solve this problem. You can download it from here: https://github.com/minbrowser/min/releases.
