### ISSUE TITLE
How to use 'pak' files for locale setting?

### ISSUE THREAD

**Issue by fethomm** [minbrowser/min#396]
I am writing an article on Min. I would like to point my mostly german readers to a way to localize the browser to german. I see the 'pak' files, but no way to make use of them. Any help appreciated.

**Comment by PalmerAL** [comment]
There currently isn't a way to change the browser language. I should be able to add this by the end of the week - I'll look into it tomorrow.

**Comment by fethomm** [comment]
That would be fantastic and a treat to my readers. The article goes to the editor on Sept. 18th. I would be happy to mention your quick response and helpfulness. Thank you for your work.

**Comment by PalmerAL** [comment]
OK, good to know, I should be able to finish this in the next few days.

I don't speak German myself - once I have a list of strings to translate (probably by tomorrow or Wednesday), would you or @burnoutberni mind translating them into German?

**Comment by fethomm** [comment]
I'll be glad to help. Just send the strings when you have them and I will translate them.

**Comment by PalmerAL** [comment]
I've added support for this in 92daf904bb1e81562a343d91b884ec807f49ed76.

Could you translate the strings in <a href="https://github.com/minbrowser/min/blob/master/localization/languages/de.json">localization/languages/de.json</a>? In the second column, just replace the English string with the translation. I've added some comments to explain how the strings are used; let me know if you have any questions. Thanks!

**Comment by fethomm** [comment]
I translated all strings, got distracted with something else. I did not save it since I wanted to go over it once more. After ~ 30 minutes Chrome jumps back to the GitHub page and everything was gone. I hope it got saved somewhere. If not, I will give it another go tomorrow.

**Comment by PalmerAL** [comment]
Sorry to hear that. Yeah, I don't think GitHub saves anything until you click commit. You could do multiple commits - translate the strings, commit those changes, come back to it later, make another commit - if you wanted to.

**Comment by fethomm** [comment]
This time things worked out, pull request is done. I have been working with GitHub and other git setups (favourite right now is Gitea) for a couple years, but never lost any data. I guess there is a first time for everything.

**Comment by PalmerAL** [comment]
I've merged your PR in #401, and added an explanation of the hosts file string. I really appreciate you doing this!

**Comment by fethomm** [comment]
Translated the 'hosts entry' string. Please let me know when 1.6.2 is available so I can check it live.

**Comment by PalmerAL** [comment]
Released: https://github.com/minbrowser/min/releases/tag/v1.6.2.

**Comment by fethomm** [comment]
Looking good, thank you!

**Comment by fethomm** [comment]
Found one typo. In the file menu (Datei), first entry is NeuerTab, needs to be: Neuer Tab

**Comment by PalmerAL** [comment]
Fixed in 69c708572ec0a9ab2a3956abe5072c5228c29209.

**Comment by PalmerAL** [comment]
I've updated the binaries in the release.

**Comment by fethomm** [comment]
Great, just in time before they go on the DVD for german magazine Linux User.
