### ISSUE TITLE
Any way to Duplicate tab?

### ISSUE THREAD

**Issue by mfarooqi** [minbrowser/min#400]
I'm a developer.. and I really loved your browser.. I'm a chrome user. but when i see developer options in it.. are the same as in chrome.. I would love to develop on this browser.. but.. there are few things... needed..
1. mouse hover on links... should have some tooltip or text as in otherbrowser to see.. where this link goes to..
2. duplicate tabs by pressing any shortcut or something..

**Comment by PalmerAL** [comment]
> mouse hover on links... should have some tooltip or text as in otherbrowser to see.. where this link goes to..

It's not quite as convenient, but you can right-click on the link and it will show in the context menu:

<img width="378" alt="screen shot 2017-09-15" src="https://user-images.githubusercontent.com/10314059/30508200-f4ddfc4c-9a56-11e7-8702-8fc891216b61.png">

> duplicate tabs by pressing any shortcut or something..

Yeah, I can see how this would be useful.

**Comment by mfarooqi** [comment]
Thanks for the reply. 
You are right.. that right-click can show this.. but you being a developer do understand .. what if we are playing with javascript event "onmousedown()"... :) That will proceed instead of showing me the context menu.  Secondly...  see below.. a longer string can be seen elsewhere instead of context menu.. isn't it..? 

![image](https://user-images.githubusercontent.com/6302459/30513573-09930286-9b1f-11e7-95b3-a3b72491172b.png)
