### ISSUE TITLE
Translation for traditional Chinese

### ISSUE THREAD

**Issue by ppromet** [minbrowser/min#403]
Would like to help translating Min into traditional Chinese (used in Hong Kong & Taiwan)
How can I help?

**Comment by PalmerAL** [comment]
Great! The language files are stored in the <a href="https://github.com/minbrowser/min/tree/master/localization/languages">localization/languages</a> directory. In that folder, there's an en-US.json file, containing the English strings. Make a copy of that file, and rename it to the language code listed here: https://electron.atom.io/docs/api/locales/. In this case, that would be ```zh-TW```.  In the zh-TW.json file you've created, change the ```name``` field on line 2 to "Chinese (Traditional)" and the "identifier" field to "zh-TW". Then, change each English string in the righthand column to the Chinese translation. Let me know if you have any questions!
