### ISSUE TITLE
Side mouse buttons are useless

### ISSUE THREAD

**Issue by BlueManCZ** [minbrowser/min#410]
Hello.

I have mouse with two side buttons, which I use for "go back" and "go forward" in other browsers.
But this feature doesn't work in Min. Can I somehow get this buttons work?

![jd755p_2](https://user-images.githubusercontent.com/17854950/30777438-c228961c-a0ba-11e7-8e0b-1da099f32815.png)

I'm using Debian 10 and _min_1.6.2_amd64.deb_ package.

**Comment by PalmerAL** [comment]
I think this requires support in Electron: electron/electron#6996.

**Comment by SpecialBomb** [comment]
@PalmerAL It appears to be possible. In Discord, you can register the back and forward buttons (mouse 8/9) for keybinds such as push to talk. This should therefore be very easy to implement within Min by adding code to keybindings.js or whatever. I have no idea what captures the mouse and keyboard inputs, so I wouldn't know where to start to fix it.

**Comment by PalmerAL** [comment]
Hmmm. The Discord app isn't open source, so we can't easily look at it to figure it out, unless we want to dig through their minified JS bundle. There's a native module to do this: https://github.com/jostrander/mouse-forward-back, but adding native modules makes it harder to build Min, so I've tried to avoid doing that. Maybe <a href="https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button">MouseEvent.button</a> has something useful?

**Comment by BlueManCZ** [comment]
```
document.addEventListener("mousemove", function(event){
    console.log(event.buttons);
});
```
If I run this script in chromium-based browsers, I can see during moving 9 and 17 output for side buttons. _(mousemove is bad solution)_ But this doesn't work in Min.

**Comment by PalmerAL** [comment]
@BlueManCZ Did you try moving the mouse over the webpage, or the navbar at the top? If you pasted that in the main browser console, its only going to work in the navbar; if you pasted it in the page console, its only going to work in the page.

If it works in Chromium, I would expect it to work in Min as well...

**Comment by BlueManCZ** [comment]
This is werid. If I paste code below to browser console, I see 8 and 16 as output. But in page console I see 9 and 17. This doesn't matter but it works. (Maybe any update fixed it). So can you bind events for "go back" and "go forward" functions on side buttons clicks?

**Comment by PalmerAL** [comment]
I guess so; which one's back and which one's forward?

It would also be know if this varies by mouse, so if anyone else has a mouse with side buttons, please try the script above as well

**Comment by BlueManCZ** [comment]
For me its **8 back** and **16 forward**.

But I don't know, how to get this works with  _mousedown_ event. Only left, middle and right button triggers this event for me.

**Comment by PalmerAL** [comment]
@BlueManCZ Does it work with a `click` event?

**Comment by BlueManCZ** [comment]
@PalmerAL Seems like not. Click event works only on the navbar and only with left mouse button.

**Comment by dlovric01** [comment]
Hello, is this resolved? I am new to Min browser and am unable to use side buttons for back and forward actions on my G305. Buttons work fine in other browsers.

**Comment by BlueManCZ** [comment]
> Hello, is this resolved? I am new to Min browser and am unable to use side buttons for back and forward actions on my G305. Buttons work fine in other browsers.

Hello, I can confirm it's now working fine for me with my Razer DeathAdder V2.

**Comment by dlovric01** [comment]
@BlueManCZ Thank you for your response, are you by any chance using it on Mac? On windows it works fine for me but on my Macbook Air its not.

**Comment by BlueManCZ** [comment]
@dlovric01 No, I tested it on Linux. I don't have a Mac to confirm it. You can try to boot a live Linux distro and test your mouse in Min there. It may be only a Mac related bug.

**Comment by PalmerAL** [comment]
Electron has an event for this on Windows and Linux, but it's not supported on macOS for some reason: https://www.electronjs.org/docs/latest/api/browser-window#event-app-command-windows-linux
We implement that here: https://github.com/minbrowser/min/blob/master/main/main.js#L288-L302

@dlovric01 This might be possible to implement by injecting some JS into webpages that listens for the mouse buttons (inside this code: https://github.com/minbrowser/min/blob/master/js/preload/default.js). Happy to accept a PR for this if you know of a working solution. It's going to be hard for me to do, since I don't have one of these mice.

**Comment by dlovric01** [comment]
After some debugging, I figured the problem was related to the version of Mac Mouse Fix 2 software I was using for custom commands, it seems like the default bind to back/forward button had a different command and after unbinding it, the side buttons work again as expected. It was weird because it worked normally in other browsers. 
@BlueManCZ and @PalmerAL sorry for bothering and thanks for your help.

**Comment by BlueManCZ** [comment]
No worries, I'm glad you found a solution. I probably can close this issue since it's been fixed for some time now and there is no real reason to keep this open.
