### ISSUE TITLE
Back/Forward buttons

### ISSUE THREAD

**Issue by SpecialBomb** [minbrowser/min#412]
It would be nice to have Forward and Back buttons in the Tab Bar. It's a common feature that many people rely on, as not many sites have dedicated "go back" links.

I am aware that you can right click, but then you have to move your mouse to somewhere a right click won't register, and it's just takes longer as well.

**Comment by code-hunger** [comment]
Dupe of #85

**Comment by PalmerAL** [comment]
Closing as duplicate.
