### ISSUE TITLE
Higher than 60hz support

### ISSUE THREAD

**Issue by SpecialBomb** [minbrowser/min#413]
Many electron applications allow for higher than 60fps rendering, such as Discord. It would be nice if Min could render at a screen's refresh rate.

**Comment by PalmerAL** [comment]
Does this not already work? I would think this would be the default in Electron, and I don't remember seeing anything in the documentation about this...

**Comment by SpecialBomb** [comment]
There are a lot of refresh problems in electron, all stemming from the fact
that it is based on chromium. However, the discord team has managed to get
it to work. I have recorded a bug or two for them involving it, however I
have no idea how they did it,

**Comment by dbfreem** [comment]
Not sure based on the thread if this is an issue or not. Maybe it can be closed and reopened if needed.

**Comment by PalmerAL** [comment]
I don't know either, I don't have a monitor higher than 60hz to test with. If it is still an issue, we should probably open an issue in the Electron repository about it.
