### ISSUE TITLE
Remove tab switching delay

### ISSUE THREAD

**Issue by SpecialBomb** [minbrowser/min#414]
When I click on a tab, there is a short 1 second delay until I can click another one. This is annoying.

Edit:

I did some experimentation, and it turns out that there may not be a delay at all. It has to do something with moving your cursor while you click, which for some reason does not register. This means that your cursor has to be 100% still to click on a tab. So, if you are used to quickly clicking through your tabs, this is a really big UI problem.

**Comment by SpecialBomb** [comment]
No matter how hard I look, I simply can't find why this happens. Blech. Where does Min handle mouse inputs?

**Comment by PalmerAL** [comment]
I think this is because of these lines:

https://github.com/minbrowser/min/blob/280bde25a227cf4fe38b3767e4fe3244c8a01b55/js/default.js#L82-L113

The intention of this was to fix #311, which was a bug where dragging the window while the mouse is hovering over a tab (which is possible on macOS, since the tab bar and the window buttons are combined into one line), caused a tab to be clicked when you didn't want it to. We probably need to add something to this to allow a little bit of movement (maybe 5px?) before the click-canceling behavior kicks in.

**Comment by SpecialBomb** [comment]
I see, will attempt tomorrow.

**Comment by SpecialBomb** [comment]
So, I think the best solution is to do this is to put a big if statement around all of this that checks if you are using a mac or not, the difference being that mac users can't quickly click tabs. In my opinion, that is the sacrifice you have made by putting part of the UI in the grab bar, but that's just me.

If you want to fix all of this, I would give the mac version the standard border back and keep the tabs within the window.

You could also specifically for mac add a dedicated drag bar, but you would still drag from the tabs.

**Comment by PalmerAL** [comment]
That would work on Linux and Windows, but it wouldn't fix the issue on Mac. I think (although I could be wrong) that when you're clicking quickly on a tab, the mouse is only moving a few pixels between the time when you press the mouse button down and when you release it. So when we update the ```isDragging``` variable, we could also keep track of how much the mouse is moving, and when the mouse is released, we can only cancel the click if the mouse has moved more than a certain amount. That should hopefully fix the issue on every platform.

**Comment by PalmerAL** [comment]
This was fixed by #423.

**Comment by PalmerAL** [comment]
The 1.7.0 version that includes this fix has been released, you can download it from here: https://github.com/minbrowser/min/releases/tag/v1.7.0.
