### ISSUE TITLE
Please add versions of nodejs and all other versions of important software in README.md

### ISSUE THREAD

**Issue by SpecialBomb** [minbrowser/min#416]
I would like to help fix bugs, but I can't even fix any if I have no idea what version of nodejs you are using to develop this.

**Comment by PalmerAL** [comment]
The node version is listed in the <a href="https://github.com/minbrowser/min/blob/master/.nvmrc">.nvmrc</a> file (although really any semi-recent version of Node should work fine, with the exception of a few that had an NPM bug that prevented you from building Min). Everything else should be listed in package.json. Is there anything in particular you're missing?

**Comment by SpecialBomb** [comment]
I just didn't know. Part of the goal for me messing around with Min is to
learn javascript. Feel free to close this issue,

**Comment by PalmerAL** [comment]
OK, will do. Feel free to reopen this if you have questions about what to install, or ask me if you have any other questions.
