### ISSUE TITLE
Single scrolldown over tabbar closes multiple windows due to momentum

### ISSUE THREAD

**Issue by code-hunger** [minbrowser/min#418]
I think an easy fix would be to stop/delete the scroll event after a tab is closed.

**Comment by SpecialBomb** [comment]
Not exactly sure what you mean, more detail?

**Comment by code-hunger** [comment]
It probably doesn't work with a normal mouse, but with a touchpad if I scroll down over a tab in the tabbar, I get two tabs closed - the one I hovered initially + the tab that appeared below the cursor thereafter.

The second tab also gets the scroll event due to the touchpad triggering a longer scroll than I physically scrolled.

**Comment by SpecialBomb** [comment]
May have to do with line 251 in navbarTabs.js

**Comment by code-hunger** [comment]
Good point:
https://github.com/minbrowser/min/blob/51b06127a10036cb763b0071f71ae414b49f83f3/js/navbar/navbarTabs.js#L251-L253
It turns out you can't really stop the event this way - a scroll consists of multiple events triggered one after another so `preventDefault()`ing the current one has no effect on the others. As I see we could use something like `tabEl.scrollTop();` to stop the current scroll entirely, but need to test.

**Comment by PalmerAL** [comment]
Using ```lastTabDeletion``` was supposed to fix this, since it limits how often you can delete tabs (currently, after the first tab is deleted, we ignore mousewheel events for the next 650ms). We could try increasing this, although that might mean some legitimate swipe gestures are ignored.

**Comment by code-hunger** [comment]
We can have a inScrollEvent flag which is set 1 on the first scroll event and cleared N ms after the last. I think this will solve the problem?

**Comment by Syndamia** [comment]
I can't replicate it, did you fix it @PalmerAL?

**Comment by PalmerAL** [comment]
Nothing about the code has changed since then, so it's probably still an issue; I think it mostly depends on the sensitivity of your trackpad.

**Comment by code-hunger** [comment]
Yes, it still behaves the same way, checking out the master branch. With a touchpad, move the cursor over a tab, swipe down swiftly and immediately raise your fingers. This closes the current tab, and depending on the scroll speed - half a second later - the next current tab.

**Comment by PalmerAL** [comment]
@code-hunger An easy way to fix this would be increasing the timeout; could you try changing the 650 on this line:

https://github.com/minbrowser/min/blob/621ced75a1b25aa27adb731ac67643dc7337af18/js/navbar/tabBar.js#L163

to 900 or 1000 and see what happens?

**Comment by code-hunger** [comment]
I'm still able to trigger it, though real users probably won't scroll so quickly when trying to close a tab.

**Comment by PalmerAL** [comment]
If you scroll at what would be a “normal” speed for you, is it an issue or not?

**Comment by code-hunger** [comment]
It works fine normally, although I managed to trigger a second tab close with the same scroll once even when I thought I was wheeling 'normally' (I left the above setting with the value of 900). I feel too biased now, though; not sure I can give an firm yes/no response but I'd say it works well almost all the time.

**Comment by PalmerAL** [comment]
Thanks. I've changed the default value to 900, which should hopefully fix this; let me know if it's still an issue and I can try to adjust it more.
