### ISSUE TITLE
Zoom secret value

### ISSUE THREAD

**Issue by Yodzorah** [minbrowser/min#422]
Trying to create a zoom bar. Since `zoomIn`, `zoomOut` and `zoomReset` methods aren't really nice for what I want (input range) using the next code for it:

`getWebview(tabs.getSelected()).setZoomLevel(...);`

And I did it, but I noticed this zoom level doesn't match the level you change with shortkeys:

1. Get some page in 100% zoom
2. Change zoom to maximum with `getWebview(tabs.getSelected()).setZoomLevel(9);` (`getZoomLevel` will show you `9`)
3. Zoom out one time with `Ctrl+-` shortkey (`getZoomLevel` will show you `-1` and the page will be zoomed to the level, because when you'll start zoom with shortkey it will be calculated _from the last zoom position you got with shortkeys_)

Since the shortkeys change `ZoomLevel` too, there is one another value `zoomIn`, `zoomOut` and `zoomReset` change and it has more priority.

But I can't find it. Could you please tell where is the code for zooming with shortkeys? I mean, zoom realization, not key bindings.

**Comment by PalmerAL** [comment]
I can reproduce this as well. The code for zooming with keyboard shortcuts is in ```js/webview/zoom.js```. We're using electrons ```webFrame```  module to zoom the page, it looks like there are some bugs when that is combined with setting the zoom level directly on the webview.
