### ISSUE TITLE
Make min more "small window" friendly.

### ISSUE THREAD

**Issue by brpaz** [minbrowser/min#424]
Hello.
I have installed min today and it looks really great. I plan to use it as a "side" browser, while doing other tasks, (Ex: reading documentation while coding or watching videos without leaving my editor or the application I am currently using.  Something like [this](https://i.imgur.com/sxMJmcj.jpg). A similar workflow than for example [Helium](http://heliumfloats.com/) provides.

This means that most of the time, i wont use min full screen but as a smaller window on the side.
Min is great for this, because of its minimalist interface, unlike for example Chrome which all the tabs, bookmarks bar etc.

Here are some small improvements that would make this workflow better:

- New settings section: Window settings.
-- Possibility to configure some window settings like "Always on top", default size and position on screen for example. For now only Always on top and maybe specifying the initial width / height of the window would be enough.

- Possibility to enable "mobile site version" -  Some websites are not responsive and would look better if mobile version is loaded. This could be as simple as setting the user agent to a mobile one.
- Open videos in "embed" mode - For example when opening youtube video and want to watch it "full window", otherwise its too small. In Helium this is done by intercepting the url "ex: youtube.com/watch?v=xpto" and replacing in with the respective "embed" url. This behavior of course could be also enabled / disabled on settings.

This features are relatively simple to implement. I might try to do something if I have some free time.

**Comment by PalmerAL** [comment]
Adding a setting for always-on-top makes sense. I'm not sure I understand how having a default window size is useful - Min will remember the location you had it in last time, so if you want it in a certain place on your screen, it should stay there the next time you launch it. Do you expand Min to fill the full screen, but want it to launch as a small window again?

2 and 3 sound interesting, but I'm not sure many people would find these useful, and I'm hesitant to add more options.

**Comment by iwittkau** [comment]
Always-on-top would be awesome and should be easy to add, @PalmerAL? 

I'm using Min as a documentation browser while writing code and it would be neat to have it always on top.

**Comment by PalmerAL** [comment]
Yeah, it should be fairly simple.

**Comment by PalmerAL** [comment]
@iwittkau I've added an always-on-top option in 951990d2a307adb11a6b3d01fc7b9b36f89bda09.

Regarding the original issue, I think the first issue should be solved now, since Min should remember the previous window position already. I don't think the second issue's worth fixing; the third issue would be cool, but is probably best done as a userscript. So I'm going to close this issue, since I don't think there's anything left that we would add.

**Comment by dj-sash** [comment]
Hi… I am a mac user. I really appreciate your browser speed.
It should be as simple as Safari in look. Don't mix the address bar and title. It is very annoying. Please give a tab below the address bar. And the close button should be on the LEFT of the tabs… not on the right, expanding further right as we close the previous tab (losing time with this). And give an option to set a default page with Bookmarks saved and a default loading page… like Google or whatever default page we want.
The app is really fast I really appreciate that.
And also, when we move on any link… it can show the link description below?
Remove that dark mode and keep a better contrast between the tabs.
And for everything in your VIEW, please some small icons somewhere to make it easier.

Thanks
