### ISSUE TITLE
Is a good idea to add progress indication?

### ISSUE THREAD

**Issue by jfdnet** [minbrowser/min#426]
I think adding a progress indication under tab will make it more interactive with users. The first time I open an address which takes long time feels like hanging up.

By the way, is there any possible you are going to consider history sync between multi devices?

**Comment by code-hunger** [comment]
Dupe of #52. About the second - there is no "min server" that could store sync information, so probably not.

**Comment by PalmerAL** [comment]
Closing as duplicate.
