### ISSUE TITLE
Interface not accessible under orca

### ISSUE THREAD

**Issue by westes** [minbrowser/min#429]
With orca running on gnome, the min window provides no spoken feedback in response to any keyboard controls.

**Comment by Syndamia** [comment]
From what I gather, this really isn't something we could fix. Looking through [this electron issue](https://github.com/electron/electron/issues/11544) and [this VS Code issue](https://github.com/Microsoft/vscode/issues/19522), it seems that the only real way to add accessibility (orca) support is via the `force-renderer-accessibility` which seems to already be given.

I couldn't find any other information on adding orca support inside electron applications.

But I must include that I tested orca support on `Ubuntu 16.04 LTS` (which should be period correct for the issue creation date) and `Ubuntu 20.04 LTS`. From what I could tell, the latter's support for orca was pretty bad, many stuff wouldn't be narrated, but on the former, it was much better.
