### ISSUE TITLE
Windows version?

### ISSUE THREAD

**Issue by outwork** [minbrowser/min#43]
Hi. Min is awesome. Any chance to get this one available for windows in the near future? Thank you.

**Comment by PalmerAL** [comment]
Yes, I plan on working on it soon, and pull requests are great too if you or someone else wants to work on it. Probably this shouldn't be too hard, since <a href="https://github.com/electron/grunt-electron-installer">grunt-electron-installer</a>'s API looks pretty straightforward.

**Comment by dbfreem** [comment]
Windows releases have been available so closing this issue
