### ISSUE TITLE
Why do some pages have more brightness than on Chrome?

### ISSUE THREAD

**Issue by ghost** [minbrowser/min#431]
Take a look at the following screenshots for the exact same page
1. Chrome:
<img width="1424" alt="screen shot 2017-10-10 at 6 11 17 pm" src="https://user-images.githubusercontent.com/753950/31383805-90e2864c-ade6-11e7-8574-38f95b686f69.png">

2. Min:
<img width="1440" alt="screen shot 2017-10-10 at 6 11 09 pm" src="https://user-images.githubusercontent.com/753950/31383812-9654a2c2-ade6-11e7-8ec6-27ec24fece2e.png">

Do you notice how the `min` screenshot is much brighter than on google chrome? Why is that?
Btw, I think this is an `electron` issue and not a `min` issue per say.

**Comment by PalmerAL** [comment]
Odd, I can see that too; it looks like the font rendering is different in Electron somehow. We're curently using an older version of Chromium, maybe upgrading will fix it?

**Comment by piotryordanov** [comment]
Maybe. But, if it doesn't, it would mean that the bug is a Chromum bug! Anything I can do to help?

**Comment by PalmerAL** [comment]
I'm not sure; I don't know a lot about how the internals of Chromium and Electron work. It looks like the font smoothing is different in Chrome than in Electron:

<img width="526" alt="screen shot 2017-10-17 at 8 25 10 pm" src="https://user-images.githubusercontent.com/10314059/31696849-9fc3b17a-b379-11e7-88e9-06251228176c.png">
<img width="529" alt="screen shot 2017-10-17 at 8 24 53 pm" src="https://user-images.githubusercontent.com/10314059/31696858-a6a9dcbc-b379-11e7-8b43-f3ca892b1489.png">

(the top image is Chrome, the bottom image is Electron).

Maybe Chromium provides some options for this when creating the webview process?

**Comment by PalmerAL** [comment]
We should probably also report this to the Electron team.

**Comment by piotryordanov** [comment]
I already did report at the electron team about the same time i opened that one ;)

https://github.com/electron/electron/issues/10737

No answer there though :/

**Comment by Syndamia** [comment]
Closing this, because this is an issue with electron, also looked through the comments and it might've been resolved.
