### ISSUE TITLE
how to identify security of site

### ISSUE THREAD

**Issue by steve-1776** [minbrowser/min#435]
Am I missing a way (lock icon e.g.) to verify the integrity of a site before entering my credentials or financial information? I do not see any way to do this currently with Min.

**Comment by PalmerAL** [comment]
You mean something like the lock icon other browsers use to indicate HTTPS?

<img width="197" alt="screen shot 2017-10-16" src="https://user-images.githubusercontent.com/10314059/31646426-645ef96c-b2c7-11e7-828e-93258ebf3ec6.png">

Min does the opposite in terms of security indicators: on HTTPS sites, you won't see any indicator at all, and on unencrypted sites, you'll see a "broken padlock" icon:

<img width="324" alt="screen shot 2017-10-16 2" src="https://user-images.githubusercontent.com/10314059/31646456-8bb8e02c-b2c7-11e7-8fc8-ce60c4b6153f.png">

We don't currently support displaying company names for EV certificates, like in the Firefox screenshot above, but those aren't particularly common anyway.

**Comment by steve-1776** [comment]
Ok thanks. I haven't seen any broken padlocks yet, so I was unaware they were a feature. Appreciate it

**Comment by PalmerAL** [comment]
OK, feel free to open another issue if you have any other questions.
