### ISSUE TITLE
naming downloaded file using save as 

### ISSUE THREAD

**Issue by steve-1776** [minbrowser/min#438]
Running Arch with Mate DE, when I right click on an image in Min and select Save As, the dialog box which appears will not accept typing until I (re)focus the cursor in the filename box (there is already a filename there highlighted). Using other browsers, I can immediately type the name of the file without having to click in the filename box.

**Comment by steve-1776** [comment]
Going thru the issues I came across the Youtube video issue and, as suggested there, replaced the official Arch package with the one in AUR and the save as dialog box now works as expected. Something is seriously wrong with the Arch package.

**Comment by dbfreem** [comment]
@steve-1776 are you still having this issue?

**Comment by steve-1776** [comment]
On 6/28/19 6:34 AM, AlwaysData wrote:
> @steve-1776 are you still having this issue?
> 
To be honest I haven't been regularly using Min browser. I checked just 
now and (at least some - no failures so far) youtube videos are playing 
for me with Min on Arch.

**Comment by steve-1776** [comment]
On 6/28/19 9:16 AM, Steve wrote:
> On 6/28/19 6:34 AM, AlwaysData wrote:
>> @steve-1776 are you still having this issue?
>>
> To be honest I haven't been regularly using Min browser. I checked just 
> now and (at least some - no failures so far) youtube videos are playing 
> for me with Min on Arch.

Sorry this was in reply to the youtube issue. I haven't tried saving 
downloaded files in a while with Min and don't have a test case handy. Sorry
