### ISSUE TITLE
control Q to quit/exit

### ISSUE THREAD

**Issue by steve-1776** [minbrowser/min#439]
Small issue, but I would love to be able to keep up the habit of quitting the browser by ctrl-q (on Linux). One or two other applications do not have this almost universal keybinding, but if possible, it would be appreciated if Min did.

**Comment by code-hunger** [comment]
According to linux philosophy it is a task of the window manager what key is used for closing windows (but I agree it's very common).  
You said you were using mate so you should be able to solve the problem yourself and set it from the GUI of your DE.

**Comment by PalmerAL** [comment]
Based on these lines, I'm surprised this doesn't already work:

https://github.com/minbrowser/min/blob/525a512d16147b893e17319045c7c865a6d523bb/main/main.js#L514-L519

**Comment by steve-1776** [comment]
Alt-F4 is set to close windows, but since closing a window and quitting the application are not always the same, I have aquired the habit of quitting as opposed to merely closing the window. Does closing the window "quit" Min? Re: lines 515-519, it doesn't work. Under File I only see New Tab, New Private Tab, New Task, Save Page As and Print. There is no Quit or Exit under File. Should there be?

**Comment by PalmerAL** [comment]
Oh, you're right, it's because that whole thing is wrapped in an ``` if (process.platform === 'darwin') {``` block.

**Comment by steve-1776** [comment]
Ok good to know it isn't an invisible gremlin. I have to say I've been using Min off and on a couple months and solidly as my primary browser for about a week and the more I use it the more I love it. Keep up the good work!

**Comment by steve-1776** [comment]
Most of the apps I use can be quit (opposed to merely closing the window) with Ctrl-Q. A couple here and there do not, but I can count them on one hand. (Really it's just Min and Handbrake in my experience - surely there are others)

**Comment by code-hunger** [comment]
Currently the Window menu has a "Close" element with a grayed `Ctrl+W` shortcut, maybe it could be moved to the File menu, renamed to Quit and remapped to Ctrl+Q?

**Comment by anonymous-user** [comment]
Is there any changes regarding this? It would be great if Min could adopt Ctrl+Q to make it similar to most other apps. Or at least have Ctrl+W close the window if there is only one tab available.

**Comment by PalmerAL** [comment]
Oops, I forgot about this; I've added a ctrl+q shortcut in a01d36037105e6b29fde3a2ee67b2fb556460cc2.
