### ISSUE TITLE
Keyboard shortcuts option is hidden.

### ISSUE THREAD

**Issue by kanna0000** [minbrowser/min#449]
After changing of keyboard shortcut, the banner which shows "You need to restart to apply these changes" will pop up.
This banner hide the last shortcut, "Show And Hide Menu Bar", so you can not change this option after the banner shown.
![screenshot from 2017-11-09 10-31-05](https://user-images.githubusercontent.com/16045487/32583942-46809d86-c539-11e7-8143-f7700702b592.png)

![screenshot from 2017-11-09 10-39-03](https://user-images.githubusercontent.com/16045487/32584120-3cec8c20-c53a-11e7-94fc-0904a44f8cfb.png)

Environment
ubuntu-gnome16.04

**Comment by PalmerAL** [comment]
Thanks for reporting this! Fixed in 220c0b444b384de80529b35d3b4c4318d68e53e1.

**Comment by PalmerAL** [comment]
The 1.7.0 version that includes this fix has been released, you can download it from here: https://github.com/minbrowser/min/releases/tag/v1.7.0.
