### ISSUE TITLE
Window maximized always out of bounds on startup

### ISSUE THREAD

**Issue by DylanC** [minbrowser/min#456]
The top part of this image is the top of my screen. The buttons are always cut off because it does not open maximized properly.

![image](https://user-images.githubusercontent.com/4488048/33075006-0916eab4-cec0-11e7-9889-62a899caa372.png)

**Comment by PalmerAL** [comment]
Can't reproduce on Windows 7. Can you try closing Min, deleting the ```C:\Users\<your username>\AppData\Roaming\Min\windowBounds.json``` file, and reopening it?

**Comment by DylanC** [comment]
@PalmerAL 

I found how to reproduce:

1.
Deleted windowBounds.json.
Launched Min.
Window displayed **correctly**.

2.
Closed Min. (it saves the windowBounds.json)
Launched Min and it used the windowBounds.json to restore.
Window displayed **incorrectly**.

**Comment by DylanC** [comment]
@PalmerAL 

Also... this is what it saves:
**{"x":54,"y":-8,"width":1634,"height":1066}**

Actually if I change it to 0, 0. The window displays correctly:
**{"x":0,"y":0,"width":1634,"height":1066}**

**Comment by PalmerAL** [comment]
OK, I can reproduce this if the taskbar is moved to the side of the screen. I think I've fixed this in c88f67ef974b8d0b4802ccd68f3d2c6a00469441; can you test it and see if it works?

**Comment by DylanC** [comment]
@PalmerAL - Yes, that is correct. My taskbar is on left of screen. How to test?

**Comment by PalmerAL** [comment]
Follow the instructions here: https://github.com/minbrowser/min#installing under "if you want to develop Min".

It's fine if you don't want to do that, I'll probably release 1.7.0 in a week or two and you can see then if it works.

**Comment by DylanC** [comment]
@PalmerAL - I will wait for the release. Thanks.

**Comment by DylanC** [comment]
@PalmerAL - Fixed in 1.7.0. Thanks.
