### ISSUE TITLE
"l is not defined" error when running from source

### ISSUE THREAD

**Issue by brpaz** [minbrowser/min#457]
Hello. 
I am trying to run min from source and when I run ```electron. ```, I get an error saying "l is not defined".

What I am missing? I dont see any "l" variable defined anywhere, nor any dependency in package.json.

**Comment by PalmerAL** [comment]
You have to build the translation files as well: ```npm run buildTranslations```. Once you do that, run Grunt again, and then it should work.

(The "l" function is coming from localization/localizationHelpers.js, and when you build the translation files, it gets combined with the translations and placed in dist/localization.build.js. Grunt then includes this file in the final build.js).

**Comment by PalmerAL** [comment]
Actually, there was a syntax error in one of the translation source files that prevented the translations from building correctly. It's fixed in bd9a847ba55963124334ceb3bfefea1caf5cbdbd, building should work now.

**Comment by brpaz** [comment]
Yes. build is working. Thank you,

**Comment by PalmerAL** [comment]
Great!
