### ISSUE TITLE
Large hosts file makes the browser hang

### ISSUE THREAD

**Issue by abis866i** [minbrowser/min#458]
I have just installed version 1.6.3 64 version of the min browser and all seemed to install OK. When I start the browser from bash using "min" command all I get is an empty window. Menus are functional but nothing happens if I click on any menu items except for the "Inspect Browser" item which will open the developer screen. I have tried to run "min --disable-gpu" as per some suggestions but there is no change in behavior. I have read that there is an issue from electron related to the screen resolution. I have a dual monitor with 1600x900 each. I have tried to reduce the resolution to  1280x720 and then I can see the google page but I cannot click on anything on the page. There is no log at the command prompt.

**Comment by PalmerAL** [comment]
If you run the <a href="https://github.com/electron/electron-api-demos/releases">Electron API demos</a> app, does that work?

**Comment by abis866i** [comment]
I tried some of the demos such as Create a window, Manage window state, frame less window, process crash, open path, error dialog, and they all seemed to work well.

**Comment by abis866i** [comment]
Not sure if helps, but when I start min and I focus my mouse on the menu bar, it takes at least 15 seconds to load (the spinning wheel to change to pointing arrow)

**Comment by abis866i** [comment]
When I close the browser window, I get the following message at the command prompt: "(node:21096) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
"

**Comment by PalmerAL** [comment]
Interesting, thanks!

I just realized that the API demos app is built with an older version of Electron, if you run this: https://github.com/electron/electron/releases/tag/v1.7.8, does it work?

If you go to Developer > Inspect Browser and open the developer tools, does anything show up in the "console" tab?

**Comment by abis866i** [comment]
The electron application from package 1.7.8 works. Console in developer tools is empty.

**Comment by PalmerAL** [comment]
OK, that's weird, from your description it sounds like a graphics issue, but if the Electron sample app works I'm not sure what we would be doing differently. I'll try to run Linux Mint in a VM and see if I can reproduce it.

**Comment by abis866i** [comment]
I made a small video that I am attaching here archived. I hope that is permissible. I don't know what more to say about the error.
[output.mp4.tar.gz](https://github.com/minbrowser/min/files/1503550/output.mp4.tar.gz)

**Comment by PalmerAL** [comment]
That's interesting, it looks like the renderer process is getting hung somehow on startup. Can you try deleting the folder ```/home/<your username>/.config/Min``` and re-launching the browser?

One other option is that we're calling an Electron API in the renderer process that never completes for some reason, I'll try to make a build with those taken out for you to test.

**Comment by abis866i** [comment]
No, it is the same...

**Comment by PalmerAL** [comment]
I've built a version of Min without ```electron.remote``` calls, can you try running this: https://send.firefox.com/download/5b62a1b76a/#35A_pRAJ8SZ6REM4FTmQyA ? (sorry about the link, the file is over Github's size limit). Alternatively, you can clone Min and run the ```startup-hang-test``` branch to get the same code.

**Comment by abis866i** [comment]
Download stopped at about 22% and then the link expired. Send the link to me one more time...

**Comment by PalmerAL** [comment]
Here you go: https://send.firefox.com/download/433b6edabc/#uu-y0dwGS2On_6NlVdjZ4w .

**Comment by PalmerAL** [comment]
If that doesn't work, maybe this alternative will: http://sendanywhe.re/U15V1KBN.

**Comment by abis866i** [comment]
Sorry, I get same behavior. BTW, I have already tried with some older versions of min and I get same behavior with all of them. Maybe there is an issue with my computer setting, I don't know.

**Comment by abis866i** [comment]
Same with the one from sendanywhe.re. Maybe I miss some dependencies.

**Comment by PalmerAL** [comment]
OK, can you try this one? https://send.firefox.com/download/2c15ce82de/#r4aebSwInSqtepo-Lv14Vw

I've disabled most of the browser code, so I would expect most of the menu items to not work (although Inspect Browser should work still), but see if startpage shows up and if you can interact with the page.

**Comment by abis866i** [comment]
OK, here is an interesting one. Last night, after I tried the two versions that you gave me, I left min browser open. This morning it was working. I navigated to startpage and enabled blocking in preferences. It advised me to restart, so I did that. But now I get a blank page with  two tabs at the top: startpage and preferences, none of them working. I will wait till afternoon to see if they would start working after a while...

**Comment by abis866i** [comment]
Update: After one hour it is still the same. There are four min-related processes that are using 50% of the CPU and around 700MB of memory. I will kill the processes.

**Comment by abis866i** [comment]
The latest version that you sent me still shows a blank page. There are 4 processes that are using no CPU and around 120 MB of memory.

**Comment by PalmerAL** [comment]
Odd, if the latest one isn't consuming CPU I would assume it fixed the hang, but you should see a page show up then.

I have one more for you to try: https://send.firefox.com/download/dfb92a462b/#m-CFwWXLV1qIOjrXHnvB_A

This is basically the smallest Electron app possible - it just opens a window and shows a ```<webview>``` in it. Do you see a page if you run that?

If that still doesn't work, maybe there's an issue with the packaging? You could try running this directly from source (You'll need to install nodejs first):
```
npm install -g electron
git clone https://github.com/minbrowser/min.git -b startup-hang-test
cd min
electron .
```

I'm kind of running out of ideas at this point (and I tried running in Linux Mint in a VM and it worked fine). Is there anything particularly unusual about your computer or system configuration that you can remember?

**Comment by abis866i** [comment]
Last one worked well. Menus have odd names and I don't see the tabs. So, I am not sure if the new tab menu item works. Memory and cpu are low. I found several instances of a process "gksu" which are related to min but I killed them and they did not start up again.

**Comment by abis866i** [comment]
For the last part:
sudo npm install -g electron

loadDep:uuid → resolveWit ▄ ╢██████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine hawk@6.0.2: wanted: {"node":">=4.5.0"} (current: {"node":"4.2.6","np/usr/local/bin/electron -> /usr/local/lib/node_modules/electron/cli.js

> electron@1.7.9 postinstall /usr/local/lib/node_modules/electron
> node install.js

sh: 1: node: not found
npm ERR! Linux 4.4.0-101-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "electron"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! electron@1.7.9 postinstall: `node install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the electron@1.7.9 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/adrian/npm-debug.log

**Comment by abis866i** [comment]
Here is the log file:
[npm-debug.log](https://github.com/minbrowser/min/files/1508328/npm-debug.log)

**Comment by PalmerAL** [comment]
> Last one worked well. Menus have odd names and I don't see the tabs. So, I am not sure if the new tab menu item works. Memory and cpu are low. I found several instances of a process "gksu" which are related to min but I killed them and they did not start up again.

OK, good! Just to confirm, Startpage shows up, and you can interact with the page? The odd tab names and the missing tabs are expected, because I disabled the localization system and most of the browser UI to see if that was causing the problem. Next step is to add features back one at a time until we figure out which one is causing the problem.

I'm not exactly sure what's wrong with your node install (based on "hawk@6.0.2: wanted: {"node":">=4.5.0"} (current: {"node":"4.2.6"", I'm guessing you might want to upgrade to the latest version), but if the build above is working, you probably don't need it for now.

**Comment by abis866i** [comment]
Now that you say it, I looked more in-depth. Startpage opens fast. I can search a term (I searched for test). I can switch between web, images, or videos.
But clicking on results on the page won't redirect me to the page, such as https://www.merriam-webster.com/dictionary/test.

**Comment by PalmerAL** [comment]
I think Startpage is trying to open the results in a new tab, which is also disabled in the test build.

**Comment by PalmerAL** [comment]
Here's another build to try: https://send.firefox.com/download/4383d3cfc9/#9r-3wFtcugFc6fCeCWihig

**Comment by abis866i** [comment]
No difference from previous one, works the same. Visually the same as well.

**Comment by PalmerAL** [comment]
OK, I've re-enabled a few more things: https://send.firefox.com/download/b00b142e4b/#j-IlNkdOPIHqPvfLDNwDvg (The menu items should look normal now).

**Comment by abis866i** [comment]
Yes, works the same with beautified menu items but no tabs.

**Comment by PalmerAL** [comment]
Next one: https://send.firefox.com/download/7b217b2b4c/#yHT2VHxCEnUp9JIKrtbhlQ

There shouldn't be any tabs still, but check to see if it hangs or not.

(Also, I apologize that this is so tedious).

**Comment by abis866i** [comment]
It is good. BTW, in between I have installed node.js 6.12.0. Do you think that would change anything?

**Comment by PalmerAL** [comment]
Electron has its own built-in version of Node, so not with the app, but it might fix the error you were having earlier when trying to run from source.

**Comment by PalmerAL** [comment]
Next one: https://send.firefox.com/download/ca14c57123/#c9GGoY1wi-_HPZLS78GqaQ

**Comment by abis866i** [comment]
Page loaded and I was able to navigate. But this time, it tool the 15 seconds to change from the spinning wheel to arrow. But I was able to interact with the page in that time window as if it was not happening.

**Comment by abis866i** [comment]
~/Downloads/min $ ls
css           icon.icns   js            main          reader
ext           icons       LICENSE.txt   package.json  README.md
Gruntfile.js  index.html  localization  pages         scripts
~/Downloads/min $ electron .
Error launching app
Unable to find Electron app at /home/adrian/Downloads/min

Cannot find module '/home/adrian/Downloads/min'

**Comment by abis866i** [comment]
Do you think that a custom hosts file may block your browser to reach some server to get some settings? At this moment I have ~884000 lines in that file... Maybe that is the cause.

**Comment by PalmerAL** [comment]
> Cannot find module '/home/adrian/Downloads/min'

Sorry, I forgot to mention that you have to do ```npm install -g grunt-cli``` and then run ```grunt``` first.

**Comment by abis866i** [comment]
And I have the pi-hole for dns...

**Comment by abis866i** [comment]
sudo npm install -g grunt-cli
[sudo] password for adrian: 
/usr/bin/grunt -> /usr/lib/node_modules/grunt-cli/bin/grunt
/usr/lib
└─┬ grunt-cli@1.2.0 
  ├─┬ findup-sync@0.3.0 
  │ └─┬ glob@5.0.15 
  │   ├─┬ inflight@1.0.6 
  │   │ └── wrappy@1.0.2 
  │   ├── inherits@2.0.3 
  │   ├─┬ minimatch@3.0.4 
  │   │ └─┬ brace-expansion@1.1.8 
  │   │   ├── balanced-match@1.0.0 
  │   │   └── concat-map@0.0.1 
  │   ├── once@1.4.0 
  │   └── path-is-absolute@1.0.1 
  ├── grunt-known-options@1.1.0 
  ├─┬ nopt@3.0.6 
  │ └── abbrev@1.1.1 
  └── resolve@1.1.7 

adrian@adrian-mint ~/Downloads/min $ grunt
grunt-cli: The grunt command line interface (v1.2.0)

Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:

http://gruntjs.com/getting-started

**Comment by PalmerAL** [comment]
> Do you think that a custom hosts file may block your browser to reach some server to get some settings? At this moment I have ~884000 lines in that file... Maybe that is the cause.

That's a really interesting idea, because we actually do load the hosts file on startup and parse it to find a list of domains that we then show as autocomplete suggestions in the searchbar: https://github.com/minbrowser/min/blob/3b980124aef1f328618f4827fa5c354478382fa6/js/util/urlParser.js#L8 . If you have that many lines in the hosts file, it probably could explain why the browser is freezing for a while when you launch it. I'm wondering if what happened is this:

* On the first two test builds, the hosts suggestions were still enabled, which would explain this:
> Update: After one hour it is still the same. There are four min-related processes that are using 50% of the CPU and around 700MB of memory. I will kill the processes.

* On the next build, the hosts suggestions were disabled, so the hang was gone: 
> The latest version that you sent me still shows a blank page. There are 4 processes that are using no CPU and around 120 MB of memory.

I'm not entirely sure why you would see a blank page on this one, though.
All the builds after that worked for you, which would make sense - the hosts suggestions were disabled in all of them.

Could you try renaming your hostsfile to something else, and re-launching Min (you can just use the normal version from the website)?

**Comment by PalmerAL** [comment]
> adrian@adrian-mint ~/Downloads/min $ grunt
> grunt-cli: The grunt command line interface (v1.2.0)
> 
> Fatal error: Unable to find local grunt.

OK, I forgot one more thing, you have to run ```npm install``` from the Min folder. Sorry about that!

**Comment by abis866i** [comment]
I just subscribe to public hosts lists, nothing special. But I will have to disable the pi-hole as well.

**Comment by PalmerAL** [comment]
You shouldn't have to disable the pi-hole, just the local hostsfile on your computer.

**Comment by abis866i** [comment]
electron . gives me a javascript error:

Uncaught Exception:
ReferenceError: l is not defined
    at createAppMenu (/home/adrian/Downloads/min/main.build.js:145:14)
    at App.<anonymous> (/home/adrian/Downloads/min/main.build.js:112:3)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:194:7)

**Comment by abis866i** [comment]
But I can run search on Startpage

**Comment by PalmerAL** [comment]
And... I forgot ```npm run buildTranslations```. I think I'm to distracted to be doing this right now... the directions in the README should have everything :)

**Comment by PalmerAL** [comment]
> But I can run search on Startpage

Is that with the hostsfile disabled?

**Comment by abis866i** [comment]
No I have not disable it yet. BTW, it misses the tabs as well.

**Comment by PalmerAL** [comment]
Oh, you're still using the build I mentioned above. Could you try disabling the hostsfile, and just running the normal Min download from the website (or are you saying that the file from there isn't working?)

**Comment by abis866i** [comment]
Pi-hole and hosts have similar functionality. I believe the pi-hole subscription is larger that the one I use locally.

**Comment by PalmerAL** [comment]
Right. To be clear, I think the issue with the hosts file isn't that it's blocking a network connection. The issue is that we use the hosts file as a source of domains to autocomplete in the searchbar. So when the browser starts up, we load the hosts file into memory, and do a bunch of (now that I'm looking back at it) really inefficient operations to turn the contents of the file into a list of domains. Looking back at the code, we're doing n factorial operations, where n is the number of hosts you have in the hosts file. 884000 factorial is...... really large, and probably more than enough to hang the browser for an hour or two.

**Comment by PalmerAL** [comment]
To be clear, the feature I'm referring to is this:
<img width="529" alt="screen shot 2017-11-27 at 9 40 22 pm" src="https://user-images.githubusercontent.com/10314059/33301484-96941a38-d3bb-11e7-8c44-7172e7ef0153.png">

**Comment by abis866i** [comment]
I believe that is it. I installed the public deb package and renamed the host file. Now it works. So there must be something that you call and my host file blocks. Sorry for making you work so much on this.

**Comment by PalmerAL** [comment]
Don't worry about it! And thank you for spending so much time on this as well! You're probably not the only person affected by this, so it's good to have it fixed.

**Comment by PalmerAL** [comment]
I'll probably have time in the next few days to fix the hosts file code so it's more efficient. In the meantime, I'll make a build for you with the hosts file autocomplete disabled.

**Comment by abis866i** [comment]
I use host-flash-master with following enabled:
hosts-file.net
mvps.org
someonewhocares.or
adaway.org

**Comment by abis866i** [comment]
Thank you so much for working with me on this one.

**Comment by abis866i** [comment]
Is it possible that you also remove my name and computer name from our conversation (in code snippets). Looks like I was careless and I did not clean it very well.

**Comment by PalmerAL** [comment]
I really appreciate you taking the time to help figure this out! I've made a build with the hosts-file suggestions disabled: https://send-anywhere.com/web/downloads/EU23ZBYZ . This should allow you to re-enable your hosts file and have Min still work. When I get time in the next few days, I'll rewrite the hosts-suggestions code to be more efficient, and I'll add a comment here when I'm done so you can test it.

> Is it possible that you also remove my name and computer name from our conversation (in code snippets). Looks like I was careless and I did not clean it very well.

OK, will do.

**Comment by PalmerAL** [comment]
I think I've removed everything from the comments, let me know if I missed anything (you should be able to edit your own comments by clicking the pencil icon in the upper-right).

**Comment by abis866i** [comment]
Thanks.

**Comment by PalmerAL** [comment]
I'm going to leave this open until I've fixed the hosts-parsing code.

**Comment by PalmerAL** [comment]
I think I've fixed this in bb984dc3f5f4198645f848a67678553f8aa84aa9. Could you try this build out, and check that it works? http://sendanywhe.re/61QABPIX

**Comment by abis866i** [comment]
It is much better now. Everything I tried worked well.

**Comment by PalmerAL** [comment]
Great!

**Comment by PalmerAL** [comment]
The 1.7.0 version that includes this fix has been released, you can download it from here: https://github.com/minbrowser/min/releases/tag/v1.7.0.
