### ISSUE TITLE
Find on page - Shift+F for previous match

### ISSUE THREAD

**Issue by code-hunger** [minbrowser/min#462]
Generally, in GUIs where Ctrl+F searches strings on a page, pressing Enter/Shift+Enter goes to the next/previous match, respectively. Min currently supports only forward searching, and it would be great if previous matches are also accessible.

**Comment by PalmerAL** [comment]
1.7.0 has been released, you can download it from here: https://github.com/minbrowser/min/releases/tag/v1.7.0.
