### ISSUE TITLE
Clearing browser cache

### ISSUE THREAD

**Issue by wfoojjaec** [minbrowser/min#465]
Was trying to use Min for development purposes, but there is no clearing browser cache option anywhere.
So even editing file and fully reloading page doesnt work. Cearing history doesnt clear cached data either.
Manually deleting Min configuration with cache fixes the problem.

**Comment by PalmerAL** [comment]
@wfoojjaec Did you intent to close this?

**Comment by wfoojjaec** [comment]
Opened by mistake. Closed as a duplicate of Refresh cache #381
