### ISSUE TITLE
YouTube fails always

### ISSUE THREAD

**Issue by levimake** [minbrowser/min#466]
I made a fresh install of the browser and checked out YouTube and it show an error occured. YouTube is not playing any videos including the ad which appears on the homepage.

**Comment by code-hunger** [comment]
There is a temporary workaround already discussed here: https://github.com/minbrowser/min/issues/353

**Comment by levimake** [comment]
Everything works better installed min from AUR. So, for installing min on Arch, better do this: 
`yaourt -S min-browser-bin`
:+1:
