### ISSUE TITLE
Why does it have a minumum height ?

### ISSUE THREAD

**Issue by Frederic-C** [minbrowser/min#467]
Browser seems to have a minimum window height (of around 500px). Why not letting user setting freely his own personnal height ?

thank you

**Comment by PalmerAL** [comment]
I've reduced the minimum height to 350px in c7ddb817fbf456e47a8af572c0bf6131e9a94825. Reducing it further breaks the browser UI, so we'll need to fix that first before we can reduce it any more.

**Comment by Frederic-C** [comment]
Great 👍
