### ISSUE TITLE
Brew package

### ISSUE THREAD

**Issue by brunobord** [minbrowser/min#468]
As a dual-OS user (MacOS & Ubuntu Linux), I wish I could run ``brew install minbrowser`` that would set up this lovely browser available in a breeze. That'd be handy to upgrade without having to go to the Github project page from time to time to see if there's something new.
I have no idea on how difficult it is, though, but I think it'd be nice and it would expand your user base a bit more.

**Comment by PalmerAL** [comment]
Hmmm, I guess I should look into what the process for doing this is at some point.

**Comment by Keloran** [comment]
there is a cask for it

**Comment by PalmerAL** [comment]
@Keloran Interesting, good to know!

For anyone else reading this issue, the command to install Min is: 

```
brew cask install min
```
