### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by CorbsEditor** [minbrowser/min#471]
There are two feature requests I would like to make:

One - Setup file for MinBrowser 

Two - Allowing Windows operating systems set their default browser as MinBrowser

If not possible, explain why? 
P.S. Your web browser is just what I have been looking for because of the user interface, too simple, love it!

**Comment by PalmerAL** [comment]
> Setup file for MinBrowser

There's an issue about a Windows installer here: #359. 

> Allowing Windows operating systems set their default browser as MinBrowser

Not sure what would be necessary to get this to work, I'll have to look into it.

In general, Windows support hasn't been a high priority, so I haven't spent a lot of time on it, but I guess I'll get around to it at some point.

**Comment by PalmerAL** [comment]
@CorbsEditor BTW, we're planning on including a new UI for Windows in the next version (from #369) that combines the titlebar and the tab bar into one line so it takes up less space. Would you be willing to test it before the release? You can either download the master branch and follow the instructions here: https://github.com/minbrowser/min#installing, or you can use these binaries: http://sendanywhe.re/946ZNXQN.

**Comment by PalmerAL** [comment]
Ugh, I just realized that sendanywhere website has a bunch of scammy ads on it. Make sure you click the right download button (the pink one at the very bottom), or just don't worry about it if you're not sure which one is right.

**Comment by CorbsEditor** [comment]
Is this version out now?

**Comment by CorbsEditor** [comment]
Thanks, I am liking this new UI! It is more compact than ever, pretty sure that's as compact as it is going to get!

Also, do I see a back button now, make sure to add the forward button too.

**Comment by PalmerAL** [comment]
I think the forward button is typically used less than the back button, so I'm not sure it's worth taking up more space in the navbar for it. You can go back by right-clicking on the page and choosing Go Back.

Please feel free to file a new issue if you run into any bugs with the new UI, it hasn't been tested very much. I'm planning on releasing it in 1.7.0 in a week or two when the next Electron update comes out.

**Comment by CorbsEditor** [comment]
Any chance this compact UI went to Linux too, I have two operating systems on my computer.

**Comment by PalmerAL** [comment]
Maybe. Electron only has native window controls that float over the window on macOS, so on Windows and Linux we have to make our own window controls in HTML if we want them to appear in the same row as the tabs. On Windows, this isn't too difficult, because there's basically only one UI, but on Linux there's a lot of different titlebar styles. #369 has a decent-looking Linux UI, but it won't match the other apps on your computer. I'm not sure which is better - a separate titlebar with native-looking window controls, or non-native controls integrated with the tabstrip. What do you think?
