### ISSUE TITLE
Pop-up video player

### ISSUE THREAD

**Issue by CorbsEditor** [minbrowser/min#475]
I do a lot of multi tasking on my computer and I would love to see pop-up video player for sites like YouTube, Vimeo, Twitter, etc...

**Comment by PalmerAL** [comment]
Not sure if we want to do this or not, but I looked around a bit to see how other browsers do this. Safari has API's to allow any website to do this (https://stackoverflow.com/questions/39607987/how-do-i-trigger-picture-in-picture-on-safari-10), but they're not standardized. Firefox has a Test Pilot addon to do this, but it works by running different code for each supported video website (https://github.com/meandavejustice/min-vid/blob/master/webextension/content-scripts/icon-overlay.js), which isn't great.

**Comment by CorbsEditor** [comment]
Oh I see, also is there a way to clear cache, cookies, and all that. Maybe there's something in the files I would delete or reset?

**Comment by PalmerAL** [comment]
Yeah, we should add a command for that - could you file a new issue? In the meantime, you can delete your profile folder (/username/application support/Min on MacOS, C:\username\appData\roaming\Min on Windows, /home/username/.config/Min on Linux), although that will delete your saved preferences and history as well.
