### ISSUE TITLE
MinBrowser does not support iFrame

### ISSUE THREAD

**Issue by CorbsEditor** [minbrowser/min#476]
![unknown](https://user-images.githubusercontent.com/26362558/34427145-c3f13024-ec0c-11e7-81da-5cb17a0e94f5.png)

This is my friend's site, he said that this browser wasn't supporting iFrame.
I don't know how that works? but okay...

**Comment by code-hunger** [comment]
Min definitely *does* support iframes, go here and see for yourself: https://www.w3schools.com/html/html_iframe.asp (a page included in another page).

**Comment by CorbsEditor** [comment]
Hmm....here is the site: https://corporal-cormorant-6710.dataplicity.io/
It isn't working on there

**Comment by PalmerAL** [comment]
@CorbsEditor It's not working in Chrome either, so I don't think it's a Min issue. It looks like the /sitemap resource is missing the ```content-type``` header, which should have a value of ```text/html```. Apparently, Firefox assumes that it's HTML even when you leave that out, while Chrome assumes it's a plain-text document.
