### ISSUE TITLE
MinBrowser startup is slow

### ISSUE THREAD

**Issue by CorbsEditor** [minbrowser/min#477]
So I just resetted my computer, unzipped Min, and now it is acting slow now.
Anyway I can speed it up?

**Comment by PalmerAL** [comment]
Is there anything in particular that's slow? Did you change anything else with your computer?

When it's running slowly, could you take a profile? Go to Developer > Inspect Browser > Performance, click the circle to start recording, use the browser for a bit, and then choose "stop". Right-click on the timeline, choose "save profile", and upload it here.

**Comment by CorbsEditor** [comment]
Ah sorry, I mean the startup is slow. It's just all black for like 5 secs.
This is reminding me of Brave Browser, which is slower on startup.

**Comment by PalmerAL** [comment]
Does it happen on the release version? Also, if you let the browser open, and then press ctrl+r quickly twice to reload the UI, is that slow?

**Comment by CorbsEditor** [comment]
I do not think this is happening on the release version, for my other computer using that version it works fine.
But I could try fully re-installing the beta version, I would just need to know what exactly to delete in my file system.

Also ctrl+r had no effect.

**Comment by PalmerAL** [comment]
To re-install, you should be able to just download the file again and run the .exe from the download (you're on Windows, right?). You could also try deleting your profile folder (which is \Users\<your username>\AppData\Roaming\Min), although if you do this you will lose your history, settings, etc.

If ctrl+r doesn't work, you could also try this:

Go to Developer > Inspect Browser > Performance, and click the reload button in the panel. Right-click on the timeline, choose "save profile", and upload it here.

**Comment by PalmerAL** [comment]
@CorbsEditor Did you figure this out?

**Comment by PalmerAL** [comment]
I'm going to close this issue for now. Feel free to re-open it if the steps listed above don't work!
