### ISSUE TITLE
Minbrowser Icons/Windows Icons

### ISSUE THREAD

**Issue by Blouko** [minbrowser/min#481]
Hi,

This might be of personal preference, but I feel the minbrowser icons do not match with the windows icons. The minbrowser icons are much "bold"-er than the windows icons which are "thin".

Here's an image from my window: 
![sketch](https://user-images.githubusercontent.com/7572864/35178625-8ef1c47a-fd59-11e7-8994-a954f4a52f50.png)

Also, not sure if this was already reported, but I cannot change the size of the window from the top of the window.

Additional information: Currently using the latest release, 1.7.0

**Comment by PalmerAL** [comment]
Regarding the second issue, there seems to be a limitation where parts of the window that are marked as draggable cannot also be used to resize. If you move your mouse cursor down a few pixels (to right above where the buttons are), it should work. It's possible we could work around this by marking the outermost 1px of the window as non-draggable; I'll have to look into it more.

**Comment by PalmerAL** [comment]
I've fixed the second issue in 67d3385c8af91a49ace18e21b9c38198cca9bd1b. Thanks for reporting this!

The icons are harder to fix, because we're using icons from Font-Awesome that only come in one weight. In order to get them to match, we'll have to draw our own icons.

**Comment by Blouko** [comment]
Thank you very much for fixing the issue in such a quick manner, this is awesome! 😄 

As for the icons, could I try making some for you? And I do mean _try_, because I don't design things often.

**Comment by PalmerAL** [comment]
You're welcome to if you want to, but I'm not sure it's worth it. The icons need to be consistent throughout, so if we change the two icons in the navbar, we'd also need to redesign the other icons throughout the app in a similar way, which is probably around 20-30 icons in total. We'd probably be better off trying to find a different icon set that works better.

**Comment by dbfreem** [comment]
The issue was reported a year ago and the bug was fixed. No one else voiced an opinion on changing the icons.
