### ISSUE TITLE
Using Electron for loading remote content: Are there security problems involed?

### ISSUE THREAD

**Issue by thorsten-panknin** [minbrowser/min#489]
Hi,

I didn't find other contact info than to enter an issue here.

Someone I know told me that Electron is not meant to power web browsers, but mostly local files. He continued that there is no sandboxing. I checked out Electron's page on security which said that loading remote content actually grants scripts etc. file system access and similar. (I'm not too savvy in this field, please apologise. )

I searched the issues here for security and/or electron, but found no fitting issue.

**Hence my question:** How does Min, if what my friend said is true, prevent security problems loading remote content? I really like Min, but would not want to possibly endanger my system.

Please keep up the good work!

**Comment by thorsten-panknin** [comment]
I was inattentive. My friend referenced that other issue here which discusses what I asked.

**Comment by PalmerAL** [comment]
For other people reading this, the issue is https://github.com/minbrowser/min/issues/440#issuecomment-338080554.
