### ISSUE TITLE
Segmentation fault writing to the console

### ISSUE THREAD

**Issue by manuelmazzuola** [minbrowser/min#493]
When I try to write something to the console or searching a string in the DOM the browser segfaults.

```
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x18} ---
+++ killed by SIGSEGV (core dumped) +++
[1]    13315 segmentation fault (core dumped)  strace min
```

**Comment by PalmerAL** [comment]
Electron 1.82-beta5 has a note for "Fixed devtools crash", so hopefully this will be fixed once we upgrade.

**Comment by csonuryilmaz** [comment]
According to `process.versions["electron"]` min_1.7.0 uses electron **1.8.2-beta.3**.
We're looking forward for next upgrade fixing the bug.

**Comment by PalmerAL** [comment]
@csonuryilmaz Next release will probably be based on Electron 2.0, which will happen once the issues listed in #503 are fixed.

**Comment by PalmerAL** [comment]
I think this is fixed, please open a new issue if it isn't.
