### ISSUE TITLE
Per site user css/javascript support

### ISSUE THREAD

**Issue by mikroskeem** [minbrowser/min#495]
Example use would be to make sites dark and/or disable Slack's `https://slack-redir.net/link?url=...`

**Comment by PalmerAL** [comment]
Duplicate of #117.

**Comment by mikroskeem** [comment]
Whoops, didn't notice 😄

---- On Sun, 04 Feb 2018 21:00:35 +0000 notifications@github.com wrote ----

Duplicate of #117.
