### ISSUE TITLE
Abrubt halting of web browsing

### ISSUE THREAD

**Issue by tejasvi8874** [minbrowser/min#502]
Version: 1.7.0- 1
OS: Manjaro (Arch Linux)
Min is my best browser - {few bugs}
Now and then after browsing sometime, it stops loading webpages and carrying out search queries. My Internet connection is fine and other Internet services work okay.
![screenshot_2018-02-19_08-48-10](https://user-images.githubusercontent.com/28995043/36381102-87166cc2-1552-11e8-8275-6d9f825128d0.png)
After killing the Min process, which dunno why lingers after closing the window, the problem goes away.

**Comment by PalmerAL** [comment]
Sorry to hear that this is happening! Can you open the searchbar and find the error code (the set of numbers after ```?ec=```) and post that here?

**Comment by Syndamia** [comment]
Closing, because the author didn't follow up on their problem and this issue is quite old.
