### ISSUE TITLE
seznam.cz blocked by min

### ISSUE THREAD

**Issue by severak** [minbrowser/min#509]
[Seznam.cz](https://en.wikipedia.org/wiki/Seznam.cz), major czech search engine/web portal is blocked by anti-phishing script of min. 

Other czech websites seems to be okay.

**Comment by PalmerAL** [comment]
This appears to no longer be an issue after 5e29390d5a90a1b9ade6dcfb14290e00afe280d7. The root issue is that we're detecting ```search.seznam.cz``` and ```login.seznam.cz``` to be third-party domains, meaning that the forms that submit to those are considered cross-domain form submissions. The easy way to fix this would be to include the entire public suffix list (https://publicsuffix.org/) and check against that, but that would slow down page load times too much. I'm not sure what the alternative would be.
