### ISSUE TITLE
Breakpoint in Mac app

### ISSUE THREAD

**Issue by TraderStf** [minbrowser/min#51]
I think a break point remains in the build mac app.
Open, crash.

**Comment by PalmerAL** [comment]
Sorry about that! Can you please post the crash report? Also, what version of OS X are you using?

Also, if you download a copy of Electron from here: https://github.com/electron/electron/releases/tag/v0.37.6 (the "electron-v0.37.6-darwin-x64.zip" file), does that crash?

**Comment by TraderStf** [comment]
OSX 10.11.4 (15E65)
I think the problem is the following.
I have iZip, it opens a zip as a volume/disk and you can drag its contents.
I saw in the report 'file too short', something was wrong with iZip.
That's the case, I unzip it normally (apple unarchiver), drag-drop the app. It's ok now.
(Just have to disable [Ostiarius](https://objective-see.com/) protection to launch it the first time, which is normal.)

(May I suggest to add a small js example in the archive, so user can see immediately how it's going on).

<pre>
Process:               Electron [2406]
Path:                  /Applications/Electron.app/Contents/MacOS/Electron
Identifier:            com.github.electron
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Electron [2406]
User ID:               501

Date/Time:             2016-04-18 11:55:47.407 +0200
OS Version:            Mac OS X 10.11.4 (15E65)
Report Version:        11


Time Awake Since Boot: 13000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/Electron.app/Contents/MacOS/Electron
  Reason: no suitable image found.  Did find:
	/Applications/Electron.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short

Binary Images:
    0x7fff60ed0000 -     0x7fff60f070d7  dyld (360.21) <D9B236BC-4AC1-325F-B3EF-3F06DBDA7119> /usr/lib/dyld

</pre>

**Comment by PalmerAL** [comment]
I haven't been able to reproduce this, and no one else has reported it, so I'm going to close this issue. If you have this problem again, please feel free to open a new issue!
