### ISSUE TITLE
[Windows] Some questions

### ISSUE THREAD

**Issue by carloscaffaratti** [minbrowser/min#517]
Hello! i want to ask two things about Windows version. How can i make to start with blank page and not with page i closed last time i used Min? and the other one is: is there any way to clear / delete cache? because i cant see in preferences.
Thank you in advance, and have a great week!

Carlos Octavio

**Comment by PalmerAL** [comment]
There isn't any way to do either of those things right now; starting with a blank page is #364. I think there's an issue for clearing the cache as well, but I can't find it right now. Thanks for the feedback!

**Comment by KagamineP** [comment]
I think this can be closed.
