### ISSUE TITLE
Remove Titlebar on Linux

### ISSUE THREAD

**Issue by CorbsEditor** [minbrowser/min#518]
![image](https://user-images.githubusercontent.com/26362558/37627880-f7ebd76e-2bac-11e8-888c-7c8d98d25345.png)
Ah, I see the titlebar isn't hidden here on Linux...maybe it is and it's just my distro(Deepin OS).
Anychange to get that removed?

I believe you have to set frame to false :thinking:

**Comment by PalmerAL** [comment]
The issue is that if we do that we need to render our own window controls. From #471:

> Electron only has native window controls that float over the window on macOS, so on Windows and Linux we have to make our own window controls in HTML if we want them to appear in the same row as the tabs. On Windows, this isn't too difficult, because there's basically only one UI, but on Linux there's a lot of different titlebar styles. #369 has a decent-looking Linux UI, but it won't match the other apps on your computer. I'm not sure which is better - a separate titlebar with native-looking window controls, or non-native controls integrated with the tabstrip.

**Comment by hezral** [comment]
If it's a consistent UI over all platforms, i don't think its too bad. Having unique UI that doesn't match the other apps in your OS isn't _that_ bad either.

**Comment by CorbsEditor** [comment]
Indeed, but I use MinBrowser because of it's compact user interface. Honestly, I have always wanted to build a browser with a compact UI, but I can't think of anything that can beat MinBrowser. MinBrowser just does it right.

**Comment by PalmerAL** [comment]
@CorbsEditor Is there a reason for closing this (and the other issues)?
