### ISSUE TITLE
Text in top menu-bar is invisible

### ISSUE THREAD

**Issue by BlueManCZ** [minbrowser/min#519]
Min version 1.7.1
Linux / Debian 10
![screenshot_20180321_232318](https://user-images.githubusercontent.com/17854950/37740790-4c89f4f0-2d5f-11e8-81a6-7545bae10e39.png)

**Comment by PalmerAL** [comment]
Looks like this is electron/electron#12331; we need to upgrade to 2.0.0-beta5 to include the fix.

**Comment by lordegeorge** [comment]
Hello, I still seem to be having this issue (not sure if it's resolved, and I'm using the latest build available on the Manjaro community repository) Is there a keyboard shortcut to get to the preferences menu?

**Comment by BlueManCZ** [comment]
@lordegeorge For me it's just alt key now..

**Comment by PalmerAL** [comment]
@lordegeorge Which version is that? If you can't get to the about dialog, you can go here: http://my-user-agent.com/ and look for the "Min/1.x.x" section.

ctrl+, should open the settings page, or you can type !settings in the searchbar.

**Comment by lordegeorge** [comment]
It's Min 1.8.0

**Comment by lordegeorge** [comment]
The top bar is usable if I press alt but I still can't see any of the labels.

**Comment by PalmerAL** [comment]
If you're using a theme with a dark title bar, this might be electron/electron#15878 as well.

**Comment by lordegeorge** [comment]
Yeah, changing my theme fixes it and I can now see the text. Thanks! (using XFCE by the way)

**Comment by PalmerAL** [comment]
OK, thanks for testing that! This was fixed in a newer Electron release, so this should be fixed the next time we upgrade the version of Electron that we're using.

**Comment by PalmerAL** [comment]
This is fixed in 1.9.0, you can download it here: https://github.com/minbrowser/min/releases/tag/v1.9.0.
