### ISSUE TITLE
Add `loading activity` or `progrss bar` when loading web page

### ISSUE THREAD

**Issue by clonezer** [minbrowser/min#52]
Please add something to make sure the browser is loading when clicking link or  open new tab

**Comment by jkanarek** [comment]
Something like this could work:
![loadingbar](https://cloud.githubusercontent.com/assets/1163147/14659902/d5ee3370-0654-11e6-9827-b551ec9f33c9.png)

**Comment by PalmerAL** [comment]
It seems kind of busy, though, since there are three different shades of green in the tabstrip. Also, having two different colors under the same text will likely be a problem, since the text may be readable on top of one color but not the other.

**Comment by jkanarek** [comment]
True, could just do a faint line on the bottom of the tab, like this:
![untitled_2](https://cloud.githubusercontent.com/assets/1163147/14660129/75ef8b9c-0657-11e6-9a5d-c501e847640d.png)

**Comment by TheInitializer** [comment]
There already is one...

**Comment by PalmerAL** [comment]
@TheInitializer No, there isn't.

**Comment by TheInitializer** [comment]
I get a little blue progress indicator directly under the tab bar... maybe I'm seeing something else?

**Comment by idle-zealot** [comment]
There's a bar like that on Google websites.

**Comment by TheInitializer** [comment]
It must have been something else, I tried loading a few pages and didn't see it.

**Comment by TheInitializer** [comment]
@idle-zealot I've only been on GitHub since I installed min, lol

**Comment by TheInitializer** [comment]
Oh lol, Github has one for its issue thing. *facepalm*

**Comment by jkanarek** [comment]
@PalmerAL how do you feel about the thin line approach? Mobile Safari and FB's browser both use this technique and I think it's pretty effective.

**Comment by PalmerAL** [comment]
A thin line would work pretty well. What should the algorithm for changing the width of the line be? There's no way to measure actual progress, so the progress shown will just be a guess.

**Comment by Smona** [comment]
Rather than a progress bar, maybe a loading indicator. Like Chrome has. But instead of that circular icon, you could use a sliding line on bottom, fading animation on the tab, etc.

**Comment by ashishwadekar** [comment]
@PalmerAL Considering the issue about algorithm, a spinner or an animated line would do just fine which will indicate that the page loading process is not yet complete. On internet connections have slow speed, I have found myself rechecking the tab if the page is loading or not and have refreshed page lot many times.

**Comment by abejfehr** [comment]
I had a hard time finding what the algorithm for a "fake progress bar" should look like, but I whipped something up in a JS Fiddle that you might find appropriate for Min: https://jsfiddle.net/6ysewx7w/

**Comment by PalmerAL** [comment]
@abejfehr That looks like it would work.

**Comment by PalmerAL** [comment]
This has been added in #453, and will be included in 1.7.0.
