### ISSUE TITLE
MIN doesnt launch without $sudo rights and display a JavaScript error

### ISSUE THREAD

**Issue by elkwaet** [minbrowser/min#524]
Hi,
Am using min since a moment, but it is not possible to run it like a own user, only with a super user right yet. I checked about /usr/bin/min directory and found its own by USER:501:GROUP:staff (i don't know what is it). Even am trying to make a chown to give the folder to USER:root, i can't run it normaly. I tryed to make a purge and re-installation several times without nothing.
My configuration: Debian9, Kernel:4.15
![capture du 2018-03-27 02-31-17](https://user-images.githubusercontent.com/18514510/37943510-5eef837e-3167-11e8-816e-dc56ccdcc69c.png)

**Comment by Syndamia** [comment]
@elkwaet are you still having this issue? For me it works fine right now.

**Comment by Syndamia** [comment]
Closing, because this issue seems to be something related to the author's configuration (from experience, Debian can be tricky) and it is quite old.
