### ISSUE TITLE
There should be a warning if another instance is already open

### ISSUE THREAD

**Issue by revolter** [minbrowser/min#526]
Cloning this project, following the instructions in the README and opening the apps throws these errors in the console:

```
database.js:81 database error occured DOMException: Internal error opening backing store for indexedDB.open.
(anonymous) @ database.js:81
database.js:81 database error occured Error: Database not open. Following error in populate, ready or upgrade function made Dexie.open() fail: UnknownError occurred when opening database browsingData. Internal error opening backing store for indexedDB.open.
    at Dexie.min.js:1
    at k (Dexie.min.js:1)
    at new t (Dexie.min.js:1)
    at Dexie.min.js:1
    at Function.t.newPSD (Dexie.min.js:1)
    at ir._promise (Dexie.min.js:1)
    at u._transPromiseFactory (Dexie.min.js:1)
    at Object.resume (Dexie.min.js:1)
    at Dexie.min.js:1
    at Array.forEach (<anonymous>)
(anonymous) @ database.js:81
database.js:81 database error occured Error: Database not open. Following error in populate, ready or upgrade function made Dexie.open() fail: UnknownError occurred when opening database browsingData. Internal error opening backing store for indexedDB.open.
    at Dexie.min.js:1
    at k (Dexie.min.js:1)
    at new t (Dexie.min.js:1)
    at Dexie.min.js:1
    at Function.t.newPSD (Dexie.min.js:1)
    at ir._promise (Dexie.min.js:1)
    at u._transPromiseFactory (Dexie.min.js:1)
    at Object.resume (Dexie.min.js:1)
    at Dexie.min.js:1
    at Array.forEach (<anonymous>)
```

**Comment by PalmerAL** [comment]
Do you have another instance of Min already running?

**Comment by revolter** [comment]
Oh

**Comment by revolter** [comment]
I struggled with this more than I wanted to :|

**Comment by PalmerAL** [comment]
Sorry about that! We should probably document that more clearly somewhere. Ideally we would support multiple instances, although since it's a restriction of IndexedDB I don't think there's anything we can do about it.

Actually, I wonder if we could detect this somehow, and show an error message like Firefox does; I'll look into that when I get time.

**Comment by revolter** [comment]
> Sorry about that! We should probably document that more clearly somewhere.

I created #527 for this.

> Actually, I wonder if we could detect this somehow, and show an error message like Firefox does; I'll look into that when I get time.

Do you want me to reopen this issue then?

**Comment by PalmerAL** [comment]
> Do you want me to reopen this issue then?

Sure, that's fine.
