### ISSUE TITLE
Npm questions

### ISSUE THREAD

**Issue by revolter** [minbrowser/min#533]
I have some questions regarding `npm`:

1. Is there any reason for not adding `electron` to it? I've done it locally and successfully used for development, by running `node_modules/electron/dist/Electron.app/Contents/MacOS/Electron .`.
This way, the docs would become easier by replacing the abstract `Path/To/Electron` with the actual path (with minor modifications for the different platforms).

2. Is there any reason for not adding the `package-lock.json` to git?

3. The first time, I had to run `npm i ajv` and `npm i webpack` because of `npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.`. Should we add these too in the README?

**Comment by PalmerAL** [comment]
> Is there any reason for not adding electron to it? I've done it locally and successfully used for development, by running node_modules/electron/dist/Electron.app/Contents/MacOS/Electron ..

Not really, I've just been using electron as a global module, but if it would be easier to do this I guess we could do that as well.

> Is there any reason for not adding the package-lock.json to git?

Generating a lock file wasn't the default when this project started, and I haven't had time to read about it yet. It looks like a good idea, I guess I'll add it.

> The first time, I had to run npm i ajv and npm i webpack because of npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.. Should we add these too in the README?

Oddly, I've never seen that warning before. If everything works without it though, I would assume that you don't actually need it.

**Comment by revolter** [comment]
> Not really, I've just been using electron as a global module, but if it would be easier to do this I guess we could do that as well.

I guess that the latest non-beta version `1.8.4`, right?

**Comment by PalmerAL** [comment]
@revolter The current release is based on 2.0, so you would have to do ```npm install electron@beta``` I think. 1.8 should work as well, but if you run Min with 1.8 after running with 2.0 you'll lose all your profile data (because Chromium changed the IndexedDB format I think).
