### ISSUE TITLE
Name too generic

### ISSUE THREAD

**Issue by ankitsultana** [minbrowser/min#54]
I liked the browser, but the name is too generic. I can't really search for it anywhere without getting a ton of unrelated garbage. Since the project is in its early stages, I think you should consider changing the name.

As an example, a google search for "Min Browser" throws UC Browser Mini etc.

**Comment by jkanarek** [comment]
I like it, think it will seem less generic when we do some light branding. Here's a mockup I was thinking about for a poster cc: @PalmerAL
![minposter](https://cloud.githubusercontent.com/assets/1163147/14659816/0e623716-0654-11e6-8206-5957efbed8ba.png)

**Comment by PalmerAL** [comment]
@jkanarek Looks nice! Maybe changing the branding should be a separate issue?

**Comment by dbfreem** [comment]
@PalmerAL I googled "Min Browser" and minbrowser.github.io was the number one hit. This one may be able to be closed now.

**Comment by PalmerAL** [comment]
It's definitely less of an issue than it used to be, although it can still be an issue in some situations (and Google still autocorrects "minbrowser" to "mi browser", so that isn't perfect either). I think I'll leave it open for now, although I doubt we'll actually end up changing the name.

**Comment by Sestowner** [comment]
@PalmerAL I think this can be closed.
