### ISSUE TITLE
Not able to keep staying signed in on Google services

### ISSUE THREAD

**Issue by toto1444** [minbrowser/min#540]
# Not able to keep staying signed in on Google services.

This issue is If turn off the browser or moves tabs to another task, 
although those tabs states are already signed in on Google, 
not able to keep stay signed in on Google services.

___
In short, could not use autologin on Min browser.

**Comment by PalmerAL** [comment]
Do you get the "please reenter your password" message, or does it act like you've never signed in before?

The part about moving tabs to another task is particularly confusing, because moving tabs shouldn't cause the page to be reloaded - is that what you're seeing?

**Comment by toto1444** [comment]
Sorry for late respond.
It is acting like I have never signed in before.
That is not only limited to Google Services.

**Comment by PalmerAL** [comment]
It's supposed to remember your data, I'm signed into a bunch of stuff (including Google) and I've never had any problems with cookies being deleted. You could try recreating your profile directory:

* Close Min.
* Go to `~/library/application support/min` on Mac, `\users\username\appdata\roaming\min` on Windows, or `/home/username/.config/min` on Linux, and delete that folder.
* Reopen Min.

**Comment by PalmerAL** [comment]
Is is just cookies that are being deleted, or do things like your browsing history and settings also disappear?

**Comment by Sestowner** [comment]
I can't reproduce this, so I'm going to close this issue. Feel free to reopen this if you have the problem again.

**Comment by Provonsal** [comment]
I have the same problem. 

Looks like history and cookies arent saving and deletes on closing the browser. I sign in youtube and after restarting browser it looks like i have never signed before. 

But i have a second tab with vk.com opened and there everything is fine, acoount saving even after restarting the browser
