### ISSUE TITLE
Possibility to delete the top bar

### ISSUE THREAD

**Issue by anim4k** [minbrowser/min#543]
In the Mozilla Firefox browser I can delete the top bar of the taskbar but in this browser can not
I wish to add a simple way to do this .
https://i.imgur.com/oyrvbGG.png

**Comment by code-hunger** [comment]
In the settings you can set a keybinding for hiding the menu.

**Comment by anim4k** [comment]
thank you

**Comment by code-hunger** [comment]
If this issue is resolved, you can click on _Close Issue_ to mark it closed.
