### ISSUE TITLE
Add developers to support plugins

### ISSUE THREAD

**Issue by anim4k** [minbrowser/min#544]
I hope that the addition of external additions will also be added. It would be very cool
https://i.imgur.com/vad1k70.png
good luck and thank you

**Comment by PalmerAL** [comment]
Duplicate of #1.

This would be really nice to have, but unfortunately I don't think it's going to happen. Supporting extension API's is a huge amount of work, and we don't have enough contributors either to initially implement that or to maintain it and make sure it is compatible with existing WebExtensions.
