### ISSUE TITLE
feature request: add tab option under command in terminal

### ISSUE THREAD

**Issue by turbochoo** [minbrowser/min#549]
min is awesome ,but it no option open tab  in terminal. open one min while clicking per url.

**Comment by PalmerAL** [comment]
I'm not sure I understand the issue, can you maybe provide a screenshot of what you're talking about?

**Comment by code-hunger** [comment]
@PalmerAL I think he wants something like firefox's `firefox -new-tab 'http://google.com'`, i.e. a command line option that will send a request to the main instance that a new tab should be opened with the given URL.

**Comment by Syndamia** [comment]
Closed because that's how it works now. By doing `min https://google.com` it will open `google.com` in a new `Min` tab (in the current task).
