### ISSUE TITLE
Copy is broken

### ISSUE THREAD

**Issue by jkanarek** [minbrowser/min#55]
Copying via command-c or edit-copy from within a tab doesn't seem to work.

**Comment by PalmerAL** [comment]
I can't reproduce this. Which OS are you using?

**Comment by jkanarek** [comment]
I'm on a Mac.

**Comment by jkanarek** [comment]
I restarted Min and the problem went away, but worth noting that there may be some inconsistency in the copy behavior.

**Comment by dbfreem** [comment]
Since this wasn't reproducable and only seemed to happen one time, Closing the issue.

@jkanarek open a new issue if this happens again or repsond here if you are still seeing the issue.
