### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by D0ve** [minbrowser/min#561]
Whould be great to use and Android version either!
Many thanks in advance!

**Comment by PalmerAL** [comment]
I agree an android version would be nice to have, but doing that would require redesigning most of the UI, and probably rewriting most of the browser, so I don't think it's very likely to happen.

**Comment by code-hunger** [comment]
This contradicts with the key phylosophy of min - a keyboard-operatable minimalistic browser with clean UI. 

Android users [almost] never use keyboards on their phones and don't need to organize more than 20 tabs in groups. These are the main features in min and also the reason for its existence - and you want to remove them.

Better use already thought-out browsers for mobile :)

**Comment by D0ve** [comment]
I use android, and am using more than 100 tabs...
And am using transparent on-screen altermative keyboard!
Have I covered by the philosophy of Min ;) ?

**Comment by D0ve** [comment]
Please, reopen the issue!
Would like using Min on Android! And using keyboard ui will enforcing using the browser, because ALL android browser's ui is very poor !!!

**Comment by code-hunger** [comment]
Min is based on Electron, which doesn't support Android. https://github.com/electron/electron/issues/562  
Making an android port is basically equivalent to starting from scratch, which is bellow any priority at the moment.

If you're really using more than 200 tabs on your phone, then you're not using the correct device to browse the internet. :laughing:
