### ISSUE TITLE
Browsing history

### ISSUE THREAD

**Issue by jejaree** [minbrowser/min#570]
How ca I delete my browsing history?

**Comment by code-hunger** [comment]
This comment shows how to clear browser data: https://github.com/minbrowser/min/issues/475#issuecomment-354016366

**Comment by jejaree** [comment]
Yeah Sorry.

**Comment by jejaree** [comment]
Can I delete this? How?

**Comment by code-hunger** [comment]
Closing an issue effectively means that you mark it as *resolved* and no longer appliable.
It can't be *deleted* the way you probably think of it. Just mark it as 'Closed'.

**Comment by jejaree** [comment]
Okay thanks sir.
