### ISSUE TITLE
Missing dependencies on Debian-based distros

### ISSUE THREAD

**Issue by sirredbeard** [minbrowser/min#571]
I had to install both libxssl1 and libasound2 to get min running from most recent released .deb file on a minimal Ubuntu 18.04 install.

Please consider adding these packages to the dependency list for Debian-based distros.

Thank you.

**Comment by dbfreem** [comment]
Are these two packages needed. I recently installed min on a fresh install of lubuntu and did get this error.

**Comment by PalmerAL** [comment]
I don't remember getting this the last time I installed min, but it should be pretty simple to add them to the list here: https://github.com/minbrowser/min/blob/master/scripts/buildLinux.js#L22, I'll go ahead and do it.

**Comment by sirredbeard** [comment]
Thank you!
