### ISSUE TITLE
Feature request : addind some !command

### ISSUE THREAD

**Issue by WilliShakes** [minbrowser/min#572]
Min is for now the minimalistic browser that I prefer, but it would be very cool if you could add some new !command,
like !history, which would display a page with history #as a list,
and !downloads, which would display a page with downloads as a list,
and create a page with bookmarks as a list.
Thank you in advance and good luck for the future !

**Comment by PalmerAL** [comment]
Good ideas! The !bookmarks command already exists, but the other ones sound good as well.

**Comment by PalmerAL** [comment]
* The !history command was added a couple releases ago.
* Starting in 1.9, there's a download manager that shows alll your downloads at the bottom of the screen.

I think that covers everything you mentioned, let me know if I missed something.
