### ISSUE TITLE
Can't login to sites by Google or Facebook

### ISSUE THREAD

**Issue by Whii** [minbrowser/min#573]
Both said "Session doesn't exist" or something like that.
Also, this website (http://notify.moe) doesn't load correctly on this browser I guess.

**Comment by abrarShariar** [comment]
hey @Whii the site is loading like this for me: 

 ![Imgur](https://i.imgur.com/5XLhz6B.png)

Can you please mention your system spec?

**Comment by lordhellraiser** [comment]
[Feedly](https://feedly.com) with Google doesn't seem to work with Min 1.8 (W10 x64)

**Comment by dbfreem** [comment]
@whii and @lordhellraiser can you comment if this is still an issue for you. If so what OS are you on?

**Comment by PalmerAL** [comment]
@dbfreem The login issues are because popup window support is missing, which is a duplicate of #140 (or one of a bunch of other issues open about this).

I can't reproduce the second issue, maybe it was a temporary thing?

**Comment by dbfreem** [comment]
duplicate of #140
