### ISSUE TITLE
Ad Blocker

### ISSUE THREAD

**Issue by ateymuri** [minbrowser/min#574]
This is not a bug but a question: Is there any Ad Blocker in min (for youtube etc.) and if so how can i set it?

**Comment by PalmerAL** [comment]
Yes, there is. If you go to the Min preferences (there's an option for it in the menu bar, or you can press ctrl+,), you'll see a "block trackers and ads" option.

**Comment by ateymuri** [comment]
Thanks for your reply, under the Preferences i don't see any "block trackers and ads" option. I am using the min version 1.7.1, is that a version issue?

**Comment by PalmerAL** [comment]
Can you post a screenshot of what your preferences screen looks like? You should see something like this:

<img width="1440" alt="screen shot 2018-06-28 at 12 21 36 pm" src="https://user-images.githubusercontent.com/10314059/42050190-dd53d7b0-7acd-11e8-8753-398f48afc348.png">

**Comment by ateymuri** [comment]
Sorry! My fault, i just saw it. Thanks for your help!
