### ISSUE TITLE
Clicking links opens new min window

### ISSUE THREAD

**Issue by ghost** [minbrowser/min#576]
Under Debian clicking on a URL Link (from outside of min, for instance on a PDF file ....) will open a new window. How can i setup min to open new links as a new tab?

thanks

**Comment by PalmerAL** [comment]
I think this is a duplicate of #243?

**Comment by ateymuri** [comment]
It doesn't seem to be solved there?

**Comment by PalmerAL** [comment]
@ateymuri It isn't fixed yet, but if both of these issues are about the same thing, it's easier to just leave one of them open.

**Comment by dbfreem** [comment]
duplicate of #243
