### ISSUE TITLE
Many harmless sites detected as malicious

### ISSUE THREAD

**Issue by surajsharma** [minbrowser/min#58]
I'm getting the "malicious" website warning way too often and on trusted sites, whats worse i cannot bypass the warning. please fix asap

**Comment by PalmerAL** [comment]
Can you please share some examples of sites that you get the warning on? Also, if you're still using 1.1.1, please upgrade to 1.1.2 from here: https://github.com/PalmerAL/min/releases. There were several bugs about this that were fixed in that version.

A bypass for the warning is something that will be added soon, there's another issue filed for that: #13 .

**Comment by howardm** [comment]
An example

I use a web site for the downloading of radiology files:  X.X.X.X:3333

(The port is "3333")

Howard

**Comment by surajsharma** [comment]
there isn't a set formula or pattern to which the blocking adheres, everything from official government websites to personal interest websites are getting blocked. once there is a bypass, it should be no problem. thanks.

**Comment by jgclark** [comment]
I'm using 1.1.2 and find that www.glassesdirect.com is OK, but trying to view my order with them (https://www.glassesdirect.co.uk/account/orders/YNKUH8-ECYCXB/) is blocked in this way.

**Comment by PalmerAL** [comment]
@jgclark Glassesdirect.co.uk is fixed in 2d895353444d9d8ae11f0ab2af25549a8a7c1dd8.

**Comment by PalmerAL** [comment]
@surajsharma Do you have any specific examples? A bypass will definitely be added, but I'd like to fix the incorrect warnings as well.

**Comment by reconstructed** [comment]
same issue. here's one example but i've encountered many others making min almost unusable for me.
http://www.theage.com.au/afl/afl-news/ivan-maric-set-to-return-for-richmond-tigers-brett-deledio-an-afl-chance-too-20160421-gobiw4.html

**Comment by surajsharma** [comment]
the examples for sites I could share are all working now, strangely. case in point: http://mea.gov.in
