### ISSUE TITLE
Unable to download picture/PDF from Google Drive

### ISSUE THREAD

**Issue by thinhakapetevn** [minbrowser/min#585]
After I click download button, save-as window appears, I choose place to save then nothing happens. I understand at this time there is no download management yet, but with other files they are still downloaded.

**Comment by PalmerAL** [comment]
I can't reproduce this on macOS, which OS are you using?

**Comment by thinhakapetevn** [comment]
Im using Arch Linux with kernel 4.17.10

**Comment by abrarShariar** [comment]
I could download both picture (*.png) and pdf from Google Drive. I am on **Ubuntu (16.04)**. 

But it didn't show any confirmation on successful download or an option to quickly navigate to the saved location. This could be a useful feature but I guess that's a different issue.

**Comment by PalmerAL** [comment]
@abrarShariar I think that's #91.

**Comment by Sestowner** [comment]
I can't reproduce this, and this been idle for a while, so I'm going to close this issue. Feel free to reopen this if you have the problem again.
