### ISSUE TITLE
[installation] Min is available via yaourt on arch.

### ISSUE THREAD

**Issue by geraltofrivia** [minbrowser/min#586]
This should be mentioned somewhere in the README.md / release page.
`yaourt -S min-browser-bin` works. Atleast for me (using Manjaro).

**Comment by code-hunger** [comment]
It is also available in the community repository and installable as a normal package via `pacman -S min`, no need for the AUR. Better use the official package instead.

**Comment by geraltofrivia** [comment]
Ah yeah you're correct. Thank. 
IMHO this should be mentioned somewhere.

**Comment by code-hunger** [comment]
I guess the Installing section in Readme could have a list of the available packages for major distros. 

I see a reason against adding it though - @PalmerAL is not the one to support them and he's not responsible for keeping them up-to-date. E.g. for Arch this is "tensor5". Don't know about other distros.

**Comment by PalmerAL** [comment]
I think it'd be OK to add a list (although we should probably mention that they might be outdated). However, there have been issues in the past with video playback not working in the official package (see #353), so you might actually want to use the AUR version.

**Comment by thinhakapetevn** [comment]
Also, official package is lack of openbox Min titlebar icon. AUR version does have it.

**Comment by Syndamia** [comment]
Closed because the [AUR package](https://aur.archlinux.org/packages/min-browser-beta-bin/) is severly out of date (version `1.8.0 Beta 1`) and Linux packages are discussed in #735

**Comment by PalmerAL** [comment]
For anyone else looking at this, the official package (https://www.archlinux.org/packages/community/any/min/) is up-to-date, and the issues with it seem to have been resolved, so that's probably the best one to use.

**Comment by kodumbeats** [comment]
As of writing, the aforementioned [community repo](https://www.archlinux.org/packages/community/any/min/) is out of date, so I updated the source files for 1.16.0 and will continue to maintain.
https://www.archlinux.org/packages/community/any/min/

**Comment by PalmerAL** [comment]
@kodumbeats Thanks for doing that! The package linked is still listed as 1.15 for me - is there a second copy somewhere else that you updated, or is there some kind of process updates have to go through to be approved?

**Comment by kodumbeats** [comment]
That's because I can't copypasta 🤦🏻 I'd upload the package to the AUR, but it's against the rules since it's maintained in the official community repo. I think the best we can do is prod the maintainer on the (incorrect) above link. Here's what I've got:
https://github.com/kodumbeats/min-archlinux

**Comment by PalmerAL** [comment]
Got it. The maintainer has responded fairly quickly when I've emailed him about the package in the past; I don't want to bother him too much, but if it isn't updated in a bit I'll ask about it.
