### ISSUE TITLE
Youtube Page Load Problem

### ISSUE THREAD

**Issue by Fabriziogit** [minbrowser/min#589]
After some days of use (about 2 weeks), when I opened youtube.com the page only loads the icons, but no the text :(

**Comment by PalmerAL** [comment]
Can you try clearing the cache for that site? (Developer menu > Inspect page > Application tab > Clear storage > Check all the boxes and click the "clear site data" button).

**Comment by abrarShariar** [comment]
hey @Fabriziogit could you make it work?

**Comment by PalmerAL** [comment]
@abrarShariar Did you try clearing the cache as well? If you open the console (developer > inspect page > console tab), do you see any resources that failed to load?

**Comment by abrarShariar** [comment]
Actually mine is loading alright. No issues with icons (didn't need to clean cache). I was thinking maybe the issue has already been sorted out by @Fabriziogit

**Comment by Fabriziogit** [comment]
Thanks for the help, what I did is only I remove and install again Min Browser and youtube worked again :) I hope in a future version of Min can solve this issue
El 26 de ago. de 2018 12:42 -0500, Abrar Shariar <notifications@github.com>, escribió:

Actually mine is loading alright. No issues with icons (didn't need to clean cache). I was thinking maybe the issue has already been sorted out by @Fabriziogit<https://github.com/Fabriziogit>
