### ISSUE TITLE
Moving a tab to a different task in TO does not refresh tab bar

### ISSUE THREAD

**Issue by clayton-grey** [minbrowser/min#593]
1. Open TO
2. Move a tab to a different task
3. Close TO 

**Issue:** Tab is still shown in the tab bar (appropriately inaccessible). You must change tasks and return to the original task in order for the bar to update.

**Comment by PalmerAL** [comment]
Sorry about that! Fixed in bdd6dac1fccbc9ca5ab632b1905e296ba00d7e2e.
