### ISSUE TITLE
Keyboard shortcut for switching tabs

### ISSUE THREAD

**Issue by achou11** [minbrowser/min#600]
Out of curiosity, is there a reason why `mod` n is implemented the way it is for switching tabs? Most browsers have it so that the shortcut chooses the nth tab whereas Min has it select the nth tab **to the right**. I'm definitely used to the former and I didn't realize Min's implementation until recently.

This is not a request for change. I'm just interested to understand the decision from a usability perspective. I think I can get used to it - and maybe even prefer it - now that I actually know what it does. 😅

**Comment by code-hunger** [comment]
By the way after I got used to it it became realy handy. Now I even find it inconvenient as is done in most browsers.

- The usual way works well so far as there are no more than 9 tabs. After that, all tabs between the eight and the last are inaccecible. 
- This point follows from another difference in Min's tab behaviour - a new tab is open not on the last, but on the position right next to the currently open tab. This makes your tabs follow some logic, i.e. similar tabs are close to each other and more unrelated tabs are far from each other. I think it's obvious that you'll more often switch between similar tabs than between distant tabs. You're more likely to want to go to a tab + - 4-5 tabs away from yours, than to one of the first 8 tabs or to the last one.
- it is usually easier to count mentally the tabs with difference from the current one than from the start. Imagine you're on the 5th tab and want to go right. It's easier to see you need to shift by 3 tabs than to determine that you want the 8th one. Of course, if instead you wanted to go left, the absolute number of the tab would work (for range 1-4), but so would the relative one. Again, the previous point applies - on the 10th tab you can hardly make out whether you want the 8th or 9th, and impossible to go to the 12th or after it.

**Comment by achou11** [comment]
Thanks for that explanation! Makes a lot of sense especially with Min's new tab behavior that you mentioned :)

**Comment by Syndamia** [comment]
Closed because OP accepted the explanation.
