### ISSUE TITLE
Uncaught Exception: TypeError: Cannot read property 'setBounds' of null

### ISSUE THREAD

**Issue by abrarShariar** [minbrowser/min#601]
This error window pops up with the msg: **A JavaScript error occurred in the main process** when clicked on the remove button (bin icon) in the top right corner. I am running it with `npm run watch` and have this in the terminal: 

`Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.`

OS: Ubuntu (16.04)

![Imgur](https://i.imgur.com/uksDDXn.png)

**Comment by PalmerAL** [comment]
Sorry about that, fixed in f1e573e9c187bb724a7350408568f988c70fa39f. Since we've rewritten a lot of the tab-handling code in this release, I'm guessing there are more bugs like this; please open more issues if you notice anything else!

**Comment by coder963** [comment]
when I hibernate my system and open after sometime, this issue come. My internet was off in that duration. using windows version.

**Comment by PalmerAL** [comment]
@coder963 Can you make a new issue for that, with the exact error message you're seeing?
