### ISSUE TITLE
Please, let us decite about ad rules

### ISSUE THREAD

**Issue by davede-git** [minbrowser/min#609]
Hello,

I would like to change/add/modify in-built adblock's rules, because I have noticed that some ads are not blocked. It would be nice to see it or provide me please any instructions how to do it :) . Thank you.

**Comment by pavel2001** [comment]
See https://github.com/minbrowser/min/issues/376#issuecomment-322046785
It's good to allow user to modify adblock rules through settings in ABP compatitable format, but now it's unimplemented.

**Comment by PalmerAL** [comment]
I'm going to close this, since it's a duplicate of #376. In the meantime, you can manually edit the `ext/filterLists/easylist+easyprivacy-noelementhiding.txt` file to add filters (the exact location of this file will depend on your operating system).
