### ISSUE TITLE
Just saying thank you for your hardwork

### ISSUE THREAD

**Issue by balbooaaa17** [minbrowser/min#624]
I've been waiting for a new version and checking every once a week too see if u dropped anything, i've been using your browser for more than a year non-stop and love it, and bang, just today i saw the beta release. I saw what did u there fam :p ... the history & bookmarks are in the menu and a fancy UI too(no more spoiling). 

Thank you fella for making awesome software . 

Peace & all the best

**Comment by PalmerAL** [comment]
Thanks, I'm glad you like it! Please feel free to open issues here if you have any suggestions.
