### ISSUE TITLE
Its more like a question rather than a issue, I guess

### ISSUE THREAD

**Issue by Elder-Louzada** [minbrowser/min#629]
Well, I've been using Min Browser for a couple of weeks and having some trouble to figure out some stuff in the software.
The first topic is more like a noob question. I wish to know how to see what am I downloading, in others browser I just used Ctrl-J shortcuts and then I could see it, but here it doesn't work.
The other trouble is with the software options that should appear on the header. I mean, instead of the header come up with options its just blank and without nothing, like a bug. PS: when I use other graphic interface, like Gnome or KDE, this bug doesn't occurs.

**Comment by PalmerAL** [comment]
> The first topic is more like a noob question. I wish to know how to see what am I downloading, in others browser I just used Ctrl-J shortcuts and then I could see it, but here it doesn't work.

We don't have a download manager yet, that's issue #91. There's been a lot of requests for this, so I'm probably going to try to add it sometime soon.

> The other trouble is with the software options that should appear on the header. I mean, instead of the header come up with options its just blank and without nothing, like a bug. PS: when I use other graphic interface, like Gnome or KDE, this bug doesn't occurs.

Does it look like the image in #519? If so, that should be fixed in the 1.8 beta release, could you try running that and see if it works?

**Comment by Elder-Louzada** [comment]
Yeah, the menu bug was exactly like the one in #519. Hopefully, it not happened when I updated to the version 1.8. By the way, thanks for the answer.
