### ISSUE TITLE
Persistent tasks

### ISSUE THREAD

**Issue by manuelmazzuola** [minbrowser/min#633]
It would be nice if tasks survive between sessions.
Like in a new session tabs are restored it could be useful add an option to restore last tasks.

**Comment by code-hunger** [comment]
What happens currently? How is what you describe different from the current behaviour? What you request is what should happen normally.

**Comment by manuelmazzuola** [comment]
UH

> What happens currently? 

They are restored

![](https://media.giphy.com/media/Ob7p7lDT99cd2/giphy.gif)
