### ISSUE TITLE
Reader shows up in history

### ISSUE THREAD

**Issue by emersion** [minbrowser/min#64]
Hide it or display the real page's URL instead.

![capture du 2016-04-18 17 13 16](https://cloud.githubusercontent.com/assets/506932/14609156/dce50afe-0588-11e6-8957-88f84db30bd0.png)

**Comment by PalmerAL** [comment]
This also applies to the other browser pages (PDF viewer, error page, preferences, etc.)

**Comment by PalmerAL** [comment]
This was fixed around a year ago in 1d45b141136f62b29e8fc6bc428fd125fb9807b9.
