### ISSUE TITLE
Youtube not displaying correctly

### ISSUE THREAD

**Issue by Fabriziogit** [minbrowser/min#640]
Version: Min 1.8.0
OS: macOS Mojave 10.14 (18A389)
 Youtube is not displaying correctly, I hope in the next version the Min team will fix this issue
<img width="1280" alt="captura de pantalla 2018-10-13 a la s 16 06 34" src="https://user-images.githubusercontent.com/31196440/46910015-55225e00-cf02-11e8-9bfe-d45267a14ccb.png">

**Comment by PalmerAL** [comment]
It works correctly for me; can you try opening the console (developer > inspect page > console tab) and seeing if there are any errors?

**Comment by dbfreem** [comment]
@Fabriziogit have you experienced this anymore?

**Comment by KagamineP** [comment]
I can't reproduce this, so I close this now. Feel free to reopen.
