### ISSUE TITLE
Feature request: task name more visually distinct

### ISSUE THREAD

**Issue by mivanit** [minbrowser/min#642]
Currently, the task name appears in a very slightly larger font with a barely noticeable difference in font color than the webpage names and URLs that follow it. Either the font size, color, or background could be changed to make the task name stand out better.

**Comment by mivanit** [comment]
> I'lll go for a few pixels to the left, thus giving the impression of tree view.

having the tasks be collapsible as well would actually be ideal

**Comment by Kepler-69c** [comment]
Close as the task view was improved.

The task font has been changed and collapsible tasks have been implemented (see image):

<img width="1000" alt="image" src="https://github.com/minbrowser/min/assets/80059906/190285d4-6a1f-4023-a290-ae716b9b91e0">
