### ISSUE TITLE
Links open a new min window

### ISSUE THREAD

**Issue by teymuri** [minbrowser/min#645]
On Debian , clicking on Links open a new window instead of a new tab. Is this behavior correctable?

**Comment by PalmerAL** [comment]
Thanks for reporting this! This is a duplicate of #390, so I'm closing this issue in favor of that one.

**Comment by teymuri** [comment]
Thanks. So is it fixed now and what should i do to get that behavior?

**Comment by PalmerAL** [comment]
@teymuri Sorry, it's not fixed yet! If you click the "subscribe" button in that other issue, you should get notifications when it is eventually fixed.
