### ISSUE TITLE
Error at the start

### ISSUE THREAD

**Issue by LucasGarais** [minbrowser/min#647]
Hey, I just download the current version of the browser and when I click at the application, this error are displayed
![error](https://user-images.githubusercontent.com/1902706/47231720-1b3ed500-d3a4-11e8-85d2-074d008610e6.png)

I hope someone could help me. 
Thankful.

**Comment by PalmerAL** [comment]
I've seen this occasionally before as well, but I've never figured out what's causing it. If you go to `C:\Users\your username\AppData\Roaming\Min` and delete the "windowBounds.json" file, and then relaunch Min, it should work.

**Comment by LucasGarais** [comment]
Thank you!
It worked here, thank you so much for the help.
