### ISSUE TITLE
MacOS High Sierra

### ISSUE THREAD

**Issue by gelderode** [minbrowser/min#649]
**Latest Min 1.8.0 darwin --  1e6a489 -- can't be opened on MacBookPro with High Sierra**

-----
Process:               Min [1184]
Path:                  /Applications/Min.app/Contents/MacOS/Min
Identifier:            com.electron.min
Version:               1.8.0 (1.8.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Min [1184]
User ID:               501

Date/Time:             2018-10-23 18:40:32.180 +0200
OS Version:            Mac OS X 10.13.6 (17G65)
Report Version:        12
Anonymous UUID:        121E43E5-8E3B-BCE3-83CD-5B22DA368643

Time Awake Since Boot: 2000 seconds
System Integrity Protection: enabled
Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/Min.app/Contents/MacOS/Min
  Reason: no suitable image found.  Did find:
	/Applications/Min.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
	/Applications/Min.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1

Binary Images:
       0x10e167000 -        0x10e167ff7 +com.electron.min (1.8.0 - 1.8.0) <81ECE029-ACAE-3254-B3E8-ACC9610CFAB3> /Applications/Min.app/Contents/MacOS/Min
       0x1132fc000 -        0x113346acf  dyld (551.4) <8A72DE9C-A136-3506-AA02-4BA2B82DCAF3> /usr/lib/dyld

Model: MacBookPro8,2, BootROM MBP81.0050.B00, 4 processors, Intel Core i7, 2 GHz, 8 GB, SMC 1.69f4
Graphics: Intel HD Graphics 3000, Intel HD Graphics 3000, Built-In
Graphics: AMD Radeon HD 6490M, AMD Radeon HD 6490M, PCIe
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1333 MHz, 0x80AD, 0x484D54333531533642465238432D48392020
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1333 MHz, 0x80AD, 0x484D54333531533642465238432D48392020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xD6), Broadcom BCM43xx 1.0 (5.106.98.102.30)
Bluetooth: Version 6.0.7f10, 3 services, 27 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: TOSHIBA MK5065GSXF, 500,11 GB
Serial ATA Device: HL-DT-ST DVDRW  GS31N
USB Device: USB 2.0 Bus
USB Device: FaceTime HD Camera (Built-in)
USB Device: Hub
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM2070 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: USB Optical Mouse
USB Device: IR Receiver
Thunderbolt Bus: MacBook Pro, Apple Inc., 22.1

----

**Comment by PalmerAL** [comment]
It looks like the file got corrupted when you downloaded it somehow, can you try downloading it again?

**Comment by gelderode** [comment]
OK issue closed.
I downloaded it again, now from the https://minbrowser.github.io/min/  and  there is no problem to open the application. Tour works, search with DDG also. So it seems all right.
Thanks, greetings.
