### ISSUE TITLE
Remove "Window" menu

### ISSUE THREAD

**Issue by emersion** [minbrowser/min#65]
Contains only "Minimize" and "Close". These tasks are the OS' responsibility, not the browser ones.

**Comment by dbfreem** [comment]
@PalmerAL was there another reason for the "Window" menu? I tend to agree with this if the only two things that are going to be under "Window" are "Minimize" and "Close" then maybe "Window" isn't needed?

**Comment by PalmerAL** [comment]
@dbfreem It seems to be standard to include a window menu on macOS, but you're right that we could probably get rid of it everywhere else.

**Comment by PalmerAL** [comment]
Fixed in a088e6a2403e37edc20ab3833f32b689b9ad5169.
