### ISSUE TITLE
[Bug] Print from Reader Mode

### ISSUE THREAD

**Issue by Matlock42** [minbrowser/min#650]
I've been trying out Min for about a week. I really like it overall.

When trying out the Reading Mode I tried printing an article out. The first page is basically blank with just "< Back to article". The other issue which is a little more anoying is the text is sometimes split between pages. (see below)

![image](https://user-images.githubusercontent.com/4711757/47590299-2c9a5b00-d929-11e8-979d-69302c1f1879.png)

>Windows 10 (1709) Build 16299.726
>Min v1.8.0
>Chromium v66.0.3359.181

I'm also using dark mode. That might be relavent.

**Comment by PalmerAL** [comment]
Thanks for reporting this!  I've fixed both of these issues in aad04231d456cf36b1b2966bd6dbead159f7a413.
