### ISSUE TITLE
Forced dark mode on Mojave

### ISSUE THREAD

**Issue by AndreiDuma** [minbrowser/min#651]
Hi! First, nice job with this browser! I just installed it and I like it, but I have a small issue: I'm not able to turn off the dark mode:
![image](https://user-images.githubusercontent.com/1846640/47623463-d5071580-db09-11e8-8258-9b2f3c951fb2.png)
I can turn it on and off in the Preferences, but it makes no difference.
![image](https://user-images.githubusercontent.com/1846640/47623477-e94b1280-db09-11e8-8245-3ff9e15e35e9.png)

Thanks!

**Comment by PalmerAL** [comment]
Currently, the dark mode is automatically enabled between 10PM and 6AM, regardless of the preference you have set. I agree there should be a way to turn this off; there's already an issue for that (#286), so I'm going to close this one.

**Comment by rharunzade** [comment]
Still not fixed. Bad idea :(
