### ISSUE TITLE
window.open does not work correctly

### ISSUE THREAD

**Issue by mailtokartik1** [minbrowser/min#652]
Operation System:All OS

Steps to reproduce:

Open http://str.cloudn-service.com/dl.lunascape.jp/dl-lunascape/dl/Phoebe/work/sbi_test.html
Try checking the links below.

I recently came across this browser based on Electron. Our own product is based on Electron and we had this difficulty of implementing window.open into a new tab our browser. We got a workaround by changing the implementation of window.open in Electron by creating guest contents in Electron when window.open is opened. We then attached the created guest web contents to the web frame in the client side code by guestInstance. This worked fine until Electron v2.0.x.
In Electron v3.0.x, they have implemented OOPIF architecture recently. Here is a link for that
electron/electron#14120.

I would love to know more about the implementation in Min regarding this issue and would be amazing to know more information about how we can workaround this issue.

Thank you.

**Comment by PalmerAL** [comment]
Currently, we override the `new-window` event and create a new view based on the given URL: https://github.com/minbrowser/min/blob/master/js/webviews.js#L338

This works fine for simple usecases, but there's no way for the original page to communicate with the popup, so not all of the examples you linked will work.

**Comment by mailtokartik1** [comment]
Thank you for the answer @PalmerAL. I could implement the same behavior in our browser too. Do you have any ideas on how to implement for the rest of the usecases?

**Comment by PalmerAL** [comment]
You might be able to use this: https://electronjs.org/docs/api/window-open#using-chromes-windowopen-implementation, but when I tested it in the past, it still didn't work completely. I'm guessing you're going to have to modify Electron to get something that works in every case.

**Comment by mailtokartik1** [comment]
I have used this implementation and it works by creating  a new browser window every time a window.open script is run. I changed the implementation to create new tab instead of a browser window and attach the web contents via guestInstance. This is almost identical as your implementation of window.open in Min browser.
