### ISSUE TITLE
Min as default browser

### ISSUE THREAD

**Issue by ghost** [minbrowser/min#656]
I created a [batch file](https://gist.github.com/lordhellraiser/57b8af565408fdbee2e8deaaeec56629) to make Min the default browser, the only thing to do is update Min.exe location. It's simple and only has support for .htm, .html, http, and https. Feel free to modify to every filetype/protocol Min supports.

**Comment by PalmerAL** [comment]
This is really great, thanks! I'll try to figure out how to integrate this into Min when I have time; I'm guessing we could probably add a "set as default" button somewhere in the UI.

**Comment by sabarishwar** [comment]
Ah the batch file is not working correctly with win 7. When I run the batch file i'm getting this error. Any idea how to fix this? 
Thanks!
![min](https://user-images.githubusercontent.com/4488418/49886230-199f0400-fe5f-11e8-90d6-014c24a27b31.JPG)

**Comment by LukaFX** [comment]
thank you for this!

**Comment by CodeIter** [comment]
batch file link broken 💔

**Comment by Syndamia** [comment]
@CodeIter the user that originaly posted it probably deleted their account (*right now the account with that name registered on `3 April 2020`, meaning the original guy deleted their account and some time later another person registered with the same username*)

**Comment by PalmerAL** [comment]
This was integrated into Min a few versions ago, so the batch file shouldn't be necessary any more.
