### ISSUE TITLE
Building instructions please ? For those who try to build from source

### ISSUE THREAD

**Issue by ScarFez** [minbrowser/min#658]
Please, if possible add building instructions along with required tools ?

**Comment by code-hunger** [comment]
Depending on whether you want to develop Min or just build an executable binary, you have two options. Both are described in the readme in the root repo directory:

For development: https://github.com/minbrowser/min#developing

For building binaries: https://github.com/minbrowser/min#building-binaries

**Comment by PalmerAL** [comment]
@ScarFez I think the instructions in the README should cover all the steps, and the tools you need to install. If there's something you think is unclear, please let us know so we can clarify!
