### ISSUE TITLE
Issue when using Ctrl-F to search

### ISSUE THREAD

**Issue by dbfreem** [minbrowser/min#679]
First, I use ctrl+f and type in the word I want to search for. After that I want to scroll up and down the page to see where the highlighted comments are. As of now when I start to scroll using the **scroll bar** on the right the search goes away.I think the preferred outcome would be for the text to stay highighlighted until you cleared the search or decided to search for something else.Thoughts??

**Comment by PalmerAL** [comment]
Right, that probably would be better. If you start interacting with the page itself, I think we do want to hide the find bar, but we need some way to detect clicks on the scrollbar vs the actual page, and ignore the scrollbar ones.

**Comment by code-hunger** [comment]
How about an invisible full-width and full-height container to catch the page clicks? This way it will catch all clicks except for the scrollbar.

**Comment by PalmerAL** [comment]
We can't stack anything on top of the BrowserView, but we could probably just attach an event listener to the document from within the preload script, and send an IPC message to the UI process.

If we do that, we'd also need to figure out what other scenarios the find bar should be hidden in as well - right now, we just hide it as soon as the text input loses focus, but if we do this we'll need to also hide it whenever you switch tabs, open the task overlay, etc.
