### ISSUE TITLE
How does Min render tabs?

### ISSUE THREAD

**Issue by neko-is-kitty** [minbrowser/min#686]
Hello.

Because GitHub has no possible way to directly message someone, I would like to ask a question here because I would like an answer as soon as possible.

Since @PalmerAL seems to know a lot about Min, I would like to ask him directly here. How does Min render tabs, and how are they styled? I would like to know because I like these sort of tabs and would like to implement this style in my app; I also am fairly new to coding in general, so I don't have the ability to look at code as if it is the finished project. Please be comprehensive about this and include code snippets, since I am a visual person and I learn better that way.

And I did notice the browser is released under the Apache 2.0 license; since I'm requesting a feature and not the browser, I believe I don't have to do the license as well. Please let me know if I'm wrong on this as well.

**Comment by PalmerAL** [comment]
The tabs themselves are just `<div>` elements, with [CSS flexbox](https://medium.freecodecamp.org/learn-css-flexbox-in-5-minutes-b941f0affc34) used to make them all equal-width.

I don't think there's anything unusual about the contents of the tabs themselves - there's an element that holds the text for the tab title, and another element with `float: right` that holds the icons. When you click on the tab, those are hidden, and an `<input>` element is displayed that you can type in.

The opening/closing animation happens as a result of this code: https://github.com/minbrowser/min/blob/master/css/tabBar.css#L172 and a CSS `transition` property - when you click on one tab, the other tabs graduallly shrink to 0 width over whatever duration you choose for the transition.

The code to calculate the color for the tabs is here: https://github.com/minbrowser/min/blob/master/js/navbar/tabColor.js. Basically, it samples some of the pixels in the tab icon, and picks the color that appears the most frequently.

One thing you might want to look at is the developer tools: "developer" menu > "inspect browser" > "elements" tab. If you right-click anywhere on the content, you can choose "expand recursively", which will show you all the elements on the page. From there, you can hover over each element to see which thing on the page it corresponds to. If you click on an element, you'll get a list of CSS properties on the right, with checkboxes for each one. If you're not sure what a property does, try disabling it and see how it affects the way the tabs look.

Without knowing specifically what you want to know about the tabs, it's kind of hard to answer this question - is there any particular part that you're looking to replicate?

> And I did notice the browser is released under the Apache 2.0 license; since I'm requesting a feature and not the browser, I believe I don't have to do the license as well. Please let me know if I'm wrong on this as well.

Any code you use from Min would be licensed under the Apache 2.0 license; however, you can use Apache 2.0-licensed code in a project even if the rest of the code isn't licensed under the same license. This page has an explanation of what you can and can't do: https://choosealicense.com/licenses/apache-2.0/ (if you hover your mouse over the items in the list at the top). If you want to mimic the way the UI looks but don't want to use any of the actual code, I don't think you have to do anything (although this isn't really a great idea in general - you want to come up with something that fits your application).
