### ISSUE TITLE
Download manager

### ISSUE THREAD

**Issue by LukaFX** [minbrowser/min#688]
The download manager is considaberly slower than all other browser's download managers. Please also add a pause and show folder button please!

**Comment by PalmerAL** [comment]
> The download manager is considaberly slower than all other browser's download managers

* Does this happen on every website, or just a specific download?
* Are downloads still slow in the currently-released version of Min, without the download manager?
* If you go here: http://www.dslreports.com/speedtest, do you get the same download speed as you do in other browsers?
* While you're downloading something, can you open the profiler (developer menu > inspect browser > performance tab > click the circle icon) and post a screenshot of the profile?

> also add a pause button

I think I want to wait and see if more people request this feature; supporting resumeable downloads makes the download manager code more complicated, and I'm not sure how many people would actually use it.

> show folder button

Good idea, I'll try to do that before the 1.9 release.

**Comment by PalmerAL** [comment]
@LukaFX I've added a button to show the item's folder in e37856fb320cf5a39c98d186909281bb926f813d.

**Comment by dbfreem** [comment]
I saw the folder icon button in the latest release. Since there haven't been other complaints about performance or the pause button, this may be able to be closed.

**Comment by PalmerAL** [comment]
I think you're right.
