### ISSUE TITLE
Weird ghosting issue

### ISSUE THREAD

**Issue by LukaFX** [minbrowser/min#690]
Sometimes when watching YouTube and ALWAYS Twitch, there is a weird ghosting effect where it played what happened before while its playing whats happening now, idk though. Its not on any other browsers.

**Comment by PalmerAL** [comment]
Interesting, it kind of sounds like this Electron issue: https://github.com/electron/electron/issues/3836 (although we don't use a transparent window). Disabling hardware acceleration would probably fix it, but it would also reduce performance on some sites; I don't really have any other advice for now.

**Comment by LukaFX** [comment]
also, When I unplug my second monitor Min still opens where the second monitor would be when I minimise and unminimize and I cant see it unless I restart. I'm not sure if this is only an issue with Min but no other programs do it.

**Comment by PalmerAL** [comment]
@LukaFX I've created a separate issue, #693, about that (and posted a reply).

**Comment by Syndamia** [comment]
@LukaFX are you still having this issue? Also, if you've stopped using Min, could you perhaps install it and check it the issue persists?
