### ISSUE TITLE
Issues with websites

### ISSUE THREAD

**Issue by LukaFX** [minbrowser/min#696]
On fiverr it says its time to upgrade your browser, anyway to fix this?

**Comment by PalmerAL** [comment]
This looks like the same issue as #657; the site works correctly if you use the same user agent as Chrome does, so we'll need to use a different user agent on that site (or get them to fix their browser-detection code, but that's probably not going to happen).

You can access the site by going to developer > inspect page > menu button (in the upper-right) > more tools > network conditions. Then, uncheck the "select automatically" option next to "user agent", and select another option like "chrome windows". However, this will stop working as soon as you close the devtools window.
