### ISSUE TITLE
Shift+ScrollUp issue

### ISSUE THREAD

**Issue by Thalos12** [minbrowser/min#698]
When tabs are overflowing from the tab bar it is possible to show the hidden tabs on the right using Shift+ScrollDown. Moving in the opposite direction does not work since Shift+ScrollUp opens the task overlay.
Moreover, any combination of (ctrl,alt,shift)+ScrollUp opens the task overlay.

**Comment by PalmerAL** [comment]
Fixed in ff74abda3ede1aab40e8dd9aa82088736911a976.
