### ISSUE TITLE
Drag & drop doesn't work?

### ISSUE THREAD

**Issue by burnoutberni** [minbrowser/min#71]
Drag & drop of text or files doesn't seem to work. E.g. dropped text should be inserted into input/textarea fields and dropped links onto non-receptive DOM elements should open a new tab.

**Comment by abejfehr** [comment]
This [seems to be intentional](https://github.com/minbrowser/min/blob/master/js/default.js#L7).

Is there a good reason for this?

**Comment by PalmerAL** [comment]
In older versions of Electron, dropping items onto webviews would load the dropped file in the main window, breaking the app. This actually seems to work now, so I guess it's fine to re-enable.

**Comment by PalmerAL** [comment]
Drag-and-drop seems to work fine now. I've removed the listener in c862a93d133eba1c3f6cbdaf1b42d68ab3c6eb2c, although it doesn't seem like it was actually having an effect.
