### ISSUE TITLE
Window bounds files can become corrupted

### ISSUE THREAD

**Issue by old-scribe** [minbrowser/min#714]
When launched, it doesn't start but renders a notification (see a snapshot)
--
Windows 10 64x Home

![image](https://user-images.githubusercontent.com/47826942/53109383-cfff2380-3549-11e9-8061-7a8941cbef51.png)

**Comment by PalmerAL** [comment]
I think this is the same issue as #325; it should start working again if you delete this file: `/home/<your username>/.config/Min/windowBounds.json`.

Also, what were you doing before this error occurred? It would be nice to figure out why this is happening, so we can prevent the error from happening in the first place, but I haven't found a way to reproduce it - if this happens consistently for you, please let me know.

**Comment by PalmerAL** [comment]
I've change this in 8e74feb3cdf723ada419889d9211ea060446b6d8 so that window bounds files with corrupted data are ignored, which should help with this; rather than producing an error, Min will create a new window that fills the entire screen.
