### ISSUE TITLE
Fullscreen videos disabling controls?

### ISSUE THREAD

**Issue by clayton-grey** [minbrowser/min#720]
Not sure what the deal is, but recently and reliably mouse (and keyboard?) behavior is being disrupted after fullscreen video playback. Sometimes reloading the page rectifies it, but more often than not I need to close and reopen the application. 1.9.2 OSX. Multiple video players seem to cause the behavior.

**Comment by PalmerAL** [comment]
This sounds like it might be electron/electron#16418, which makes the upper part of the window unclickable after you exit fullscreen mode. That issue seems to be fixed in Electron 5, it should be fixed in Min soon, but that shouldn't have any effect on keyboard behavior - what issues are you seeing with that?

**Comment by clayton-grey** [comment]
Non-responsiveness? But I it might just be the mouse; as it can't change focus, the keyboard merely appears not to work.

**Comment by PalmerAL** [comment]
This affects both the browser's keyboard shortcuts, and trying to type in the page, right? Also, if you switch to another app (making the Min window lose focus), and switch back, does it start working again?

**Comment by clayton-grey** [comment]
The shortcuts seem to work. So I think I was correct about just not being able to select a textfield makes it seems that way. 

Alt-Tab seems to _sometimes_ fix the responsiveness of the page, but not the tab bar. Unfortunately this behavior is not consistent. Performing combinations of Alt-Tab only, Alt-Tab + click within the alt window, along side clicking different elements in a YouTube tab, it seems to both return mouse control to the page returning to normal behavior, maintaining the non-responsive behavior except for the video, and oddly remove control from the video but restoring mouse control to the page but not the tabs. Additionally, when the mouse control does return to the page it sometimes seems to need multiple clicks in order to do so. Additionally, after leaving full screen, occasionally the first click will register - for example selecting the comment field, where subsequent clicks fail to register. In this instance the keyboard typing works, as the field has focus, but cannot lose the focus.

In no instance is normal tab behavior restored for the mouse without restarting the browser.

Additionally, closing the video tab in fullscreen with the keyboard shortcut causes the tab bar to remain hidden even after exiting the full screen context with the OS UI button.

EDIT: One exception: If you use the OS UI button to make Min full screen _before_ entering video full screen, the tabs and other UI continue to work with the mouse while in the full screen context after exiting a full screen video. However, returning to the standard window context causes the mouse to lose functionality again until you return to the full screen context via UI button or restarting the browser.

**Comment by PalmerAL** [comment]
That's really odd; I'm pretty sure the issue with the tab bar is the electron issue I linked above, but I have no idea what's going on with the webpage area.

> Additionally, closing the video tab in fullscreen with the keyboard shortcut causes the tab bar to remain hidden even after exiting the full screen context with the OS UI button.

This looks like a separate issue: we currently track fullscreen status globally, but the "leave-html-full-screen" event is never emitted when the view is destroyed, so all future views will also be rendered as if they were in full screen. Apparently, when I originally implemented this, the necessary events to do this correctly were missing from the Electron documentation (making me think they didn't exist at all), but they do exist, and the documentation was just added to Electron a few days ago: https://github.com/electron/electron/commit/ac88b3ead5e1a7ba89b6b96d46439754c45fcb42#diff-9b078be8f43e00e3b99edb5be31fa353. So I think that issue should be fairly simple to fix.

**Comment by PalmerAL** [comment]
> Additionally, closing the video tab in fullscreen with the keyboard shortcut causes the tab bar to remain hidden even after exiting the full screen context with the OS UI button.

Fixed in d2eeee6b7bae1eb083f953c600daf932f539d0a5.

**Comment by clayton-grey** [comment]
Glad some of this seems readily fixable! I guess the simplest thing would be to see if these behaviors continue past the Electron update, in which case I'll try to test figure out a means of reproducing specific cases.

**Comment by PalmerAL** [comment]
@clayton-grey Thanks for testing that! If you build Min from the master branch to try running it with Electron 5, make sure to make a copy of your profile folder first to avoid losing data, see here for an explanation: https://github.com/minbrowser/min/issues/717#issuecomment-471325465

**Comment by clayton-grey** [comment]
I am more likely to wait for a stable release, but if I find I have some time, I'll give it a go.

**Comment by PalmerAL** [comment]
@clayton-grey I think this is fixed now, can you check in 1.10 and see if this is still an issue?

**Comment by Sestowner** [comment]
Does anyone know if this issue still exists for Mac?

**Comment by clayton-grey** [comment]
Quick test of YouTube in 1.15 seems to suggest it works fine. Closing.
