### ISSUE TITLE
Add 'min://settings' style pages.

### ISSUE THREAD

**Issue by AwesomeTech10** [minbrowser/min#724]
This is a feature request, but instead of the settings page being ```C:\...\pages\settings\index.html```, make a UI change to make the UI say the page is ```min://settings```, or something similar. Also, add some code that when the user types ```min://settings``` the browser loads the page ```C:\...\pages\settings\index.html```. Same for all the other internal pages.

**Comment by PalmerAL** [comment]
I think this should be pretty simple to do; we would need to modify `urlParser.parse` to convert the min:// URL into the equivalent file one, and `urlParser.getSourceURL` to convert it back.

**Comment by PalmerAL** [comment]
Fixed in 433aa94bad8b44abea94f9fb673de0d9749bd9a4.
