### ISSUE TITLE
ContextMenu

### ISSUE THREAD

**Issue by JGSangara** [minbrowser/min#729]
Can you provide an insight on how you implemented the `ContextMenu `on the `webView`.

**Comment by PalmerAL** [comment]
There's a `context-menu` event on webContents that provides the data you need to create the menu: https://electronjs.org/docs/api/web-contents#event-context-menu. From there, you can use the [menu](https://electronjs.org/docs/api/menu) module to create the menu.

The code for the menu is here, if you want to take a look at that as well: https://github.com/minbrowser/min/blob/master/js/webviewMenu.js
