### ISSUE TITLE
Lost all open tabs and tasks

### ISSUE THREAD

**Issue by Yutolio** [minbrowser/min#734]
I just closed Minbrower normally and on reopen later today I was greeted with the "Welcome to Min" only tab.
All my tasks and tabs are gone (i had many of them open...) and the history/bookmarks dont contain all of them.
Is there a backup file anywhere to be found in the min-browser folder?

**Comment by Yutolio** [comment]
Alternatively, the history file could work too! So I can just scroll through my links from there

**Comment by PalmerAL** [comment]
Hi, I'm sorry that happened!

Just to clarify, do you still have your history and bookmarks (view > history), or are those gone as well?

Normally, if your open tabs were corrupted, you would see a screen that says "an error occurred", and in that case a backup file would be created in the folder that holds the rest of Min's data. However, based on your description, I'm guessing the data was deleted completely somehow, which unfortunately means there probably isn't a backup file, although as you mentioned, if you still have your history data you might be able to use that.

It's fairly unusual for localStorage data to disappear, so I'm not entirely sure what would make this happen. One possibility is that you ran a version of Min with a newer version of Chromium, and then downgraded to an older version - is there any possibility that you have multiple versions of Min installed?

**Comment by Yutolio** [comment]
Thanks for the quick reponse!
Yes, I can still see search old history entries via !history and !bookmarks is there too.
I'm not really tech-savvy so maybe the backup file has been created and I can't find it.
I would have to look inside this folder right? 
![explorer_2019-04-19_01-16-48](https://user-images.githubusercontent.com/28668131/56396798-eb806500-6240-11e9-924d-28bef81800a6.png)
As for history data, where can I locate the history file so I can use that instead perhaps?

**Comment by Yutolio** [comment]
Regading your question, I just checked if I had different versions of Min running and no, the one I run is in fact starting from the folder I attached in the picture.

**Comment by PalmerAL** [comment]
If there was a backup file, it would be in `C:\Users\your username\AppData\Roaming\Min`, and the name would start with "sessionRestoreBackup"; however, there likely isn't one based on the fact that you never saw an error message.

If you just type `!history ` (with a space but no other text), you should see a list of some of your recent history; you should be able to get some of your tabs from there. Getting older history without searching for it is a bit more complicated (which is also something we should probably fix):

1. Go to developer > inspect browser
2. Go to the "console" tab.
3. In the row of buttons at the top, you should see something that says "top" with an arrow next to it. Click on that, and choose "placesWorker.js":
<img width="244" src="https://user-images.githubusercontent.com/10314059/56398815-5a919580-6210-11e9-8cf8-c5b5603f7f10.png">
4.. Paste this in the text input at the bottom of the window and press enter:

```
db.places.orderBy("lastVisit").each(i => console.log(i.url))
```

You should see a list of all your history (sorted with the most recent at the bottom), which you could copy the URL's from into new tabs.

Once again, I'm really sorry this happened! It's a bit hard to say exactly what happened, but I'm thinking we could probably either start auto-generating backup files, or switch to a simpler method of saving the tabs that might have fewer problems.

**Comment by Yutolio** [comment]
I checked under AppData\Roaming\Min and there's sadly no "sessionRestoreBackup". However I managed to recover my tabs from the history dump thanks to your method. 
Thanks for the help!

**Comment by PalmerAL** [comment]
I'm glad it worked! I've opened a new issue to change the way session restore works (which should hopefully be more reliable): #737
