### ISSUE TITLE
Donation/monetary contribution?

### ISSUE THREAD

**Issue by will-ca** [minbrowser/min#736]
Not everyone can code or enjoys coding. Nearly everyone has some kind of currency that they can trade, though.

Why not have some kind of donation system or other financed distribution model? If Min had a "Donate" button like many other projects or a pay-what-you-want option like Elementary OS, then I'd probably chip in a few bucks after trying it.

**Comment by PalmerAL** [comment]
Thanks for being willing to donate! You're right I probably should do this; I'll look into it at some point.

**Comment by Syndamia** [comment]
Closing, because @PalmerAL enabled Sponsorship.
