### ISSUE TITLE
Add link destination when hovering over link

### ISSUE THREAD

**Issue by ireallydontwantthisaccount** [minbrowser/min#742]
In other browsers, when you hover over a link a small box in the bottom left corner appears with the destination of the link. It would be nice to be able to do this with Min, too. Having it in the bottom corner might not look too great but having it appear under the link would probably look cool.

**Comment by PalmerAL** [comment]
Duplicate of #134. I like the under-the-link idea, it might not work on all page layouts though (and since we can't layer things on top of the BrowserView, we'd have to inject elements into the page, which might not always work).

**Comment by ireallydontwantthisaccount** [comment]
Oops.
