### ISSUE TITLE
Page forward button

### ISSUE THREAD

**Issue by consllogluke** [minbrowser/min#744]
There's an option to have a page back button in the top bar but why not a page forward?

**Comment by ireallydontwantthisaccount** [comment]
And a reload button, too.

**Comment by PalmerAL** [comment]
I'm not sure adding more buttons to the navbar is a good idea, it makes the UI more cluttered and takes up a lot of space when the window is at a small size. I do agree there should be a way to reload other than a keyboard shortcut; we could probably add that to the context menu.

**Comment by ireallydontwantthisaccount** [comment]
Alright, you could also do something like double clicking the back button goes forward and triple click restarts the page or something like that.

**Comment by PalmerAL** [comment]
Double-click seems like it would be fairly confusing, and it would also introduce a delay when going backwards (since you'd have to wait to see whether the button gets clicked a second time or not). Maybe a context menu on the back button itself?

**Comment by Tomadelostacos** [comment]
Three functions for the same button would be a bad pattern. 
I suggest showing a page forward button that's hidden by default, showable by a setting, and displayed only when a forward page is available. This way the UI stays as light as possible most of the time, and the button is displayed only when it has a meaning.

**Comment by ep1955** [comment]
Given the importance of being able to go back/forward, it would seem a forward button would be well worth the real estate.  An alternative would be a generic button; left-click for back, right-click for forward.  Possibly better yet, you'd use the mouse wheel to go back and forth.

**Comment by ebrensi** [comment]
I really like Min with as minimal a GUI as possible.  I have never had a problem with going forward.  ctrl-right.
In fact, I would go the other way and say a back button is not really necessary.  ctrl-left.

**Comment by ep1955** [comment]
ebrensi, I agree with you completely regarding ctrl L & R, I use hotkeys most of the time anyway.  I just thought a corresponding forward button would be useful given you likely already have your hand on the mouse anyway, clicking on links and all.  That said, I'm certainly going to use Min as I like the speed and simplicity.

**Comment by ebrensi** [comment]
@ep1955 have you seen this? https://github.com/PalmerAL/min-vim-mode

**Comment by lubiedo** [comment]
Forward button merged on #1665.
