### ISSUE TITLE
Menus and key shortcuts for commands

### ISSUE THREAD

**Issue by ireallydontwantthisaccount** [minbrowser/min#745]
There are commands like `!history` and `!bookmarks` but there should be menus and key combination shortcuts for them, too.

**Comment by ireallydontwantthisaccount** [comment]
Just found out how to use those commands, nevermind!

**Comment by PalmerAL** [comment]
There are menu items in the view menu (which isn't named very well, I'm not sure what else to call it). I think you're right that there should be keyboard shortcuts, though. Maybe shift+ctrl+b and shift+ctrl+h ?
