### ISSUE TITLE
Improve the task system

### ISSUE THREAD

**Issue by PalmerAL** [minbrowser/min#747]
From #738:

> One thing I've been thinking about is changing the task overlay so that tasks are sorted based on how recently you've used them, and tasks you haven't opened in a long time would get collapsed so they don't take up as much space. That way, you could leave tasks open for longer without them getting in the way as much, so that you wouldn't have to delete anything unless you're really sure you don't need it anymore (although the actual state of the pages open would probably be discarded to save memory). But I'm not sure if that would address what you're talking about?
>
>I think I'm going to include a survey about the tasks feature in the next release; it would be good to know what other people think about this as well, since I don't want to disrupt anyone's workflow too badly if they're relying on the existing feature.

Current draft of the survey: https://forms.zohopublic.com/minbrowser/form/Taskssurvey/formperma/b6qx5QWqMx5SW6NSef3sbITA28WE65AujUBvXemZ8YE

I think this could probably work as a link at the top of the task overlay, hopefully it's not too disruptive:

<img width="841" src="https://user-images.githubusercontent.com/10314059/57563567-f3758580-7364-11e9-9944-055fe16c568b.png">

**Comment by PalmerAL** [comment]
@brakkum I wasn't sure if you had any other thoughts on possible changes, is there anything else you think I should ask?

**Comment by PalmerAL** [comment]
I think it might be useful to include the date a task was last opened, some possible ways to do that:

<img width="1217" src="https://user-images.githubusercontent.com/10314059/58603894-0be80a00-8258-11e9-9932-09f6a94db6a8.png">

**Comment by PalmerAL** [comment]
The tasks survey has around 20 responses so far, some preliminary results:

<img width="1210" src="https://user-images.githubusercontent.com/10314059/59733553-e37a7c80-9213-11e9-98b0-e33792944743.png">
<img width="1176" src="https://user-images.githubusercontent.com/10314059/59733552-e37a7c80-9213-11e9-9764-d3b7f46a7b1b.png">
<img width="588" src="https://user-images.githubusercontent.com/10314059/59733551-e2e1e600-9213-11e9-92f8-88cd9ff23ecb.png">

("na" means no answer provided)

* Automatic task sorting is (surprisingly to me) unpopular, I guess we won't do that.
* Collapsing tasks seems reasonably popular, and I think it doesn't have too many downsides to implement, so I'll probably implement this for the tasks prototype.
* Adding other content types is much more complex, so I don't think I'll do it for now, but there's enough interest in it that we should consider adding this in the future (if we can figure out a good UI for it).

**Comment by swiftmas** [comment]
any possiblity of favicons getting worked into tasks? would help track down a tab when your doing fast switching.

**Comment by PalmerAL** [comment]
I'm kind of skeptical that favicons would help with tab switching; in most cases, I have a bunch of tabs from the same site open anyway, and if you're trying to read the tab titles to find a tab, I think the favicon ends up being distracting more than anything else. But I can definitely add an option for it so we can collect some feedback on it.

**Comment by PalmerAL** [comment]
I've added a setting to show icons next to each tab in 249dbeb5e921bd6636b2970a5b122988984ce92c; hopefully this will allow us to collect some feedback on whether this should be included in the final design or not.

**Comment by swiftmas** [comment]
Awesome! I'll be sure to leave some feedback. I had not thought about your concern and I understand why what might be a problem. I'll let you know.

**Comment by dbfreem** [comment]
@palmeral are you leaving this open for a reason or can it be closed since the PR is merged?

**Comment by PalmerAL** [comment]
I think it's fine to close this, since most of the improvements are done. It might be good to fix some of the things I mentioned in https://github.com/minbrowser/min/pull/784#issuecomment-514367117 eventually, but I don't think it has to be done now.
