### ISSUE TITLE
Min couldn't connect securely to this website

### ISSUE THREAD

**Issue by cjimenezvz** [minbrowser/min#748]
This website is not available. Min couldn't connect securely to this website:
https://correo.ivic.gob.ve/ or https://mail2.ivic.gob.ve/

SSL certificate error! The page you are trying to access has the following errors in the SSL certificate: The server certificate is not trusted How do you add an exception for that certificate?

**Comment by PalmerAL** [comment]
That website uses a self-signed certificate, so I think the fact that it's showing an error is correct. There's currently no way to add an exception, that's issue #249.
