### ISSUE TITLE
Installer can be maximized, but not can be unmaximized.

### ISSUE THREAD

**Issue by MairwunNx** [minbrowser/min#751]
![image](https://user-images.githubusercontent.com/39625750/57937915-b0209700-78cf-11e9-83d3-574883a54ef2.png)

> For reproduce:
> ###### 1. Download installer for windows from releases.
> ###### 2. Run it, and wait showing installer window.
> ###### 3. Just move to top screen position by height.
> ###### 4. Snap window and unpress mouse.

> Excepted behavior:
> ###### 1. Installer window must be able for resizing.
> ###### 2. Installer window can't be maximized \ or change maximized state.

> `W10x64 1809. Min v1.10.0.`

**Comment by Syndamia** [comment]
After a bit of research, I'm pretty sure this is a problem, either with [Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows) (the framework we use to create the windows installer) or with [electron-installer-windows](https://github.com/electron-userland/electron-installer-windows) (the tool that actually creates the installer).

Either way, I don't think there is much we can do about it at our end.

**Comment by Milad-Laly** [comment]
As this is an issue beyond our team. I'll be closing the issue due to the fact we can't do anything.
