### ISSUE TITLE
White bottom line on large screens.

### ISSUE THREAD

**Issue by MairwunNx** [minbrowser/min#752]
Please, see screenshots. This is not very noticeable on sites with a light background, but if you look at a line of 15 to 20 pixels, if you change the size of the window a little smaller, it line not will be visible.

![image](https://user-images.githubusercontent.com/39625750/57968791-b36f5d80-7977-11e9-8399-918bac09e4a4.png)

![image](https://user-images.githubusercontent.com/39625750/57968795-cbdf7800-7977-11e9-9858-84d4b206d0fd.png)

![image](https://user-images.githubusercontent.com/39625750/57968800-e580bf80-7977-11e9-9dec-cc4a527f9fe7.png)

`W10x64 1809. Min v1.10.0.`

**Comment by PalmerAL** [comment]
Thanks for reporting this, fixed in 5017716084baa30bc277b27f76df36e3fe1ed618.
