### ISSUE TITLE
Request: context menu with "cut, paste, etc" not show when right click on search bar.

### ISSUE THREAD

**Issue by MairwunNx** [minbrowser/min#753]
It would not be bad to add a context menu to the search field, in some situations when I hold a beer in my left hand it is not convenient for me to press `ctrl + c \ v`, it’s more convenient with a mouse in this situation, but it’s a pity that the context menu wasn’t :(

**Comment by Tomadelostacos** [comment]
Nice comment ! I'm on it, it works, i just need to translate it before pushing. (Cut, Copy, Paste, Select All, Undo or Redo)

**Comment by Tomadelostacos** [comment]
#754 it's here (translated in french, and in english atm for all other languages, with a comment to let people translate by themselves, i'm not polyglot enough for all those languages)

**Comment by MairwunNx** [comment]
@Tomadelostacos good job! I review your PR and suggest strings for russian strings.

**Comment by Tomadelostacos** [comment]
Resolved in #754 ! (Not by me though, sorry ! )
