### ISSUE TITLE
openSUSE Version

### ISSUE THREAD

**Issue by Tezeug** [minbrowser/min#767]
Hello,

do you plan to create the compiled version of the Min browser for the Fedora or openSUSE, too?

Thanks.

**Comment by PalmerAL** [comment]
I think this is a duplicate of #219.

There was a PR to add this a really long time ago (#96), it might be worth trying to get that to work again.

**Comment by Tezeug** [comment]
Thank you.

**Comment by Tezeug** [comment]
I would definitely appreciate it. I like your browser.

**Comment by PalmerAL** [comment]
Fixed in 31384f19f8966aa23b2c4f89a3d1a4ce2d2452fa; a prebuilt RPM file will be provided starting with the next release.
