### ISSUE TITLE
Min won't play twitch.tv videos

### ISSUE THREAD

**Issue by unnamedcrewman** [minbrowser/min#77]
Thanks for this browser.  I seems fast, and I really appreciate the minimal approach.

For some reason, I can't get Min to play videos from twitch.tv.  It works great with youtube and other video content though.  I've tried twitch.tv with the Ad-blocker on and off and after multiple restarts. The site loads just fine, but the videos won't start.

Thanks.

**Comment by PalmerAL** [comment]
Twitch.tv still uses flash player for video, but Min doesn't support flash player. Most other sites have switched to HTML5 at this point, which is why Youtube works fine.

**Comment by idle-zealot** [comment]
Chromium's Pepper Flash works with electron, so it would be possible to include optional support for Flash.

**Comment by unnamedcrewman** [comment]
Thanks for the heads up.  I didn't know about the flash issue.  It is not a big deal for me, and for sure not a priority.  I can use Chrome when I get desperate to watch twitch :).  I'll just wait and see if any solution develops over time.

Thanks again for the help.

**Comment by liam4** [comment]
Yeah, I can't view Scratch projects with Min, either -- pretty big downside. Of course eventually Scratch will be moving to HTML5, but until then..

**Comment by wb9688** [comment]
@PalmerAL To add support for plugins like Flash Player, you've to add the [plugins attribute](https://github.com/electron/electron/blob/master/docs/api/web-view-tag.md#plugins) to the `<webview>` tag...

**Comment by OverGlass** [comment]
You can use this trick to watch Twitch with Min
**http://player.twitch.tv/?html5&channel=[Chanel_Name]**

Safari works well with twitch in html5 without this trick, I'm not developper but I presume it is possible to run Twitch in html5 with Min ?

Thank you for your browser, it's great!

**Comment by PalmerAL** [comment]
Interesting, I thought HLS (which is what Twitch's HTML5 player is using) only worked in Safari, but apparently it works in other browsers too.

**Comment by dbfreem** [comment]
@PalmerAL I went to https://www.twitch.tv/ and videos were playing. Since most things are moving to HTML5, and min is desinged to be minimal shouldn't flash continue to be unsupported?

**Comment by towerofnix** [comment]
It's indeed been nearly three years (and Twitch and Scratch are HTML5 now), and since Flash is being formally deprecated 2020ish, I guess it doesn't make sense to prioritize work on supporting it at this point.

Although it would be interesting if Flash could run anyway.

**Comment by PalmerAL** [comment]
Electron has built-in support for Flash, so it probably wouldn't actually be that difficult to get it to work: https://electronjs.org/docs/tutorial/using-pepper-flash-plugin

However, like you said, pretty much every site has migrated away from Flash anyway, so I don't think there's much point in doing this (and Flash tends to be slow and insecure, so I'm not sure we want to support it anyway).

**Comment by dbfreem** [comment]
Since Flash isn't really support be by alot of other browsers and this is from 2016, closing
