### ISSUE TITLE
Pressed "ALT" always opens submenu [non-convenient for 2 languages users]

### ISSUE THREAD

**Issue by Gawhie** [minbrowser/min#779]
Good Day! First of all, thank you for the browser - I was amazed by its superspeed! 
My issue is the following. I am using 2 languages in Windows 10 and I always press "ALT + SHIFT" in order to switch between 2 languages while typing. 

The problem is that the pressed "ALT"-button or "ALT"+any button combination always turns on sub-menu with "File, Edit and etc." [_see the screenshot below_] and totally prevents the language switch. 
Is there a way to turn off "ALT"-button causing this sub-menu to appear? 

**Screenshots with explanations:**
https://files.catbox.moe/55nb10.png
OR
https://i.postimg.cc/X7q7LxWz/ALT-screenshot-20190708.png

**Comment by PalmerAL** [comment]
That is pretty annoying! I'm guessing we should change this shortcut to something else that isn't triggered so easily - any ideas?

In the meantime, if you open the settings, find "show and hide menu bar" under "keyboard shortcuts", and remove the "alt" entry, it should stop this from happening.

**Comment by PalmerAL** [comment]
This will be fixed as part of #784 by changing the default shortcut to ctrl+m.

**Comment by PalmerAL** [comment]
This will be fixed in the next release.
