### ISSUE TITLE
Feature Request: "clean data" button 添加清理数据按钮

### ISSUE THREAD

**Issue by qq892640791** [minbrowser/min#785]
我认为清理数据是很重要的，因为我的缓存目录超过1g在浏览网页1个小时，而且键入的网页历史太长，我认为应该像chrome一样清理缓存，历史纪录，cookie，和其他的垃圾
I think it's important to clean up the data because my cache directory is more than 1G and I've been browsing the web for an hour, and the history of the typed pages is too long. I think we should clean up the caches, history, cookies, and other garbage like chrome.

**Comment by PalmerAL** [comment]
Min definitely shouldn't be using that much space after just an hour - it's using around 3.5gb on my computer, and that's for 6 weeks of history and several hundred bookmarks. Can you please check the following?

* Inside the main Min directory, check the size of each of the following:
    * `Cache`
    * `IndexedDB/file__0.indexeddb.leveldb`
    * `Local Storage`
* Open the developer tools (`developer > inspect browser > console`), and look for the item that says "top":
<img src="https://user-images.githubusercontent.com/10314059/56398815-5a919580-6210-11e9-8cf8-c5b5603f7f10.png" width="300"/>

  * Click on it, and select "placesWorker.js"
  * Paste the script below and press enter:
```
var tokens = 0, len = 0, items = []

db.places.each(function(item) {
  tokens += item.searchIndex.length;
  len += item.searchIndex.join("").length;
  items.push({url: item.url, len: item.searchIndex.join("").length})
}).then(function() {

console.log(tokens, len, items.sort((a, b) => {return b.len - a.len}).slice(0, 20).map(item => {return item.url + "\t" + item.len}).join("\n"));

});
```

Remove any URL's you don't want to share, and post the results here.

<hr>

（使用谷歌翻译翻译）闵绝对不应该在一小时后使用那么多空间 - 它在我的电脑上使用大约3.5gb，这是6周的历史和数百个书签。 你能检查一下吗？

* 在主Min目录中，检查以下各项的大小：
    * `Cache`
    * `IndexedDB/file__0.indexeddb.leveldb`
    * `Local Storage`
* 打开开发人员工具（`developer> inspect browser> console`），然后查找显示“top”的项目：

<img src="https://user-images.githubusercontent.com/10314059/56398815-5a919580-6210-11e9-8cf8-c5b5603f7f10.png" width="300"/>

  * 单击它，然后选择“placesWorker.js”
  * 粘贴下面的脚本，然后按Enter键：
```
var tokens = 0, len = 0, items = []

db.places.each(function(item) {
  tokens += item.searchIndex.length;
  len += item.searchIndex.join("").length;
  items.push({url: item.url, len: item.searchIndex.join("").length})
}).then(function() {

console.log(tokens, len, items.sort((a, b) => {return b.len - a.len}).slice(0, 20).map(item => {return item.url + "\t" + item.len}).join("\n"));

});
```

删除您不想分享的任何网址，并在此处发布结果。

**Comment by qq892640791** [comment]
我认为那不是bug，我观看8k视频在线，而且还在浏览许多网页，我只是需要一个清理数据按钮，我认为对大多数人来说那是必要的，不是所有人都会手动查找删除数据和历史和cookie，毕竟不是所有人都是程序员。良好的用户体验可以提升知名度，使用度，顺便，这是个很棒的项目，我要给这个项目点一个大大的赞，希望该项目越来越好
I don't think it's a bug. I watch 8K videos online and I'm browsing a lot of web pages. I just need a data cleaning button. I think it's necessary for most people. Not everyone will find deleted data and history and cookies manually. After all, not everyone is a programmer. Good user experience can enhance visibility, usability, by the way, this is a great project, I want to give this project a big compliment, hope that the project is getting better and better.

**Comment by PalmerAL** [comment]
We might add a button, but I'd also like to find out why Min is using so much storage space for you. The actual cache (which is where things like videos would be stored) is managed by Chromium, and shouldn't ever get larger than a few hundred megabytes regardless of how many pages you visit. That leaves around 800 mb that is taken up by something else. I think the issue might be the full-text search index, so checking the size of `IndexedDB/file__0.indexeddb.leveldb` and running the script above will show whether or not that's the issue, and probably provide some ideas as to how this can be fixed - can you try doing that?

Hopefully, this will let us reduce the amount of storage space used, so you won't need to click a button constantly to free up storage space.

<hr>

我们可能会添加一个按钮，但我也想知道Min为什么要为你使用这么多存储空间。 实际缓存（存储视频的内容）由Chromium管理，无论您访问多少页面，都不应超过几百兆。 这留下了大约800 MB，被其他东西占用。 我认为问题可能是全文搜索索引，因此检查“IndexedDB/file__0.indexeddb.leveldb”的大小并运行上面的脚本将显示这是否是问题，并且可能提供一些关于如何修复它的想法  - 你能尝试那样做吗？

希望这会让我们减少使用的存储空间量，因此您不需要经常单击按钮来释放存储空间。

**Comment by qq892640791** [comment]
i clean the C:\Users\Administrator\AppData\Roaming\Min\*  ,so now it's zero,the high speed is back,i used a lite windows10 , it cut many many  assembly ，just use 1.0gb ram and it's very fast , It has many small visible bugs. ,i think maybe because this ，Thank you very much for your attention to this issue.min is very fast than other browser（chrome, firefox,),Thank you again for your contribution to this project,

**Comment by kalepf22** [comment]
> i clean the C:\Users\Administrator\AppData\Roaming\Min* ,so now it's zero,the high speed is back,i used a lite windows10 , it cut many many assembly ，just use 1.0gb ram and it's very fast , It has many small visible bugs. ,i think maybe because this ，Thank you very much for your attention to this issue.min is very fast than other browser（chrome, firefox,),Thank you again for your contribution to this project,

say, does Min clean history by default? so far it works excellent but I don't know what's going on with history and offline files since I'm new to the browser
