### ISSUE TITLE
userscript not launch

### ISSUE THREAD

**Issue by nwdxlgzs** [minbrowser/min#788]
userscript not launch.
miyun.smartclass.cn.js
?????
window.onload=alert("running");
?????
i change some word to show our native language, but the userscript not launch?i just translate the word.....

**Comment by PalmerAL** [comment]
I can't load that website to test this, but here are a couple things you could try:

1. Make sure userscripts are enabled in the settings page.
2. Make sure the userscript is in the right place. It should be in one of these places:
    ~/library/application support/min/userscripts on Mac
    \users\username\appdata\roaming\min\userscripts on Windows
    /home/username/.config/min\userscripts on Linux
3. Make sure you restarted Min after saving the userscript.
4. Make sure you're using the correct syntax. `window.onload=alert("running");` will cause a syntax error, it should be `window.onload= function () {alert("running");}`.
5. It's possible the page never finishes loading, so the onload event never occurs. You could try removing that and just using `alert("running")` for the script.
6. If you create a userscript for a different website, does it work correctly?

**Comment by nwdxlgzs** [comment]
Not launch

**Comment by PalmerAL** [comment]
@nwdxlgzs So none of those things worked?

**Comment by nwdxlgzs** [comment]
yes,not run

**Comment by PalmerAL** [comment]
Could you try this?

1. Open the console: developer > inspect browser > console
2. Run this script:
```
 var path = require('path')
    var scriptDir = path.join(remote.app.getPath('userData'), 'userscripts')

    fs.readdir(scriptDir, function (err, files) {
      if (err || files.length === 0) {
        return
      }

      // store the scripts in memory
      files.forEach(function (filename) {
        if (filename.endsWith('.js')) {
          fs.readFile(path.join(scriptDir, filename), 'utf-8', function (err, file) {
            if (err || !file) {
              return
            }

            var domain = filename.slice(0, -3)
            if (domain.startsWith('www.')) {
              domain = domain.slice(4)
            }
            if (!domain) {
              return
            }
	   console.log(domain, file)
          })
        }
      })
      
    })

```
3. Post the results here.

**Comment by nwdxlgzs** [comment]
[video.zip](https://github.com/minbrowser/min/files/3420346/video.zip)

in webview devtools:Uncaught ReferenceError: require is not defined
    at <anonymous>:1:12

in main devtools:undefined
VM135:24 miyun.smartclass.cn ﻿window.onload= function () {alert("running");}

you can watch the video of the operation process.

**Comment by nwdxlgzs** [comment]
Oh, I seem to have misread the instructions. I'll do it again when I'm free. I can't use the computer now.

**Comment by PalmerAL** [comment]
It looks like the `load` event doesn't work on any other website either. I'm not entirely sure why, but depending on what you're trying to  do with the userscript, you might be able to remove the listener, so your script would just be `alert("running")`.

**Comment by nwdxlgzs** [comment]
I cleaned up all the data about min, including the data in appdata, downloaded it again, turned on the function, and wrote the script, but it still didn't work.

**Comment by nwdxlgzs** [comment]
raw min

**Comment by nwdxlgzs** [comment]
oh,i think i can open webviewtag to use preload=""
so ,i think i can use this way to use js.
<head>
  <meta charset="utf-8">
  <title>直播课堂助手</title>
  <link rel="stylesheet" href="css/skeleton.css">
  <link rel="stylesheet" href="css/index.css">
  <script type="text/javascript" >
    window.onload = function () {
        alert("提示：不要通过本页面点击进入直播课堂，要通过输入课堂ID进入，否则webview会卡，但是，使用前请先在webview里登陆。")
      }
  </script>
</head>

<body>
  <div>
    <form>
      <input id="myurltext" class="u-full-width" type="text" autofocus placeholder="在这里输入直播课堂的课堂ID">
      <button type="submit">进入课堂</button>
    </form>
  </div>
    <webview id="mainwebview" nodeintegration="on" src="http://miyun.smartclass.cn/Login.aspx" style="display:inline-flex;height:100%;width:100%;" partition="persist:sitesession" allowpopups  plugins preload="smartclass.cn.js">
      <div class="indicator"> </div>
    </webview>

    <script>
      onload = () => {

        const webv = document.getElementById('mainwebview')
        // webv.addEventListener('dom-ready', () => {
        //   let currentURL = webv.getURL();
        //   document.getElementById('myurltext').value = currentURL;
        //   //读回webview网址
        // })

        document.querySelector('form').addEventListener('submit', (event) => {
          event.preventDefault();

          //     const urlin = document.querySelector('urltext').innerText;

          //  const {value} = document.querySelector('urltext');
          //  alert(value);
          const newurl = "http://miyun.smartclass.cn/MiYun/LiveShow.aspx?liveID=" + document.getElementById('myurltext').value;
          webv.loadURL(newurl);
          //   webv.src = urlin;
        });

      }

    </script>
</body>

**Comment by PalmerAL** [comment]
If you're still trying to use a userscript inside Min, I'm pretty sure the issue is that you need to stop listening for the `load` event, and just make your script this:

```
alert("running")
```

Or if you want to modify Min to use your preload script, that would probably work too.
