### ISSUE TITLE
Windows Installer Not Signed

### ISSUE THREAD

**Issue by AwesomeTech10** [minbrowser/min#789]
When trying to use the Windows Installer, I got a Unknown Publisher and the installer would not immediately start. Consider signing the installer

**Comment by PalmerAL** [comment]
Signing is expensive and fairly complex to do, and there really isn't any benefit to doing so; it would be nice if the installation was a bit easier, but I don't think it's worth it:

https://blog.kowalczyk.info/article/lh6f/Buying-a-certificate-for-signing-windows-applica.html
https://notepad-plus-plus.org/news/notepad-7.6.4-released.html

**Comment by lawrencenull** [comment]
You can use a self signed certificate but you do need visual studio installed to generate it. Here are the instructions. 

https://www.npmjs.com/package/electron-installer-windows?source=post_page---------------------------

**Comment by PalmerAL** [comment]
@lawrencenull Do you know if that actually changes anything when the package is installed? The instructions end with "Now get a standard code signing certificate from a real certificate authority", so I'm guessing a self-signed certificate won't work to avoid the warning.
