### ISSUE TITLE
Request: ability to open localhost

### ISSUE THREAD

**Issue by surajsharma** [minbrowser/min#79]
I run a local server at port 8080 which works fine in safari, here though,  localhost:8080 returns nothing, could this please be implemented soon?

**Comment by b0elter** [comment]
#24 would provide a workaround for this, and in the meantime prepending `http://` should work.

**Comment by PalmerAL** [comment]
#24 has been merged, so this should work now.

**Comment by surajsharma** [comment]
thanks but its not working for me...http://localhost:8080/index.html showing error or a blank page

**Comment by PalmerAL** [comment]
This is supposed to work now, and we haven't gotten any other reports about it not working, so I'm going to assume it's something specific to your setup. Feel free to reopen this if you can reproduce it again in the latest version.
