### ISSUE TITLE
Tab / Address bar customization

### ISSUE THREAD

**Issue by BenTearzz** [minbrowser/min#790]
Hi, a small change / option I personally would like is to disable auto-coloring in the tab bar. So that, the tab bar will just keep being a specific color no matter what URL I'm on. E.g. when you go to StackOverflow, the tab bar changes to orange, which I would like to disable.

**Comment by dbfreem** [comment]
I would second this.

**Comment by Qemics** [comment]
I like the default settings.

**Comment by PalmerAL** [comment]
There was a PR a while ago to add this: https://github.com/minbrowser/min/pull/632; I think it would be fairly simple to finish that off.

@BenTearzz @dbfreem Is there anything in particular you don't like about the effect? I'm fine with adding an option for it, but if there's something that could be done to improve it, that might be an option as well.

**Comment by dbfreem** [comment]
Sometimes I feel like the tabs get lost visually and you really have to look for a second to distinguish the site from the tabs.

**Comment by BenTearzz** [comment]
Personally I think the color change is just like it should be and I think that it works like it should. Although, I'd just like to have a solid color, so for me the effect doesn't need an improvement, I just wouldn't have it enabled if optional.

**Comment by PalmerAL** [comment]
@dbfreem @BenTearzz Makes sense, I've added an option for this in 8dbfdef8c36052d400c6fa8dfe84522778f8a2d4.

It might be worth looking into adjusting the effect so that the current tab stands out more (something like #703), hopefully that would reduce the need to turn this off in the first place.
