### ISSUE TITLE
Release Stats

### ISSUE THREAD

**Issue by dbfreem** [minbrowser/min#791]
I thought this was interesting. I pulled the release data from the github api and looks like the windows installer has been a big hit compared to historical downloads of the windows build. Thoughts??

*    Release 1.10.1: Bug fixes was published at 2019-05-21T01:59:00Z
*        min-1.10.1-setup.exe was downloaded 6896 times
*        Min-v1.10.1-darwin-x64.zip was downloaded 2114 times
*        Min-v1.10.1-win32-ia32.zip was downloaded 1142 times
*        Min-v1.10.1-win32-x64.zip was downloaded 782 times
*        min_1.10.1_amd64.deb was downloaded 2729 times
*    Release 1.10: Better reader mode and easier installation was published at 2019-05-16T02:43:19Z
*        min-1.10.0-setup.exe was downloaded 767 times
*        Min-v1.10.0-darwin-x64.zip was downloaded 194 times
*        Min-v1.10.0-win32-ia32.zip was downloaded 161 times
*        Min-v1.10.0-win32-x64.zip was downloaded 201 times
*        min_1.10.0_amd64.deb was downloaded 435 times
*    Release 1.9.2: Security fix was published at 2019-03-09T00:02:54Z
*        Min-v1.9.2-darwin-x64.zip was downloaded 2457 times
*        Min-v1.9.2-win32-ia32.zip was downloaded 1379 times
*        Min-v1.9.2-win32-x64.zip was downloaded 5492 times
*        min_1.9.2_amd64.deb was downloaded 4441 times
*        min_1.9.2_i386.deb was downloaded 896 times
*    Release 1.9.1: Bug fixes and minor improvements was published at 2019-02-18T21:32:35Z
*        Min-v1.9.1-darwin-x64.zip was downloaded 715 times
*        Min-v1.9.1-win32-ia32.zip was downloaded 410 times
*        Min-v1.9.1-win32-x64.zip was downloaded 1666 times
*        min_1.9.1_amd64.deb was downloaded 874 times
*        min_1.9.1_i386.deb was downloaded 318 times
*    Release 1.9.0: Improved content blocking and download management was published at 2019-02-03T20:06:06Z
*        Min-v1.9.0-darwin-x64.zip was downloaded 842 times
*        Min-v1.9.0-win32-ia32.zip was downloaded 387 times
*        Min-v1.9.0-win32-x64.zip was downloaded 2012 times
*        min_1.9.0_amd64.deb was downloaded 882 times
*        min_1.9.0_i386.deb was downloaded 275 times
*    Release 1.8.1: Security fix was published at 2018-12-17T23:35:45Z
*        Min-v1.8.1-darwin-x64.zip was downloaded 1788 times
*        Min-v1.8.1-win32-ia32.zip was downloaded 986 times
*        Min-v1.8.1-win32-x64.zip was downloaded 4063 times
*        min_1.8.1_amd64.deb was downloaded 1943 times
*        min_1.8.1_i386.deb was downloaded 626 times
*    Release 1.8.0: Userscripts and custom search engines was published at 2018-10-08T20:35:10Z
*        Min-v1.8.0-darwin-x64.zip was downloaded 3854 times
*        Min-v1.8.0-win32-ia32.zip was downloaded 2010 times
*        Min-v1.8.0-win32-x64.zip was downloaded 8954 times
*        min_1.8.0_amd64.deb was downloaded 4812 times
*        min_1.8.0_i386.deb was downloaded 1216 times
*    Release 1.8.0-beta1 was published at 2018-09-02T01:35:45Z
*        Min-v1.8.0-beta1-darwin-x64.zip was downloaded 160 times
*        Min-v1.8.0-beta1-win32-ia32.zip was downloaded 86 times
*        Min-v1.8.0-beta1-win32-x64.zip was downloaded 303 times
*        min_1.8.0-beta1_amd64.deb was downloaded 401 times
*        min_1.8.0-beta1_i386.deb was downloaded 131 times
*    Release 1.7.1: Bug fixes and minor improvements was published at 2018-03-19T19:46:22Z
*        Min-v1.7.1-darwin-x64.zip was downloaded 5916 times
*        Min-v1.7.1-win32-ia32.zip was downloaded 3929 times
*        Min-v1.7.1-win32-x64.zip was downloaded 12850 times
*        min_1.7.1_amd64.deb was downloaded 9520 times
*        min_1.7.1_i386.deb was downloaded 3290 times
*    Release 1.7.0: Back button, progress bars, redesigned PDF viewer, new languages, and more was published at 2018-01-16T21:52:09Z
*        Min-v1.7.0-darwin-x64.zip was downloaded 3130 times
*        Min-v1.7.0-win32-ia32.zip was downloaded 2498 times
*        Min-v1.7.0-win32-x64.zip was downloaded 5526 times
*        min_1.7.0_amd64.deb was downloaded 5967 times
*        min_1.7.0_i386.deb was downloaded 2213 times
*    Release 1.6.3: More languages was published at 2017-09-29T00:25:42Z
*        Min-v1.6.3-darwin-x64.zip was downloaded 5650 times
*        Min-v1.6.3-win32-ia32.zip was downloaded 816 times
*        Min-v1.6.3-win32-x64.zip was downloaded 2783 times
*        min_1.6.3_amd64.deb was downloaded 8276 times
*        min_1.6.3_i386.deb was downloaded 3340 times
*    Release 1.6.2: Now available in German was published at 2017-09-17T03:46:12Z
*        Min-v1.6.2-darwin-x64.zip was downloaded 226 times
*        Min-v1.6.2-win32-ia32.zip was downloaded 70 times
*        Min-v1.6.2-win32-x64.zip was downloaded 482 times
*        min_1.6.2_amd64.deb was downloaded 546 times
*        min_1.6.2_i386.deb was downloaded 890 times
*    Release 1.6.1: Bug fixes and minor improvements was published at 2017-09-05T23:27:48Z
*        Min-v1.6.1-darwin-x64.zip was downloaded 1224 times
*        Min-v1.6.1-win32-ia32.zip was downloaded 1804 times
*        Min-v1.6.1-win32-x64.zip was downloaded 324 times
*        min_1.6.1_amd64.deb was downloaded 666 times
*        min_1.6.1_i386.deb was downloaded 268 times
*    Release 1.6.0 was published at 2017-07-01T01:10:08Z
*        Min-v1.6.0-darwin-x64.zip was downloaded 3926 times
*        Min-v1.6.0-win32-ia32.zip was downloaded 3132 times
*        Min-v1.6.0-win32-x64.zip was downloaded 2543 times
*        min_1.6.0_amd64.deb was downloaded 3644 times
*        min_1.6.0_i386.deb was downloaded 1169 times
*    Release 1.5.1: Bug fixes was published at 2016-12-15T00:40:03Z
*        Min-v1.5.1-darwin-x64.zip was downloaded 9410 times
*        Min-v1.5.1-win32-ia32.zip was downloaded 4264 times
*        Min-v1.5.1-win32-x64.zip was downloaded 8074 times
*        min_1.5.1_amd64.deb was downloaded 12787 times
*        min_1.5.1_i386.deb was downloaded 5573 times
*    Release 1.5.0: Dark theme, menu bar hiding, and more was published at 2016-10-13T03:33:34Z
*        Min-v1.5.0-darwin-x64.zip was downloaded 3135 times
*        Min-v1.5.0-win32-ia32.zip was downloaded 760 times
*        Min-v1.5.0-win32-x64.zip was downloaded 1408 times
*        min_1.5.0_amd64.deb was downloaded 3277 times
*        min_1.5.0_i386.deb was downloaded 1656 times
*    Release 1.4.1: Bug fixes was published at 2016-07-25T20:31:45Z
*        Min-v1.4.1-darwin-x64.zip was downloaded 7352 times
*        Min-v1.4.1-win32-ia32.zip was downloaded 1194 times
*        Min-v1.4.1-win32-x64.zip was downloaded 2663 times
*        min_1.4.1_amd64.deb was downloaded 22624 times
*        min_1.4.1_i386.deb was downloaded 1846 times
*    Release 1.4.0: Full text search, browser actions, and more was published at 2016-07-22T16:08:21Z
*        Min-v1.4.0-darwin-x64.zip was downloaded 229 times
*        Min-v1.4.0-win32-ia32.zip was downloaded 134 times
*        Min-v1.4.0-win32-x64.zip was downloaded 286 times
*        min_1.4.0_amd64.deb was downloaded 2107 times
*        min_1.4.0_i386.deb was downloaded 646 times
*    Release 1.3.1: Bug fixes was published at 2016-06-01T17:01:09Z
*        Min-v1.3.1-darwin-x64.zip was downloaded 2831 times
*        Min-v1.3.1-win32-ia32.zip was downloaded 523 times
*        Min-v1.3.1-win32-x64.zip was downloaded 867 times
*        min_1.3.1_amd64.deb was downloaded 3733 times
*        min_1.3.1_i386.deb was downloaded 1153 times
*    Release 1.3.0: More customization options was published at 2016-05-31T15:46:55Z
*        Min-v1.3.0-darwin-x64.zip was downloaded 307 times
*        Min-v1.3.0-win32-ia32.zip was downloaded 111 times
*        Min-v1.3.0-win32-x64.zip was downloaded 109 times
*        min_1.3.0_amd64.deb was downloaded 628 times
*        min_1.3.0_i386.deb was downloaded 107 times
*    Release 1.2.2: Faster, more accurate content blocking was published at 2016-05-08T21:08:30Z
*        Min-v1.2.2-darwin-x64.zip was downloaded 3938 times
*        Min-v1.2.2-win32-ia32.zip was downloaded 406 times
*        Min-v1.2.2-win32-x64.zip was downloaded 946 times
*        min_1.2.2_amd64.deb was downloaded 4157 times
*        min_1.2.2_i386.deb was downloaded 1544 times
*    Release 1.2.1: Bug fixes and UI improvements was published at 2016-05-06T05:09:10Z
*        Min-v1.2.1-darwin-x64.zip was downloaded 312 times
*        Min-v1.2.1-win32-ia32.zip was downloaded 35 times
*        Min-v1.2.1-win32-x64.zip was downloaded 70 times
*        min_1.2.1_amd64.deb was downloaded 192 times
*        min_1.2.1_i386.deb was downloaded 40 times
*    Release 1.2.0: tasks, host file search, and more was published at 2016-04-28T05:15:45Z
*        Min-v1.2.0-darwin-x64.zip was downloaded 1212 times
*        Min-v1.2.0-win32-ia32.zip was downloaded 78 times
*        Min-v1.2.0-win32-x64.zip was downloaded 186 times
*        min_1.2.0_amd64.deb was downloaded 237 times
*        min_1.2.0_i386.deb was downloaded 100 times
*    Release 1.1.2 was published at 2016-04-16T01:56:01Z
*        Min-v1.1.2-darwin-x64.zip was downloaded 5809 times
*        Min-v1.1.2-win32-ia32.zip was downloaded 212 times
*        Min-v1.1.2-win32-x64.zip was downloaded 825 times
*        Min_1.1.2_amd64.deb was downloaded 1517 times
*        Min_1.1.2_i386.deb was downloaded 239 times
*    Release 1.1.1 was published at 2016-04-11T22:35:53Z
*        Min-v1.1.1-darwin-x64.zip was downloaded 3167 times
*        Min-v1.1.1-win32-ia32.zip was downloaded 43 times
*        Min-v1.1.1-win32-x64.zip was downloaded 222 times
*        Min_1.1.1_amd64.deb was downloaded 741 times
*        Min_1.1.1_i386.deb was downloaded 66 times
*    Release 1.1.0 was published at 2016-04-03T19:04:51Z
*        Min-v1.1.0-darwin-x64.zip was downloaded 58 times
*        Min-v1.1.0-linux-ia32.zip was downloaded 7 times
*        Min-v1.1.0-linux-x64.zip was downloaded 10 times
*        Min-v1.1.0-win32-ia32.zip was downloaded 14 times
*        Min-v1.1.0-win32-x64.zip was downloaded 11 times
*    Release 1.1.0-alpha1 was published at 2016-03-25T01:37:19Z
*        Min-v1.1.0-alpha1.zip was downloaded 30 times
*    Release 1.0.1 was published at 2016-02-22T19:22:12Z
*        Min-v1.0.1-darwin-x64.zip was downloaded 109 times
*        Min-v1.0.1-linux-ia32.zip was downloaded 9 times
*        Min-v1.0.1-linux-x64.zip was downloaded 9 times
*        Min-v1.0.1-win32-ia32.zip was downloaded 219 times
*        Min-v1.0.1-win32-x64.zip was downloaded 152 times
*    Release 1.0.0 was published at 2016-02-22T00:31:37Z
*        min-v1.0.0-darwin-x64.zip was downloaded 42 times
*    Release 0.5 was published at 2016-01-23T21:07:46Z

**Comment by PalmerAL** [comment]
I think it definitely has increased some, although the number also just looks large because the release has been out for so long (2 months now). I wrote a [script](https://gist.github.com/PalmerAL/e6f38aad641e3783041adc633ed8803e) a while ago to computer some statistics about the downloads, and the proportion of windows builds has increased from 40-50% in previous releases to around 60%, which is nice to see. Total downloads do seem to be roughly the same, so I suppose that could also just be a decrease in linux/mac downloads, although those numbers seem to be really variable, so it's hard to say.

The majority of the downloads are for the installer, but I suspect this is mostly because most downloads happen from the website (https://minbrowser.github.io/min/), and the installer is now the default for everyone with a 64-bit OS. And I think that's also why Windows downloads increased from 17% to 42% between 1.6.3 and 1.7.0, because that's when windows downloads were first added to the website.

Either way, I don't think there's really enough information to say for sure, since these numbers tend to be pretty variable in general. In order to see whether people actually like the installer, I think we'd have to track what percentage of people keep using Min after downloading it, but I haven't done anything about that. The installer definitely seems like a better experience though, I wish I'd done it sooner. 

```
v0.5			0 downloads			0/day			NaN% mac			NaN% windows (folder)			NaN% windows (installer)			NaN% linux
1.0.0			42 downloads			53/day			100% mac			0% windows (folder)			0% windows (installer)			0% linux
1.0.1			498 downloads			16/day			22% mac			74% windows (folder)			0% windows (installer)			0% linux
v1.1.0-alpha1			30 downloads			3/day			0% mac			0% windows (folder)			0% windows (installer)			0% linux
v1.1.0			100 downloads			12/day			58% mac			25% windows (folder)			0% windows (installer)			0% linux
v1.1.1			4239 downloads			1024/day			75% mac			6% windows (folder)			0% windows (installer)			19% linux
v1.1.2			8602 downloads			709/day			68% mac			12% windows (folder)			0% windows (installer)			20% linux
v1.2.0			1813 downloads			227/day			67% mac			15% windows (folder)			0% windows (installer)			19% linux
v1.2.1			649 downloads			243/day			48% mac			16% windows (folder)			0% windows (installer)			36% linux
v1.2.2			10993 downloads			483/day			36% mac			12% windows (folder)			0% windows (installer)			52% linux
v1.3.0			1262 downloads			1200/day			24% mac			17% windows (folder)			0% windows (installer)			58% linux
v1.3.1			9109 downloads			179/day			31% mac			15% windows (folder)			0% windows (installer)			54% linux
v1.4.0			3402 downloads			1069/day			7% mac			12% windows (folder)			0% windows (installer)			81% linux
v1.4.1			35679 downloads			450/day			21% mac			11% windows (folder)			0% windows (installer)			69% linux
v1.5.0			10238 downloads			163/day			31% mac			21% windows (folder)			0% windows (installer)			48% linux
v1.5.1			40108 downloads			203/day			23% mac			31% windows (folder)			0% windows (installer)			46% linux
v1.6.0			14414 downloads			215/day			27% mac			39% windows (folder)			0% windows (installer)			33% linux
v1.6.1			4286 downloads			383/day			29% mac			50% windows (folder)			0% windows (installer)			22% linux
v1.6.2			2214 downloads			187/day			10% mac			25% windows (folder)			0% windows (installer)			65% linux
v1.6.3			20865 downloads			190/day			27% mac			17% windows (folder)			0% windows (installer)			56% linux
v1.7.0			19344 downloads			312/day			16% mac			42% windows (folder)			0% windows (installer)			42% linux
v1.7.1			35507 downloads			214/day			17% mac			47% windows (folder)			0% windows (installer)			36% linux
v1.8.0-beta1			1083 downloads			29/day			15% mac			36% windows (folder)			0% windows (installer)			49% linux
v1.8.0			20847 downloads			297/day			18% mac			53% windows (folder)			0% windows (installer)			29% linux
v1.8.1			9406 downloads			197/day			19% mac			54% windows (folder)			0% windows (installer)			27% linux
v1.9.0			4399 downloads			292/day			19% mac			55% windows (folder)			0% windows (installer)			26% linux
v1.9.1			3983 downloads			220/day			18% mac			52% windows (folder)			0% windows (installer)			30% linux
v1.9.2			14684 downloads			216/day			17% mac			47% windows (folder)			0% windows (installer)			36% linux
v1.10.0			1760 downloads			354/day			11% mac			21% windows (folder)			44% windows (installer)			25% linux
v1.10.1			14243 downloads			230/day			15% mac			14% windows (folder)			50% windows (installer)			20% linux
total			293799						24% mac			31% windows (folder)			3% windows (installer)			43% linux
```
