### ISSUE TITLE
buildDebian broken in git master after commit fe2855a61b5b475ad3330ecd1a2f27cb17348182

### ISSUE THREAD

**Issue by glitsj16** [minbrowser/min#793]
Hi, this is what I see on Arch Linux when building min from git master:

```
$ npm run buildDebian
...
> node ./scripts/buildPreload.js

Packaging app for platform linux x64 using electron v6.0.0-beta.15
(node:9385) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, rename '/tmp/electron-packager/linux-x64/min-linux-x64/electron' -> '/tmp/electron-packager/linux-x64/min-linux-x64/min'
(node:9385) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9385) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

When leaving out https://github.com/minbrowser/min/commit/fe2855a61b5b475ad3330ecd1a2f27cb17348182, the build works fine again. Feel free to ask if there's more info I can provide.

$ pacman -Q nodejs
nodejs-lts-dubnium 10.16.0-1

**Comment by PalmerAL** [comment]
It works fine for me on mac and Ubuntu, so I'm not sure what would make it not work for you. If you have anything in the `/tmp/electron-packager` directory, could you try deleting it and building it again?

It looks like there's someone else with the same issue on Windows: https://github.com/electron/electron-packager/issues/1024; you could try running the debugging steps there as well.

**Comment by glitsj16** [comment]
@PalmerAL Turned out to be an issue unrelated to min. I'm quite actively using/contributing to [Firejail](https://github.com/netblue30/firejail) and its `unzip` profile prevented electron-packager from finding the needed paths. I'll fix that after some extra debugging, but let me repeat this issue is not in min or electron{-packager}. Sorry for the noise.
