### ISSUE TITLE
command line

### ISSUE THREAD

**Issue by andrewg78** [minbrowser/min#801]
Hi.
1. I'd like to open two addresses from the command line in the separate tabs. It works fine for one address, but how to pass more to the cmd line ?
2. How can I use min as portable browser with all user data/history stored on the pen drive?
I'm on Windows.

**Comment by dbfreem** [comment]
For your second question it is portable if you download and use the zip archive on windows.

**Comment by andrewg78** [comment]
So there must be a bug.
I have portable version unzipped to the pendrive from the file Min-v1.10.1-win32-x64.zip.
History of the opened tabs is not saved to the pen, but to localhost instead.

**Comment by PalmerAL** [comment]
I've fixed the first issue in bad8b00932728fee1aafa7a43e2454817dff305f.

I don't think we support running as a portable version - the zip download will prevent you from having to install anything, but there still isn't a way to control where the cache and other data gets stored. Electron has an API to do that (app.setPath), so I imagine we could add support for launching Min with an argument like `--user-data-path` that would let you specify that data should be saved on the drive.

**Comment by KagamineP** [comment]
I think that is maybe outdated and can be closed right now.
