### ISSUE TITLE
Disable notifications

### ISSUE THREAD

**Issue by mpalczew** [minbrowser/min#802]
Would be nice if notifications were disabled by default, or at least an otion to disable them.

**Comment by dbfreem** [comment]
What notifications are you referring to? A screenshot may help.

**Comment by mpalczew** [comment]
Web site notifications. Some web sites ask to send you notificationns.

**Comment by ashis07** [comment]
I agree with this feature request as well. If we will have an option to disable the desktop notification then it will very much helpful. Thanks

**Comment by PalmerAL** [comment]
Fixed in 1.13.2: https://github.com/minbrowser/min/releases/tag/v1.13.2
