### ISSUE TITLE
How install Min on OpenSUSE 15.1

### ISSUE THREAD

**Issue by ghost** [minbrowser/min#808]
Install Min on OpenSUSE wow is the big task is possible what someone post the help or instructions for this, with npm not work and the package rpm not work show dependencies nss, libXtst and libuuid but I have install and show error.

Help, Please

**Comment by PalmerAL** [comment]
It should work if you download the prebuilt package and run this to install it:
```
sudo rpm -i /path/to/download --ignoreos
```

if that doesn't work, what error message do you get?

**Comment by Poncho09** [comment]
```
error: Error de dependencias:
	libXtst es necesario por min-1.11.0-1.x86_64
	libuuid es necesario por min-1.11.0-1.x86_64
	nss es necesario por min-1.11.0-1.x86_64
```

**Comment by PalmerAL** [comment]
I'm guessing you could install those packages using [this guide](https://www.opensuse-guide.org/installpackage.php):

```
zypper install libXtst && zypper install libuuid && zypper install nss
```

**Comment by Poncho09** [comment]
Normally that would work but here it is not so it does not work either allows starting from npm

**Comment by KagamineP** [comment]
I think, this can be closed.
