### ISSUE TITLE
Page reload script

### ISSUE THREAD

**Issue by soctemp** [minbrowser/min#809]
Hello,

I would like to refresh/reload specific page every 10 minutes. like with ctrl+r shortcut.
I created global.js script in \users\username\appdata\roaming\min
with content:

```
if (window.location.hostname === "https://test.com/index.html" {
  setTimeout(function(){
   window.location.reload(1);
}, 600000);
}
```

But this doesn't work, any ideas?

Thanks

**Comment by soctemp** [comment]
Yeah my global.js is located in \users\username\appdata\roaming\min\userscripts I made a mistake and provided wrong location.

userscript is enabled in preferences.

For test purpose I will use host:

```
if (window.location.hostname === "google.com" {
  setTimeout(function(){
   window.location.reload(1);
}, 5000);
}
```

When I am on google.com it doesn't refresh every 5 sec.

**Comment by soctemp** [comment]
Works correctly, thanks. I still have problem with window.location.toString() but that probably just me and my silly mistakes :)

**Comment by PalmerAL** [comment]
Maybe try opening the console (developer > inspect page > console), typing in window.location.toString(), and make sure it’s  the same as what you’re using in your user script.

**Comment by h0ek** [comment]
https://github.com/h0ek/Min-WebBrowser-Autorefresh

You can add this to https://github.com/minbrowser/min/wiki/userscripts as example at the bottom of the page like suggestion says (if you want to, of course)

**Comment by PalmerAL** [comment]
Thanks!

**Comment by Sestowner** [comment]
I think this can be closed.
