### ISSUE TITLE
Package in Archlinux not updated.

### ISSUE THREAD

**Issue by janaabpakaal** [minbrowser/min#811]
Package maintainer in ArchLinux has not updated the package, can we get direct download of the package like rpm,deb ? 
If not possible then process to install in ArchLinux.

**Comment by PalmerAL** [comment]
There are debian and RPM builds  on the releases page: https://github.com/minbrowser/min/releases. I don't know how to install those on arch specifically, but I would guess it's pretty similar to other distributions.

**Comment by anonymous-user** [comment]
This issue can be closed now. The package in Arch Linux's repository has been updated.
