### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by archicu** [minbrowser/min#812]
I don't select the dark theme, but the browser's default theme is dark...

**Comment by antfu** [comment]
![image](https://user-images.githubusercontent.com/11247099/87456178-25553c80-c639-11ea-9484-1cb6656e7af1.png)

It's based on the time by default.

**Comment by PalmerAL** [comment]
(The setting mentioned above was added a few months ago; once you upgrade to the latest version, you can disable the dark mode completely).

**Comment by archicu** [comment]
OK,  thank you very much.
