### ISSUE TITLE
Umail error

### ISSUE THREAD

**Issue by ZZYYYKK** [minbrowser/min#817]
The page does not load. Disabling ad blocking does not help

**Comment by PalmerAL** [comment]
I can't reproduce this, can you please provide the same troubleshooting information as in #816?

**Comment by ZZYYYKK** [comment]
<img width="1792" alt="Screenshot 2019-09-25 at 16 09 33" src="https://user-images.githubusercontent.com/26084800/65604500-44061c00-dfb0-11e9-820a-3b93d09604fa.png">
![Screenshot 2019-09-25 at 16 09 49](https://user-images.githubusercontent.com/26084800/65604501-44061c00-dfb0-11e9-9578-a09e555e5327.png)

**Comment by ZZYYYKK** [comment]
[2.har.zip](https://github.com/minbrowser/min/files/3652675/2.har.zip)

**Comment by ZZYYYKK** [comment]
![Screenshot 2019-09-25 at 16 09 49](https://user-images.githubusercontent.com/26084800/65604903-e1f9e680-dfb0-11e9-85df-dd83b879bde0.png)

**Comment by PalmerAL** [comment]
This is the same issue as #816.
