### ISSUE TITLE
secure and environment friendly search engine Ecosia

### ISSUE THREAD

**Issue by edmundlaugasson** [minbrowser/min#819]
Would propose to add and set default the Ecosia search engine - https://www.ecosia.org/
More information at https://info.ecosia.org/what
[As lots of trees has been burned at Amazonas rainforest](https://www.sciencefocus.com/planet-earth/the-amazon-rainforest-could-it-become-a-desert/) then it is the least we can do to survive.
Search command is pretty simple:
`https://www.ecosia.org/search?q=%s`

**Comment by PalmerAL** [comment]
Sounds good to me!

Also, I had no idea Ecosia had grown so much in the past few years.

**Comment by benstandaert** [comment]
This is included in the latest release: https://github.com/minbrowser/min/releases/tag/v1.11.1

**Comment by PalmerAL** [comment]
This is fixed in the latest release: https://github.com/minbrowser/min/releases/tag/v1.11.1
