### ISSUE TITLE
Roboform v8 not working.

### ISSUE THREAD

**Issue by Emmanuel65** [minbrowser/min#828]
Hi. I tried to install Roboform v8 without result, simply the download button does not appear. Now I'm using web RF but it's not the best solution.  I hope the issue will be solved. Thanks.

**Comment by PalmerAL** [comment]
Chrome extensions aren't supported; they might be at some point, but no guarantees.

There's work happening in #822 to support integration with some password managers in Min. If Roboform has a CLI, we could support it as well, but it doesn't look like they have one.

**Comment by Emmanuel65** [comment]
I Will follow #391. Many thanks.
