### ISSUE TITLE
Latest release - win x64 zip is broken

### ISSUE THREAD

**Issue by TheInitializer** [minbrowser/min#83]
![image of error when trying to open zip in explorer.exe](http://u.cubeupload.com//MaO9wX.png)
Windows 10 x64

**Comment by TheInitializer** [comment]
Update: It works when I extract it from 7-Zip, explorer.exe just doesn't seem to like it. Weird.

**Comment by dbfreem** [comment]
When I installed on windows I didn't seem to have any issues with the zip not working. This may be an old outdated issue.

**Comment by PalmerAL** [comment]
Yeah, I think so, Explorer is able to unzip it for me as well.
