### ISSUE TITLE
Min doesn't start properly after a crash

### ISSUE THREAD

**Issue by Papuchochoe** [minbrowser/min#835]
Min crashed after trying to load a tab with a youtube video, when I now try to start it again the interface stays "minimized". When I hover over the taskbar icon it shows it's working (the bar at the top is blinking) but I can't get the window to expand. I recorded it below. How can I get it to work without losing my open tasks and tabs?
[Video of the issue](https://puu.sh/ErQ80/e773ab1aad.mp4)

**Comment by PalmerAL** [comment]
That's really strange, I haven't seen that before. Before doing anything, I would make a copy of your data to reduce the chances of losing anything. The folder containing your data is located at `\users\username\appdata\roaming\min`; you can just make a copy of that folder and name it "min-backup" or something (make sure Min is closed first).

After that, the next thing I would try is to find this file: `\users\username\appdata\roaming\min\windowBounds.json`, and rename it to "windowBounds-old.json", then relaunch Min.

Let me know what happens!

**Comment by Papuchochoe** [comment]
It worked!! I didn't lose any data whatsover either, for reference the windowbounds file showed: {"x":-32000,"y":-32000,"width":320,"height":350}

**Comment by PalmerAL** [comment]
I'm glad it worked! It's odd the window bounds ended up being saved like that. Do you have more than one display?

I think I'm going to modify the window restore code to make sure the window fits within the bounds of the current displays to prevent this.

**Comment by Syndamia** [comment]
@PalmerAL has window restore undergone any (significant) changes?

**Comment by PalmerAL** [comment]
I'm pretty sure this was fixed in c60ef3bb824b9c93285b1fd421100e58eabebb13.
