### ISSUE TITLE
Restore previous open session

### ISSUE THREAD

**Issue by Yutolio** [minbrowser/min#838]
Sadly I was just greeted by the "Welcome to Min" page upon reopening the browser and I lost my previous tabs/tasks!
I'm not tech savvy enough to navigate through the "Session Storage" folder myself, could you help me restore it?

**Comment by PalmerAL** [comment]
Unfortunately, I think this is the same situation as last time (#734); if a backup file had been generated, you would see a screen like [this](https://user-images.githubusercontent.com/10314059/30006434-f9801142-90bd-11e7-94a2-2123f1f44d13.png), so there likely isn't one.

[These instructions](https://github.com/minbrowser/min/issues/734#issuecomment-484732116) should still give you a list of all your history, which should hopefully let you recover most of what you had open.

It's really unfortunate this has happened twice to you. I went ahead and changed the way session restore works to be a bit simpler (in 597d20a72b9cf58b925c34d963a2680f865ceb70). I'm not sure if this will actually prevent the issue or not, but hopefully it works.
