### ISSUE TITLE
the 2 biggest problems, in my opinion

### ISSUE THREAD

**Issue by MrLeLama** [minbrowser/min#839]
I want to use Min, it's light, quick and i love the UI. BUT not being able to import my bookmarks AND not being able to set it as my default browser in windows (like.. why ?) simply DOESNT DO IT for me.

i really hope these 2 issues get fixed because i really want to use min, like really

**Comment by PalmerAL** [comment]
Sorry for taking so long to respond to this issue; both of these have been added in the 1.12 beta release. You can try it here: https://github.com/minbrowser/min/releases/tag/v1.12.0-beta1.
