### ISSUE TITLE
Add support for setting Min as the default browser on Windows and Linux

### ISSUE THREAD

**Issue by PalmerAL** [minbrowser/min#84]

**Comment by emersion** [comment]
On Linux: set `MimeType` in desktop file (see https://wiki.archlinux.org/index.php/xdg-open#Set_the_default_browser).

Coming soon: https://github.com/unindented/electron-installer-debian/pull/15

Firefox one's:
```ini
Exec=firefox %u
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=firefox
Categories=GNOME;GTK;Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;x-scheme-handler/chrome;video/webm;application/x-xpinstall;
StartupNotify=true
Actions=NewWindow;NewPrivateWindow;
```

**Comment by PalmerAL** [comment]
Thanks for the info! Do you know how Linux handles opening links in the default browser? It looks like Electron doesn't have an event for that, but I could be wrong.

**Comment by emersion** [comment]
The `%u` in the `Exec` property is replaced by the URL.

**Comment by emersion** [comment]
In the latest version, I'm able to set Min as the default browser :)

![capture du 2016-05-11 13 19 02](https://cloud.githubusercontent.com/assets/506932/15179289/11fc536a-177b-11e6-8797-98071f6a2981.png)

**Comment by PalmerAL** [comment]
The second part of this (actually opening URL's) is fixed in facf72152968a709b484892b217dcbcb398be81f.

**Comment by PalmerAL** [comment]
Still not fixed for Windows, though.

**Comment by moigagoo** [comment]
Bumping this issue just to let you know it's impossible to set Min as the default browser on Windows.

**Comment by PalmerAL** [comment]
I'm not really sure how to do this; Brave does it by manually editing a bunch of registry values: https://github.com/brave/browser-laptop/commit/f26e16020252c867adcc7c5793f4ff596bc8c154, but that looks like it would be fairly difficult to do. Does anyone know a different way?

**Comment by AwesomeTech10** [comment]
I _might_ be able to add some code using ```windows-registry``` to add the values.

**Comment by AwesomeTech10** [comment]
@PalmerAL What I would do is add an option in settings that looks something like this:

# Make Min your default browser
Min is currently _not_ set as your default browser
╭───────────────────╮
| Make Min the Default Browser │
╰───────────────────╯
which runs the ```windows-registry``` code.

**Comment by PalmerAL** [comment]
That does sound like a good idea, I imagine something like that would work. A lot of people probably won't think (or remember) to check in the settings, so we should probably add a prompt on startup as well.

**Comment by AwesomeTech10** [comment]
Yeah, I’ll work on a PR containing the backend code
    	
    	

    	Sent from my awesometech10@icloud.com email address.
    
  




On Sun, Mar 31, 2019 at 7:24 PM -0700, "PalmerAL" <notifications@github.com> wrote:












That does sound like a good idea, I imagine something like that would work. A lot of people probably won't think (or remember) to check in the settings, so we should probably add a prompt on startup as well.

**Comment by BenTearzz** [comment]
Any updates on this?

**Comment by AwesomeTech10** [comment]
PR almost ready.

**Comment by PalmerAL** [comment]
I've added the code to register Min as a browser in b021081c6f0b26ca1604048ddc089b528a69c8e0, so you can set Min as the default if you open the Windows settings. There should probably still be a prompt somewhere in Min about this as well.
