### ISSUE TITLE
Suggestion "Dark mode"

### ISSUE THREAD

**Issue by twil81** [minbrowser/min#845]
Inplement something like the "Dark Reader" extension twitching to Dark Mode to make the most popular sites all dark. 
https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh

**Comment by PalmerAL** [comment]
I wrote a simple userscript a bit ago to do something similar, although it doesn't work on every website: https://github.com/PalmerAL/min-dark-mode-userscript

It's probably possible to port dark reader to a userscript, but Chromium is getting a built-in feature for this: https://www.pocket-lint.com/apps/news/google/149866-how-to-enable-dark-mode-for-google-chrome, so it might make more sense to offer that as an option instead.

**Comment by twil81** [comment]
So, when is min being updated to version 78? 
And is it then possible to use it then?

**Comment by PalmerAL** [comment]
> So, when is min being updated to version 78?

Soon-ish, maybe another couple of weeks?

> And is it then possible to use it then?

Probably, although I'm not sure exactly what we would need to do to enable it.
