### ISSUE TITLE
Fullscreen Videos have White Border

### ISSUE THREAD

**Issue by Kaleb-Jen-1619** [minbrowser/min#848]
When going fullscreen on video players (such as youtube or vimeo), a white border displays around the entire frame. Not sure if it has anything to do with a 4k screen.
Edit: To see the white border, click on the image.
![Screenshot (29)](https://user-images.githubusercontent.com/22247389/67709365-07e12500-f97b-11e9-9332-8001b78edbe4.png)

**Comment by PalmerAL** [comment]
This is electron/electron#19481, so it should be fixed once we upgrade to a newer version of Electron. In the meantime, if you un-maximize the window before entering fullscreen it should prevent the border from showing up.

**Comment by PalmerAL** [comment]
I think this is fixed, please open a new issue if it isn't.
