### ISSUE TITLE
Can Chrome Extensions affect Min Browser?

### ISSUE THREAD

**Issue by manoger** [minbrowser/min#851]
When I had downloaded "Dark Reader" extension from Web Store to Chrome, my Min Browser became night mode without this option enabled.
Please, someone investigate it for me.

**Comment by PalmerAL** [comment]
Chrome extensions are separate from Min. What you're most likely seeing is that the dark mode is enabled automatically between 10PM-6AM, regardless of whether the checkbox is enabled. (And there probably should be an option to disable that).

If you want something like "dark reader" for Min, I wrote a userscript to do something similar: https://github.com/PalmerAL/min-dark-mode-userscript.

**Comment by manoger** [comment]
oh, I see. I didn't know about this automatic behaviour.
 I would like to see this type of information in my "min://settings" in future updates.
