### ISSUE TITLE
Not Recognized as Browser in Windows

### ISSUE THREAD

**Issue by seanrouf** [minbrowser/min#852]
I really wanted to make Min my default browser however windows won't recognize it as a browser in the settings. Maybe there is a way to fix that from the back end but on the front end it isn't cooperating.

**Comment by PalmerAL** [comment]
Fixed in b021081c6f0b26ca1604048ddc089b528a69c8e0. This is included in the [1.12 beta release](https://github.com/minbrowser/min/releases/tag/v1.12.0-beta1), if you're interested in trying that out.
