### ISSUE TITLE
Can you make it more user friendly? That Min Browser. Read all the requests below

### ISSUE THREAD

**Issue by dj-sash** [minbrowser/min#858]
Hello,
I am a Mac user. I appreciate your min browser a lot. I have some request to you. Because despite being very fast, it is quite unuser friendly. And some issues with it.
• Can you separate the Tab and address bar please? We are just clicking on a tab and we do not want to see it displaying the address bar and the list of browsing below, this is very annoying.
Just give a top address bar and below it the Tabs with page title.
• Make it a lite gray color option. We are not on a phone, dark mode is not so interesting here. And also do a better contrast on the selected tab and the other tabs behind.
• Please add the closing tab icon on the LEFT please, not on the Right.
• When we hover on any link, please show it in a sort of hovering status bar at the bottom.
• Give the option to have a Bookmark window like Safari. Option if new tab open with bookmark or default home page.
• Load some very important icons for users not to click uselessly a lot. Icons like; New Tab, Bookmarks, History, Download, Back and Next (while holding on Back and Next you can give the list of previous loaded pages).

I hope you really consider my requests and give a very good update for the mac users.
Your browser is superfast.
Thanks for that.

**Comment by dj-sash** [comment]
••• And also, make it possible to load a translator plugin for mac.
Thanks

**Comment by kohlrak** [comment]
Created a github account just to add to this:
・some way of disabling that god-forsaken scrolling of the address bar from basically deleting all your tabs, or at least some way to undo that. It took me a couple weeks to find out why my tabs kept disappearing when i was putting my mouse up there to avoid accidental add clicks.

**Comment by PalmerAL** [comment]
> • Can you separate the Tab and address bar please? We are just clicking on a tab and we do not want to see it displaying the address bar and the list of browsing below, this is very annoying.

Having a separate address bar takes up a lot more space, which I'd like to avoid. Clicking on the already-selected tab doesn't normally due anything anyway, so I don't see how showing the address bar should be an issue.

> • Make it a lite gray color option. We are not on a phone, dark mode is not so interesting here. And also do a better contrast on the selected tab and the other tabs behind.

There's an option to disable the tab coloring in preferences. Are there any specific examples of sites where you think the contrast is bad?

> • Please add the closing tab icon on the LEFT please, not on the Right.

Why?

> • When we hover on any link, please show it in a sort of hovering status bar at the bottom.

There's a userscript to do this: https://github.com/PalmerAL/min-link-tooltip-userscript

> • Give the option to have a Bookmark window like Safari. Option if new tab open with bookmark or default home page.

The list of frequently-visited sites on a new tab should help solve that issue already; we could consider changing the way sites are picked or show more sites if that isn't enough. But I don't think having a list of every bookmark on new tabs is very useful.

> • Load some very important icons for users not to click uselessly a lot. Icons like; New Tab, Bookmarks, History, Download, Back and Next (while holding on Back and Next you can give the list of previous loaded pages).

New tab and back exist already; a download bar will show up if you download something. There's an existing issue open about having history show up if you hold down on the back button. You can get to bookmarks and history fairly quickly by pressing cmd+e and typing the beginning of the name; in most cases, that's even faster than clicking a button.

In general, it sounds like the Safari UI works pretty well for you; why not just use Safari? Firefox also lets you do pretty much all of that, you could try that if you're looking for an alternative.

**Comment by dj-sash** [comment]
Because Safari loads too much cache. That's why Im preferring your browser.

1. There is NO CONTRAST in the ACTIVE and Behind Tabs. Can you buy default make it look at a greater contrast the 'ACTIVE' and 'BEHIND' Tabs? The colors are too close on differentiating.
And on clicking a link, to open in a New Tab. I want to remain on the actual page I am. I do not want it to automatically shift to the link I just clicked NEW TAB.
2. I am asking you the Icon of CLOSE on the left. Because our movement of the mouse it from Right to Left. So, it is easier and closer to CHOOSE the CLOSE button if it is on LEFT, instead of having to swipe slowly to reach the CLOSE icon when it is on the RIGHT.
3. >>>> • When we hover on any link, please show it in a sort of hovering status bar at the bottom.
There's a userscript to do this: https://github.com/PalmerAL/min-link-tooltip-userscript
WHERE IS YOUR JAVASCRIPT FILE TO COPY AND PASTE THAT? CAN YOU EXPLAIN PLEASE?

4. BOOKMARK PAGE; I DO NOT LIKE THE LIST OPTION. I am just asking you to give the option to load the Default to New Tab option either with a URL or a WINDOW OF BOOKMARKS.
> But I don't think having a list of every bookmark on new tabs is very useful.
For you it is not very useful. But it is for me and others it is VERY IMPORTANT. Because we know the importance of the site to tag a bookmark. And if the option is there we can or cannot use it.
Can you do it please?

5.  Just add a Forward ICON. Why I have to lose time to PRESS Command E on that? I know the Back Icon is already there.
If YOU are a programmer, who likes typing a lot. We are designers. We like using the MOUSE a lot. And most people prefer ICONS instead of typing commands for everything. It is easier with ICONS.

If you like the browser to be ONLY in the ways that ONLY you find easy. Please let me know.
Or you can kindly load these options for the users to choose. Because you are like trying to force everyone who will use MIN to adopt your ways. We have other things to remember as commands in design, where we do not want to learn any command in browsing.
This is how ICONS solves the issues here.

Thanks

**Comment by PalmerAL** [comment]
It is definitely true that the browser is designed more to be used with a keyboard than a mouse, but there's nothing necessarily wrong with that (the same way that having the close button on the right, displaying bookmarks in a list, ... has both benefits and downsides). And it's fine if you disagree with that! But given how many things you disagree with, I think you're probably going to be happier using a different browser with a more traditional interface than trying to change Min to fit what you want. The nice thing about browsers is that there's a ton of options you can pick from; in particular I would point out that:

* Firefox has an option to control the cache size
* Something like [ungoogled-chromium](https://github.com/Eloston/ungoogled-chromium) will load pages just as fast as Min, and display them the same way.

If you don't like either of those, you still have more options: Brave, Opera, Vivaldi, ...

**Comment by dj-sash** [comment]
I am not talking of Firefox or Chromium. I am talking about your Min browser.
Can you give a guide how to manipulate the coding on Mac and do the modifications to make it look like Safari?

**Comment by PalmerAL** [comment]
No, that would be really complicated to do, there isn't any simple way to do that.
