### ISSUE TITLE
Add icon for Windows

### ISSUE THREAD

**Issue by TheInitializer** [minbrowser/min#86]
Currently it just has the default Electron icon.

**Comment by chrissbendel** [comment]
Fixed, tested, and working on Windows. #107

**Comment by DylanC** [comment]
+1 Also have this issue.

**Comment by dbfreem** [comment]
@PalmerAL I was able to see the min icon on windows. Can this be closed?

**Comment by PalmerAL** [comment]
Yup, this was fixed by #107 (thanks for going through these issues BTW!)
