### ISSUE TITLE
Min : Make it more like Safari for Mac

### ISSUE THREAD

**Issue by dj-sash** [minbrowser/min#870]
Hi,
I am requesting, if you can make the Min browser look, icons, address bar be similar like Safari for mac? Because truly your browser if very fast, it is just not easy and not user-friendly.

Can you:
1. Make the Address Bar and Tabs separately? Like on 2 horizontal rows, that address bar above and the tabs below?
2. The colors of the Selected Tab and the Behind Tabs, can you please make a fix color for each, in very good contrast? Or just give us the option to choose which color we want the tabs to be… The Active tab and the Behind ones.
3. Can you give a lot more icons; Forward, Backward, Home Page, Downloads, History, Bookmarks. And give us some option to move the icons where we want on the, which is to be on the Address Bar, being completely above in the window. And below it the Tabs.
4. The Tabs… Can you please make it a Fix width? Not auto-expand to full width of the window. If there are many tabs, the it is just like on Safari. It slides to the tab to you clicking on.
5. The close button of the Tabs, can you please place if on the LEFT? It is easier place to click close for mac users.

I wish and hope to at least get a reply from you.

Thanks.

**Comment by PalmerAL** [comment]
I responded to the original issue.
