### ISSUE TITLE
Load window with android app 

### ISSUE THREAD

**Issue by carlosnizer** [minbrowser/min#881]
Hi
How could I use NOD. JS to load in an window an android app on WIN OS? It would need emulation, correct?
I thoroughly tested the 'arc welder', 'archron' projects but they are limited. Some APPs i believe they need external libraries and google, things apart from chrome.
I know that 'min' is based on chrome. I hope I am not escaping much of the scope of this forum.
Then I thought of the possibility, via nod js, to load a window with the app loaded, through emulation from back. I would put the minimum image of android and minimum version, only with necessary additions to the app.
I need run this app on 'win'. I not have time  while for developing one especific version for WIN.
Guys, thanks.

**Comment by PalmerAL** [comment]
It might be possible, but I really have no idea. I hadn't even heard of ARC until now; it looks like Google basically bundled an emulator as part of Chrome (but they might not support it anymore?). If you wanted to connect that to nodeJS, I think you'd have to modify Chromium's emulator code pretty substantially to do that (and if you did that, you would want to use Chromium or Electron directly, not Min). This may or may not be possible, but even if it is, it's going to be a huge amount of work and probably won't work very well.

If you're developing an android app, you'd probably be better off using react native instead, and making a separate UI layer for a desktop version.
