### ISSUE TITLE
Integration with third party applications?

### ISSUE THREAD

**Issue by Vilscon** [minbrowser/min#90]
I'm unsure how far this ever will be implemented, as focus lies on privacy. However, I cannot use MIN as my primary browser, even if I'd want to, mainly because the lack of integration of third party applications. These include primarily: 1Password and perhaps even Dictionary, to correct my typing/untidiness at Facebook, forums, Github, etc.

Perhaps let's just post this question: will 1Password will ever see an integration with MIN?

**Comment by openmedi** [comment]
I asked 1Password and they answered:

- "@1Password Any chance for 1Password support for the new Browser Min? https://t.co/s8a3jVTLE6" ([source](https://twitter.com/openmedi/status/723118906785837056))
- "@openmedi Not right now, but we'll keep an eye on the project." ([source](https://twitter.com/1Password/status/723144830751219712))

I don't know if Min can do anything on their end to provide support, but it seems to be not happening too soon.

**Comment by Blackvibes** [comment]
Hm, I thought it was an issue of MIN, instead of 1Password, because non of my additional applications work with Min. But okay. Like I said, if 1P isn't working, min won't be sufficient. But thanks! 

_Go ahead to change this to closed or anything. _

**Comment by PalmerAL** [comment]
I think 1Password is just a standard chrome extension? If that's the case, than it would be an issue with Min, because we need to add support for extensions.

**Comment by Blackvibes** [comment]
Oh wow, I feel ashamed for totally forgetting this.

I tested this by going to a login form and press the "login-with-1password"-keyboard shortcut, with the Chrome extension enabled and disabled. The result: 1Password will not work when the extension is disabled.

So tl;dr: Min requires support for (1password) extensions to support 1Password.

Well, that brings a little light to the case. Thanks in advance, looking forward to this feature update.

**Comment by jrschumacher** [comment]
For others who want to follow the development of Extension support see #1

**Comment by peteringram0** [comment]
+1 for 1password support

**Comment by Syndamia** [comment]
1Password was implemented in #915 and spellchecking was implemented in #193.
