### ISSUE TITLE
Touch right-click context menu opens on cursor instead of touch location

### ISSUE THREAD

**Issue by richbordoni** [minbrowser/min#903]
As the title says. When you right-click using touch by holding down on the screen with your finger, the context menu opens up wherever your cursor is/was, rather than in the spot where you were touching the screen. Not really the worst issue in the world but it is a little inconvenient if you happened to leave your cursor in an awkward spot.

I'm on Windows 10 x64 btw, Min 1.12.0.

**Comment by PalmerAL** [comment]
I don't have a touch screen to test this with, but I think I possibly have a solution; can you either run this build: https://send.firefox.com/download/2b3bbd906b6df25b/#efzvlt3hpi43Y0s0YMs85g

or use the patch below and create your own build:
```diff
--- a/js/webviewMenu.js
+++ b/js/webviewMenu.js
@@ -194,7 +194,11 @@ var webviewMenu = {
       menu.append(new MenuItem({ type: 'separator' }))
     })
 
-    menu.popup(remote.getCurrentWindow())
+    var offset = webviews.getViewBounds()
+    menu.popup({
+      x: data.x + offset.x,
+      y: data.y + offset.y
+    })
   },
   initialize: function () {
     webviews.bindEvent('context-menu', function (webview, tabId, e, data) {
```

And see what happens?

**Comment by richbordoni** [comment]
I ran the build that you linked and the problem seems to be fixed! 👍

**Comment by PalmerAL** [comment]
OK, great!

**Comment by richbordoni** [comment]
Hey @PalmerAL (tagging you in case you're unsubscribed from this thread and because I can't re-open a closed issue), I found another similar instance of this behaviour. If you tap the triple vertical dot menu button on the top-left of the browser with your finger, the menu window opens up where your cursor was/is instead of on the button itself. I also tested this out in the new build you sent me and the issue persists there as well.

**Comment by PalmerAL** [comment]
Should be fixed in 885a14b8f9ead265bdc62afcb103aec4b5d0d4b2. The next release should be soonish, let me know if it's still an issue after that.

**Comment by PalmerAL** [comment]
Can you try running the 1.13 release and make sure everything's fixed?

**Comment by richbordoni** [comment]
Fixed! 👍
