### ISSUE TITLE
min often outside the screen [Solved]

### ISSUE THREAD

**Issue by antoineboy75** [minbrowser/min#904]
Hello guys, 

Min 1.12, Windows 10

I am telecommuting someday at home and often i cannot watch min on my screen. 

I think min (or windows 10) save the navigator window position and when there are multiple monitors it's a mess. When i come back to my office (2 monitors in addition to the laptop), min is at the same place but at home (1 monitor in addition to the laptop), i should alway change my screen viewing to find it. If I work only with my laptop i cannot do anything to make it comes back to the screen. 

Oddly, it is happening only with min, not firefox or any other software. 

Could it possible to not save the windows position or to purge the position ? Or to add  a shift + right click option to move the windows back to the screen ? 

thanks by advance

**Comment by PalmerAL** [comment]
Thanks for reporting this! I think I've fixed this, can you either run this build: https://send.firefox.com/download/e94554b12c90f675/#fT8R6DA6t-DsZjf1PYDuYA

or build Min with this patch:
```diff
--- a/main/main.js
+++ b/main/main.js
@@ -8,6 +8,10 @@ const webContents = electron.webContents
 const session = electron.session
 const ipc = electron.ipcMain
 
+function clamp(n, min, max) {
+  return Math.max(Math.min(n, max), min);
+}
+
 if (process.platform === 'win32') {
   (async function () {
   var squirrelCommand = process.argv[1];
@@ -108,7 +112,7 @@ function createWindow (cb) {
     }
     if (e || !data || !bounds) { // there was an error, probably because the file doesn't exist
       var size = electron.screen.getPrimaryDisplay().workAreaSize
-      var bounds = {
+      bounds = {
         x: 0,
         y: 0,
         width: size.width,
@@ -116,6 +120,15 @@ function createWindow (cb) {
       }
     }
 
+    var containingRect = electron.screen.getDisplayMatching(bounds).workArea;
+
+    bounds = {
+      x: clamp(bounds.x, containingRect.x, (containingRect.x + containingRect.width) - bounds.width),
+      y: clamp(bounds.y, containingRect.y, (containingRect.y + containingRect.height) - bounds.height),
+      width: clamp(bounds.width, 0, containingRect.width),
+      height: clamp(bounds.height, 0, containingRect.height),
+    }
+
     // maximizes the window frame in windows 10
     // fixes https://github.com/minbrowser/min/issues/214
     // should be removed once https://github.com/electron/electron/issues/4045 is fixed
```

and see if it works?

**Comment by antoineboy75** [comment]
Tks you so much for this aswer PalmerAL. 

Unlunckily i cannot use an .exe setup file on my office computer without administrative rights. Could you give me a patch on a portable version of min ? Or could you tell me which files i need to patch with this code ?

**Comment by PalmerAL** [comment]
Sure: https://send.firefox.com/download/2a5912d191a79ff9/#AT8iBenRuqV3ZIOVTkH6bA

**Comment by antoineboy75** [comment]
perfect, I will let you know, next tuesday the latter, if the issue is solved.

**Comment by antoineboy75** [comment]
perfect apparently it is solved ! wonderful Job :)

**Comment by PalmerAL** [comment]
Great!

**Comment by antoineboy75** [comment]
Hum but it seems that the min version you sent me cannot load pdf correctly anymore (?)

**Comment by PalmerAL** [comment]
Oops, it looks like I built that version with the wrong version of PDFJS, this should fix it: https://send.firefox.com/download/1a140ba0cfec8726/#6Ry1qwqyX5Kbls_MqmgZnw
