### ISSUE TITLE
Opening new tab when tab bar is scrollable causes tab bar to scroll to beginning

### ISSUE THREAD

**Issue by richbordoni** [minbrowser/min#906]
Hi, I'm on Min 1.12.0, W10 x64. Basically as the title says, if you have enough tabs open that the tab bar becomes scrollable, and you open a new tab anywhere to the right of the tabs that you can see when the tab bar is in its default (not scrolled) position, Min scrolls all the way back to the beginning of the tab bar resulting in the newly opened tab being out of sight. Example:

![min](https://user-images.githubusercontent.com/8562062/74366326-d0697d80-4d9d-11ea-876c-7df41aeb6292.gif)

The same issue also happens if you:
➊ open a new tab and then close the URL bar without navigating to any site
➋ click on the current tab to open the URL bar, and then close the URL bar
➌ click on the current tab to open the URL bar, and then navigate to a new site (in the same tab)
➍ bookmark a tab using `Ctrl` `D` or by clicking on the current tab and then the star icon

Originally I posted this in #662 but after re-reading the original post I realised that this is actually a different issue.

**Comment by PalmerAL** [comment]
I think the only fix for this is to make the searchbar input a separate layer on top of the tabs; that's reasonably complicated unfortunately, but I'll probably get to it at some point.

**Comment by PalmerAL** [comment]
I think #943 should fix this. Test build if you'd like to try it out: https://send.firefox.com/download/072ee41768185673/#mmeXRazKJR6t01i1IOtHzQ

**Comment by richbordoni** [comment]
Seems like that fixed it. 👍

**Comment by richbordoni** [comment]
Hey, so I think I found another unintended behaviour related to this issue. Entering and then exiting focus mode also results in the tab bar being scrolled all the way back to the beginning if you have many tabs open, even if your current tab is, for instance, the last one open.

**Comment by richbordoni** [comment]
@PalmerAL just tagging you in case my reply above didn't send you a notification. Not sure if you want to hold off on this issue or not pending any possible changes to focus mode.

**Comment by PalmerAL** [comment]
I got it, thanks. I haven't found focus mode very useful either, and since I suspect that very few people use it, I'm think I'm going to go ahead and make the changes I described, in which case this issue should go away. (Or if I don't, it shouldn't be too hard to fix it the way it is either).
