### ISSUE TITLE
Autofill button appears incorrectly in Github author dropdown

### ISSUE THREAD

**Issue by PalmerAL** [minbrowser/min#919]
<img width="398" src="https://user-images.githubusercontent.com/10314059/75740638-da600b80-5ccd-11ea-91fb-077afd42f456.png">

It would probably make sense to only show the icon if the page contains both a username and a password field.

**Comment by Syndamia** [comment]
Can this be related to 1Password? I did a bit of testing and the problem occurred only with 1Password enabled, not with Bitwarden.

**Comment by PalmerAL** [comment]
This is fixed now.
