### ISSUE TITLE
Mac says integrity cannot be verified

### ISSUE THREAD

**Issue by jerm5802** [minbrowser/min#921]
I tried to download Min but it shows me this message. 
<img width="481" alt="Screen Shot 2020-03-05 at 2 55 25 PM" src="https://user-images.githubusercontent.com/61848236/76020537-94838d00-5ef1-11ea-9f37-4d5942ec5538.png">

**Comment by PalmerAL** [comment]
Does it work if you right-click on it and open it from there?

**Comment by jerm5802** [comment]
No it shows the same message.

**Comment by PalmerAL** [comment]
In the dialog that comes up after right-clicking > "open", is there an "open" button that you can use?

The other way to do this is to try opening the app, and then go to system preferences > security > general, and you should see an "open anyway" option:

![](https://img.gadgethacks.com/img/75/46/63549500655103/0/open-third-party-apps-from-unidentified-developers-macos.w1456.jpg)

**Comment by jerm5802** [comment]
That worked, thanks.

**Comment by PalmerAL** [comment]
Great!
