### ISSUE TITLE
Ошибка запуска установщика

### ISSUE THREAD

**Issue by garfildalex6** [minbrowser/min#928]
Не могу даже запустить установку
Windows 7 - 64x
[SquirrelSetup.log.txt](https://github.com/minbrowser/min/files/4308187/SquirrelSetup.log.txt)

**Comment by PalmerAL** [comment]
I don't know enough about how Squirrel works to know the cause of this; could you try deleting `C:\users\username\AppData\Local\SquirrelTemp` and `C:\users\username\AppData\Local\min` and running the installer again?

(Из Google Translate)
Я не знаю достаточно о том, как работает Белка, чтобы понять причину этого; не могли бы вы попробовать удалить `C:\users\username\AppData\Local\SquirrelTemp` и `C:\users\username\AppData\Local\min` и снова запустить установщик?

**Comment by garfildalex6** [comment]
Сделал, как вы сказали. Теперь лог файл пустой, но запустить установщик так и не удалось. 
http://prntscr.com/re6kc9
http://prntscr.com/re6kij

**Comment by KagamineP** [comment]
> Сделал, как вы сказали. Теперь лог файл пустой, но запустить установщик так и не удалось.
> http://prntscr.com/re6kc9
> http://prntscr.com/re6kij

Visual C++ 2015-2019 установлены?

**Comment by garfildalex6** [comment]
Да. Установлено. Еще раз проверил -  не запускается установщик.
http://prntscr.com/retp6z

**Comment by KagamineP** [comment]
> Да. Установлено. Еще раз проверил - не запускается установщик.
> http://prntscr.com/retp6z

Странно.

**Comment by KagamineP** [comment]
> Да. Установлено. Еще раз проверил - не запускается установщик.
> http://prntscr.com/retp6z

Попробуйте создать пользователя с именем на латинице например: Alexey

**Comment by garfildalex6** [comment]
Создал нового пользователя на латинице.
Долго запускался. Потом запустилось окно браузера, но через 30 сек закрылось и появилась та же ошибка связанная с Update.
В установленных приложениях браузера нет и после повторных попыток уже ничего не получилось запустить.

**Comment by KagamineP** [comment]
I think that is maybe outdated and this can be closed right now.
