### ISSUE TITLE
Bitwarden sign in fails if 2FA is enabled

### ISSUE THREAD

**Issue by anonymous1184** [minbrowser/min#929]
For the miriad of sites in the password manager, I only use a few with more than one account.

Is there any plans for selecting the desired credentials? I belive every internet user has the need to use at very least a service with more than one set of credentials (e.g. work/personal email).

**Comment by PalmerAL** [comment]
You should see a list that allows you to pick which credentials you want to use, like this: https://user-images.githubusercontent.com/10314059/73512567-b8622900-43af-11ea-9880-5f72efdc7b33.png. Are you not seeing that? Or do you mean something else?

**Comment by anonymous1184** [comment]
I was not seeing that.

There's no way of setting up 2FA on the initial configuration of Bitwarden in Min. The issue arised after disabling 2FA, setting up Min and subsecuently enabling 2FA. It was solved by manually re-logging while Min was closed (re-syncing by restarting Min didn't work):

```
bw logout
bw login email password --method 3 --code <OTP>
```
(Refer to [online documentation](https://help.bitwarden.com/article/cli/#enums) for `--method` values, since CLI help doesn't cover them.)

On a side note, its worthy to remember that [match detection](https://help.bitwarden.com/article/uri-match-detection) rules applies, because even after being able to choose credentials one of them didn't appear (this was totally a layer 8 issue).

**Comment by PalmerAL** [comment]
Thanks for investigating more; I guess it would make sense to add some options to the sign in form for that.

**Comment by gpioneer90** [comment]
> 
> 
> I was not seeing that.
> 
> There's no way of setting up 2FA on the initial configuration of Bitwarden in Min. The issue arised after disabling 2FA, setting up Min and subsecuently enabling 2FA. It was solved by manually re-logging while Min was closed (re-syncing by restarting Min didn't work):
> 
> ```
> bw logout
> bw login email password --method 3 --code <OTP>
> ```
> 
> (Refer to [online documentation](https://help.bitwarden.com/article/cli/#enums) for `--method` values, since CLI help doesn't cover them.)
> 
> On a side note, its worthy to remember that [match detection](https://help.bitwarden.com/article/uri-match-detection) rules applies, because even after being able to choose credentials one of them didn't appear (this was totally a layer 8 issue).

Hi anon,
Can you clarify, does following your steps allow you to use 2FA (namely email authentication) with Bitwarden in Min after making these changes? I cannot rely on non-2FA for a password manager because of a fear of a keylogger logging my master password and then there's no recourse for a third party to easily access ALL my logins

**Comment by anonymous1184** [comment]
No workaround yet. I was tasked to create a full Windows integration of Bitwarden that doesn't rely in any 3rd party AND support for TOTP (email is less secure). Right now what I do have is a KeyPass-like autotype (you need to edit entries for match detection but as you noted it can be a handful). It shouldn't take me more a week to have it up and running and as I envision it will work in-browser regardless of extensions or administrative permissions. I'll keep you posted if interested.

**Comment by hakarune** [comment]
I am on Arch so I don't know what to do with a pkg file. As for the newer op cli, min doesn't have a section to enter in the user's 1P site and does it handle the 2FA OTP code? 

Using OP app command is "op signin [vault url] [email] [secret key]" then entering 2FA OTP code to get a session token.
