### ISSUE TITLE
Congratulations

### ISSUE THREAD

**Issue by manuelmazzuola** [minbrowser/min#931]
Hi, I would like to congratulate @PalmerAL, all the developers, the contributors and community for the new release, password management and improved bookmarks pushed that browser a step forward to the others, imo.
I use min since v1.3 alternating it with others browsers, but now, I would like to use it full time, congratulations!

**Comment by PalmerAL** [comment]
Thank you, I really appreciate it! There's definitely been a lot of changes since then; let me know how it goes.
