### ISSUE TITLE
Google Meet video problem

### ISSUE THREAD

**Issue by flber** [minbrowser/min#934]
When attempting a Google Meet call, the video and microphone are blocked and Min has no way to enable them for specific sites. Is this a bug or something that just hasn't been implemented yet.

**Comment by PalmerAL** [comment]
It's not implemented yet, there's an existing issue for this: #332.

I don't think it's too hard to do this, so I'll probably do it soon. (also, now is probably a good time to support videoconferencing).

**Comment by PalmerAL** [comment]
This turns out to be more complicated than I thought, but I'm mostly done with it: https://github.com/minbrowser/min/tree/permissions

**Comment by PalmerAL** [comment]
Released: https://github.com/minbrowser/min/releases/tag/v1.13.2. Let me know if you run into any issues with it.

**Comment by flber** [comment]
Wow, thank you so much!

**Comment by flber** [comment]
Also, where is the permissions for camera and audio for websites? I do not see any option to enable anything new in the settings

**Comment by flber** [comment]
So as of now (I still cannot figure out where that setting is), audio in and the camera are still disabled
:(

**Comment by flber** [comment]
(side question, is there a way to check the version in-browser?)

**Comment by PalmerAL** [comment]
The way it's supposed to work is that a button shows up next to the tab title when the site asks for access:

<img width="214" src="https://user-images.githubusercontent.com/10314059/76790331-a46e5d00-678c-11ea-99e6-eae4de50c6f8.png">

Clicking that grants access to the site:

<img width="215" src="https://user-images.githubusercontent.com/10314059/76790378-ba7c1d80-678c-11ea-86f0-6795fe365a50.png">

Do you see anything like that?

The browser version is listed in Min > about Min on macOS, or three-dot menu > help > about on Windows, or help > about on Linux.

**Comment by flber** [comment]
Ah, lovely! Both of those work! Thank you so much for your help!
