### ISSUE TITLE
Flowchart Min

### ISSUE THREAD

**Issue by idAlencar** [minbrowser/min#938]
I know it will take some time, but you could do something similar to a flow chart of the files (html, css, js) of how Min works. I wanted to understand more to know where to go,
and it can also help more people to contribute

**Comment by PalmerAL** [comment]
Sure.

**Comment by PalmerAL** [comment]
What I have so far: https://gist.github.com/PalmerAL/73e09dfb0817e6fd21d8299715ed9da2. Once it's more complete, I'll add it to the wiki.

**Comment by PalmerAL** [comment]
I've added this information to the wiki. I think it covers enough to get an overview of how everything fits together, but it would probably be good to document some of the individual modules in more detail at some point as well; let me know if there's anything in particular you think is missing.
