### ISSUE TITLE
Windows requires redhat installer

### ISSUE THREAD

**Issue by borowyalan** [minbrowser/min#941]
`npm install` requires `electron-installer-redhat` as stated in `package.json`. 

![image](https://user-images.githubusercontent.com/38703820/76981707-416ef880-693b-11ea-9aaa-5aab33be21f9.png)

It can't install it on Windows and throws an error, tho.

![image](https://user-images.githubusercontent.com/38703820/76981680-3ae08100-693b-11ea-8487-7c19fa05c49e.png)

Removing it from devDependecies fixes the issue.

Am I missing something?

**Comment by PalmerAL** [comment]
Thanks for pointing that out, I guess that should just be an optionalDependency like the debian installer is.
