### ISSUE TITLE
[SOLVED] Doesn't work on Windows 7 

### ISSUE THREAD

**Issue by hosadokha** [minbrowser/min#944]
I downloaded the portable version of Min, Im on x64 updated Windows 7 and I get only a black blank screen when I run the browser.. 
Do I need .Net Framework or something? 
Other browsers run fine..

**Comment by KagamineP** [comment]
> I downloaded the portable version of Min, Im on x64 updated Windows 7 and I get only a black blank screen when I run the browser..
> Do I need .Net Framework or something?
> Other browsers run fine..

Hello.
Do you have Visual C++ 2015-2019 installed?

**Comment by hosadokha** [comment]
I just checked I have " Microsoft Visual C++ 2015 Redistribtable (x86) - 14.0.24215" Installed
for some reason its x86 not x64.. I also have other older versions installed

**Comment by KagamineP** [comment]
> I just checked I have " Microsoft Visual C++ 2015 Redistribtable (x86) - 14.0.24215" Installed
> for some reason its x86 not x64.. I also have other older versions installed

Try to install Visual C++ 2015-2019. I have a PC with installed Windows 7 and there Min works good.

**Comment by PalmerAL** [comment]
If that doesn't work, you could also try running with `--disable-gpu`.

**Comment by hosadokha** [comment]
It works now after installing a few Windows security updates I was ignoring and a bunch of optional Windows updates.. I dont know what exactly was the main cause but i dont care now..
