### ISSUE TITLE
Rearrange tabs idea

### ISSUE THREAD

**Issue by 956MB** [minbrowser/min#948]
Referencing #684. 
I don't know if this sort of thing has been suggested or considered before, but I thought Id put an idea for this out there. Being that the task rearranging thing is less than perfect, maybe this could be one possible solution to tab rearranging.

![8dd61e748c85d6db780170202a0cffe2 (1)](https://user-images.githubusercontent.com/39519792/77843771-00aa8700-7166-11ea-8a61-21d31119baec.png)

With the red in this screenshot being the draggable area (on macOS at least), the small blue dots in the left of each tab could be the spot to drag tabs around. With them only being visible in the tab on hover of course. They could be small dots like in this, a thin line, or like a small right angle arrow facing the top left of the tab. Really anything that fits the minimal aesthetic of Min.

**Comment by Syndamia** [comment]
I'm not sure how well this will work. The thing is that when clicking on a tab you open the `search`. If it's a small thing on the side, accidental openings of `search` and of moving tabs will inveitably happen and if it's big, then it will clutter the UI.

Also the drag spots being visibe only on hover will be less than ideal, because every time you hover over a tab it will add the button and move the text to the right (*I can see people, myself included, being annoyed by that*). Another options is for it to be just a blank space that fills in with the icon, but then you have a (*relatively*) big blank space most of the time.

Another thing to consider is such a feature will probably require a fair amount of rework of tab functionality, maybe even needing a rewrite of most of it (*I don't know how it works exactly, @PalmerAL should chime in*) which might not be worth it.

**Comment by Bloumbs** [comment]
@Syndamia  Addressing the points you gave:

Opening search:
I think a resonable work around for this would be just a double click action to trigger search. So you can navigate in and out of tabs with the normal one click, drag around around your window on top of any of your tabs, not worrying about opening search, then a real quick double tap to open search for a tab. Or also a keybind to open search as well, like "_key_+mouseClick" on the tab.

The drag spots:
I dont think what you said about text being moved would really be an issue. The tab already has padding on the left for the text, so theres already room for it I think. I think it could be like the screenshot in the initial post above, the blue dot being the drag point doesnt need to be that large, just enough to be noticable, and the encapsulating div or whatever would be placed just to the left of the tabs text, filing vertically to the top/bottom of the tab. So there wouldnt be any reason for the drag area/dot to move the tabs text in any way, the dots color or whatever would just become visible on hover of the entire tab. And of course it could be a thin line or something instead if that looked better or took up even less space.

Rework:
I agree that it might take a good amount of effort and work for it to be implemented, and its not for me to say if its worth it for the project. However thats basically what projects like this are for after all, having to possibly do some rework to implement a feature. Just my opinion though, I dont know 100% if it would work out from a flow persective, if the feature would be easy and intuitive enough for people to like. Just personally, I think it would be a better system if it was this way. I would like it at least :)

**Comment by PalmerAL** [comment]
* On Windows and Linux (which is 83% of users), the window drag area is now separate from the tab bar, so we could probably just do normal tab dragging there without any additional UI.
* I do think something like this could work, although I share some of the same concerns that @Syndamia has. In particular, making important actions like opening the searchbar rely on a double-click seems like a bad idea - most people won't expect that, and there won't be any clear indication that that's what you need to do.
* One alternative might be to put this behind a keyboard shortcut, like requiring you to press cmd while dragging.

**Comment by PalmerAL** [comment]
For the next release, I'm going to implement normal tab dragging on Windows and Linux; since dragging on the tab area doesn't do anything else, that shouldn't cause any issues.

For macOS, I'm not completely sure what to do yet, but I think the best option is to hold down cmd while dragging.
