### ISSUE TITLE
Running min development version throws error

### ISSUE THREAD

**Issue by flber** [minbrowser/min#949]
I cloned the repo, installed dependencies, made sure I had node, and tried to run min with the given command `node_modules/.bin/electron .`

It threw the error in the command line `'node_modules' is not recognized as an internal or external command, operable program or batch file.`

Any suggestions?

**Comment by flber** [comment]
Hmmm. I actually cd'ed to `node_modules/.bin/` and ran `electron .`

It responded with this:
<img width="418" alt="launchError" src="https://user-images.githubusercontent.com/42008155/77958850-89bade80-728a-11ea-8573-e30d7069ad64.png">

**Comment by PalmerAL** [comment]
Did you run `npm install`?

This sequence works for me:

```
cd \Documents\min
npm install
npm run build
node_modules\.bin\electron .
```

**Comment by flber** [comment]
Ah, lovely!
Thank you!
