### ISSUE TITLE
Bug Menu

### ISSUE THREAD

**Issue by idAlencar** [minbrowser/min#952]
Hi @PalmerAL, I noticed an error in the menu, when it is hidden (Ctrl + M) when exiting full screen mode, the horizontal menu and the menu points appear together

![menu](https://user-images.githubusercontent.com/58848807/78241689-311c5900-74b7-11ea-9f8a-f7660c463537.png)

**Comment by PalmerAL** [comment]
This might be fixed once the window controls are inline with the tab bar: https://github.com/minbrowser/min/issues/909#issuecomment-592997788, since in this mode, the horizontal menu would be disabled completely.
