### ISSUE TITLE
Dark mode messes up with backgrounds.

### ISSUE THREAD

**Issue by luxoriant** [minbrowser/min#954]
So, I have started to notice Min's firm dark mode's blue-ish gray background on other sites' pages. From what I see so far, Google Dev shows me that it replaces or shows under "transparent backgrounds" (or is it changing backgrounds to transparent?).

This issue is not present in light mode, nor after using Google Dev > Rendering (prefers light). Can you help me with this bugging problem?

![image](https://user-images.githubusercontent.com/58133782/78289365-be4cc580-752a-11ea-85bc-e36d657bee42.png)

**Comment by luxoriant** [comment]
So, if the color is not defined directly, the browser assumes it's intentionally transparent, so it shows me new tabs' background. Well, existentially, that's a well thought-off behaviour :)

**Comment by luxoriant** [comment]
After I leave Google Dev, background becomes white, till the next reload. Although, in Dev mode (opened afterwards), the background is still not set.

**Comment by idAlencar** [comment]
I also noticed this behavior

![tela](https://user-images.githubusercontent.com/58848807/78353876-38a83480-7581-11ea-9591-ba62c87a1bdd.png)

**Comment by PalmerAL** [comment]
Thanks for reporting this, this is a regression from 4b359ce42d8a006baa6f08c10a4fc7403014bda4. Electron's API to set a background color for the BrowserView has been broken on Windows and Linux for a while, so the color that is behind the view (which is also the color you see on a new tab) can bleed through. Previously, we only made new tabs have a dark background on mac to avoid this issue, and left them white everywhere else. However, this commit made the background dark everywhere by mistake.
