### ISSUE TITLE
How add hide and show  sidebar to Min?

### ISSUE THREAD

**Issue by IProudNoob** [minbrowser/min#960]
Hello!
Thanks for the interesting application)
I begin to study the electron with examples.
I want to add a sidebar but I don’t know how to do it, so as not to destroy the browser.
Tell me how and where to do it.
![image1](https://user-images.githubusercontent.com/49113349/78469504-8613d580-772a-11ea-83d0-f5b923644b87.png)
Thanks)

**Comment by PalmerAL** [comment]
Once you can build the browser (see the readme for instructions), you would want to:

1. Create a `<div>` in the index.html file for the sidebar, and add some CSS to position it where you want. The navbar height can vary, so if you want the sidebar to be directly below the navbar, you can do this:
```
top: calc(36px + var(--control-space-top))
```
2. Modify the webview sizing code [here](https://github.com/minbrowser/min/blob/master/js/webviews.js#L174-L177) to leave room for the sidebar. You'll want to add the sidebar width to `x`, and subtract it from `width`.

From there, I think it would depend what you want the sidebar to display.

**Comment by IProudNoob** [comment]
Hi!
Is it work but only if I not open site.
![Before](https://user-images.githubusercontent.com/49113349/78523743-6a680800-77da-11ea-8ed5-09e59f076442.png)

After this sidebar not showing.
![After](https://user-images.githubusercontent.com/49113349/78523771-82d82280-77da-11ea-9b96-997a0c07c404.png)

**Comment by PalmerAL** [comment]
What changes did you make in `webviews.js`, and did you rebuild (npm run build) after doing that?

**Comment by IProudNoob** [comment]
It's work!!!
I just started to learn and understand everything :)
I figured out how to add a working button in navbar.
But I still do not understand whether it is possible to name the sidebar to be visible and not visible, and how to change the width of the loaded page?

You create very interesting project!

**Comment by PalmerAL** [comment]
Can you explain further what you mean? When do you want the sidebar to be visible?

The width of the page is calculated by the function I linked to earlier - were you able to modify that successfully?

**Comment by IProudNoob** [comment]
I want show and hide sidebar after click button. But I understand need change width not only sidebar, need change width  site load zone. 
How do it?

**Comment by IProudNoob** [comment]
Found this function **adjustMargin** :)
I think it's help me.
Thank you!

**Comment by PalmerAL** [comment]
Yup, that should work.
