### ISSUE TITLE
Can't sign google account

### ISSUE THREAD

**Issue by og900aero** [minbrowser/min#961]
I plan to switch from Chromium to Minbrowse, but there are a big problems. I get an error message when I try to sign in to my google account:
**Couldn't sign you in**
This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

Is there any solution or should I still use Chromium?

**Comment by PalmerAL** [comment]
Can you try the instructions at the top of #868?

**Comment by og900aero** [comment]
1. No. I dont' enabled 2FA
2. My OS is Arch Linux whit Openbox WIndowsManager
3. My location is Hungary

I don't know how rebuild minbrowser, because your website only has debian and redhat descriptions. I install from Arch community repository.

**Comment by PalmerAL** [comment]
I'm not sure how to build the arch package directly, but I think you can either:

1. Use the instructions here to run in development mode: https://github.com/minbrowser/min#developing
2. Edit the `main.build.js` file within `/usr/lib/min/` directly - look for the line containing "userAgentFallback".

**Comment by dymaxionkim** [comment]
> > I'm not sure how to build the arch package directly, but I think you can either:
> > 
> > 1. Use the instructions here to run in development mode: https://github.com/minbrowser/min#developing
> > 2. Edit the `main.build.js` file within `/usr/lib/min/` directly - look for the line containing "userAgentFallback".
> 
> Dear PalmerAL
> 
> When I edit /usr/lib/min/main.build.js, and search userAgentFallback, and replace string to app.userAgentFallback = 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:74.0) Gecko/20100101 Firefox/74.0', then works a charm. Now I sign to Google account! This is a solution, thx!

I tried these commands and have got good result for Min-1.14.0 in Ubuntu 20.04 :

```
sudo mv /usr/lib/min/resources/app/main.build.js /usr/lib/min/resources/app/main.build.js.old

sed "s/app.userAgentFallback = newUserAgent/\/\* app.userAgentFallback = newUserAgent \*\/\napp.userAgentFallback = \'Mozilla\/5.0 \(Windows NT 10.0\; WOW64\; rv\:74.0\) Gecko\/20100101 Firefox\/74.0'/g" /usr/lib/min/resources/app/main.build.js.old | sudo tee -a /usr/lib/min/resources/app/main.build.js
```
