### ISSUE TITLE
Unable to login to any Google service

### ISSUE THREAD

**Issue by VictorAlbertsson** [minbrowser/min#962]
Whenever I attempt to login to any Google service (such as Youtube) it displays the following message:

> Couldn't sign you in
   This browser or app may not be secure. Learn more
   Try using a different browser. If you’re already using a supported browser, you can refresh your 
   screen and try again to sign in.

I am running Windows 10 but I have tested it on Arch Linux as well and I have the same problem there.

I really want to switch to Min but this is a deal-breaker, any help would be greatly appreciated!

**Comment by PalmerAL** [comment]
Can you try the instructions at the top of #868?

**Comment by VictorAlbertsson** [comment]
After recompiling with the suggested changes it now works, though it would be nice if this was in the binaries.

**Comment by abampalexnder** [comment]
I have got solution for google after 3 weeks brain storming and spent all day and night time to resolve the issue any one need solution can contact on 
Email: abmpanalexander@protonmail.com
on wire @abampalxender

**Comment by Sestowner** [comment]
Fixed in 936a1ea9e7909fcc159931979de3771079c257cd.
