### ISSUE TITLE
The tasks not appears anymore

### ISSUE THREAD

**Issue by elkwaet** [minbrowser/min#968]
Since some weeks, my Min tasks don't appears anymore.
I make several time dpkg-reconfigure in the way to reload settings in vain.

**Comment by PalmerAL** [comment]
Can you clarify what you mean? You can't get to the tasks list? Or you had a set of saved tabs that don't appear in the list any more?

**Comment by elkwaet** [comment]
When am working, i can only switch in a single task tabs but clicking on the tab title, not in task list.
When i create a new task, i lose the previous task and and can't toogle beetween previous tabs: the overlay not appears list no more.
![Capture du 2020-04-20 06-08-58](https://user-images.githubusercontent.com/18514510/79719543-55a56d00-82ce-11ea-863d-c710b483ce8d.png)

**Comment by PalmerAL** [comment]
After clicking on the task button, can you go to developer > inspect browser > console, and copy any errors that appear there?

Also, would you be willing to share your saved task data? It's located in `/home/.config/username/min/sessionRestore.json`; you can remove the actual titles and URLs of the pages if you want.

**Comment by elkwaet** [comment]
From the browser console, when clicking on the task button:
`bundle.js:7155 Uncaught TypeError: Cannot read property 'title' of undefined
    at Object.infoContainer (bundle.js:7155)
    at Object.container (bundle.js:7193)
    at createTaskContainer (bundle.js:7278)
    at bundle.js:1552
    at Array.forEach (<anonymous>)
    at TaskList.forEach (bundle.js:6965)
    at Object.show (bundle.js:1551)
    at Object.toggle (bundle.js:1615)
    at HTMLButtonElement.<anonymous> (bundle.js:1482)`

**Comment by elkwaet** [comment]
At finish, i mv the current "~/.config/Min" folder totaly then the browser reset their settings and let me get back my Tasks.
![Capture du 2020-04-20 11-59-08](https://user-images.githubusercontent.com/18514510/79749427-b8aef800-82fe-11ea-9e06-8e4593997ec2.png)

**Comment by PalmerAL** [comment]
The symlinks are from Electron's [singleInstance API](https://www.electronjs.org/docs/api/app#apprequestsingleinstancelock), so I wouldn't expect that to have any effect (although I don't know why they're broken).

The error is happening [here](https://github.com/minbrowser/min/blob/master/js/taskOverlay/taskOverlayBuilder.js#L166), so most likely you somehow ended up with a task with no tabs in it, which shouldn't ever happen. I can't think of any way for that to occur, but I'll probably spend some time looking at some point and see if I can find a way that could happen.

**Comment by PalmerAL** [comment]
I just experienced the same problem myself. Still not sure what's causing it.

**Comment by PalmerAL** [comment]
I can reproduce this:

1. Create a task where every tab is a private tab.
2. Switch to a new task.
3. Quit the browser.
4. Re-open and open the task overlay.

@elkwaet do you think you might have done that?
