### ISSUE TITLE
can it open tab in command line ?

### ISSUE THREAD

**Issue by turbochoo** [minbrowser/min#970]
i want to open special url in terminal ,but it can't ,any one know how to do it, ths. :)

**Comment by PalmerAL** [comment]
You should be able to run “min <url>”, does that work for you?

**Comment by NikSays** [comment]
If you want to open an url you need to specify protocol
so `min http://github.com` or `min file:///home/user/localFile.html` for local files

It'd be cool, if min tried to guess the protocol
