### ISSUE TITLE
Password Autofill with RPi4 64bit kernel.

### ISSUE THREAD

**Issue by lee-yunseok** [minbrowser/min#978]
**This is not a Min browser issue.** Just wanted check.

Currently Bitwarden does not provide armhf binary. So password autofill feature doesn't work in the usual way(dragging bw) for **RPi4 64bit kernel** users. For use it, users need to install Bitwarden using npm: `npm i -g @bitwarden/cli`

Please close this after you confirm.

**Comment by PalmerAL** [comment]
Thanks for pointing that out, I guess we should add some documentation to the wiki about that.

**Comment by PalmerAL** [comment]
Added to the wiki.

**Comment by lee-yunseok** [comment]
Thanks.
