### ISSUE TITLE
Native Titlebar is Showing

### ISSUE THREAD

**Issue by KorbsStudio** [minbrowser/min#984]
![image](https://user-images.githubusercontent.com/51213244/80431429-6f8f1300-88bf-11ea-8ceb-aa5c3ac4c17e.png)
The native titlebar on Elementary OS 5.1.3 is showing.

**Comment by PalmerAL** [comment]
This should be fixed by #963.

**Comment by KorbsStudio** [comment]
Then why is it still happening on my end?

**Comment by PalmerAL** [comment]
Did you build from the master branch, or are you using the latest released version?

**Comment by KorbsStudio** [comment]
I downloaded the latest version from the website

**Comment by PalmerAL** [comment]
That PR hasn't been released yet; I'll probably make a new release pretty soon, or you can use the build instructions in the readme if you want to use it sooner.

**Comment by idAlencar** [comment]
hi, what is in bold is what you modify (add)
 
**modify /usr/lib/min/js/default.js**

if (navigator.platform === 'MacIntel') {
  document.body.classList.add('mac')
  window.platformType = 'mac'
} else if (navigator.platform === 'Win32' **|| navigator.platform.includes('Linux'**)) {
  document.body.classList.add('windows')
  window.platformType = 'windows'
} else {
  document.body.classList.add('linux')
  window.platformType = 'linux'
}


**modify /usr/lib/min/js/windowsCaptionButtons.js**

if (**true**) {
  updateCaptionButtons()

  captionMinimise.addEventListener('click', function (e) {
    remote.getCurrentWindow().minimize()
  })


**modify /usr/lib/min/main.build.js**

minWidth: (process.platform === 'win32'? 400: 320), // controls take up more horizontal space on Windows
minHeight: 350,
titleBarStyle: 'hiddenInset',
icon: __dirname + '/icons/icon256.png',
frame: **process.platform === 'darwin' || settings.get ('useSeparateTitlebar') === true,**



**modify /usr/lib/min/dist/bundle.js**


if (navigator.platform === 'MacIntel') {
  document.body.classList.add('mac')
  window.platformType = 'mac'
} else if (navigator.platform === 'Win32' **|| navigator.platform.includes('Linux'**)) {
  document.body.classList.add('windows')
  window.platformType = 'windows'
}


if (**true**) {
  updateCaptionButtons()

  captionMinimise.addEventListener('click', function (e) {
    remote.getCurrentWindow().minimize()
  })

**Comment by PalmerAL** [comment]
I made a new release with this change included.

**Comment by KorbsStudio** [comment]
Maybe add the option to move the button to the left side, I use the OSX layout @PalmerAL!

**Comment by PalmerAL** [comment]
Is that the Elementary default, or something you've customized?

If it's something custom, I'm not sure it's worth the additional complexity, but if it's the default it would affect a lot more people, so it might be worth doing.

**Comment by KorbsStudio** [comment]
The default layout for Elementary OS is a bit weird actually, most odd as no other OS uses that layout.
By default, Elementary OS would use the `close:maximize` layout. Although, [this post](https://www.reddit.com/r/elementaryos/comments/gyq35m/why_does_elementary_use_the_closemaximize_layout/) does make a good point to why.
