### ISSUE TITLE
side mouse buttons trigger twice on some websites

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#987]
Hello, first of all i love this browser, already switched to it full time. 
There is this small issie with my mouse buttons, if i press back it sometimes goes back twice. For example if i go to youtube, choose a video and then choose a second video, when i press back it will go to youtube's home page, but i expect it to return to first video. This also happens on Slack, if i select different Slack channles like 1 -> 2 -> 3 and press back, it bring me to first channel

it seems that only this issue happens on websites that use javascript for navigation or something, i am not sure. holding the back forward buttons goes back once, and on release it goes back once again.

**Comment by PalmerAL** [comment]
Does the same thing happen if you use the back button in the navbar, or the item in the context menu?

**Comment by shalva97** [comment]
no, they work fine

**Comment by BramVerb** [comment]
I experienced this issue as wel, for example when navigating through a projects structure on github. Is there any way I could help to fix this?
As said by @shalva97 the normal back button in the navbar works fine, just the mousebuttons act incorrect.

**Comment by PalmerAL** [comment]
It looks like this is this issue: https://github.com/electron/electron/issues/18322. So I guess the fix is to only register the listener on Windows.

**Comment by PalmerAL** [comment]
@shalva97 @BramVerb Can you test the master branch with 4a0c243664c66022187cf7181e9c799e6ed73437 and see if it works as expected?

**Comment by BramVerb** [comment]
Awesome, that did the trick! Thank you for such a quick fix.
