### ISSUE TITLE
UI looks outdated, change icon sets

### ISSUE THREAD

**Issue by gczark** [minbrowser/min#997]

**Comment by PalmerAL** [comment]
Can you provide more detail about what you think looks outdated? What do you dislike about the icons?

**Comment by granadokristoffer** [comment]
![image](https://user-images.githubusercontent.com/28706158/82830320-f697d100-9ee7-11ea-9ec1-b7fdeafef03e.png)
Icons doesn't match up with the system icons, I suggest you should use icons from "Segoe MDL2 Assets Font"

**Comment by PalmerAL** [comment]
The icons are being replaced in #1134.
