### ISSUE TITLE
Autoupdate app functionality

### ISSUE THREAD

**Issue by raj123** [minbrowser/min#999]
Just wanted to know if there is auto update functionality in it.

Thanks

**Comment by raj123** [comment]
found this in previous issues
https://github.com/minbrowser/min/issues/397

however you can do autoupdate for windows only if it is related to money.

**Comment by PalmerAL** [comment]
I think Windows updates also require code signing (and it's even more difficult there than on macOS); I might not be remembering correctly at this point though.

Closing since #397 already exists.

(Also, there are update notifications now that appear in the searchbar).

**Comment by raj123** [comment]
yes update notifications are there but that is also like manual process. user has to click on notification download it and then install it.

ok no issues, I am trying. Thanks.
